### ISSUE TITLE
OSX toolbox doesn't install git :)

### ISSUE THREAD

**Issue by SvenDowideit** [docker/toolbox#100]
but it does on Windows.

(I just put an ssd in my OS X box, so installed toolbox on a fresh OS)

when you type `git`, it gives you a popup to install Xcode, but i'm not totally sure I want to do that (perhaps we should add some warning/guidance to options)

**Comment by SvenDowideit** [comment]
@jeffdm I then went to install the upstream OS X installers from http://git-scm.com, and they're unsigned!

I wonder if we can help out https://github.com/timcharper/git_osx_installer/issues/55 - we could also set up package signing

**Comment by SvenDowideit** [comment]
and boom, i don't get `make` either - I wonder how long i can avoid installing Xcode.

**Comment by mchiang0610** [comment]
@SvenDowideit We don't need Git by default. It will work out of the box. Now, most developers will choose to install something on their own. (either through Xcode or something else)
