### ISSUE TITLE
fatal error: runtime: bsdthread_register error

### ISSUE THREAD

**Issue by myappleguy** [docker/toolbox#103]
```
bash-3.2$ docker run hello-world
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x7df0b5)
	/usr/local/go/src/runtime/panic.go:491 +0xad fp=0x7fff5fbff770 sp=0x7fff5fbff740
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.c:104 +0x70 fp=0x7fff5fbff788 sp=0x7fff5fbff770
runtime.schedinit()
	/usr/local/go/src/runtime/proc.c:141 +0x5f fp=0x7fff5fbff7b0 sp=0x7fff5fbff788
runtime.rt0_go(0x7fff5fbff7e8, 0x3, 0x7fff5fbff7e8, 0x0, 0x0, 0x3, 0x7fff5fbff988, 0x7fff5fbff98f, 0x7fff5fbff993, 0x0, ...)
	/usr/local/go/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbff7b8 sp=0x7fff5fbff7b0
```

Fresh install with the toolbox. OSX 10.9.5.
Following the tutorial http://docs.docker.com/mac/step_one/
Just ran `docker run hello-world` as the first step.

**Comment by mchiang0610** [comment]
@myappleguy Hey, thanks for this. We will look into this issue. It seems like for some odd reason your computer went into panic mode.

**Comment by myappleguy** [comment]
@mchiang0610 thank you. I have tried uninstall / reinstall and got same results. If there is any more information that could help please don't hesitate to ask. My team and I would love to start using docker instead of Vagrant.

**Comment by mattwg** [comment]
I have this as well.  I have previously used boot2docker and wonder if this is some form of conflict.  
OSX 10.10.5

**Comment by mattwg** [comment]
Could it be Anti Virus software?   See this thread https://groups.google.com/forum/#!topic/golang-nuts/HtcZc3wO-rw

**Comment by myappleguy** [comment]
Good question @mattwg we are using Norton AV on OSX. I will try and see if I can replicate on my personal MBP w/out AV.

**Comment by myappleguy** [comment]
Wow, thank you @mattwg After reading that thread I am pretty sure that is is AV related.

**Comment by myappleguy** [comment]
Ok i this works just fine an my personal MBP without AV and same version of OSX.

**Comment by mattwg** [comment]
Great - glad it fixed your problem - I just removed my Symantec Endpoint Protection and unfortunately I still get the error ;-(  I guess I need to get a VM on my Mac to play with this.

**Comment by mattwg** [comment]
Turns out it was Websense - removed the websense endpoint and all fine!
