### ISSUE TITLE
Docker Quickstart Terminal doesn't honour .bash_profile on Mac OS X

### ISSUE THREAD

**Issue by rija** [docker/toolbox#104]
HI. I have installed Docker Toolbox 1.8.1b on Mac OS X 10.10.4 Yosemite. 
When I launch Docker QuickStart Terminal. A terminal window is opened but none of the aliases, functions and commands from ~/.bash_profile are run.

When creating a new terminal window from the Terminal application, .bash_profile configuration file is executed automatically.

In theory, .bash_profile should only be executed with login shells. For non logging shells .bashrc is the one that should executed.

At the very least Docker QuickStart Terminal should honour the .bashrc file as the user is already logged in by then. 

Then those of us who had our environment set in .bash_profile and use the Terminal app can source it from within the .bashrc.

**Comment by mchiang0610** [comment]
@rija Thanks for reporting.

**Comment by jeffdm** [comment]
This should be fixed in https://github.com/docker/toolbox/releases/tag/v1.8.1d which now runs bash with the `--login` flag.
