### ISSUE TITLE
Uninstaller deleted me all config! 

### ISSUE THREAD

**Issue by imton** [docker/toolbox#106]
I think this is just plain wrong. Dangerous stuff. I had to go back to TimeMachine.

Thanks

````
rm -rf ~/.docker
rm -rf /usr/local/share/boot2docker
````

**Comment by thaJeztah** [comment]
Oh, yes, that doesn't look right. At least it should be *optional* (i.e., pass an option to also delete user data)

**Comment by mchiang0610** [comment]
@imton Thanks for reporting, looking into this issue.

**Comment by SydOps** [comment]
@imton , thanks to report this, I have installed toolbox, and will not do the uninstallation until this problem is fixed.

**Comment by mchiang0610** [comment]
@imton @thaJeztah @SydOps It's fixed in the script on our GitHub.

**Comment by SydOps** [comment]
@mchiang0610 

Before you close the ticket, could you please link the pull request to it, that we know what is changed.

**Comment by mchiang0610** [comment]
@SydOps sorry about that: 
https://github.com/docker/toolbox/commit/aff62a973f2e2132fd6306957e0a58603bcefa5d

**Comment by mchiang0610** [comment]
Basically we stopped removing: ~/.docker folder

**Comment by SydOps** [comment]
So @jeffdm is belong to Docker company and update the repository directly? Looks it is wrong change workflow.

**Comment by thaJeztah** [comment]
> update the repository directly

Agreed here; using pull-requests, also for maintainers, makes the process much more visible, and allows people to review changes before they get merged
