### ISSUE TITLE
ToolBox Quickstart fail

### ISSUE THREAD

**Issue by bgrissin** [docker/toolbox#110]
The .exe installer worked as expected.

Once the install is completed, the next step is to start the default VM using a quickstart script.  This is what failed, as the expectation of this script running would start a VM known as default locally.   Instead of it working (i.e. running) it instead launched quickstart as if it were a file to edit.  I have, nor did the user have any idea why it performed this way.  Still puzzled.  We re-installed toolbox completely and it is a repeat-able scenario.

However, if you got to the CLI after the successful install and performed a docker-machine ls, one could see that there was a default instance and it is started.

We just used docker-machine ssh default to get into the container from their and we were able to execute docker commands, etc.

**Comment by mchiang0610** [comment]
@bgrissin Thanks for reporting. Looking into this.

**Comment by bgrissin** [comment]
forgot to post the actual error Caleb received after installation and the attempt to run QuickStart

$ docker ps

Get http://127.0.0.1:2375/v1.20/containers/json: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it..

* Are you trying to connect to a TLS-enabled daemon without TLS?

* Is your docker daemon up and running?

 

Caleb Peterson | Consulting Systems Developer

**Comment by phpguru** [comment]
You'll get this error if you have no DOCKER_HOST or other environment variables set, or old/deprecated ones for boot2docker, since the docker-toolkit has a new IP. I have my whole ~/.bash_profile as a gist [here](https://gist.github.com/phpguru/1582784db2b7ea5c4f40). It would be very helpful to include this in the quickstart docs, and to make it clear that you can run, eg, `docker ps -a` within the quicklaunch vm terminal, but not from the Mac terminal (yet) without adding environment vars and/or sourcing your revised profile.

**Comment by jeffdm** [comment]
Thanks, this seems to be related to Git not being properly installed. Will merge with https://github.com/docker/toolbox/issues/95

**Comment by ashishksingh** [comment]
FYI , I had faced a similar issue and the resolution was to re-install the Virtual box test build 5.0.5 with the NDIS5 driver , i.e. VirtualBox-5.0.5-103003-Win.exe  -msiparams NETWORKTYPE=NDIS5"

**Comment by misterflop** [comment]
I've fixed the same issue.
My default VirtualBox machine was using the wrong Windows network adpter.
You can fix that in the network configuration of your virtual machine.

**Comment by larssb** [comment]
Doing what @ashishksingh did helped me :-) - thank you.

**Comment by Schandlich** [comment]
@larssb Same.
Thank you @ashishksingh
