### ISSUE TITLE
can't find virtualbox due to different folder

### ISSUE THREAD

**Issue by larrycai** [docker/toolbox#111]
similar to the case in machine https://github.com/docker/machine/issues/1737 , the virtualbox installation path is hard coded https://github.com/docker/toolbox/blob/master/windows/start.sh 

Actually It could be `C:\Program Files\Oracle VM VirtualBox` for some users, better to use registry or other way to locate.

**Comment by jeffdm** [comment]
Closing in favor of https://github.com/docker/toolbox/issues/89
