### ISSUE TITLE
Docker Toolbox Migration of Boot2Docker suggests opening machine issue on error

### ISSUE THREAD

**Issue by pthorson** [docker/toolbox#113]
We got an error from docker toolbox on the migration of the Boot2Docker VM (see https://github.com/docker/toolbox/issues/112). 

The error dialog suggests opening an issue at https://github.com/docker/machine/issues/new. 

Probably should be directing the user to create a new issue at docker toolbox github instead.

**Comment by timgluz** [comment]
I just got same error for OSx10.10.5 . 
I tried the `docker-machine env default` and `docker-machine env -u` commands, any of them made it work.


<img width="312" alt="screenshot 2015-08-26 10 12 51" src="https://cloud.githubusercontent.com/assets/1223889/9488554/33d2a834-4bdb-11e5-9b54-2c886f92761b.png">

**Comment by timgluz** [comment]
ok, found solution #97  - upgrade virtualbox.5.2 -> 5.3

**Comment by jeffdm** [comment]
Agreed, thanks, will update in 1.8.1c.

**Comment by jeffdm** [comment]
Fixed in 1.8.1c. Thank again!
