### ISSUE TITLE
docker-machine hang when ssh config is set to ControlPersist

### ISSUE THREAD

**Issue by lifei** [docker/toolbox#118]
```
Host *
    ControlMaster auto
    ControlPath /tmp/%r@%h:%p
    ControlPersist yes
```

**Comment by mchiang0610** [comment]
@lifei Thanks for reporting.

**Comment by sheeley** [comment]
Commenting out `ControlPersist yes` fixed https://github.com/docker/machine/issues/1722 for me.

**Comment by mchiang0610** [comment]
@nathanleclaire any thoughts on this? Would like to close this.

**Comment by nathanleclaire** [comment]
If I'm not mistaken we have fixed this in master by setting the `ControlMaster` etc. options in the SSH command we run directly.
