### ISSUE TITLE
VirtualBox 5.0.2 incompatible with many Mac devices

### ISSUE THREAD

**Issue by lukemarsden** [docker/toolbox#119]
Completely brand new Macbook and I get, after downloading and installing Docker Toolbox 1.8.1b and starting up Kitematic:

`/Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users/<redacted>/.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.`

**Comment by lukemarsden** [comment]
Looks like this is a dupe of https://github.com/docker/machine/issues/1716 - sorry for the noise.

Will we see an updated VirtualBox being bundled with Docker Toolbox? This seems serious enough for new users that an older or newer VBox should be bundled IMHO.

**Comment by lukemarsden** [comment]
FTR, https://www.virtualbox.org/ticket/14412 was the underlying issue, and upgrading to the dev build for Mac linked to from there resolved the issue for me.

**Comment by fernandomora** [comment]
I think commit 93ccd5170d704e8cb25ad11b129c7275a1985062 should be reverted until VirtualBox 5.0.3 is released.
Current version of toolbox doesn't work as-is, at least in OS X, not sure if same problem in windows.

Opening Quickstart terminal produces following output:
```
STDERR: 
executing: /usr/local/bin/VBoxManage modifyvm default --nic2 hostonly --nictype2 82540EM --hostonlyadapter2 vboxnet0 --cableconnected2 on
STDOUT: 
STDERR: 
executing: /usr/local/bin/VBoxManage modifyvm default --natpf1 delete ssh
STDOUT: 
STDERR: VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1766 of file VBoxManageModifyVM.cpp

executing: /usr/local/bin/VBoxManage modifyvm default --natpf1 ssh,tcp,127.0.0.1,54267,,22
STDOUT: 
STDERR: 
executing: /usr/local/bin/VBoxManage startvm default --type headless
STDOUT: Waiting for VM "default" to power on...
VM "default" has been successfully started.

STDERR: 
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
Starting machine default...
exit status 1
```

If a machine is manually created:
```
~ $ docker-machine create default -d virtualbox
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

and VBox.log gives:
```
00:00:00.032535 SUP: Loading failed for VMMR0.r0 (/Applications/VirtualBox.app/Contents/MacOS/VMMR0.r0) rc=VERR_VMM_SMAP_BUT_AC_CLEAR
00:00:00.032593 PDMLdr: pdmR3LoadR0U: pszName="VMMR0.r0" rc=VERR_VMM_SMAP_BUT_AC_CLEAR szErr="SUPR3LoadModule: supLoadModule returned VERR_VMM_SMAP_BUT_AC_CLEAR"
00:00:00.032604 VMSetError: /Users/vbox/tinderbox/mac-rel/src/VBox/VMM/VMMR3/VM.cpp(595) int vmR3CreateU(UVM*, uint32_t, int (*)(UVM*, VM*, void*), void*); rc=VERR_VMM_SMAP_BUT_AC_CLEAR
00:00:00.032611 VMSetError: Failed to load VMMR0.r0
00:00:00.032715 ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={872da645-4a9b-1727-bee2-5585105b9eed} aComponent={ConsoleWrap} aText={Failed to load VMMR0.r0 (VERR_VMM_SMAP_BUT_AC_CLEAR)}, preserve=false aResultDetail=0
00:00:00.032813 Console: Machine state changed to 'PoweredOff'
00:00:00.040601 Power up failed (vrc=VERR_VMM_SMAP_BUT_AC_CLEAR, rc=NS_ERROR_FAILURE (0X80004005))
```

So, it seems there is an incompatibility with Virtualbox 5.0.2 as explained in
https://github.com/docker/machine/issues/1722 and https://github.com/docker/machine/issues/1716

**Comment by jeffdm** [comment]
Thanks @fernandomora . Will bump the mac version back down to 5.0.0 unless 5.0.3 is released very soon.

**Comment by thaJeztah** [comment]
FYI, got an issue reported in Docker that VirtualBox 5.0.3 may be having some issues as well; https://github.com/docker/docker/issues/16046

**Comment by mchiang0610** [comment]
@thaJeztah thanks. 5.0.4 is out, and we are testing with that.

**Comment by yunti** [comment]
There seems to be multiple issues created with docker not working on OS X - some have solved with updating to a virtual box test build (5.0.3) but however, 
5.0.3 (r102467) didn't solve the issue for me . the default host still fails to start

Error is:

VT-x is disabled in the BIOS for both all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED).

Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
ConsoleWrap
Interface: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

Hmmm in the virtual box settings mentioned by yuan78 . I can't see an option for VTX for the CPU. And I can only select 32bit version of Linux there are no 64 bit options for some reason?

update: I believe the vtx option for the cpu is under acceleration (under system) this is greyed out for me, so it looks like this version of virtual box is pretty broken.

my details:

Study:~ $ docker version
Client:
Version: 1.8.1
API version: 1.20
Go version: go1.4.2
Git commit: d12ea79
Built: Thu Aug 13 02:49:29 UTC 2015
OS/Arch: darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.

Are you trying to connect to a TLS-enabled daemon without TLS?
Is your docker daemon up and running? Study:$ docker info Get http:///var/run/docker.sock/v1.20/info: dial unix /var/run/docker.sock: no such file or directory.
Are you trying to connect to a TLS-enabled daemon without TLS?
Is your docker daemon up and running? Study$ uname -a Darwin Study_Pc.home 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64 Study_Pc:$

**Comment by lukemarsden** [comment]
@yunti have you enabled VT-x in your BIOS? Or do you have a CPU that doesn't support hardware virtualization? You can check for the VT-x flag on the Intel product page for your CPU.

**Comment by yunti** [comment]
Update 5.0.4 (102546)virtual box has same issue:
(let me know if I can provide more detailed logs which may help)

VT-x is disabled in the BIOS for both all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED).


Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
ConsoleWrap
Interface: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

---------
Will double check for Vt-x compatibility.

**Comment by yunti** [comment]
@lukemarsden thanks didn't even think of my actual hardware rather than that of the virtual machine.   Vt-d not enabled was the issue.

**Comment by lukemarsden** [comment]
@yunti great!

@mchiang0610 @thaJeztah might be worth a separate issue for checking/warning about VT-x in the installer, rather than failing post-installation with this slightly obscure error?

**Comment by thaJeztah** [comment]
@lukemarsden yes, I agree; a clear warning and instructions would be good. Probably add a note in the documentation as well. To prevent duplicates; will you create an issue, or want me to create one?

**Comment by lukemarsden** [comment]
It would be great if you could create it @thaJeztah - I'm not on the toolbox issues often ;)

**Comment by yunti** [comment]
That would definitely be useful to have some sort of warning. Interestingly although I now have Vt-x selected and enabled in the acceleration - section of virtual box , (after changing the intel virtualisation and VT-d settings in my bios to enabled) - I still get an error in the virtual box at the boot2 docker screen (using 1.8.1c toolbox) stating that my cpu isn't x86 compatible but an i686 - I think this still has to do with virtualisation support (my cpu is intel i5 4570 - which supports virtualisation).  Additionally using docker on windows on the same machine (different ssd) works fine with virtualisation enabled.

**Comment by thaJeztah** [comment]
@lukemarsden created a placeholder issue https://github.com/docker/toolbox/issues/166

**Comment by jeffdm** [comment]
This should be fixed in https://github.com/docker/toolbox/releases/tag/v1.8.1d which includes 5.0.4
