### ISSUE TITLE
The link to the toolbox website should open a new tab

### ISSUE THREAD

**Issue by gdevillele** [docker/toolbox#12]
I don't think we want the user to leave the documentation page when he/she clicks on the toolbox website link.
<img width="1317" alt="screen shot 2015-07-13 at 9 36 31 am" src="https://cloud.githubusercontent.com/assets/939999/8654996/136f2640-2943-11e5-9463-29ff28910c44.png">

windows 8.1 + IE 11 in VMWare Fusion Pro

**Comment by jeffdm** [comment]
Thank you for the issue!

If possible, please open a ticket on in the [docs repo](https://github.com/docker/tutorials) or comment on https://github.com/docker/tutorials/pull/10 :memo:

**Comment by moxiegirl** [comment]
Used target=_blank
