### ISSUE TITLE
Let User choose Vbox path, not just "C://Program Files/.."

### ISSUE THREAD

**Issue by ZhengzhongZhang** [docker/toolbox#121]
in toolbox/windows/start.sh

    if [ ! -f $DOCKER_MACHINE ] || [ ! -f /c/Program\ Files/Oracle/VirtualBox/VBoxManage.exe ]; then
      echo "Either VirtualBox or Docker Machine are not installed. Please re-run the Toolbox Installer and try again."
      exit 1
    fi

I think it's not good, some people may install it in other place(like me), you should make user choose virtualbox's path

**Comment by ndarilek** [comment]
Agreed. This also fails with Cygwin where the actual path is the same but in the environment is prepended with /cygdrive/.

Why not check if VBoxManage can be found already? If it is already on the path then you don't need to hardcode one in. Maybe check if it is on the path, then try a few fallbacks if it isn't.

**Comment by BrianEliotWhipple** [comment]
+1

**Comment by larrycai** [comment]
see #111 , we shall check this in registry

**Comment by jeffdm** [comment]
Closing in favor of https://github.com/docker/toolbox/issues/89

@ndarilek thanks for the extra info w/ cygwin
