### ISSUE TITLE
docker-compose  Illegal instruction: 4

### ISSUE THREAD

**Issue by masieroi** [docker/toolbox#125]
**Description of problem**:
Just migrated to the Toolbox following the migration process provided by the Mac OS installer.
I can't execute `docker-compose` the command line, it says `Illegal instruction: 4`  

`docker version`:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 1
Images: 15
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 2
Total Memory: 1.956 GiB
Name: default
ID: FX4D:6KPF:IHKA:EJPE:ZAGM:CSX5:VLLS:RNBR:CMYT:H2M6:3LL5:OCYQ
Debug mode (server): true
File Descriptors: 110
Goroutines: 116
System Time: 2015-08-26T09:49:38.596061341Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: masieroi
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

`uname -a`:
Darwin Kernel Version 14.4.0: 
root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

**Steps to Reproduce:**
1. open Docker Quickstart Terminal
2. type `docker-compose`

**Actual Results:**
`Illegal instruction: 4`

**Comment by jeffdm** [comment]
This seems to be a known issue in `docker-compose`:

The fix right now is to install it via pip: https://github.com/docker/compose/issues/1885

--- 
**Note:** Some older Mac OS X CPU architectures are incompatible with the binary. If you receive an "Illegal instruction: 4" error after installing, you should install using the `pip` command instead.
