### ISSUE TITLE
Windows-style line endings in start.sh

### ISSUE THREAD

**Issue by ndarilek** [docker/toolbox#126]
Maybe this has to do with me running Cygwin rather than Mingw and Cygwin's bash attempting to run start.sh. I got this error:

```
./start.sh: line 2: $'\r': command not found
```

Running dos2unix on the file makes this error go away.

**Comment by jeffdm** [comment]
Thanks for the issue.

dos2unix doesn't seem to change the file for me, and I can run it in cygwin.

Which version of the Toolbox are you running?

**Comment by SvenDowideit** [comment]
The worst thing is that some `git clone`s will convert to Windows line endings, and then doing a `docker build` will fail to run scripts..

**Comment by SvenDowideit** [comment]
I recal this working in b2d, but i really can't remember what we did.

**Comment by SvenDowideit** [comment]
for building Docker, the best thing is to avoid the issue by setting `git config --global core.autocrlf input` which makes git clone using unix endings, and converts windows endings on commit

**Comment by jeffdm** [comment]
This should be fixed in 1.8.1c. Thank again!

**Comment by elleache** [comment]
Not fixed.
