### ISSUE TITLE
Docker toolkit on VMWare workstation 11

### ISSUE THREAD

**Issue by jvd1** [docker/toolbox#127]
Are their any plans to create a version of Docker/Toolbox that run on top of VMWare Workstation. We are heavily invested in VMWare workstation (version 11.1.2 build-2780323) use here and having to use Virtualbox would represent a severe dislocation of our workflow.

Please let us know.

**Comment by mchiang0610** [comment]
@jvd1 Docker machine currently does not support VMWare Workstation. This is a discussion for VMWare as they have support with VMWare Fusion / vSphere / vCloud etc. 

Closing this for now.
