### ISSUE TITLE
can't uninstall one component of the docker toolbox like kitematic 

### ISSUE THREAD

**Issue by larrycai** [docker/toolbox#129]
I installed the all components, and start to experience it. And I am happy with the migration of boot2docker.  Kitematic is just alpha version.

Then I want to remove kitematic only, but I can't find the way to uninstall it separately.  In control panel, I have to remove all, which is not my intention

**Comment by jeffdm** [comment]
Hi there, and thanks for the issue!

The best way to remove Kitematic is to:

- Remove C:\Program Files\Docker Toolbox\kitematic
- Remove C:\Users\<user>\AppData\Roaming\Kitematic
