### ISSUE TITLE
Cannot start 'default' VM on OS X

### ISSUE THREAD

**Issue by eproxus** [docker/toolbox#131]
On OS X, after a fresh install, clean reinstall (using the uninstall script), I get the following error when trying to run Docker Quickstart Terminal for the first time (and subsequent tries):

```
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : exit status 255
Getting to WaitForSSH function...
Testing TCP connection to: localhost:50327
Using SSH client type: external
About to run SSH command:
exit 0
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/alind/.docker/machine/machines/default/id_rsa -p 50327 docker@localhost exit 0] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
```

(Full output [here](https://gist.github.com/eproxus/3de63c1a6610fe5238bb))

After this, the terminal just hangs.

I have tried with VirtualBox 4.3.30, 5.0.0, 5.0.2 and 5.0.3-102322 with the same results. There seems to be a few similar issues, but I couldn't find any that had the same problems over all VirtualBox versions, so I'm posting this as a new one.

**Comment by eproxus** [comment]
This is probably the real issue: https://github.com/docker/machine/issues/1722

**Comment by AlanJui** [comment]
After a lot of struggle and study what is Host-only Adapter for, and how to configure to let that function work well. Finally I find out the problem which I deal with.
 
My network use segment 192.168.99.0/24. IP for gateway is 192.168.99.1. But the default configuration of "Host-only Adapter" on VisualStudio conflict with my network setting.

# Procedures for finding out problem 

0. Run "Docker Quickstart Terminal" to create default docker-machine, but it fail.

1. Check the Network Adapter 2 in VirtualBox. Find out the name of interface for __Host-only Adapter__.

  ![2015-09-06_16-23-08](https://cloud.githubusercontent.com/assets/2138279/9704507/4309023a-54dc-11e5-8257-2aa341e3f246.png)

2. Use ifconfig command to find out IP used by vboxnet2.

  ![2015-09-06_16-23-56](https://cloud.githubusercontent.com/assets/2138279/9704534/952038ee-54dd-11e5-9009-ed54785cff5c.png)

3. Remove default docker-machine.

  ```
  $ docker-machine rm default
  ```

4. Change my network configuration.   192.168.99.0/24 ==> 192.168.66.0/24

5. Run "Docker Quickstart Terminal" App again. It is succeed.

  ![2015-09-06_16-17-49](https://cloud.githubusercontent.com/assets/2138279/9704695/35f1bf1e-54e2-11e5-8971-5f1b863b99da.png)

# Verify

1. Run docker command: __docker run hello-world__ 

  ![2015-09-06_16-43-20](https://cloud.githubusercontent.com/assets/2138279/9704715/d8d06c62-54e2-11e5-8b53-98e37a14b7e2.png)

2. Run docker-machine command: __docker-machine env default__

  ![2015-09-06_16-19-08](https://cloud.githubusercontent.com/assets/2138279/9704723/34d12a74-54e3-11e5-896f-cc61eff08694.png)

3. Run "Kitematic (Beta)" App.

  ![2015-09-06_16-20-45](https://cloud.githubusercontent.com/assets/2138279/9704726/478f18ec-54e3-11e5-96da-e6d1c28616fe.png)

# Conclusion

I think it could be better to let user to change configuration of "Host-only Adapter" for their own network environment.

# My Environment

  * Mac OS X: 10.10.5
  * Docker Toolbox: 1.8.1c
  * VirtualBox: 5.0.2 r102096

**Comment by eproxus** [comment]
I'm on a network with the segment `185.74.15.0/24` so I'm not sure this is the issue for me.

**Comment by AlanJui** [comment]
I am sorry to say my post is not for your case. I just want to share my situation and how to find out problem and fix it. And raise my suggestion to Docker Toolbox giving user a chance to configure Host-only Adapter.

After all, change segment of network is a terrible job. It is most likely to trigger a ripple effect。 U_U !!

**Comment by eproxus** [comment]
I wouldn't be surprised if my problem is also related to the network somehow, I'm getting a timeout after all.

**Comment by mchiang0610** [comment]
Merging with #66 for discussion there.
