### ISSUE TITLE
Cannot run "docker run hello-world" after a fresh installation on windows 10

### ISSUE THREAD

**Issue by amocodev** [docker/toolbox#135]
I recently fetched docker and installed it on my fresh windows 10 install, I don't have any firewall
or anything like it, however - when I try to run "docker run hello-world"  I get the following message in "Docker Quickstart Terminal" : 

```
$ docker run hello-world
Post http://127.0.0.1:2375/v1.20/containers/create: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it..
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

note: 
If I access the VM directly in VirtualBox's console and add nameserver (127.0.0.1 and 8.8.8.8) I
can access and pull the machine, however I still can't use from git-bash / "Docker Quickstart Terminal" .

note: 
I do not see any service listening on that port, maybe something in the installation failed ? 
How can I verify that ? Is there any log or something which states which components are supposed to be installed ? 

Did anyone else encounter this sort of issue or know how to solve it ? 

Edit 1:

I think this is related to the fact that my docker VM bridged IP is different every time I turn on my
workstation, is there a way to specify the docker host when running the "docker" command from the command line ?

I can see the that in the "default" VM it is listening to 2376 but I don't know how to specify it when running the "docker" command. Is there any environment variable I should change ? 

Edit 2:

It seems like a routing issue on the boot2docker/"default" vm itself, following the boot log I can see one segmentation fault right after sysctl of ipv4_forward ( which succeeds ) .
However, it doesn't seem to be able to touch ipv6_forward (as I don't have ipv6).

I do have a network connection but I can't seem to access the "default" vm from git-bash, I'm not sure what sort of neteworking I should change (obviously the eth1 / bridged connector networking) but I'm not sure what to do.

Can anyone comment on that ?

**Comment by amocodev** [comment]
Can anyone assist ?

**Comment by dgmdevelopment** [comment]
Hi, the most recent version [DT 1.8.1c](https://github.com/docker/toolbox/releases/tag/v1.8.1c) worked out of the box just fine on Windows 10. A few things to ask.  

What v. DT?

What v. VB? If older than 5.0.2, uninstall it and use the one bundled with DT. 

I also let DT install Git 2.5 for Windows 64-bit. 

There are logs for VB here

`C:\Users\your-user-name\.docker\machine\machines\default\default\Logs`

Might be easier to start fresh again.  Uninstall DT, VB, reboot and reinstall.  

If there is no important data on the default vm, you could perhaps delete the 
`C:\Users\your-user-name\.docker` folder. This wipes out the default VM and starts fresh. 

Good luck!

**Comment by Morgy93** [comment]
Same issue here on two different Windows 10 machines. (Surface Pro 3 and HP Spectre x360)

DT 1.8.1c with VB 5.0.2

No solution found so far. Any help?

**Comment by mchiang0610** [comment]
@amocodev @Morgy93 Sorry about the issues. Are you doing 
```
docker run
``` 
through the quickstart terminal? If not, you would have to run this command first: 

```
eval "$(docker-machine env default)"
```
and then your commands. 

Hope this helps!! If not, please reopen this issue. 

Thanks!
Michael

**Comment by Morgy93** [comment]
Yes, I am using the Docker Quickstart Terminal. But I'm getting the same error within powershell or cmd.
Still couldn't find a solution, so some more help would be appreciated.
