### ISSUE TITLE
"cannot enable tty mode on non tty input" when trying to run -it ubuntu bash 1.8.1c.

### ISSUE THREAD

**Issue by avelinos** [docker/toolbox#136]
With DockerToolbox 1.8.1c for Windows, I get "cannot enable tty mode on non tty input" when trying to run
```
docker run -it ubuntu bash
```
I'm seeing this behavior with both Windows 7 Pro and 10 Pro.

This also happens to affect a number of my other containers for a work project, but I don't always see the "tty" error until trying to attach to a container.  All of the containers worked fine under 1.8.1b

This is with a fresh install and an upgrade from 1.8.1b.  If I uninstall 1.8.1c and reinstall 1.8.1b, then I can run the above command and my work containers just fine.

I've noticed that 1.8.1b uses MINGW32 and 1.8.1c uses MINGW64.  It looks like MINGW64 is part of the Git 2.5 upgrade.  I can't run Git 2.5 with 1.8.1b so I can't verify whether or not that is related to the bug.

**Comment by withinboredom** [comment]
+1

**Comment by Negashev** [comment]
+1, try
winpty docker run -it

**Comment by mchiang0610** [comment]
Thanks! We'll dive deeper into the problem. 

cc/ @jeffdm

**Comment by austin881** [comment]
+1

Ever since installing the latest version of the Docker Toolbox ([v1.8.2](https://github.com/docker/toolbox/releases))

When I run...
```
docker run -it ubuntu bash
```

I am given this message...
> cannot enable tty mode on non tty input

I'm running 64-bit Windows 7.
```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by cagdascirit** [comment]
+1 same with @austin881

**Comment by jwsongkr** [comment]
+1 same.

**Comment by jpt007** [comment]
+1

**Comment by keatz55** [comment]
+1

**Comment by laofenggithub** [comment]
+1

**Comment by loboolsson** [comment]
+1 Windows 10

**Comment by Callero** [comment]
+1 Windows 7

**Comment by adaminspace** [comment]
+1 Windows 10

**Comment by kvickyk** [comment]
+1 Windows 8.1

**Comment by zhaohc10** [comment]
+1 windows 7

**Comment by redutan** [comment]
```docker run -it ubuntu bash```

**Comment by zhaohc10** [comment]
thanks but it did not work.I did this way first and it works now: docker-machine ssh default Thanks


 
Best regards, 

Andrew Zhao  (510) 375-9935  “When you are right
you cannot be too radical; when you are wrong, you cannot be too
conservative.”            


Date: Mon, 21 Sep 2015 18:51:42 -0700

**Comment by tiangolo** [comment]
I wrote a simple workaround / quick fix to allow using Docker Toolbox from Babun, it may help some of you:

https://github.com/tiangolo/babun-docker

With that you can keep using your ```docker``` commands as normal.

And if you are using Cygwin, you should use Babun, a very improved version of Cygwin.

-----

You just have to run one command to setup everything. Although I encourage you to check the source code before running any script (including mine) in your terminal.

Inside, it installs and sets up winpty, and tries to start your default docker-machine VM and set up its environment.

Maybe it gets more relevant now since newer versions of Docker Toolbox come with Git 2.5, which uses mintty and has the same problem of "cannot enable tty mode on non tty input" as in Babun.

**Comment by r4j4h** [comment]
+1 this affects me on Windows 8.1. SSH'ing into the VM and running the command works with -t from there, but not from Windows cmd or other native-level shells.

**Comment by takashi209** [comment]
+1 same with @austin881

**Comment by jeffdm** [comment]
Sorry for the delay. Looking into how we can update the Toolbox to fix this. Hadn't realized Git 2.5 had made such a drastic change.

**Comment by jeffdm** [comment]
https://github.com/docker/toolbox/releases/tag/v1.8.2c should have this temporarily fixed. Sorry again for the delay.

As always, feel free to email me at jmorgan@docker.com

**Comment by adaminspace** [comment]
Yes, working OK now on Windows 10. Many thanks Jeff.

**Comment by mchiang0610** [comment]
Thanks everyone for filing this issue. Closing this for now, but do reply back if you are still having problems with it. A more permanent solution will be in the works.

**Comment by avelinos** [comment]
Thanks for the temp fix.  It does resolve the specific bug, however, my teammates who use Windows don't have access to any of the tools they already have installed on their boxes, like Maven.  They could always install them in the Docker VM, but that ends up eating up more space and they'd have to reinstall all of the tools should they have to create another Docker VM.  So, I hope the permanent solution works more like DockerToolbox 1.8.1b where they can use their tools immediately after installing DockerToolbox.

**Comment by gmanfunky** [comment]
Instead of going into the limited use-case ```docker-machine ssh```(https://github.com/docker/toolbox/commit/f8c52017a01a2c5be6a9f05cefa0df5a4ae1f7ec) a slightly better temporary fix, if staying with Git for windows using MSYS 2, could be
```
alias docker="winpty docker"
```
Winpty comes with the git for windows package being installed. 

This should help with our expected windows use case of ```docker exec/run -it stuff`` While in the MSYS2 Bash shell from Git for Windows. 


Is there another open issue to pursue better fixes?

**Comment by gmanfunky** [comment]
Scratch that alias recommendation. It might fail for ```docker login```

**Comment by tiangolo** [comment]
By the way, I think my script / fix in this comment above: https://github.com/docker/toolbox/issues/136#issuecomment-143058036 is still relevant.

It tries to execute the docker command you ask, it auto-checks if it needs to run it with winpty, and then re-runs it again.

It also checks if it was able to run or if it has to start and set the environment for the virtual machine, and then executes again, automatically.

And you get all the benefits of Babun (Cygwin) over MINGW. It may help someone... Just saying...

**Comment by gmanfunky** [comment]
@tiangolo I like your technique in the script. But it is notably for use in cygwin/babun. The current docker toolbox comes by default with the Git for Windows alread, which already includes winpty, which you and others have identified as a good workaround. 

It appears ```docker login``` not working is a separate issue. 

I think it's much better to apply the alias workaround compared to changing the Quick Start shortcut just SSH into the VM. ssh into VM isn't super nice for local development.

**Comment by jeffdm** [comment]
Thanks @gmanfunky @tiangolo - seems like using winpty may be a great fix for this, and maybe even `docker-compose`. Taking a look.

**Comment by tiangolo** [comment]
@jeffdm should I try a PR including some sort of winpty trick like the one I made for Babun? Or are you already doing it?

**Comment by mhailstone** [comment]
I am still experiencing this error. The winpty alias workaround did not work unfortunately. Here is my environment:

$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64


$ docker info
Containers: 1
Images: 30
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 32
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.10-boot2docker
Operating System: Boot2Docker 1.8.3 (TCL 6.4); master : af8b089 - Mon Oct 12 18:56:54 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: H7QM:57IH:CCD4:NPLN:X5J4:QTI5:G6XF:PFOC:ZSZZ:R53S:2XVA:JNRV
Debug mode (server): true
File Descriptors: 12
Goroutines: 16
System Time: 2015-10-19T16:24:47.969083209Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

$ uname -a
MINGW64_NT-6.3 ITB-HPDV8PT 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys

**Comment by gmanfunky** [comment]
@mhailstone The winpty alias workaround was removed in the latest docker toolbox. (1.8.3)
Right now, the workaround is to manually prepend any interactive command with ```winpty```

It sounds like we still could use a reminder.

**Comment by gmanfunky** [comment]
@tiangolo  - the alias trick results in problems when calling docker from inside scripts (like build scripts) and when redirecting input and output. 

There was a bit of time where it looked like a bash function would do the trick and survive into sub-shells, but it failed when doing things like ``` docker info > info.txt```

**Comment by mhailstone** [comment]
@gmanfunky Thanks for the note and reminder. For basic -it option interaction the winpty seems to be working.

For mounting volumes, though, I am different issues. (This may warrant a new bug, but because this is really related to this workaround I'm keeping the thread here.) My virtual mounts and current working directory mounts are now not working correct. It doesn't recognize the paths specified. Here are the commands run from inside a bash script file:

docker run --name my_node_modules -v //opt/webroot/mycode/node_modules ubuntu 2> /dev/null
winpty docker run --rm -i -t -p 9000:9000 --name myrunningcontainer -v /$(pwd)/mycode://opt/webroot/mycode --volumes-from=my_node_modules -w //opt/webroot/mycode myimage sh -c "./run.sh"

Note: All paths here have a leading slash which is needed apparently when running from the Git bash shell for Windows. Also, if I remove the leading winpty and then the -i -t options, it will run just fine, but now I don't have my interactive terminal.

**Comment by tiangolo** [comment]
Thanks @gmanfunky for the notes, I was seeing those issues with the output redirection with my script, so I just refactored it all, it's working better now and a lot cleaner.

https://github.com/tiangolo/babun-docker

I'm not using an alias in my script, it's rather a bit more complex function that uses Winpty only when needed, and also that auto-starts and sets the environment of the docker-machine when it fails to connect to it.

@mhailstone In case you are using Babun, here's the guide to make volumes work with it: [Docker Volumes with Babun](https://github.com/tiangolo/babun-docker/wiki/Docker-Volumes-with-Babun)

Also, I will try to submit a Pull Request soon to integrate (and modify) my fix in the official toolbox.

**Comment by gary-harpaz** [comment]
Amazing I spent an entire day on this guys! This is very important because without this some dockers can't be run from the command line in Windows. It takes a two steps.
My workaround: __Works in Powershell__

**Comment by Sandipbhole81** [comment]
Hi Docker Team,

Currently I am building an QA automation in robot framework for docker interaction for which I am running "docker exec -it"  or  "sh test.sh" from Robot SSH library Execute Command . When I an trying to run Robot tests from Windows 7 system I am getting return code as msg="cannot enable tty mode on non tty input" 

I have gone through all the thread but could not found any workaround to resolve my issue as I am executing this from Robot framework. 

Can someone please help me...?

docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

Robot logs
Executing command 'sudo docker exec -it containerAlias  cp /tmp/abc.csv /var/tmp'.  
12:07:34.745 INFO Command exited with return code 1.  
12:07:34.746 INFO ${Feed_the_docker} = ['', u'time="2015-11-10T06:37:34Z" level="fatal" msg="cannot enable tty mode on non tty input" '] 

Regards,
Sandip

**Comment by thaJeztah** [comment]
@Sandipbhole81 docker 1.5 is really ancient, and will not get patch fixes.

**Comment by Sandipbhole81** [comment]
Thanks @thaJeztah

**Comment by KristerV** [comment]
in my case using `ssh -t` worked just fine. Actual command: `ssh -t $ip "docker exec -it mongodb mongodump -o dump/$(date +%F)/";`

**Comment by Sandipbhole81** [comment]
Hi There 
I have docker version as below and when  I am running "docker exec -it" or "sh test.sh" from Robot SSH library Execute Command . When I an trying to run Robot tests from Windows 7.1 system I am getting return code as msg="cannot enable tty mode on non tty input".

Can someone please help .?
docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

**Comment by Sandipbhole81** [comment]
@thaJeztah  Can you please provide your inputs on my issue..?

**Comment by wuebbel** [comment]
Just had the same problem on cygwin. For me, using the native ssh client would work:

$ docker exec -it proto /bin/bash
cannot enable tty mode on non tty input
$ docker-machine ssh default docker exec -it proto /bin/bash
cannot enable tty mode on non tty input
exit status 1
$ docker-machine --native-ssh ssh default docker exec -it proto /bin/bash
wuebbel@proto:~$

Probably, the cygwin ssh should be called with the -t argument inside docker. But, as stated, the native ssh will solve my problem.

Best wishes, Frank

**Comment by jeffdm** [comment]
This should be fixed in the Docker QuickStart Terminal - but not in other instances of Git Bash. In that case I think appending `winpty` is the best option.

**Comment by azizur** [comment]
Although this issue has been marked as Windows issue, I got the same issue on OSX.

**Comment by darkn3rd** [comment]
I am having the same problem when running on Ubuntu Trusty Tahr Linux.  It works from the command line, but fails from TeamCity.

**Comment by obimod** [comment]
Make sure you're not appending -t when launching the process from a non-tty environment.

Removing the -t per inotify-invoked docker cmd worked for me.

**Comment by rhoerbe** [comment]
removing -t worked for me as well (centos 7/docker 1.11.2)

**Comment by dargoan** [comment]
@jlsphar & @rhoerbe , it totally worked for me. I was able to just launch the container and in another terminal, I could go & see stuff, modify files etc...  Thanks!

**Comment by f-w** [comment]
Removing -t doesn't work for me

```
x@x MINGW64 /
$ docker run -i <some-docker-image> bash
C:\Program Files\Docker Toolbox\docker.exe: An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create: open //./pipe/docker_engine: The system cannot find the file specified..
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```
