### ISSUE TITLE
Failed to install DockerToolbox-1.8.1c on OS X Yosemite 10.10.5

### ISSUE THREAD

**Issue by daituzhang** [docker/toolbox#140]
Hi,
I was not able to install the dockertoolbox, here are the screenshots of errors:
![screen shot 2015-09-01 at 11 53 41 am](https://cloud.githubusercontent.com/assets/4118473/9610716/e45f30a4-50a0-11e5-8b29-d720dbc898c9.png)
![screen shot 2015-09-01 at 11 53 27 am](https://cloud.githubusercontent.com/assets/4118473/9610680/b4f30ba6-50a0-11e5-94b6-2d47d1b1fce9.png)
![screen shot 2015-09-01 at 11 53 33 am](https://cloud.githubusercontent.com/assets/4118473/9610684/ba759a30-50a0-11e5-8f0b-342cbdee4ac2.png)
![screen shot 2015-09-01 at 11 53 09 am](https://cloud.githubusercontent.com/assets/4118473/9610687/becba9b2-50a0-11e5-8bc9-e23e99e4262f.png)

It seems like unable to create directory because of permission. Is there anyway I can fix it?
Thank you!

**Comment by jeffdm** [comment]
Can you provide the output of:

```
ls -al ~/.docker
```

**Comment by v1k0d3n** [comment]
same issue here. 

<pre>
THEDUDE01:certs v1k0d3n $ ls -asl
total 32
0 drwx------  6 v1k0d3n  staff   204 May 31 11:41 .
0 drwx------  5 v1k0d3n  staff   170 May 31 11:41 ..
8 -rw-------  1 v1k0d3n  staff  1679 May 31 11:41 ca-key.pem
8 -rw-r--r--  1 v1k0d3n  staff  1029 May 31 11:41 ca.pem
8 -rw-r--r--  1 v1k0d3n  staff  1054 May 31 11:41 cert.pem
8 -rw-------  1 v1k0d3n  staff  1679 May 31 11:41 key.pem
THEDUDE01:certs v1k0d3n $ 
<pre>

when you try to read from the dir, it complains about permissions (it's setup as root), so got kicks i 'chown -R v1k0d3n:staff ~/.docker' but the installer forces root again before the migration. possibly part of the issue?

**Comment by v1k0d3n** [comment]
can you try this command manually and let me know if it works?

<pre>
sudo docker-machine create -d virtualbox --virtualbox-import-boot2docker-vm boot2docker-vm docker-vm
</pre>

**Comment by v1k0d3n** [comment]
ok, i don't like this installer at all in it's current state. during the installation process it changes ownership of the ~/.docker directory to root. i don't know if that's supposed to happen, but that causes issues for the Docker QS Terminal after completion. i took a cowboy approach, exported my containers (this was a really old dev docker install anyway), fried the ~./docker directory and tried to re-run and that produced some "fun" results. wouldn't really suggest it. personally, i would stay away from the tools package at the moment.

i upgraded using using the latest pull of machine.

<pre>
JINKITOSXLT01:Downloads bjozsa$ sudo rm -rf ~/.docker/
JINKITOSXLT01:Downloads bjozsa$ docker-machine create --driver virtualbox default
Creating CA: /Users/bjozsa/.docker/machine/certs/ca.pem
Creating client certificate: /Users/bjozsa/.docker/machine/certs/cert.pem
Image cache does not exist, creating it at /Users/bjozsa/.docker/machine/cache...
No default boot2docker iso found locally, downloading the latest release...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.8.1/boot2docker.iso to /Users/bjozsa/.docker/machine/cache/boot2docker.iso...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
To see how to connect Docker to this machine, run: docker-machine env default
JINKITOSXLT01:Downloads bjozsa$ ls -asl ~/.docker/
ls: : Permission denied
JINKITOSXLT01:Downloads bjozsa$ sudo ls -asl ~/.docker/
total 0
0 drwx------   3 root    staff   102 Sep  1 23:43 .
0 drwxr-xr-x@ 52 bjozsa  staff  1768 Sep  1 23:43 ..
0 drwx------   5 root    staff   170 Sep  1 23:43 machine
JINKITOSXLT01:Downloads bjozsa$ sudo chown -R bjozsa:staff ~/.docker/
JINKITOSXLT01:Downloads bjozsa$ 
</pre>

You can at this point rerun the installer...if you really way, but then change the directory permissions again and then the Docker QS Tool and Kitematic will work for you. At least it's a work around for those east coast all-nighters.

v1k out

**Comment by daituzhang** [comment]
@jeffdm 
here is the output:

**Comment by daituzhang** [comment]
@v1k0d3n 
here is the output for sudo docker-machine create -d virtualbox --virtualbox-import-boot2docker-vm boot2docker-vm docker-vm
```Creating CA: /Users/yuluzhang/.docker/machine/certs/ca.pem
Creating client certificate: /Users/yuluzhang/.docker/machine/certs/cert.pem
Creating VirtualBox VM...
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.```
doesn't seem work

**Comment by daituzhang** [comment]
@v1k0d3n 
I followed your Possible workaround solution, I am able to to run docker quickstart terminal, but not the Kitematic(I guess it's not a big of deal), same error message showed up:
```
/Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: stat /Users/<redacted>/.docker/machine/certs: permission denied
```
The installation failed message still came up, It's probably because Kitematic still failed.

**Comment by v1k0d3n** [comment]
@daituzhang, change the permissions after you've run the installer.

$ sudo chown -R yuluzhang:staff ~/.docker

and it should work. let me know if that does the trick.

**Comment by v1k0d3n** [comment]
and if you notice...you can  probably run the DQST, however you're likely getting the error message:

open /Users/yuluzhang/.docker/machine/machines/default/config.json: permission denied

is that true?

**Comment by daituzhang** [comment]
@v1k0d3n I have changed permission:
```
sudo ls -l ~/.docker                   
total 0
drwx------  5 yuluzhang  staff  170 Sep  3 15:58 machine
```
And running the installer change the permission back  -_-|||||||
```
sudo ls -l ~/.docker
total 0
drwx------  5 root  staff  170 Sep  3 15:58 machine
```

**Comment by v1k0d3n** [comment]
That's the problem. After the installer has finished...change the permissions back and it will work! :-)

It leaves the permissions...

**Comment by daituzhang** [comment]
Great thanks! Yes it works!

**Comment by jeffdm** [comment]
This should be fixed in the current version of the Toolbox (post-install script was updated to correctly change permissions on `~/.docker`. Please re-open this issue if it's still observed.

Thanks!
