### ISSUE TITLE
Migration from boot2docker errors out (but not fails) due to DOCKER_TLS=no

### ISSUE THREAD

**Issue by sosedoff** [docker/toolbox#141]
I had a boot2docker machine running with docker TLS turned off, so the service was listening on tcp://0.0.0.0:2375 (instead of 2376). After installing toolbox it prompted if i wanted to migrate the existing boot2docker vm and i hit yes. Waited a bit until all steps are completed, but got an error on the final step.
Looking at the logs i noticed that migration script tried to connect to docker on port 2376, which did not work.  

I think it would be useful to detect which port docker is currently running during migration and attempt to use that. Some people might have docker running without TLS.

P.S Sorry i dont have migration logs, did migration a couple of days ago.

**Comment by pbitty** [comment]
I had the same issue.  Here are the [migration logs](https://gist.github.com/pbitty/22f60d0bd7be6df34c70)

**Comment by mchiang0610** [comment]
@sosedoff @pbitty seems like it's the same migration error that others are seeing. Merging this with #153 for discussion. 

Thanks!
