### ISSUE TITLE
Mac OS X Installer doesn't support more than one user

### ISSUE THREAD

**Issue by fsamin** [docker/toolbox#142]
## Description of problem:

Toolbox fails on VM Migration with the following message.
<img width="618" alt="capture d ecran 2015-09-01 a 20 07 04" src="https://cloud.githubusercontent.com/assets/684151/9612296/1479fa32-50e5-11e5-840b-0a152a9b465b.png">

## How to reproduce:

The installation process has been launched while another user (`othery`) was previously logged on another session (but has nothing to do with docker).

## Actual Results:
I'm surprised that the `.docker` directory in my home directory (`/home/fsamin`) belongs to the other user `othery`

<img width="636" alt="capture d ecran 2015-09-01 a 20 17 41" src="https://cloud.githubusercontent.com/assets/684151/9612548/8ca9d2b0-50e6-11e5-84b5-fb22e6715581.png">

So obviously the `mkdir` command `mkdir /Users/fsamin/.docker/machine/certs` failed with `permission denied` because the .docker directory hasn't been created with the correct owner.

<img width="640" alt="capture d ecran 2015-09-01 a 20 20 11" src="https://cloud.githubusercontent.com/assets/684151/9612624/fb0759ee-50e6-11e5-90cc-bcd250108414.png">

## Additional info:
`uname -a`: `Darwin MacBookPro.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64`
filename:  `DockerToolbox-1.8.1c.pkg`

Let me know if your want more details

**Comment by v1k0d3n** [comment]
see if my work around in #140 works for you, and let me know.

**Comment by fsamin** [comment]
Finally i install the previous release with no issue. DockerToolbox-1.8.1b.pkg

**Comment by v1k0d3n** [comment]
the workaround didn't help at all? i think all you have to do is change permissions before you do the migration (in the pause just before the migration).

**Comment by jeffdm** [comment]
Thanks!

**Comment by jeffdm** [comment]
This should be fixed in the current version of the Toolbox (post-install script was updated to correctly change permissions on `~/.docker`. Please re-open this issue if it's still observed.

Thanks!
