### ISSUE TITLE
Illegal Hardware Instruction

### ISSUE THREAD

**Issue by tabr0201** [docker/toolbox#143]
I installed docker toolbox and it looks like something went wrong with docker-compose.

~ ❯ docker -v                                                                 ⏎
Docker version 1.8.1, build d12ea79
~ ❯ docker-machine -v
docker-machine version 0.4.1 (e2c88d6)
~ ❯ docker-compose -v
[1]    1205 illegal hardware instruction  docker-compose -v
~ ❯ docker-compose -v                                                         ⏎
[1]    1257 illegal hardware instruction  docker-compose -v
~ ❯ docker-compose -v                                                         ⏎
[1]    1308 illegal hardware instruction  docker-compose -v

**Comment by mchiang0610** [comment]
@tabr0201 thanks for reporting this.

**Comment by mchiang0610** [comment]
Merging with #159
