### ISSUE TITLE
Migration fail on Windows 7

### ISSUE THREAD

**Issue by chevdor** [docker/toolbox#145]
```
C:\Program Files\Docker Toolbox>"C:\Program Files\Git\bin\sh.exe" --login -i migrate.sh 
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
Creating CA: C:\Users\name\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\name\.docker\machine\certs\cert.pem
```

[toolbox-migration-logs.txt | uploaded via ZenHub](https://files.zenhub.io/55e834a192a7fa2e7b5ade20)

**Comment by mchiang0610** [comment]
@chevdor Thanks for the report. 

Can you open virtualbox. 
1. If you see a VM named "default"- please right click on it and remove it. - Delete all files. 
2. Restart the Docker Toolbox installer.

**Comment by chevdor** [comment]
@mchiang0610 sure. I don´t have access to the machine where I got the issue at the moment but I will test on Monday.

**Comment by chevdor** [comment]
hi @mchiang0610 
So, for the record: VirtualBox v5.0.2 r102096

1. I start with Docker not running.
2. default VM deleted
3. running docker tools installer. Selecting only Docker* components
4. running docker toolbox\start.sh

```
Creating Machine default...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
Looks like something went wrong... Press any key to continue...
```

**Comment by mchiang0610** [comment]
@chevdor Thanks! Merging all these into one single issue:  #153 where we can discuss and help there.
