### ISSUE TITLE
Windows 7 error

### ISSUE THREAD

**Issue by edpichler** [docker/toolbox#146]
Is this a bug or it's not supported on my windows version?

![captura_de_tela_090315_105229_am](https://cloud.githubusercontent.com/assets/358696/9660014/e62649e2-5229-11e5-8f4e-835bfd50ab5b.jpg)

![captura_de_tela_090315_105328_am](https://cloud.githubusercontent.com/assets/358696/9660048/03d68e48-522a-11e5-9683-acb8dfe613a9.jpg)

Is there any docker I can play on my Win. version?

**Comment by mchiang0610** [comment]
@edpichler Can you check if you have vt-x enabled on your PC?

**Comment by edpichler** [comment]
@mchiang0610 I just enabled it and it worked!
