### ISSUE TITLE
On step 6 of installation I had to interrupt the launching of the VM and Docker Quickstart Terminal could not recover.

### ISSUE THREAD

**Issue by chamunks** [docker/toolbox#148]
https://docs.docker.com/mac/step_one/ 
I made it to step 6 and due to my impatience I ended up interrupting the launching of the "Quickstart Terminal" and then would only get error 255.  There was no suggestion of how to repair this available.  Kitematic had a similar issue where the instantiation of the default VM was interrupted so it offered to delete the default VM and attempt setup again.  

My suggestion is potentially to add some prompt when it launches to detect this kind of failure.

**Comment by chamunks** [comment]
My solution was to run 

    docker-machine ls
which resulted in:

    [chamunks@imac-spring-2015]  ~  $ docker-machine ls
    error getting URL for host default: exit status 255
    NAME      ACTIVE   DRIVER       STATE     URL   SWARM
    default            virtualbox   Timeout
    dev                virtualbox   Stopped
    [chamunks@imac-spring-2015]  ~  $ docker-machine rm default dev
    Successfully removed default
    Successfully removed dev

Which resulted in my ability to finally launch `Docker Quickstart Terminal`.

**Comment by jeffdm** [comment]
Thanks!

**Comment by mchiang0610** [comment]
@chamunks Thanks for this. Going to close this as it's fixed.
