### ISSUE TITLE
Docker Quickstart Terminal doesn't prompt me which terminal app I would like to use on launch. 

### ISSUE THREAD

**Issue by chamunks** [docker/toolbox#149]
Right now it uses the default built in `Terminal` application which Mac OS X Yosemite uses.  But I would like for this to run in my iTerm instance.  So I have to copy and paste the script over that runs when the OS X Terminal launches into my iTerm window.  

Finally there's no clear suggestion once the Docker Quickstart Terminal script finishes how to launch it again but from the console.  This could potentially be made more user friendly.

**Comment by Julime** [comment]
+1

**Comment by nicolasclaudon** [comment]
Right now i am lauching in iterm 
````
. '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'

**Comment by mchiang0610** [comment]
@chamunks @nicolasclaudon There is a PR in the works: https://github.com/docker/toolbox/pull/155 

Closing this for now.

**Comment by chamunks** [comment]
Excellent thank you very much :) you guys are awesome!
