### ISSUE TITLE
Docker Tookbox 1.8.1c Windows Install Error

### ISSUE THREAD

**Issue by cgers** [docker/toolbox#150]
Installer: DockerToolbox-1.8.1c.exe
Target Environment: Windows 8.1

Setup Error: "Failed to created docker machine cache dir" when running the application setup as an administrator.

![setuperror](https://cloud.githubusercontent.com/assets/14121781/9677902/a49f32e8-52df-11e5-979a-6d077c97f167.png)

When I click OK on the error above this error follows:

![movingfilefailed](https://cloud.githubusercontent.com/assets/14121781/9677971/72c7d95e-52e0-11e5-9b79-3de46d8a083d.png)

I would like to include log files but don't know where to locate them.

Thanks
Craig

**Comment by mchiang0610** [comment]
@cgers Thanks for reporting this. This is the first time we've seen this issue. 

Are you able to reproduce this on other computers?

**Comment by cgers** [comment]
Hi Micheal

 

I will see if I am able to replicate it on another computer.

 

Sincerely

Craig Gers

**Comment by biligeny** [comment]
The issue even occur on 1.8.2a release on windows7, please have a check

**Comment by biligeny** [comment]
I have tried 2 different PC/windows7 but both are failed with same error above.

**Comment by mchiang0610** [comment]
@biligeny Just to make sure...you are not connected through proxies / VPNs, and also has VT-X enabled in the BIOS?

**Comment by biligeny** [comment]
Hi,

I have enabled VT in BIOS, but in behind proxy.

On the otherhand, I have tried at home without proxy, this time termial
started correctly, but when i did docker run hello-world, got error saying
vm engine not started.

really have no idea how to get over those problem.

2015年9月25日(金) 午後9:29 Michael Chiang <notifications@github.com>:

**Comment by mchiang0610** [comment]
@biligeny When you are home without a proxy. Open up virtualbox and remove the "default" VM by choosing delete all files. 

Run the installer again without proxy.

**Comment by biligeny** [comment]
thanks for the tips.

i will try the 1st tomorrow morning.
isn't there any workaroud for the proxy interference issues?

2015年9月25日(金) 午後11:32 Michael Chiang <notifications@github.com>:

**Comment by mchiang0610** [comment]
@biligeny There is a workaround 

```
create a windows batch script "C:\Program Files\Docker Toolbox\kitematic_proxy.cmd" and insert following script and replace "YOUR_PROXY" with the http://host:port of your proxy
-------------
set proxy=YOUR_PROXY
SET HTTP_PROXY=%proxy%
SET HTTPS_PROXY=%proxy%
for /f %%i in ('docker-machine.exe ip default') do set DOCKER_HOST=%%i
SET NO_PROXY=%DOCKER_HOST%
set DOCKER_HOST=tcp://%DOCKER_HOST%:2376
cd Kitematic
Kitematic.exe
-------------


Btw. if you have generally an enterpise proxy between your station and internet you also shall configure this proxy in your boot2docker vm host:

Because of worng keyboard layout and problems with special key in oracle virtual box native console i connected with WinScp on my docker host using DOCKER_HOST IP login user:docker and pwd:tcuser. Then edit the profile to add proxy settings:
-------------
sudo vi /var/lib/boot2docker/profile

Press 'i' to start editing mode
export HTTP_PROXY=http://your.proxy.name:8080
export HTTPS_PROXY=http://your.proxy.name:8080


Press 'escape' and then type ':x' to save and exit the file. Now restart your vm to make proxy active
```

**Comment by blitzd** [comment]
Receiving this same error on Windows 10 with Docker Toolbox 1.8.3, I tried removing the default vm and uninstalling/reinstalling, but there's no difference.

**Comment by mchiang0610** [comment]
Merging with #153

**Comment by dustinmoris** [comment]
I am receiving the same error on Windows 10 with Docker Toolbox v1.11.2

**Comment by chseeling** [comment]
same error on windows 8,1 system

**Comment by Billy-** [comment]
Having this issue with Win7 + Toolbox 1.11.2. Tried two different Win 7 pc's with the same error and varying levels of functionality once install has finished (always with the same error during install)
