### ISSUE TITLE
Toolbox setup fails when only selecting Kitematic.

### ISSUE THREAD

**Issue by FunTimeCoding** [docker/toolbox#151]
When I installed DockerToolbox-1.8.1c.pkg and selected Customize, I only chose Kitematic because the other dependencies I already had installed using brew.
 
After it was done the installer said it failed, however, the .app bundle is in /Applications/Docker and seems to work.

**Comment by mchiang0610** [comment]
@FunTimeCoding Thanks for reporting this. May I ask what the error message you received? 

Is working now that you are starting from the applications folder?

**Comment by FunTimeCoding** [comment]
Yes.

**Comment by FunTimeCoding** [comment]
The error message was that an error occurred. I don't have the exact wording anymore. I could try to reproduce it if you like.

**Comment by mchiang0610** [comment]
@FunTimeCoding Yes, please. That would be super helpful. I'm unable to consistently reproduce it on our side.

**Comment by FunTimeCoding** [comment]
http://i.imgur.com/rdD215g.png

**Comment by jeffdm** [comment]
This should be fixed in https://github.com/docker/toolbox/releases/tag/v1.8.1d, which doesn't allow you to install Kitematic standalone anymore.

**Comment by FunTimeCoding** [comment]
I believe this installer is too much simplification for my taste. For all I know I'll end up unable to install or update VirtualBox on itself without causing complications with the toolbox. So I hope the GH release archive and brew cask install way will remain.

**Comment by mchiang0610** [comment]
@FunTimeCoding We don't have any plans to pull GH archive or brew cask. That being said, brew cask is not directly maintained by us, and is by the community.
