### ISSUE TITLE
Error when installing dockertoolbox on Mac using brew cask

### ISSUE THREAD

**Issue by m1n1b00** [docker/toolbox#152]
I am getting an error when trying to install docktoolbox using brew cask.  I've verified sudo rights are working.

Below is the command I executed at the terminal and the resulting output:

$ brew cask install dockertoolbox
==> Satisfying dependencies
==> Installing Cask dependencies: virtualbox
virtualbox ...
already installed
complete
==> Downloading https://github.com/docker/toolbox/releases/download/v1.8.1c/DockerToolbox-1.8.1c.pkg
Already downloaded: /Library/Caches/Homebrew/dockertoolbox-1.8.1c.pkg
==> Running installer for dockertoolbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is Docker Toolbox
==> installer: Upgrading at base path /
==> installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/dockertoolbox/1.8.1c/DockerToolbox-1.8.1c.pkg>", "-target", "/"]

==> Output of failed command:
installer: Package name is Docker Toolbox
installer: Upgrading at base path /
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

==> Exit status of failed command:
#<Process::Status: pid 3361 exit 1>

**Comment by mchiang0610** [comment]
@m1n1b00 Thanks for reporting this. We are looking into this. cc/ @jeffdm @nathanleclaire

**Comment by mchiang0610** [comment]
Looking into this further. Seemed like it was caused by migration issue. Merging with #153 

Thanks!

**Comment by tdensmore** [comment]
Getting an error as well, but it is a little different... it complains about **Virtual box**.

`==> installer: Error - The installer has detected running virtual machines. Please shut down all running VirtualBox machines and then restart t
Error: Command failed to execute!`

**Solution**: kill all running Virtual Box processes

`ps -ae | grep VB
kill -9 <VB PID>`

**Comment by kevinSuttle** [comment]
Curious as to what the level of official Docker support for the Caskroom formula is here.
