### ISSUE TITLE
disk is full - seems all containers share the same root space.

### ISSUE THREAD

**Issue by SydOps** [docker/toolbox#157]
I got strange issue and need confirm if this is toolbox issue. Seems all containers share the same root space. 

```
$ docker run -ti ubuntu bash
root@c5441582a2a5:/# df -k
Filesystem     1K-blocks    Used Available Use% Mounted on
none            19049892 8879580   9179588  50% /

$ docker run -ti centos:centos6 bash
[root@3935aa86a02d /]# df -k
Filesystem     1K-blocks    Used Available Use% Mounted on
none            19049892 8880188   9178980  50% /

```
With more and more images pulled and container running on my Macbook, sometimes the root size is still 19GB, but used size is up to 19GB already for a new container, when i try to start other containers, I get disk full and read-only issue. 

Is the issue in boot2docker iso image or it is new issue in toolbox?

Can I set a bigger root size for docker?

**Comment by SydOps** [comment]
Anyone has the same issue?

**Comment by SydOps** [comment]
I recreate the machine with option `--virtualbox-disk-size "100000"` , I can see the disk storage is 100GB in virutalbox, but when login the container, it is only 1.8GB now. 

```
$ docker run -ti --rm ubuntu bash
root@371c0b5df09f:/# df -h /
Filesystem      Size  Used Avail Use% Mounted on
none            1.8G  496M  1.3G  28% /
root@371c0b5df09f:/#
```
Whatever I set to any size, it always 1.8GB, but if I didn't set this option, it is back to 20GB.

**Comment by SydOps** [comment]
I fix this issue by myself, after remove the old machine, and re-create for several times, I got the right size. 

Not sure, why this is happen, but I am fine now.

**Comment by tiangolo** [comment]
I had the same problem, I think the default shouldn't be only 20 GB of disk, knowing that VirtualBox creates a dynamic disk size, it only takes as much (real) space as it is needing, limited by a maximum of the specified disk size.

In my case, after having several images built and working I got my VM disk space full, and having to re-build every image with a not-so-speedy connection is sort of painful.

I will send a Pull Request increasing the default size of the default machine to 1 TB. As I said, VirtualBox will start with only what it needs (200 MB) but the Virtual Machine will think that it has 1 TB to use and won't stop working just because of this.

**Comment by tiangolo** [comment]
@SydOps Can you re-open this issue? (I don't know if it's possible)

I guess that would make the maintainers pay more attention to the problem, helping them know that this could still be improved...

**Comment by SydOps** [comment]
Re-open this issue as required by @tiangolo

**Comment by tiangolo** [comment]
Thanks for reopening @SydOps, great!

**Comment by mchiang0610** [comment]
@SydOps @tiangolo May I ask what images / your use cases are to hit the 20GB limit? Trying to figure out if there are other issues that we should be addressing (ie. easier volume mounting etc.)

**Comment by SydOps** [comment]
@mchiang0610 

As I show in the first post, every time, when you pull a new image, the available space will reduce, until all space used out. 

If you pull  50~ 100 different images based on ubunbu/centos/debian or build several big images by yourself, you will get the dis full issue.

**Comment by mchiang0610** [comment]
@SydOps Just wondering if you are using all the images? Not wanting to remove them?

**Comment by SydOps** [comment]
@mchiang0610 

I normally keep pulling new images if required, never delete them, because I have enough space on my laptop. But this 20GB space limitation is really annoying.

**Comment by tiangolo** [comment]
I think that also, the default of preserving the docker volumes of removed containers helps increasing the space.

As I understand, to remove the docker volumes attached to a container you have to explicitly set the "-v" flag, as in:

```
docker rm -v my_container
```

I'm referring to the volumes auto-created for each container, not the volumes "mapped" from local directories. Sadly both have the same name (if I'm not wrong).

Nevertheless, I don't even know how to recover the data from a removed container, even if it is there, preserved in some stray docker volume. And I don't know either how to remove docker volumes of already removing containers. 

I ended up using this: https://github.com/chadoe/docker-cleanup-volumes, but it's not even an "official" solution. I haven't read and understand the code from that repo, but it's 147 lines, so I don't think it's an easy task to do by hand after you removed a container forgetting the "-v" flag. If it actually is an easy task with Docker, I think it's quite hidden in the docs (that repo has 410 stars).

----

Either way, 20GB is a very, very low hard limit, even if you always remember to remove your containers with the "-v" flag and have a very clean / controlled Docker environment. I had just about 5 - 10 images and some containers based on them when I hit the limit and had to start from scratch in a newly created docker-machine.

I'm not completely sure about the images I was using in that machine, but it was probably 

* a custom Dockerfile based on some Redmine to integrate plug-ins and a DB dump 
* another custom (fast and dirty) Dockerfile to build [Echonest echoprint-server](https://github.com/tiangolo/echoprint-server) 
* possibly some Drupal or Wordpress with MySQL 
* and possibly some Django-nginx-uwsgi

**Comment by tiangolo** [comment]
@SydOps As the PR https://github.com/docker/toolbox/pull/203 was merged, I think you can close this issue now.
