### ISSUE TITLE
Toolbox installs Compose build not compatible with old Macs

### ISSUE THREAD

**Issue by iBobik** [docker/toolbox#159]
This issue describes how to build compose for older Macs: https://github.com/docker/compose/issues/1885

Toolbox should do it automatically.

**Comment by mchiang0610** [comment]
@iBobik Thanks for reporting this.

**Comment by iBobik** [comment]
No chance. I am new in whole Docker ecosystem and things described in the issue are at the edge of my understanding.

**Comment by mchiang0610** [comment]
Thanks! Going to merge this issue with the compose issue since it's something that's related to compose - Toolbox merely copies the binaries. 

https://github.com/docker/compose/issues/271

**Comment by antek-drzewiecki** [comment]
So what is the solution? Install compose manually with brew / pip / fig?
Arn't this dependencies for old macs, to install the toolbox tool chain properly?

**Comment by GabLeRoux** [comment]
[Install using pip](https://github.com/docker/compose/blob/master/docs/install.md#install-using-pip)

**Comment by iBobik** [comment]
Yes install it by PIP. And be careful to configure PATH properly, so
binaries from PIP will have bigger priority than that installed by Toolbox.

Is there anybody who understands it enough to make PR to docker/compose
project?



Jan Pobořil

2015-10-26 12:08 GMT-05:00 Gabriel Le Breton <notifications@github.com>:
