### ISSUE TITLE
In light of #155 being closed, can there be a command alias created for Docker Quickstart Terminal

### ISSUE THREAD

**Issue by chamunks** [docker/toolbox#161]
Because as it stands the default behavior of needing to launch it in whatever terminal session you're planning to work within is a bit jinky by default it would be nice to have a nice pretty command that might put it into a tmux / screen session or something.

Please tag this for Mac

**Comment by mchiang0610** [comment]
@chamunks Hey, thanks for this! 

The reason why that was closed is because it's in the works. Take a look here:  https://github.com/docker/toolbox/pull/155 

Thanks!

**Comment by chamunks** [comment]
@mchiang0610 the reason I opened this ticket wasn't some passive aggressive attempt to re-hash a closed ticket.  It was to suggest a new improvement.  

My suggestion is to potentially create a command alias upon installation which would basically just wrap around the path to the shell script so its easier to access.
