### ISSUE TITLE
Docker Quickstart Terminal is unable to connect to the running VM

### ISSUE THREAD

**Issue by vandamon** [docker/toolbox#162]
I am using Windows 7.When I start the default VM from the Docker Quickstart Terminal, VirtualBox shows the VM has started successfully and is running (I can run Docker commands on it), but the Docker Quickstart Terminal seems to be unable to connect to it. 

![vm_running](https://cloud.githubusercontent.com/assets/1415261/9752704/f8418dca-56d0-11e5-96fc-e18ba8b232ed.png)

```

$ docker-machine ls
```
throws this output
```
NAME      ACTIVE   DRIVER       STATE     URL   SWARM
default            virtualbox   Timeout
```
and
```
$ docker version
```
shows
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      windows/amd64
Get http://127.0.0.1:2375/v1.20/version: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it..
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

I have already tried changing the VB network adapter IP and deleting it.

When I the start the Docker Quickstart Terminal for the first time, I get this error:

```
Unexpected error getting machine url: exit status 255
```

I am using the VirtualBox that comes with Docker.

Thanks for any help in advance.

**Comment by mchiang0610** [comment]
@vandamon Thanks for this. This is the same issue as the exit 255 bug we are looking into. 
Merging the bug there.

Please discuss in: #66 

We are aware of this issue, and are looking into it. The reason why it's taking a lot of time is because this issue is very hard to isolate. 

Thanks.

**Comment by ropstah** [comment]
@vandamon @mchiang0610 - don't know if this issue is still relevant, but I experienced the same problems and this was simply due to not starting the Docker Terminal as Administrator. I don't think that the application needs Administrator rights, but I believe it has to align with the user running the VM and perhaps environment variables.

**Comment by Waog** [comment]
closing the virtual box window worked for me
