### ISSUE TITLE
Unable to mount volumes on Windows

### ISSUE THREAD

**Issue by bweston92** [docker/toolbox#165]
Related to dduportal-dockerfiles/docker-compose#16

```
bash.exe"-3.1$ docker run --rm -it -v $(pwd):"/workspace" denisura/phpmd
invalid value "d:\\;C:\\Program Files (x86)\\Git\\workspace" for flag -v: bad mount mode specifie
d : \Program Files (x86)\Git\workspace
See 'c:\Program Files\Docker Toolbox\docker.exe run --help'.
bash.exe"-3.1$ docker run --help
```

Take note `C:\\Program Files (x86)\\Git` is where bash is so `workspace` is being appended to my bash location.

**Comment by austin881** [comment]
The temporary fix on Windows is avoid using `"$(pwd)"` and provide absolute paths with an extra `/` in front of them. 

From the *Git Bash* Docker Quickstart Terminal...
```
$ docker run -it --rm -v //c/Users/your/path/to/app:/app -v //var/run/docker.sock:/var/run/docker.sock dduportal/docker-compose up -d
```

**Comment by mchiang0610** [comment]
@austin881 Thanks for the suggestion. 

@bweston92 Does that help? Unfortunately this is more of a docker issue. I will pass it on to the rest of the Docker team. The Toolbox worked as an installer to get Docker started. 

Thanks!

**Comment by byrne-yan** [comment]
@austin881 double-slash work around seems incomplete:
no error report when running docker run, however files in my workspace disappear in workspace in container

test code:
```
mkdir -p /c/testdir
cd /c/testdir
touch hello.txt
docker run -it -v //c/testdir:/home/testdir ubuntu bash
cd /home/testdir
ls
```
no hello.txt file exists
```
touch world.txt
exit
ls
```
no world.txt found!
