### ISSUE TITLE
Bad link in toolbox online tutorial

### ISSUE THREAD

**Issue by mibinn** [docker/toolbox#167]
Hi,

didn't find a better place to inform that the link to "step four" at the end of "step three" for windows installation redirect to the mac tutorial :

https://docs.docker.com/windows/step_three/ => https://docs.docker.com/mac/step_four/

Not a trouble for me but some rookies could be lost when switching from Win instructions to Mac instructions.

Christophe

**Comment by mibinn** [comment]
Oh! and there's stil some reference to 'mac' instead 'windows" in the text : 

https://docs.docker.com/windows/step_four/ : 

*...You also just used Linux from your Mac yet again...*

A cool, but a little bit expensive, resolution would be to deliver a Mac to every docker toolbox user   ;)

Christophe

**Comment by jeffdm** [comment]
Thanks!

**Comment by jeffdm** [comment]
Should be fixed now, thanks again!
