### ISSUE TITLE
Docker QuickStart Terminal doesn't work on the  Window 7 machine !!!

### ISSUE THREAD

**Issue by wzymaster** [docker/toolbox#168]
I downloaded Docker Toolbox and select full installation. After installation, I tried to start Dockerr QuickStart Terminal like the below sequences : 

Start > All Programs > Docker > Docker Quickstart Terminal > ...opens start.sh in Wordpad, nothing starts up.

The screenshots are attached.
![docker-quickstart-terminal](https://cloud.githubusercontent.com/assets/2967108/9769777/30e3743a-56fa-11e5-8f87-165c3b39052e.jpg)
![window](https://cloud.githubusercontent.com/assets/2967108/9769778/30e42da8-56fa-11e5-829c-39ee8b87ffd3.jpg)

**Comment by jeffdm** [comment]
Is this with Toolbox `1.8.1c`?

**Comment by jeffdm** [comment]
Also, did you install Git with the Toolbox?

**Comment by wzymaster** [comment]
@jeffdm Yes, it's a full installation. Git for windows is installed.

**Comment by jeffdm** [comment]
This should be fixed in the next release, 1.8.1d. I just pushed a fix to master

**Comment by jeffdm** [comment]
This should be fixed in https://github.com/docker/toolbox/releases/tag/v1.8.1d
