### ISSUE TITLE
docker run --net=host not usable from toolbox ?

### ISSUE THREAD

**Issue by tdeheurles** [docker/toolbox#171]
Hi,
I'm trying to run a container with `--net=host` but it seems the option is not available with toolbox :

Context :
- Windows7
- Toolbox

**I create a container from toolbox :**
```
docker run -ti --net=host ubuntu bash
docker: --net: invalid net mode: invalid --net: host.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```

The help say to give default to the --net option.

so : 
```
docker run -ti --net=default ubuntu bash
```
and I have no error.

But when I test my container, the network is not shared (container/VM default).

**I tried another way :**
```
docker-machine ssh default
docker run -ti --net=host ubuntu bash
``` 
and that time it works, the network is shared.

So is there a reason that we cannot use the `--net=host` from toolbox docker ?
`I'm not talking to share the windows network but the VM one with the container one.`

**Comment by mchiang0610** [comment]
@tdeheurles Thanks for this. I will try to reproduce it on a Windows environment. 

In the mean while, may I ask what you looking to do?

**Comment by tdeheurles** [comment]
I was more in an exploration than a really use case.
I'd like to know the differences between linux docker and the toolbox. I didn't find a documentation on that.
It seems that this command as been written to not work exactly the same as the original one.

My feeling was toolbox say `default` as the name of the machine in order to not be mistaken with `host`. As host can be understand as the `windows host`.

`--net=host` is used in a lot of example through the net. It can be a problem for lots of people no ?
In another way, I'm maybe just making an error with my code.

**Comment by gmanfunky** [comment]
Docker 1.8.x client on windows has a bug where it will not let you use ```--net=host```.

It looks like it has been fixed in the source tree a while ago but is pending another release. Probably ```1.9.0``

**Comment by tdeheurles** [comment]
@gmanfunky great, thanks for information ^^
==> Will close issue after test on that version

**Comment by takashi209** [comment]
@tdeheurles 
docker1.9.0 was released as follows
https://github.com/docker/toolbox/releases/tag/v1.9.0

```
$ winpty docker run -ti --net=host ubuntu bash
root@default:/#
```
Please check it

**Comment by tdeheurles** [comment]
And it works ! ^^
Great. Thank you !
