### ISSUE TITLE
Toolbox should upgrade docker instead of getting users to manually type docker-machine upgrade

### ISSUE THREAD

**Issue by mchiang0610** [docker/toolbox#175]
Toolbox should upgrade docker instead of getting users to manually type docker-machine upgrade.

**Comment by jeffdm** [comment]
+1 Agreed, best place to do this would be where the Boot2Docker migration takes place!

**Comment by mariuslundgard** [comment]
+1

**Comment by dideler** [comment]
It seems like this is already happening in DockerToolbox 1.9.1?

![screenshot 2015-11-24 12 44 27](https://cloud.githubusercontent.com/assets/497458/11367087/3d56e996-92a9-11e5-822e-8f8119143c6f.png)

**Comment by jeffdm** [comment]
It is! Sorry - this issue should be closed. Thanks!
