### ISSUE TITLE
'Docker Quickstart Terminal App' Destroy All Current Images

### ISSUE THREAD

**Issue by fzx** [docker/toolbox#176]
I have setup docker 1.8 ok in my macbookpro, and today I accidently select the 'Docker Quickstart Terminal App' and all current images in my disk are destroyed and I have to rebuild them.

**Comment by jeffdm** [comment]
We're you using the Docker Quickstart Terminal previously? It's possible it's using a different VM

**Comment by fzx** [comment]
I did not use Docker Quickstart Terminal previously.

**Comment by jeffdm** [comment]
Ah I see. The quickstart terminal creates a separate VM named `default`, which did not carry forward your previous VM.  Sorry for the inconvenience there.

If you were using Boot2Docker previously, you can remove the `default` vm via `docker-machine rm -f default` and re-run the toolbox installer to migrate your Boot2Docker VM.

It should be relatively simple to switch to using this new VM. Re-run any `docker` commands you ran on your previous VM. Commands such as `docker export` and `docker import` may also help. Let me know if there's anything else I can do to help.
