### ISSUE TITLE
A new install should reset/delete ~/Library/Application Support/DockerToolbox/default_terminal

### ISSUE THREAD

**Issue by josephwinston** [docker/toolbox#179]
I'm having iTerm2 errors `iTerm got an error: Can’t get «class Ctrm». (-1728)` due to using a newer version of iTerm2 when I invoke ` /Applications/Docker/Docker\ Quickstart\ Terminal.app`  A new install does not replace/reset/delete   ~/Library/Application Support/DockerToolbox/default_terminal thus the error remains until this file is manually removed.

**Comment by jeffdm** [comment]
Merging with https://github.com/docker/toolbox/issues/178
