### ISSUE TITLE
In mac , How to close toolbox process and vbox ?

### ISSUE THREAD

**Issue by rfyiamcool** [docker/toolbox#181]
In mac , How to close toolbox process and vbox ?

**Comment by fsamin** [comment]
you should try `$ docker-machine stop default`

**Comment by mchiang0610** [comment]
@rfyiamcool 

After installing, you can stop via command line through ```docker-machine stop default``` 

By default, closing Kitematic will stop the VM as well. 

Closing Virtualbox will work as well.

**Comment by pleerock** [comment]
how to do it when its installed via toolbox? there is no more machine named default, no running machines at all when running `docker-machine ls`
