### ISSUE TITLE
Kitematic and Docker Quickstart Terminal don't share VM

### ISSUE THREAD

**Issue by iBobik** [docker/toolbox#184]
I use Kitematic and Docker from console (started by Docker Quickstart Terminal), both installed by Docker Toolbox on OS X. I figured out both tools starts their own virtual machine in VirtualBox even they could share it, couldn't they?

Kitematic starts "dev" VM, Terminal starts "default" VM.
![snimek obrazovky 2015-09-14 v 21 59 01](https://cloud.githubusercontent.com/assets/614232/9866737/d51cefce-5b2b-11e5-8593-414fe2273670.PNG)

**Comment by mchiang0610** [comment]
@iBobik Kitematic has been using the "default" VM for a while now. Install the new Kitematic from Toolbox, and it'll use "default". 

Thanks!

**Comment by iBobik** [comment]
Aha, sorry. It seems I have some old config.



Jan Pobořil

2015-09-15 0:12 GMT-05:00 Michael Chiang <notifications@github.com>:
