### ISSUE TITLE
postinstall step fails on MacOS

### ISSUE THREAD

**Issue by volker-fr** [docker/toolbox#186]
I ran into some issues while executing `sudo -E -- /usr/sbin/installer -verbose -pkg ~/Downloads/DockerToolbox-1.8.2.pkg -target /` (similar to `brew cask install dockertoolbox`)

From `/var/log/install.log`:
```
Sep 15 10:43:36 myuser-mac.local installd[36091]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.BYLFGD/Scripts/io.boot2dockeriso.pkg.boot2dockeriso.qonURZ
Sep 15 10:43:36 myuser-mac.local installd[36091]: ./postinstall: chown: myuser:staff: No such file or directory
Sep 15 10:43:36 myuser-mac.local installd[36091]: ./postinstall: chown: myuser:admin: No such file or directory
Sep 15 10:43:36 --- last message repeated 2 times ---
[...]
Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “DockerToolbox-1.8.2.pkg”." UserInfo=0x7fb2834a2770 {NSFilePath=./postinstall, NSURL=file://localhost/Users/myuser/Downloads/DockerToolbox-1.8.2.pkg#boot2dockeriso.pkg, PKInstallPackageIdentifier=io.boot2dockeriso.pkg.boot2dockeriso, NSLocalizedDescription=An error occurred while running scripts from the package “DockerToolbox-1.8.2.pkg”.} {
        NSFilePath = "./postinstall";
        NSLocalizedDescription = "An error occurred while running scripts from the package \U201cDockerToolbox-1.8.2.pkg\U201d.";
        NSURL = "file://localhost/Users/myuser/Downloads/DockerToolbox-1.8.2.pkg#boot2dockeriso.pkg";
        PKInstallPackageIdentifier = "io.boot2dockeriso.pkg.boot2dockeriso";
    }
Sep 15 10:43:36 myuser-mac.local installer[58977]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “DockerToolbox-1.8.2.pkg”." UserInfo=0x7ff34046f450 {NSFilePath=./postinstall, NSURL=file://localhost/Users/myuser/Downloads/DockerToolbox-1.8.2.pkg#boot2dockeriso.pkg, PKInstallPackageIdentifier=io.boot2dockeriso.pkg.boot2dockeriso, NSLocalizedDescription=An error occurred while running scripts from the package “DockerToolbox-1.8.2.pkg”.}
```

These `chown` seem to be from https://github.com/docker/toolbox/blob/master/osx/mpkg/boot2dockeriso.pkg/Scripts/postinstall#L8-L13

All these three files and the one folder exist. It is therefore unclear why it fails. Deleting the `~/.docker` folder and running the installer again will create the file `~/.docker/machine/cache/boot2docker.iso` but the `chown` is not able to pick it up. Executing the `chown` commands manually works.

**Comment by mchiang0610** [comment]
@volker-fr Thanks for reporting this. We will fix the issue.

**Comment by volker-fr** [comment]
Ticket can be closed. My merge requests wasn't be processed for weeks for unknown reasons. Now there is another fix for this bug I am not going to test for now. Disappointing experience with this project.

**Comment by jeffdm** [comment]
I deeply apologize that you didn't receive a response sooner on this issue or on your PR that fixes it. We'll be sure to respond more promptly (within a couple days) next time, and would love to work with you to fix any more issues with the Toolbox.

Regarding the PR, please see https://github.com/docker/toolbox/pull/187.
