### ISSUE TITLE
Accomodate new plugin model for Docker Machine

### ISSUE THREAD

**Issue by nathanleclaire** [docker/toolbox#192]
Given the new plugin model that Docker Machine will be introducing, each driver will need to be distributed as a separate binary.  So, at the very least, `docker-machine-virtualbox` binary will need to be bundled / installed with the Toolbox in order to keep functioning properly.

I can work with you to make sure this is integrated properly when all the plugins stuff is merged upstream into Machine, but it is important to call out / note as a detail which needs to be taken care of for 1.9.0.

cc @jeffdm @mchiang0610 @amylindburg

**Comment by mchiang0610** [comment]
Thanks @nathanleclaire. We will definitely need to bundle the virtualbox plugin at the minimum. 

My suggestion is to bundle all the plugins that Docker is planning to maintain itself. WDYT?

**Comment by nathanleclaire** [comment]
> My suggestion is to bundle all the plugins that Docker is planning to maintain itself. WDYT?

That would be my inclination as well
