### ISSUE TITLE
Unexpected error getting machine url: exit status 255

### ISSUE THREAD

**Issue by GuyReeves** [docker/toolbox#194]
HI 
I tried installing docker DockerToolbox-1.8.2a on my OS X 10.10.5.  I had a prior  Boot2Docker version which I tried to uni(which never worked) .  
the VirtualBox Graphical User Interface   is Version 5.0.5 r102721

When I run the 'Docker Quickstart Terminal'  i get this error below, could anybody tell me what to do to get it to work ?
I would be very grateful 
Thanks

Guy

 bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
Machine default already exists in VirtualBox.
Starting machine default...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


exit status 255
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com

Unexpected error getting machine url: exit status 255
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)

**Comment by mchiang0610** [comment]
@GuyReeves Thanks for reporting this. It seems like Docker machine instance was not provisioned correctly via VirtualBox. 

Can you open up virtualbox -> remove the ```default``` VM by removing all files,  and then run the installer again? 

Thanks!

**Comment by mchiang0610** [comment]
@GuyReeves If that doesn't work, can you also try VirtualBox 5.0.4 stable?   (5.0.5 is in RC)

**Comment by GuyReeves** [comment]
Thanks so much for the quick reply.  
I removed the virtualbox -> remove the default.  Uninstalled VirtualBox 5.0.5 stable using the provided tool.  Then reinstalled VirtualBox 5.0.4.  Then ran the dockertoolbox again.  This is what I got- looks to my uneducated eye that it fixed the url problem, but one problem is still preventing it work.
thanks

Guy
 bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'

Creating Machine default...
No default boot2docker iso found locally, downloading the latest release...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.8.2/boot2docker.iso to /Users/Guy F/.docker/machine/cache/boot2docker.iso...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
To see how to connect Docker to this machine, run: docker-machine env default
Starting machine default...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/

docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)

**Comment by mchiang0610** [comment]
going to cc @nathanleclaire

**Comment by mchiang0610** [comment]
Merging with #153

**Comment by jonasheinrich** [comment]
Although this is closed I think [this post](https://github.com/docker/machine/issues/1031#issuecomment-118474481) might help

**Comment by abbinv** [comment]
For me it was because visualization was not enabled in my bios. Enabled it and issue was resolved.

I could see “this kernel requires an x86-64 CPU, but only detects an i686 CPU, unable to boot” error in virtual box screen
