### ISSUE TITLE
Merge conflict marker in Mac docs

### ISSUE THREAD

**Issue by adamtheturtle** [docker/toolbox#198]
http://docs.docker.com/mac/step_one/ includes "<<<<<<< HEAD" which is a merge conflict marker.

**Comment by mchiang0610** [comment]
@adamtheturtle Thanks. This is not part of the toolbox. cc'ing @moxiegirl to be aware.

**Comment by moxiegirl** [comment]
@adamtheturtle thanks! I'll sort that.
