### ISSUE TITLE
/bin/bash: /bin/bash: cannot execute binary file

### ISSUE THREAD

**Issue by oli99sc** [docker/toolbox#199]
On my MAC for a reason I do not understand yet, (assumption is our active directory integration)
dscl /Search -read /Users/$USER UserShell
on my machine results in two identical result entries : 
UserShell: /bin/bash
UserShell: /bin/bash

wich leads to USER_SHELL being /bin/bash /bin/bash, which makes starting the shell fail.

**Comment by mrryanjohnston** [comment]
There's a quick fix for this posted here: https://github.com/docker/docker/issues/16479#issue-107688329

**Comment by OscarF** [comment]
This is fixed by #211
