### ISSUE TITLE
Update Docker-compose 1.4.2

### ISSUE THREAD

**Issue by ChrisCinelli** [docker/toolbox#202]
Please update to 1.4.2 that fixes this problem: https://forums.docker.com/t/docker-compose-hangs-at-attaching-to/2517/6

**Comment by mchiang0610** [comment]
@ChrisCinelli Thanks for reporting. 

Try the pre-release version here: https://github.com/docker/toolbox/releases/tag/v1.8.2b 

Closing this issue for now. Feel free to reopen it.
