### ISSUE TITLE
can't install toolbox 1.8.2b on mac os x10.10.5

### ISSUE THREAD

**Issue by Alienero** [docker/toolbox#205]
<img width="622" alt="screen shot 2015-09-26 at 4 38 03 pm" src="https://cloud.githubusercontent.com/assets/5100733/10116641/0455ba6a-646d-11e5-8a43-45cbf8f44cb9.png">

**Comment by mchiang0610** [comment]
@Alienero It seems like the download of the installer was corrupt. 

Please re-download, and if the issue still persists please let us know. 

Thanks!

**Comment by Alienero** [comment]
I try to re-download 2 times, the problem is still persists. well,1.8.2 can be installed successfully

**Comment by mchiang0610** [comment]
@Alienero can you press command+L when this error comes up for us to get the logs?

**Comment by mchiang0610** [comment]
merging with #153
