### ISSUE TITLE
Can install toolbox 1.8.2.c on OS X

### ISSUE THREAD

**Issue by bilby91** [docker/toolbox#207]
While trying to upgrade my Docker Toolbox I run into this issue when migration the boot2docker VM.

```
executing: VBoxManage 
STDOUT: 
STDERR: 
Error creating machine: exec: "VBoxManage": executable file not found in $PATH
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

On a standard `zsh` session `VBoxManage` is loaded on $PATH.

**Comment by mchiang0610** [comment]
@bilby91 Thanks for this. 

Do you have non-recoverable data there? If not, can you try manually removing the boot2docker-VM (by selecting delete all files), and then run the installer again? 

Thanks. Closing this for now. If the issue persists, please reopen this, and we will help more!

**Comment by bilby91** [comment]
@mchiang0610 Deleting the boot2docker vm did the trick. 

Thanks! Keep up the good work!
