### ISSUE TITLE
"(null") disc error during installation

### ISSUE THREAD

**Issue by spitcat** [docker/toolbox#209]
Hi when i try install toolbox on el capitan gm i get this error 
Insert the "(null)" disc to continue the installation 

you have choosen to install software that requires this disc

![image](https://cloud.githubusercontent.com/assets/3325447/10169731/c83365f6-66d2-11e5-87fc-520a36ff354e.png)

I get this error with 1.8.2c 1.8.2a 1.8.1.c 
thanks for help

**Comment by mchiang0610** [comment]
@spitcat Thanks for this issue. 

This is actually the first time we've seen the issue of "(null)" disc. 

Can you run the installer again? When the error comes up, press cmd+L  to get the logs. This will help us troubleshoot this further. We are having trouble reproducing this problem here. 

Thanks!

**Comment by spitcat** [comment]
cant attach log so here is it 


Sep 29 18:12:38 spitcat Installer[5551]: LSExceptions [0x7f85db515c00] loaded
Sep 29 18:12:38 spitcat Installer[5551]: @(#)PROGRAM:Install  PROJECT:Install-1000
Sep 29 18:12:38 spitcat Installer[5551]: @(#)PROGRAM:Installer  PROJECT:Installer-853
Sep 29 18:12:38 spitcat Installer[5551]: Hardware: MacBookPro11,1 @ 2.60 GHz (x 4), 8192 MB RAM
Sep 29 18:12:38 spitcat Installer[5551]: Running OS Build: Mac OS X 10.11.1 (15B17c)
Sep 29 18:12:38 spitcat Installer[5551]: Env: __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
Sep 29 18:12:38 spitcat Installer[5551]: Env: TMPDIR=/var/folders/gr/710n254j74d_4_9f6xr_q4zm0000gn/T/
Sep 29 18:12:38 spitcat Installer[5551]: Env: HOME=/Users/spitcat
Sep 29 18:12:38 spitcat Installer[5551]: Env: SHELL=/bin/zsh
Sep 29 18:12:38 spitcat Installer[5551]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.1JNuX936AS/Listeners
Sep 29 18:12:38 spitcat Installer[5551]: Env: Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Iso2dAgndm/Render
Sep 29 18:12:38 spitcat Installer[5551]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Sep 29 18:12:38 spitcat Installer[5551]: Env: LOGNAME=spitcat
Sep 29 18:12:38 spitcat Installer[5551]: Env: XPC_SERVICE_NAME=com.apple.xpc.launchd.oneshot.0x1000000f.Installer
Sep 29 18:12:38 spitcat Installer[5551]: Env: COMMAND_MODE=unix2003
Sep 29 18:12:38 spitcat Installer[5551]: Env: USER=spitcat
Sep 29 18:12:38 spitcat Installer[5551]: Env: XPC_FLAGS=0x0
Sep 29 18:12:38 spitcat Installer[5551]: Docker Toolbox %INSTALLER_VERSION% Installation Log
Sep 29 18:12:38 spitcat Installer[5551]: Opened from: /Volumes/Untitled/DockerToolbox-1.8.2c.pkg
Sep 29 18:12:39 spitcat Installer[5551]: Product archive /Volumes/Untitled/DockerToolbox-1.8.2c.pkg trustLevel=202
Sep 29 18:12:41 spitcat Installer[5551]: JS: Hardware architecture detected: x86_64
Sep 29 18:12:41 spitcat Installer[5551]: JS: OS version detected: 10.11.1
Sep 29 18:12:41 spitcat Installer[5551]: JS: 5.0.0
Sep 29 18:12:42 spitcat Installer[5551]: JS: system.run /bin/sh .. returned: 1 result=true
Sep 29 18:12:42 spitcat Installer[5551]: JS: result:true
Sep 29 18:12:44 spitcat Installer[5551]: InstallerStatusNotifications plugin loaded
Sep 29 18:12:48 spitcat Installer[5551]: LSExceptions [0x7f85db515c00] unloaded
Sep 29 18:12:50 spitcat Installer[5551]: Administrator authorization granted.
Sep 29 18:12:50 spitcat Installer[5551]: ================================================================================
Sep 29 18:12:50 spitcat Installer[5551]: User picked Standard Install
Sep 29 18:12:50 spitcat Installer[5551]: Choices selected for installation:
Sep 29 18:12:50 spitcat Installer[5551]: 	Upgrade: "Docker Toolbox"
Sep 29 18:12:50 spitcat Installer[5551]: 	Upgrade: "Docker Client 1.8.2"
Sep 29 18:12:50 spitcat Installer[5551]: 		DockerToolbox-1.8.2c.pkg#docker.pkg : io.docker.pkg.docker : 1.8.2
Sep 29 18:12:50 spitcat Installer[5551]: 	Upgrade: "Docker Machine 0.4.1"
Sep 29 18:12:50 spitcat Installer[5551]: 		DockerToolbox-1.8.2c.pkg#dockermachine.pkg : io.docker.pkg.dockermachine : 0.4.1
Sep 29 18:12:50 spitcat Installer[5551]: 	Upgrade: "Docker Compose 1.4.2"
Sep 29 18:12:50 spitcat Installer[5551]: 		DockerToolbox-1.8.2c.pkg#dockercompose.pkg : io.docker.pkg.dockercompose : 1.4.2
Sep 29 18:12:50 spitcat Installer[5551]: 	Upgrade: "Docker Quickstart Terminal"
Sep 29 18:12:50 spitcat Installer[5551]: 		DockerToolbox-1.8.2c.pkg#dockerquickstartterminalapp.pkg : io.docker.pkg.dockerquickstartterminalapp : 1.8.2c
Sep 29 18:12:50 spitcat Installer[5551]: 	Upgrade: "Docker Kitematic 0.8.5"
Sep 29 18:12:50 spitcat Installer[5551]: 		DockerToolbox-1.8.2c.pkg#kitematicapp.pkg : io.docker.pkg.kitematicapp : 0.8.5
Sep 29 18:12:50 spitcat Installer[5551]: 	Upgrade: "Oracle VM VirtualBox 5.0.4"
Sep 29 18:12:50 spitcat Installer[5551]: 		DockerToolbox-1.8.2c.pkg#VBoxKEXTs.pkg : org.virtualbox.pkg.vboxkexts : 5.0.4
Sep 29 18:12:50 spitcat Installer[5551]: 		DockerToolbox-1.8.2c.pkg#VirtualBox.pkg : org.virtualbox.pkg.virtualbox : 5.0.4
Sep 29 18:12:50 spitcat Installer[5551]: 		DockerToolbox-1.8.2c.pkg#VirtualBoxCLI.pkg : org.virtualbox.pkg.virtualboxcli : 5.0.4
Sep 29 18:12:50 spitcat Installer[5551]: 		DockerToolbox-1.8.2c.pkg#boot2dockeriso.pkg : io.boot2dockeriso.pkg.boot2dockeriso : 1.8.2
Sep 29 18:12:50 spitcat Installer[5551]: ================================================================================
Sep 29 18:12:50 spitcat Installer[5551]: It took 0.00 seconds to summarize the package selections.
Sep 29 18:12:50 spitcat Installer[5551]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Sep 29 18:12:50 spitcat Installer[5551]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#docker.pkg
Sep 29 18:12:50 spitcat Installer[5551]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#dockermachine.pkg
Sep 29 18:12:50 spitcat Installer[5551]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#dockercompose.pkg
Sep 29 18:12:50 spitcat Installer[5551]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#dockerquickstartterminalapp.pkg
Sep 29 18:12:50 spitcat Installer[5551]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#kitematicapp.pkg
Sep 29 18:12:50 spitcat Installer[5551]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#VBoxKEXTs.pkg
Sep 29 18:12:50 spitcat Installer[5551]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#VirtualBox.pkg
Sep 29 18:12:50 spitcat Installer[5551]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#VirtualBoxCLI.pkg
Sep 29 18:12:50 spitcat Installer[5551]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#boot2dockeriso.pkg
Sep 29 18:12:50 spitcat Installer[5551]: Set authorization level to root for session
Sep 29 18:12:50 spitcat Installer[5551]: Will use PK session
Sep 29 18:12:50 spitcat Installer[5551]: Using authorization level of root for IFPKInstallElement
Sep 29 18:12:50 spitcat Installer[5551]: Starting installation:
Sep 29 18:12:51 spitcat Installer[5551]: Configuring volume "Macintosh HD"
Sep 29 18:12:51 spitcat Installer[5551]: Preparing disk for local booted install.
Sep 29 18:12:51 spitcat Installer[5551]: Free space on "Macintosh HD": 197,45 GB (197445218304 bytes).
Sep 29 18:12:51 spitcat Installer[5551]: Create temporary directory "/var/folders/gr/710n254j74d_4_9f6xr_q4zm0000gn/T//Install.5551jmvbnW"
Sep 29 18:12:51 spitcat Installer[5551]: IFPKInstallElement (9 packages)
Sep 29 18:12:51 spitcat installd[568]: PackageKit: Adding client PKInstallDaemonClient pid=5551, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Sep 29 18:12:51 spitcat Installer[5551]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Sep 29 18:12:51 spitcat installd[568]: PackageKit: ----- Begin install -----
Sep 29 18:12:51 spitcat installd[568]: PackageKit: request=PKInstallRequest <9 packages, destination=/>
Sep 29 18:12:51 spitcat installd[568]: PackageKit: packages=(
	    "PKLeopardPackage <file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#docker.pkg>",
	    "PKLeopardPackage <file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#dockermachine.pkg>",
	    "PKLeopardPackage <file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#dockercompose.pkg>",
	    "PKLeopardPackage <file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#dockerquickstartterminalapp.pkg>",
	    "PKLeopardPackage <file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#kitematicapp.pkg>",
	    "PKLeopardPackage <file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#VBoxKEXTs.pkg>",
	    "PKLeopardPackage <file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#VirtualBox.pkg>",
	    "PKLeopardPackage <file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#VirtualBoxCLI.pkg>",
	    "PKLeopardPackage <file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#boot2dockeriso.pkg>"
	)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Will do receipt-based obsoleting for package identifier io.docker.pkg.docker (prefix path=)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Will do receipt-based obsoleting for package identifier io.docker.pkg.dockermachine (prefix path=)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Will do receipt-based obsoleting for package identifier io.docker.pkg.dockercompose (prefix path=)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Will do receipt-based obsoleting for package identifier io.docker.pkg.dockerquickstartterminalapp (prefix path=Applications/Docker/)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Will do receipt-based obsoleting for package identifier io.docker.pkg.kitematicapp (prefix path=Applications/Docker/)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Will do receipt-based obsoleting for package identifier org.virtualbox.pkg.virtualboxcli (prefix path=usr/local/bin)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Will do receipt-based obsoleting for package identifier io.boot2dockeriso.pkg.boot2dockeriso (prefix path=usr/local/share/boot2docker)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Extracting file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#docker.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox/Root, uid=0)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Extracting file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#dockermachine.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox/Root, uid=0)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Extracting file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#dockercompose.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox/Root, uid=0)
Sep 29 18:12:52 spitcat installd[568]: PackageKit: Extracting file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#dockerquickstartterminalapp.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox/Root/Applications/Docker, uid=0)
Sep 29 18:12:53 spitcat installd[568]: PackageKit: Extracting file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#kitematicapp.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox/Root/Applications/Docker, uid=0)
Sep 29 18:12:53 spitcat installd[568]: PackageKit: Extracting file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#VBoxKEXTs.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox/Root/Library/Application Support/VirtualBox, uid=0)
Sep 29 18:12:54 spitcat installd[568]: PackageKit: Extracting file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#VirtualBox.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox/Root/Applications, uid=0)
Sep 29 18:12:55 spitcat installd[568]: PackageKit: Extracting file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#VirtualBoxCLI.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox/Root/usr/local/bin, uid=0)
Sep 29 18:12:55 spitcat installd[568]: PackageKit: Extracting file://localhost/Volumes/Untitled/DockerToolbox-1.8.2c.pkg#boot2dockeriso.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox/Root/usr/local/share/boot2docker, uid=0)
Sep 29 18:12:56 spitcat installd[568]: PackageKit: prevent user idle system sleep
Sep 29 18:12:56 spitcat installd[568]: PackageKit: suspending backupd
Sep 29 18:12:56 spitcat installd[568]: PackageKit: Executing script "./preflight" in /private/tmp/PKInstallSandbox.ITjng0/Scripts/org.virtualbox.pkg.virtualbox.aVRfoR
Sep 29 18:12:56 spitcat install_monitor[5560]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Sep 29 18:12:56 spitcat installd[568]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/08122825-6A2D-46BA-802A-757BEE2041AC.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox
Sep 29 18:12:56 spitcat installd[568]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/08122825-6A2D-46BA-802A-757BEE2041AC.activeSandbox/Root (3 items) to /
Sep 29 18:12:56 spitcat installd[568]: PackageKit: Executing script "./postflight" in /private/tmp/PKInstallSandbox.ITjng0/Scripts/org.virtualbox.pkg.vboxkexts.Pag1ER
Sep 29 18:12:56 spitcat installd[568]: ./postflight: /Library/LaunchDaemons/org.virtualbox.startup.plist
Sep 29 18:12:57 spitcat installd[568]: PackageKit: Executing script "./postflight" in /private/tmp/PKInstallSandbox.ITjng0/Scripts/org.virtualbox.pkg.virtualbox.aVRfoR
Sep 29 18:12:57 spitcat installd[568]: ./postflight: Python found: python, installing bindings...
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running install
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running build
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running build_py
Sep 29 18:12:57 spitcat installd[568]: ./postflight: creating build
Sep 29 18:12:57 spitcat installd[568]: ./postflight: creating build/lib
Sep 29 18:12:57 spitcat installd[568]: ./postflight: creating build/lib/vboxapi
Sep 29 18:12:57 spitcat installd[568]: ./postflight: copying vboxapi/__init__.py -> build/lib/vboxapi
Sep 29 18:12:57 spitcat installd[568]: ./postflight: copying vboxapi/VirtualBox_constants.py -> build/lib/vboxapi
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running install_lib
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running install_egg_info
Sep 29 18:12:57 spitcat installd[568]: ./postflight: Removing /Library/Python/2.7/site-packages/vboxapi-1.0-py2.7.egg-info
Sep 29 18:12:57 spitcat installd[568]: ./postflight: Writing /Library/Python/2.7/site-packages/vboxapi-1.0-py2.7.egg-info
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running clean
Sep 29 18:12:57 spitcat installd[568]: ./postflight: removing 'build/lib' (and everything under it)
Sep 29 18:12:57 spitcat installd[568]: ./postflight: 'build/bdist.macosx-10.11-intel' does not exist -- can't clean it
Sep 29 18:12:57 spitcat installd[568]: ./postflight: 'build/scripts-2.7' does not exist -- can't clean it
Sep 29 18:12:57 spitcat installd[568]: ./postflight: removing 'build'
Sep 29 18:12:57 spitcat installd[568]: ./postflight: Python found: python2.6, installing bindings...
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running install
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running build
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running build_py
Sep 29 18:12:57 spitcat installd[568]: ./postflight: creating build
Sep 29 18:12:57 spitcat installd[568]: ./postflight: creating build/lib
Sep 29 18:12:57 spitcat installd[568]: ./postflight: creating build/lib/vboxapi
Sep 29 18:12:57 spitcat installd[568]: ./postflight: copying vboxapi/__init__.py -> build/lib/vboxapi
Sep 29 18:12:57 spitcat installd[568]: ./postflight: copying vboxapi/VirtualBox_constants.py -> build/lib/vboxapi
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running install_lib
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running install_egg_info
Sep 29 18:12:57 spitcat installd[568]: ./postflight: Removing /Library/Python/2.6/site-packages/vboxapi-1.0-py2.6.egg-info
Sep 29 18:12:57 spitcat installd[568]: ./postflight: Writing /Library/Python/2.6/site-packages/vboxapi-1.0-py2.6.egg-info
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running clean
Sep 29 18:12:57 spitcat installd[568]: ./postflight: removing 'build/lib' (and everything under it)
Sep 29 18:12:57 spitcat installd[568]: ./postflight: 'build/bdist.macosx-10.11-intel' does not exist -- can't clean it
Sep 29 18:12:57 spitcat installd[568]: ./postflight: 'build/scripts-2.6' does not exist -- can't clean it
Sep 29 18:12:57 spitcat installd[568]: ./postflight: removing 'build'
Sep 29 18:12:57 spitcat installd[568]: ./postflight: Python found: python2.7, installing bindings...
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running install
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running build
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running build_py
Sep 29 18:12:57 spitcat installd[568]: ./postflight: creating build
Sep 29 18:12:57 spitcat installd[568]: ./postflight: creating build/lib
Sep 29 18:12:57 spitcat installd[568]: ./postflight: creating build/lib/vboxapi
Sep 29 18:12:57 spitcat installd[568]: ./postflight: copying vboxapi/__init__.py -> build/lib/vboxapi
Sep 29 18:12:57 spitcat installd[568]: ./postflight: copying vboxapi/VirtualBox_constants.py -> build/lib/vboxapi
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running install_lib
Sep 29 18:12:57 spitcat installd[568]: ./postflight: running install_egg_info
Sep 29 18:12:57 spitcat installd[568]: ./postflight: Removing /Library/Python/2.7/site-packages/vboxapi-1.0-py2.7.egg-info
Sep 29 18:12:57 spitcat installd[568]: ./postflight: Writing /Library/Python/2.7/site-packages/vboxapi-1.0-py2.7.egg-info
Sep 29 18:12:58 spitcat installd[568]: ./postflight: running clean
Sep 29 18:12:58 spitcat installd[568]: ./postflight: removing 'build/lib' (and everything under it)
Sep 29 18:12:58 spitcat installd[568]: ./postflight: 'build/bdist.macosx-10.11-intel' does not exist -- can't clean it
Sep 29 18:12:58 spitcat installd[568]: ./postflight: 'build/scripts-2.7' does not exist -- can't clean it
Sep 29 18:12:58 spitcat installd[568]: ./postflight: removing 'build'
Sep 29 18:12:58 spitcat installd[568]: ./postflight: Installing vboxwebsrv launchd file to /Users/spitcat/Library/LaunchAgents
Sep 29 18:12:58 spitcat installd[568]: ./postflight: Register file extensions for "spitcat"
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.ITjng0/Scripts/io.boot2dockeriso.pkg.boot2dockeriso.2jwPem
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Writing receipt for io.docker.pkg.docker to /
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Writing receipt for io.docker.pkg.dockermachine to /
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Writing receipt for io.docker.pkg.dockercompose to /
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Writing receipt for io.docker.pkg.dockerquickstartterminalapp to /
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Writing receipt for io.docker.pkg.kitematicapp to /
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Writing receipt for org.virtualbox.pkg.vboxkexts to /
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Writing receipt for org.virtualbox.pkg.virtualbox to /
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Writing receipt for org.virtualbox.pkg.virtualboxcli to /
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Writing receipt for io.boot2dockeriso.pkg.boot2dockeriso to /
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Touched bundle /Applications/Docker/Docker Quickstart Terminal.app
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Touched bundle /Applications/Docker/Kitematic (Beta).app
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Touched bundle /Applications/Docker/Kitematic (Beta).app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/crash_report_sender.app
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Touched bundle /Applications/Docker/Kitematic (Beta).app/Contents/Frameworks/Electron Helper EH.app
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Touched bundle /Applications/Docker/Kitematic (Beta).app/Contents/Frameworks/Electron Helper NP.app
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Touched bundle /Applications/Docker/Kitematic (Beta).app/Contents/Frameworks/Kitematic (Beta) Helper.app
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Touched bundle /Applications/VirtualBox.app
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Touched bundle /Applications/VirtualBox.app/Contents/Resources/VirtualBoxVM.app
Sep 29 18:12:58 spitcat installd[568]: PackageKit: Touched bundle /Applications/VirtualBox.app/Contents/Resources/vmstarter.app
Sep 29 18:12:58 spitcat installd[568]: Installed "Docker Toolbox" (%INSTALLER_VERSION%)
Sep 29 18:12:58 spitcat install_monitor[5560]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Sep 29 18:12:59 spitcat installd[568]: PackageKit: releasing backupd
Sep 29 18:12:59 spitcat installd[568]: PackageKit: allow user idle system sleep
Sep 29 18:12:59 spitcat installd[568]: PackageKit: ----- End install -----
Sep 29 18:12:59 spitcat installd[568]: PackageKit: 7.3s elapsed install time
Sep 29 18:12:59 spitcat installd[568]: PackageKit: Running idle tasks
Sep 29 18:12:59 spitcat installd[568]: PackageKit: Done with sandbox removals
Sep 29 18:12:59 spitcat Installer[5551]: PackageKit: Registered bundle file:///Applications/Docker/Docker%20Quickstart%20Terminal.app/ for uid 501
Sep 29 18:12:59 spitcat Installer[5551]: PackageKit: Registered bundle file:///Applications/Docker/Kitematic%20(Beta).app/ for uid 501
Sep 29 18:12:59 spitcat installd[568]: PackageKit: Sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/8E9DF37E-C332-4589-A4B6-E9AFC78E697F.sandbox: relevance 672
Sep 29 18:12:59 spitcat Installer[5551]: PackageKit: Registered bundle file:///Applications/Docker/Kitematic%20(Beta).app/Contents/Frameworks/Electron%20Framework.framework/Versions/A/Resources/crash_report_sender.app/ for uid 501
Sep 29 18:12:59 spitcat Installer[5551]: PackageKit: Registered bundle file:///Applications/Docker/Kitematic%20(Beta).app/Contents/Frameworks/Electron%20Helper%20EH.app/ for uid 501
Sep 29 18:12:59 spitcat Installer[5551]: PackageKit: Registered bundle file:///Applications/Docker/Kitematic%20(Beta).app/Contents/Frameworks/Electron%20Helper%20NP.app/ for uid 501
Sep 29 18:12:59 spitcat Installer[5551]: PackageKit: Registered bundle file:///Applications/Docker/Kitematic%20(Beta).app/Contents/Frameworks/Kitematic%20(Beta)%20Helper.app/ for uid 501
Sep 29 18:12:59 spitcat Installer[5551]: PackageKit: Registered bundle file:///Applications/VirtualBox.app/ for uid 501
Sep 29 18:12:59 spitcat Installer[5551]: PackageKit: Registered bundle file:///Applications/VirtualBox.app/Contents/Resources/VirtualBoxVM.app/ for uid 501
Sep 29 18:12:59 spitcat Installer[5551]: PackageKit: Registered bundle file:///Applications/VirtualBox.app/Contents/Resources/vmstarter.app/ for uid 501
Sep 29 18:12:59 spitcat installd[568]: PackageKit: Removing client PKInstallDaemonClient pid=5551, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Sep 29 18:13:00 spitcat Installer[5551]: Running install actions
Sep 29 18:13:00 spitcat Installer[5551]: Removing temporary directory "/var/folders/gr/710n254j74d_4_9f6xr_q4zm0000gn/T//Install.5551jmvbnW"
Sep 29 18:13:00 spitcat Installer[5551]: Finalize disk "Macintosh HD"
Sep 29 18:13:00 spitcat Installer[5551]: Notifying system of updated components
Sep 29 18:13:00 spitcat Installer[5551]:
Sep 29 18:13:00 spitcat Installer[5551]: **** Summary Information ****
Sep 29 18:13:00 spitcat Installer[5551]:   Operation      Elapsed time
Sep 29 18:13:00 spitcat Installer[5551]: -----------------------------
Sep 29 18:13:00 spitcat Installer[5551]:        disk      0.00 seconds
Sep 29 18:13:00 spitcat Installer[5551]:      script      0.00 seconds
Sep 29 18:13:00 spitcat Installer[5551]:        zero      0.00 seconds
Sep 29 18:13:00 spitcat Installer[5551]:     install      8.75 seconds
Sep 29 18:13:00 spitcat Installer[5551]:     -total-      8.76 seconds
Sep 29 18:13:00 spitcat Installer[5551]:

**Comment by mchiang0610** [comment]
@spitcat This is really weird. It seems like things are fine from the logs. 

Are you able to reproduce this from other computers?

**Comment by spitcat** [comment]
ok just found the problem. Iam using nifty for saving downloads. 
When you try install toolbox from nifty (usb) you got this error.
