### ISSUE TITLE
Toolbox 1.8.2c installed Kitematic isn't able to start the default VM on OS X 10.9.5

### ISSUE THREAD

**Issue by iserko** [docker/toolbox#214]
Cleaned up my previous Docker Toolbox by:
- removing Virtualbox from Applications
- removing Docker Kitematic from Applications
- rm -rf ~/.docker

Downloaded 1.8.2c and installed it.
Installation was successful, then I opened up Kitematic and it fails to start Docker.

I checked the logs in Virtualbox for that virtual machine and saw:
```
00:00:17.773772 VMMDev: Guest Additions information report: Version 5.0.4 r102546 '5.0.4'
00:00:17.773805 VMMDev: Guest Additions information report: Interface = 0x00010004 osType = 0x00053100 (Linux >= 2.6, 64-bit)
00:00:17.773867 VMMDev: Guest Additions capability report: (0x0 -> 0x0) seamless: no, hostWindowMapping: no, graphics: no
00:00:17.773924 VMMDev: vmmDevReqHandler_HeartbeatConfigure: fHBCheckEnabled=false
00:00:17.773937 VMMDev: Heartbeat checking timer set to trigger every 4000 milliseconds
00:00:17.773962 VMMDev: Guest Log: VbgdCommonInitDevExt: Setting up heartbeat to trigger every 2000 milliseconds
00:00:17.774077 VMMDev: Guest Log: vboxguest: misc device minor 56, IRQ 20, I/O port d020, MMIO at 00000000f0400000 (size 0x400000)
00:00:22.771578 NAT: Link up
00:00:34.841009 VMMDev: Guest Log: VBoxService 5.0.4 r102546 (verbosity: 0) linux.amd64 (Sep  8 2015 09:05:09) release log
00:00:34.841025 VMMDev: Guest Log: 00:00:00.000064 main     Log opened 2015-09-30T14:57:00.612423000Z
00:00:34.842566 VMMDev: Guest Log: 00:00:00.001627 main     OS Product: Linux
00:00:34.842613 VMMDev: Guest Log: 00:00:00.001685 main     OS Release: 4.0.9-boot2docker
00:00:34.842633 VMMDev: Guest Log: 00:00:00.001706 main     OS Version: #1 SMP Thu Sep 10 20:39:20 UTC 2015
00:00:34.842649 VMMDev: Guest Log: 00:00:00.001723 main     OS Service Pack: #1 SMP Thu Sep 10 20:39:20 UTC 2015
00:00:34.842667 VMMDev: Guest Log: 00:00:00.001739 main     Executable: /sbin/VBoxService
00:00:34.842670 VMMDev: Guest Log: 00:00:00.001740 main     Process ID: 2054
00:00:34.842672 VMMDev: Guest Log: 00:00:00.001741 main     Package type: LINUX_64BITS_GENERIC
00:00:34.847381 VMMDev: Guest Log: 00:00:00.006451 main     5.0.4 r102546 started. Verbose level = 0
00:00:34.856452 VMMDev: Guest Log: 00:00:00.015506 vminfo   rtldrNativeLoad: dlopen('libdbus-1.so.3', RTLD_NOW | RTLD_LOCAL) failed: libdbus-1.so.3: cannot open shared object file: No such file or directory
00:00:34.856490 VMMDev: Guest Log: 00:00:00.015562 vminfo   Error: Unable to connect to system D-Bus (1/3): D-Bus not installed
00:00:35.188900 NAT: IPv6 not supported
00:00:35.620620 NAT: DHCP offered IP address 10.0.2.15
00:00:35.620860 NAT: DHCP offered IP address 10.0.2.15
00:00:39.857660 VMMDev: Guest Log: 00:00:05.019020 vminfo   Error: Unable to connect to system D-Bus (2/3): D-Bus not installed
00:00:44.864993 VMMDev: Guest Log: 00:00:10.028855 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed
```

**Comment by mchiang0610** [comment]
@iserko Thanks. Do you have any logs from Kitematic itself? 

This usually happens when Docker-machine is not set up correctly. (Usually due to internal networking issues with Virtualbox / host-only adaptors). 

Can you open up virtualbox, and remove the 'default' VM by choosing delete all files. Run the installer again. Then you can run the quickstart terminal (It's pretty much the base command line version of Kitematic, and you'll be able to find logs from there if it still fails). 

Hope this helps! Please re-open this issue if you are still having problems. (Linking this to Kitematic's issue as well: https://github.com/kitematic/kitematic/issues/1029)

**Comment by iserko** [comment]
@mchiang0610 can't reopen the issue as I don't have access, but I've done what you asked.

- manually removed the default VM by selecting 'Remove' -> 'Delete all files'
- reran the installer
- ran quickstart terminal (it hangs on Starting VM...)
- looked into Virtualbox VM 'default' log and got the same error as I pasted above

**Comment by iserko** [comment]
@mchiang0610 Also ran this script https://github.com/kitematic/kitematic/blob/master/util/reset ... rebooted my computer and it still doesn't work

**Comment by iserko** [comment]
Managed to make it work by installing Virtualbox 4.3.30 instead of 5.0.4, but the funny thing is that I still get the message I pasted above. Any ideas?

**Comment by jiv-e** [comment]
Had the same problem. Downgrading didn't work. No other ideas.

**Comment by iserko** [comment]
The downgrade option didn't work for long. Eventually solved it by just upgrading OS X to 10.11.

**Comment by mchiang0610** [comment]
@iserko @jiv-e Do any of you have a way to reproduce this on your computer or  another computer? We are having trouble reproducing this. If you are okay, are you willing to jump on a call with one of our engineers working on Docker machine and do a debug session so we can learn more about this issue? 

please message me mchiang@docker.com 

merging this issue with #153 as well.

**Comment by jiv-e** [comment]
I got it to work, but I was in hurry and the steps that resolved it are a little bit unclear.

I think this resolved the problem:
1. I went to a Docker documentation page that instructed to install some test(?) version of Virtualbox. I did that. I don't know if this actually did anything.

I couldn't find the documentation page anymore, even by browsing the history. I found this https://docs.docker.com/kitematic/known-issues/ from the history. But I think the content was different. Has the page updated recently?

Currently I have Virtualbox version 5.0.7 r103249. I'm not sure if this is the test(?) version or if I installed a newer one afterwards.

2. I uninstalled and reinstalled Docker Toolbox. I created the Docker host using the Docker Quickstart Terminal. After that Kitematic also worked.

**Comment by maxibra** [comment]
Thank you jiv-e!

System Version:	OS X 10.10.5 (14F27)
I have installed https://www.virtualbox.org/download/testcase/VirtualBox-5.0.7-103383-OSX.dmg and it works.
It's very stranger behaviour. After that I tried to upgrade to VirtualBox-5.0.8-103449-OSX and downgrade and it's doesn't work
VirtualBox-5.0.7-103383-OSX.dmg is only version that works for me

**Comment by amasson88** [comment]
I cannot start  "Docker Quickstart Terminal" or Kitematic (toolbox 1.9.1f), I have the same kind of error on Windows 8.1:
00:00:45.613089 VMMDev: Guest Log: 00:00:10.011751 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed

**Comment by HumiH** [comment]
I also have the same problem on my win 10,VirtualBox version of 5.0.20 r106931:
`Details: 00:00:48.365491 VMMDev: Guest Log: 00:00:10.040688 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed.`
Is there any way to solve this problem?

**Comment by eniniz** [comment]
+1
