### ISSUE TITLE
"From your shell" docs need clarification

### ISSUE THREAD

**Issue by bfirsh** [docker/toolbox#22]
http://docker-manthony.s3-website-us-east-1.amazonaws.com/installation/mac/#from-your-shell

This is not immediately clear that your not using the Docker CLI.app, particuarly when reading on from the particular section. Probably needs a bit of clarification that these are instructions for something different ("If don't want to use Docker CLI.app and use your own shell, then you can do this...").

**Comment by jeffdm** [comment]
Cross referenced in https://github.com/docker/tutorials/pull/10, so I'll close this for now

Thanks Ben!

**Comment by moxiegirl** [comment]
The Getting Started requires them to use the Quickstart Terminal.
