### ISSUE TITLE
DockerToolbox-1.8.2c not running on Windows 8.1 

### ISSUE THREAD

**Issue by RafPe** [docker/toolbox#223]
Hey ,

I just installed DockerToolbox-1.8.2c on windows machine. Installation itself went without any problems however when running the docker Terminal I get the following error 

```
Machine default already exists in VirtualBox.
Starting machine default...
Error setting up host only network on machine start: strconv.ParseUint: parsing "128": value out of range
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Error: Cannot run SSH command: Host "default" is not running
Looks like something went wrong... Press any key to continue...
```

If I try to startup VM manually I get message "FATAL: Could not read from the boot medium! System Halted"

Any tips where to look for more details to find what cause this ?

**Comment by mchiang0610** [comment]
@RafPe Can you open up virtualbox and remove the "default" VM by choosing delete all? 

And then run the installer again. The problem seems to be attributed to virtual networking problems presented in VirtualBox.  

Hope this helps! Merging this with the larger thread #153

**Comment by cespujunk66** [comment]
thx! thi s worked perfectly for me
