### ISSUE TITLE
VM becomes inaccessible after host reboots

### ISSUE THREAD

**Issue by jayfk** [docker/toolbox#225]
Don't know if this is a bug in virtualbox, docker-machine or docker-toolbox. With every host reboot die virtual machine running boot2docker becomes inaccessible. 

When opening the VirtualBox Manager, I get:

    Machine UUID {5710466a-9901-4e68-9809-d31488c7ea8e} in 
    '/Users/foo/.docker/machine/machines/default/default/default.vbox' doesn't match its UUID 
    {e477bf41-8056-40e2-a3f4-9fe958b36727} in the registry file
     '/Users/foo/Library/VirtualBox/VirtualBox.xml'

**Comment by jeffdm** [comment]
@jayfk Thanks!

**Comment by mchiang0610** [comment]
cc  @docker/machine-maintainers

**Comment by mirageglobe** [comment]
Same-ish issue 

Machine UUID {85da4262-e97b-461a-953a-368c179ab69c} in '/Users/foo/.docker/machine/machines/default/default/default.vbox' doesn't match its UUID {fd09d3b7-8e77-4f94-a0ee-2894ebe8763b} in the registry file '/Users/foo/Library/VirtualBox/VirtualBox.xml'.
Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
MachineWrap
Interface: 
IMachine {f30138d4-e5eb-4b3a-8858-a059de4c93fe}

**Comment by tiger-seo** [comment]
+1
```
C:\Program Files\Oracle\VirtualBox>VBoxManage list vms
"<inaccessible>" {c6772f71-f192-4031-a40e-1c591b1c79f7}
```

**Comment by jeffdm** [comment]
This appears to be a bug with VirtualBox. While we'd love to help tackle this, it's a bit out of scope for Toolbox.

For specific VirtualBox & `docker-machine` related issues, please open an issue on the `docker/machine` repo.

Thanks!

**Comment by talktejas** [comment]
While this may be a virtual box issue, docker's behavior of removing old docker default docker machine and re-creating new one, thereby removing all stored images etc. is what creating pain. And docker is doing nothing about it other than shifting blame on virtualbox.
