### ISSUE TITLE
start.sh cannot set VBOXMANAGE of VirtualBox 5.0.6 on Windows

### ISSUE THREAD

**Issue by foverzar** [docker/toolbox#227]
```sh
$ VBOXMANAGE=/$(reg query HKEY_LOCAL_MACHINE\\SOFTWARE\\Oracle\\VirtualBox //v InstallDir | grep InstallDir | awk '{print substr($0, index($0,$3))}' | sed 's/\\/\//g' | sed 's/://')VBoxManage.exe
ERROR: The system was unable to find the specified registry key or value.
```

**Comment by gmanfunky** [comment]
I'm wondering, Was Docker Toolbox this the very first time VirtualBox was installed on your host? 

As an aside, if you start a cmd.exe window and type ```set```, do you see an environment variable named VBOX_MSI_INSTALL_PATH= ?

**Comment by foverzar** [comment]
No, it wasn't. Only after I reinstalled VBox for 5.0.6.

The envvar is there and seems to be set correctly. You suggest using it, instead of capturing registry value?

**Comment by jeffdm** [comment]
Pushed a quick fix on master that uses the VBOX_MSI_INSTALL_PATH and VBOX_INSTALL_PATH variables, thanks @foverzar, @gmanfunky !
