### ISSUE TITLE
Cannot build an image with 1.8.2d and Quickstart Terminal (windows 10)

### ISSUE THREAD

**Issue by avelinos** [docker/toolbox#230]
I wanted to give the winpty docker fix a try and after completely wiping my existing docker install and installing the 1.8.2d version of Toolbox, I cannot do any docker build commands with the default Docker Quickstart Terminal window which is using MINGW64/winpty.  I get:

repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"

If I try and build and image from the same dockerfile in a MINGW32 terminal that I initialize with
```
eval "$(docker-machine env --shell=bash default)"
```
I can build the image.

Here's a Dockerfile you can use to reproduce it.  Don't mind what it's doing, I was just messing with something.  But I can reproduce the error with all of my Dockerfiles:
```
FROM mysql:5.6.26
RUN usermod -u 1000 mysql
RUN usermod -G staff mysql
RUN chown mysql /var/run/mysqld
EXPOSE 3306
```

The command I used to build the image was
```
docker build --tag="testrepo/mysql":5.6.26 .
```

Quick summary,
Build fails with MINGW64/winpty
Build succeeds with MINGW32

Note:  Oh, I see, if I remove the "/" from the tag, it works in MINGW64/winpty. Slashes should be allowed characters in the tag, right?  Why would it only be like that for MINGW64/winpty?

**Comment by gmanfunky** [comment]
@avelinos can you try this? I'm wondering if the MSYS path conversion is messing it up. 

```
MSYS_NO_PATHCONV=1 docker build --tag="testrepo/mysql":5.6.26 .
```

**Comment by avelinos** [comment]
Thanks for the response.  Unfortunately, MSYS_NO_PATHCONV=1 doesn't seem to help.

**Comment by avelinos** [comment]
I installed https://github.com/git-for-windows/git/releases/tag/v2.6.1.windows.1 mentioned in
https://github.com/docker/toolbox/issues/226

on top of Toolbox 1.8.2d and everything seems to work like they did with 1.8.1b.  I'm going to try using Toolbox 1.8.2b before the winpty resolution to see whether or not it's needed.

**Comment by gmanfunky** [comment]
I was able to look into this a bit. Using winpty is converting forward
slash to a back slash. You can temporarily work around the workaround by
typing

docker.exe build ...

**Comment by jeffdm** [comment]
@avelinos thanks for the issue. We had followed Git for Windows' tty fix by aliasing `docker` to `winpty docker`.

Unfortunately this doesn't work as expected. This is being reverted before marking 1.8.2d as a full released.

**Comment by jeffdm** [comment]
This should be fixed on master now, where `winpty` is not used by default. Look out for an updated release soon.

**Comment by gpetz** [comment]
@gmanfunky if I type docker.exe in MINGW64 in /c/Program Files/Docker Toolbox

$ docker.exe
bash: docker.exe: command not found
