### ISSUE TITLE
Windows MinTTY winpty workaround breaks output redirecting

### ISSUE THREAD

**Issue by gmanfunky** [docker/toolbox#231]
Windows 7. Docker Toolbox 1.8.2d (with winpty workaround) in Git for Windows Shell using MSYS2 64 Mintty stuff. 

When run under winpty, Docker pty code doesn't like its STDOUT when redirecting output to a file. 

```
$ docker info >/dev/null
output is not a tty

$ echo $?
1
```

Previous behavior can be shown by bypassing our winpty alias function by calling by full name (docker.exe)
```
$ docker.exe info >/dev/null

$ echo $?
0
```

**Comment by gmanfunky** [comment]
My best experience really has been to run all these tools under a terminal like http://cmder.net/ , which uses conemu for this type of thing. I wonder if upstream docker itself would be able to better work around this terminal hassle in the long term. 

In the near-term, maybe the bash function implemented in Docker Toolbox start.sh could get some more intelligence to help out. I was thinking it might be expanded to only apply the winpty workaround if -i or -t is passed to run or exec? 

Or, maybe we bundle a different shell with the project instead of the MSYS2  MinTTY coming with Github's Git for Windows.

**Comment by jeffdm** [comment]
@gmanfunky huge thanks for looking into this, and for a solid proposed solution. Agreed, this seems like a larger issue that needs to be fixed in the Docker client itself.

In the meantime, I'll rever the winpty update and will add a warning message in the quickstart terminal. For example:

"For interactive commands such as `docker run -it`, pleaseuse `winpty docker run -it`."

What do you think?

**Comment by jeffdm** [comment]
@gmanfunky scratch that, I think we should keep the winpty hack for now, but tell the user to use `docker.exe` for piping to work. Alternatively they can use `docker-machine ssh default`

**Comment by gmanfunky** [comment]
@jeffdm I personally prefer the "warning message" solution. Mostly because it works better with any existing scripts. For example, I ran into this when testing our internal tutorial and archetype project, which includes scripts around docker commands for local dev and pushing.

**Comment by gmanfunky** [comment]
I suspect this might even be an issue with how docker is using some golang libraries. But my go-fu is a bit too weak at the moment to dive in confidently. 

For example, we see that ```docker-machine ssh``` works fine in multiple windows terminals. While  ```docker run -it``` has issues occasionally. And windows ```docker-login``` totally fails to grab input on any windows terminal.

**Comment by jeffdm** [comment]
I think there may be a good middle ground:

Define `docker` as an alias instead. This way it won't be brought into scripts. Originally I chose function because I couldn't figure out how to define export an alias, but I'll dive deeper.

**Comment by jeffdm** [comment]
@gmanfunky what do you think of this? https://github.com/docker/toolbox/pull/232

**Comment by gmanfunky** [comment]
We've been working through some alternatives on PR https://github.com/docker/toolbox/pull/232 , and i figured we should document another apparent drawback of ```winpty``` here. 

When using winpty, it is changing some forward slashes to back slashes. I verified this using procmon.exe and reviewing process created event. Maybe it is an MSYS rule, but it doesn't appear to hit any of them as described [here](http://www.mingw.org/wiki/Posix_path_conversion). So maybe it is something else doing it. 

```
# With the alias or the function to send docker calls to winpty...

$ docker pull jeffdm/data
Using default tag: latest
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"

$ docker.exe pull jeffdm/data
Using default tag: latest
Pulling repository docker.io/jeffdm/data
...
```
^Note the "repository name component must match" error. (Interestingly, that error doesn't include the forward slash which I think is also a valid character.)

I'm not seeing any great way around this yet. Things i"m thinking of:
1. Reduce exposure if we used a function that was smart enough to try and detect passing the -t or -it arguments to ```docker run``` or ```docker exec``` specifically. 
2. Blurt out a really big warning when the quickstart shell is used: ```"If you want to use interactive commands such as *docker run -it busybox* or *docker exec -it ...*, prepend winpty to your command."``` 
3. Abandon the Git for Windows shell. Go back to what was used before or package another shell that uses conemu emulation.

**Comment by jeffdm** [comment]
@gmanfunky going to close this for now, though there is definitely a larger issue here of using Powershell or properly interacting with TTYs via the docker cli.

Packaging the old MSYS is an option, but since it's being phased out for Git for Windows, I don't know if that's the best option.

**Comment by jeffdm** [comment]
@gmanfunky huge thanks for your help!

**Comment by amarouane-ABDLHAK** [comment]
just run `winpty docker run -it ubuntu bash`
