### ISSUE TITLE
Linux installation failing on 15.04

### ISSUE THREAD

**Issue by moxiegirl** [docker/toolbox#233]
Is docs.docker.com/linux/step_one/ up to date? Which Linux distro are you testing with? "docker run ..." step doesn't work with Ubuntu 15.04

Most likely need to update to rpm installation with apt.

**Comment by mchiang0610** [comment]
@moxiegirl I think you have the wrong repo?

**Comment by moxiegirl** [comment]
Moved to https://github.com/docker/tutorials/issues/36
