### ISSUE TITLE
OSX - start.sh replaces shell

### ISSUE THREAD

**Issue by vladgh** [docker/toolbox#234]
Docker Toolbox 1.8.2c on OSX El Capitan

If bash is upgraded via homebrew, the resulting binary is located at `/usr/local/bin/bash`.
This means that start.sh will start without a login shell for this particular example.
If someone loads for example dotfiles in .bash_profile it will not be sourced because of this.

```bash
USER_SHELL=$(dscl /Search -read /Users/$USER UserShell | awk '{print $2}')
if [ "$USER_SHELL" = "/bin/bash" ] || [ "$USER_SHELL" = "/bin/zsh" ] || [ "$USER_SHELL" = "/bin/sh" ]; then
  $USER_SHELL --login
else
  $USER_SHELL
fi
```

**Comment by jeffdm** [comment]
@vladgh Thanks! Fixed on master.
