### ISSUE TITLE
1.8.2d failure on Windows 10

### ISSUE THREAD

**Issue by hantsy** [docker/toolbox#235]
I am trying to install a clean version on Windows 10. After I have removed the `default` machine and uninstalled the old version of Toolbox and Virtualbox, then I installed a clean 1.8.2d.

When ran Kitematic (Alpha), it tried to create a `default` machine, and finally I got the following error in the dialog.

<pre>
C:\Program Files\Docker Toolbox\kitematic\resources\resources\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="E:\Users\<redacted>\disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.
</pre>

I copied the command line `docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default ` to a new `cmd` and ran it. 

The following error info I got.

<pre>
STDERR:
Creating VirtualBox VM...
Creating SSH key...
Creating disk image...
Creating 20000 MB hard disk image...
Converting from raw image file="stdin" to file="E:\Users\hantsy\.docker\machine\machines\default\disk.vmdk"...
Creating dynamic image with size 20971520000 bytes (20000MB)...
executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe createvm --basefolder E:\Users\hantsy\.docker\machine\machines\default --name default --register
STDOUT: Virtual machine 'default' is created and registered.
UUID: 96303af4-3871-46e6-8f27-42ba0a897614
Settings file: 'E:\Users\hantsy\.docker\machine\machines\default\default\default.vbox'

STDERR:
VM CPUS: 1
VM Memory: 2048
executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm default --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 2048 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd
STDOUT:
STDERR:
executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm default --nic1 nat --nictype1 82540EM --cableconnected1 on
STDOUT:
STDERR:
using 192.168.99.1 for dhcp address
executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
STDOUT:
STDERR:
executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create
STDOUT:
STDERR: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: SetupDiCallClassInstaller (DIF_INSTALLDEVICE) failed (0x00000002)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 71 of file VBoxManageHostonly.cpp

Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
</pre>

**Comment by jeffdm** [comment]
Thanks @hantsy ! Merging with #65
