### ISSUE TITLE
Cannot install fresh toolbox on Mac El Capitan 10.11

### ISSUE THREAD

**Issue by jc21** [docker/toolbox#236]
![screen shot 2015-10-12 at 8 49 18 am](https://cloud.githubusercontent.com/assets/1518257/10419542/2a955caa-70be-11e5-84a3-d9a1c216325e.png)

Fresh install of Mac OS 10.11
Docker Toolbox installer DockerToolbox-1.8.2c.pkg

System Integrity Protection is disabled:
```bash
~ root# csrutil status
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
        Apple Internal: disabled
        Kext Signing: disabled
        Filesystem Protections: disabled
        Debugging Restrictions: disabled
        DTrace Restrictions: disabled
        NVRAM Protections: disabled
```

I have a ~/.dockercfg file with only my dockerhub credentials and no ~/.docker directory.

Any clues?

**Comment by jeffdm** [comment]
@jc21 thanks for creating an issue. Any errors in the logs? (`cmd+l`)

**Comment by jc21** [comment]
Yep :)

https://www.dropbox.com/s/v6ezgbasfxj8kre/Installer%20Log%2012-Oct-2015.txt?dl=0

**Comment by jeffdm** [comment]
@jc21 thanks! Looking

**Comment by jeffdm** [comment]
@jc21 what's the file size of the `pkg`? Perhaps it was corrupt and needs to be re-downloaded?

**Comment by jc21** [comment]
I redownloaded the installer and saved to my Downloads folder instead of the mounted NTFS drive.

The installer worked this time, Thanks :)

**Comment by am17torres** [comment]
Just a heads up, this happened to me too. I'm not sure if there is a way to prevent this problem but I wouldn't have had to thought to re-download the installer, I was fortunate to find this thread.
