### ISSUE TITLE
'clear' doesn't clean the screen when I run docker on Windows Command Prompt

### ISSUE THREAD

**Issue by hmny** [docker/toolbox#240]
I am using docker on windows with an Ubuntu Image. Everything is just fine on docker itself, but when I run one of those images, whenever I try to clean the screen, the cursor moves to the fist line but all of the others line are still there. I just have this problem with Cmd and this doesn't happen on Docker Terminal.

**Comment by mchiang0610** [comment]
@hmny unfortunately it seems like a problem with the windows CMD. It's out of our control.

**Comment by suexcxine** [comment]
I met this problem too. Are there any solutions?

**Comment by Dekken** [comment]
I happens with gitbash and conemu, so doesn't sound like a CMD issue tbh
