### ISSUE TITLE
bad mount mode specified (cannot mount volumes in 1.8.3)

### ISSUE THREAD

**Issue by braderhart** [docker/toolbox#241]
```
$ winpty docker run -it -v /c/Users/Brad/Desktop:/home/test ubuntu bash
invalid value "C:\\Users\\Brad\\Desktop:\\home\\test" for flag -v: bad mount mode specified : \home\test
See 'docker run --help'.
```

I've tried all the workarounds I could find. Seems like a duplicate bug, but 1.8.3 changes the way you access Docker and requires winpty for interactive mode. Any suggestions?

**Comment by anthony-o** [comment]
I have opened a stackoverflow question for a similar problem: http://stackoverflow.com/q/33126271/535203

**Comment by braderhart** [comment]
Thank you! I've found a workaround in the interim by creating a data volume container as explained here:

https://docs.docker.com/userguide/dockervolumes/

    $ docker create -v //c/Users/myuser:/myuser --name data busybox

    $ winpty docker run -it --rm --volumes-from data ubuntu bash

It appears that winpty adds additional complexity to the POSIX path conversion since it works without:

https://github.com/rprichard/winpty

Should we file a bug there as well?

**Comment by braderhart** [comment]
Another subpar workaround:

    $ docker-machine ssh default

**Comment by davide** [comment]
@braderhart thanks for creating this issue and providing those 2 workarounds.

I spent around an hour reading other threads where the "working" recommendation is adding a double-slash:
 - https://github.com/docker/docker/issues/13741
 - https://github.com/docker/docker/issues/12751
 - https://github.com/boot2docker/boot2docker/issues/846
 - https://github.com/docker/toolbox/issues/165
which doesn't work while using winpty.

Updating to winpty 0.2.0 fixes the issue and even the double-slash is no longer required. Everything just works as expected.

@mchiang0610 can we keep this case open until the winpty binary that is distributed with Docker Toolbox is updated?

**Comment by braderhart** [comment]
Thanks! Any idea when the winpty binary will be updated?

**Comment by ShortyFR** [comment]
The issue doesn't seem to be corrected in the last toolbox version (1.9.1). I still get the same kind of error. 

Why is this issue marked as closed ?

**Comment by gravis** [comment]
Confirmed, volumes don't work with 1.9.1 and windows 8.1

**Comment by evbo** [comment]
Please reopen this issue. The above work-arounds are not working nwith docker 1.9.1. The above work arounds do not persist data from the local machine to the container.

**Comment by krishna81m** [comment]
How does docker-machine ssh default help in mounting (did not work for me)? and how do you upgrade to winpty 0.2.0.

This hack is perfect if you have downgraded to 1.9 due to AUFS issues in 1.9.1
```
docker create -v //c/Users/myuser:/myuser --name data hello-world
winpty docker run -it --rm --volumes-from data ubuntu
```

**Comment by VertigoRay** [comment]
@krishna81m An idea how to do that with docker-compose v3+?

I'm trying to add a Windows 2016 Core node to a swarm and this is being far more difficult than it should be.

**Comment by ggajos** [comment]
I've hit this page multiple times when searching for a solution and I [ended up using this](https://stackoverflow.com/a/50591102/397677)
