### ISSUE TITLE
 Toolbox 1.8.3 Kitematic failed to create a functional default VM 

### ISSUE THREAD

**Issue by hantsy** [docker/toolbox#243]
Cleaned installation.

Started Kitematic and got the same errors as in 1.8.2d.

![image 1](https://cloud.githubusercontent.com/assets/854520/10474451/890c1452-7269-11e5-85cc-001ccc07009b.png)

**Comment by hantsy** [comment]
Seems an issue from VirtualBox 5.0.6, it can not create a HostOnly adapter on Windows 10.

https://www.virtualbox.org/ticket/14545?cversion=0&cnum_hist=6

**Comment by mchiang0610** [comment]
Merging with #153
