### ISSUE TITLE
Issue running docker on a windows 2008 server VM

### ISSUE THREAD

**Issue by anilbhagwat** [docker/toolbox#244]
I installed the docker terminal on a VM that has win 2008 server OS. It installed virtualbox 5.0.6. Unfortunately when I run the docker terminal, this is what I get. Any ideas?

I already have 127.0.0.1 pointing to localhost in hosts file
I also have ControlPersist no in config file in .ssh folder
I also reinstalled / rebooted / deleted contents of .docker just to rule out all options

Pl. help

Machine default already exists in VirtualBox.
Starting machine default...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...
Unexpected error getting machine url: exit status 255

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/

exit status 255
docker is configured to use the default machine with IP
For help getting started, check out the docs at https://docs.docker.com
NOTE: When using interactive commands, prepend winpty. Examples: 'winpty docker run -it ...', 'winpty docker exec -it ...'.

**Comment by mchiang0610** [comment]
@anilbhagwat This is an issue for Docker machine. Can you make an issue: https://github.com/docker/machine/issues/ 

If you are a Hub / Docker enterprise user: please email support@docker.com for immediate help.
