### ISSUE TITLE
Kitematic hanged at 99% in Windows 10 with latest 1.8.3 installation

### ISSUE THREAD

**Issue by ynagarjuna1995** [docker/toolbox#247]
Initially when I installed it worked properly but it stopped working suddenly and started hanging at 99% this all started when I enabled the option to shut down the VM automatically when I close the kitematic window.

**Comment by ynagarjuna1995** [comment]
A Quick and obviously not a desired fix for a developer which I followed was
=================================================== 
1. Uninstalled the Toolbox 
2. Deleted all the files in 
>`C:/Users/User_Name/.docker`
>`C:/Users/User_name/.virtualbox`

Re-Installed the Tool Box again work like a charm ...

May be problem with that option which will cause trouble

**Comment by mchiang0610** [comment]
@ynagarjuna1995 Thanks for reporting most of the problems are from Virtualbox. We are working on a fix. 

Thanks
