### ISSUE TITLE
docker run try to use certificate from ~/.boot2docker insteaf of ~/.docker

### ISSUE THREAD

**Issue by BenoitLeveque** [docker/toolbox#248]
After removing my old boot2docker installation and installing the new docker toolbox on osx 10.11.

when i run `docker run hello-world`

I got 
```
Could not read CA certificate "/Users/Benoit/.boot2docker/certs/boot2docker-vm/ca.pem": open /Users/Benoit/.boot2docker/certs/boot2docker-vm/ca.pem: no such file or directory
```

`~/.boot2docker` directory doesn't exist but there is a `~/.docker` directory which contains the certificate

**Comment by jeffdm** [comment]
Do you happen to have anything in your `~/.bashrc` file?

**Comment by BenoitLeveque** [comment]
good catch, i've found something inside my ~/.zsrc with some docker variable

**Comment by arikogan** [comment]
Great catch @jeffdm, thank you.
