### ISSUE TITLE
1.8.3 Toolbox on Win8.1: created VM "default" but not accessible

### ISSUE THREAD

**Issue by carloreggiani** [docker/toolbox#250]
Hi

Big problem configuring docker on Win8.1 corporate machine, tryed to install on a new pc (new hardware, same Win8.1 Pro), but Docker Toolbok failed again!

First run "Docker Quickstart Terminal" killed after default VM preparation (work fine), still waiting.
Second run:

Get http://127.0.0.1:2375/v1.20/containers/json: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it..

![dockertoolbox1 8 3_secondrun](https://cloud.githubusercontent.com/assets/1014429/10607454/d7c4c358-7739-11e5-8a87-19b25ae8aee6.png)
![dockertoolbox1 8 3_secondrun_bash](https://cloud.githubusercontent.com/assets/1014429/10607453/d7c4490a-7739-11e5-8550-be19b342b188.png)

Any idea?

**Comment by mchiang0610** [comment]
@carloreggiani Seems like Virtualbox networking has failed, and causing the failure. 

Are you in a corporate VPN / proxy environment?

**Comment by mchiang0610** [comment]
cc/ @nathanleclaire @dmp42

**Comment by dmp42** [comment]
cc @docker/machine-maintainers

**Comment by nathanleclaire** [comment]
It's pretty strange that the `docker ps` invocation is attempting to connect to `127.0.0.1:2375`.  That _definitely_ will not have any daemons listening.  It looks like `DOCKER_HOST` is not being set properly, either by the Toolbox or Machine.  Looking at it further too, you can see the cert error which indicates the provisioning process did not finish correctly.  How about Gist-ing the output of `docker-machine rm default; docker-machine -D create -d virtualbox default` please @carloreggiani ?

**Comment by carloreggiani** [comment]
I deleted the defaul VM (also the files) directly by the VirtualBox GUI, relaunched "Docker Quickstart Terminal" and it works now!

**Comment by nathanleclaire** [comment]
OK great @carloreggiani !  Sorry for the trouble in between.
