### ISSUE TITLE
Unable to use docker commands in CLI on Windows 10

### ISSUE THREAD

**Issue by drywolf** [docker/toolbox#256]
I'm trying to run the Toolbox v1.8.3 on Windows 10.
During the setup of the docker VM I get error dialogs that tell me that "there was an error renaming a network connection because another connection with the same name already exists" (roughly translated from german).

The Docker shell initialization continues nonetheless, but when I try to run docker commands, e.g. `docker images` in the docker shell I get the following error:

	$ docker images
	Get http://127.0.0.1:2375/v1.20/images/json: dial tcp 127.0.0.1:2375: ConnectEx tcp: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte..
	* Are you trying to connect to a TLS-enabled daemon without TLS?
	* Is your docker daemon up and running?

(Translated: "a connection could not be established because the remote host rejected the connection")

Is there a fix for this issue ? 

PS: I also tried the 1.9.0rc2 release, but that one gave me other issues that stopped usage as well.

**Comment by drywolf** [comment]
Following this [suggestion on the VirtualBox issue tracker](https://www.virtualbox.org/ticket/14412) I downloaded the latest VirtualBox [test-build for windows](https://www.virtualbox.org/wiki/Testbuilds) and using the Docker Toolbox v1.8.3 install I got everything running again. (1.9.0rc2 still didn't work so it seems there were some other issues unrelated to this one).

**Comment by thomasbley** [comment]
127.0.0.1 looks like environment variables are not set

I'm doing this on Win10 and Console2/cmd:

@echo off
docker-machine.exe start default
docker-machine.exe env --shell=cmd default >%temp%\docker_env.bat
%temp%\docker_env.bat

docker images

**Comment by jeffdm** [comment]
@drywolf thanks for the issue.

Closing as this Things seem to be running now. @thomasbley thanks for chiming in!

**Comment by shyamhd** [comment]
#450 #570 
This not worked for me.
I have tried all the solutions but still getting error on Kitematic (Alpha) 
I have attached snapshot.
Once it was running after close the toolbox and open again gives me error.
![image](https://cloud.githubusercontent.com/assets/7995684/18783098/88ccb764-81a7-11e6-992f-b42b04934703.png)
