### ISSUE TITLE
Error creating machine: Error in driver during machine creation: This computer doesn't have VT-X/AMD-v enabled.

### ISSUE THREAD

**Issue by braderhart** [docker/toolbox#257]
Getting this error with the latest Docker Toolbox 1.9.0-rc2 for Windows:

![screenshot - 10_26_2015 6_00_09 am](https://cloud.githubusercontent.com/assets/10714305/10729564/8df1f346-7ba7-11e5-94d6-25b879456145.png)

**Comment by dgageot** [comment]
Hi @braderhart, can you tell us which version of windows this is?

Also, can you provide the output of running this command:
```
wmic cpu get VirtualizationFirmwareEnabled
```

Can you also make sure, VT-X is enabled in the BIOS level. Even when the CPU supports it, it might be disabled.

**Comment by braderhart** [comment]
I'm using Windows 10. I can confirm that it shows that it isn't enabled (FALSE) by running that command. I am using KVM with UEFI firmware and verified that I have nested virtualization enabled. I take it that the UEFI firmware doesn't support this though.

**Comment by dgageot** [comment]
Thanks for the feedback @braderhart!

**Comment by braderhart** [comment]
I believe the command you are using to check to see if VT-X is enabled is not working correctly (or only works under specific conditions). I can confirm that it shows up correctly in the logs:

https://github.com/docker/machine/issues/1983#issuecomment-148350284

The value VMMonitorModeExtensions shows as TRUE. Can you use that instead?

**Comment by dgageot** [comment]
What we are going to do in machine is just log a warning before vm creation if we think VT-X is disabled and then fail with a clear error when the started vm has no VT-X support. This should solve corner cases like like one and still provide some feedback. see https://github.com/docker/machine/issues/2093

**Comment by braderhart** [comment]
Thank you so much!

**Comment by cosmicdreams** [comment]
I ran into this problem but I DO have virtualization enabled.

**Comment by dgcaron** [comment]
@cosmicdreams i had the same issue, i resolved it by uninstalling hyper-v (quite drastic) but there are more elegant solutions explained here:

https://social.technet.microsoft.com/Forums/windows/en-US/118561b9-7155-46e3-a874-6a38b35c67fd/hyperv-disables-vtx-for-other-hypervisors

**Comment by dgageot** [comment]
In docker-machine 0.5.5, the virtualbox driver detects that Hyper-v is also installed and prints a clear message pointing to this virtualbox ticket https://www.virtualbox.org/ticket/12350

**Comment by jeffdm** [comment]
Closing this as it seems to be resolved.

@cosmicdreams if this issue persists please open an issue on [`docker/machine`](https://github.com/docker/machine)

Thanks all!

**Comment by veton** [comment]
If you get FALSE after checking  Virtualization:
`wmic cpu get VirtualizationFirmwareEnabled`
Try disabling Hyper-V (requires reboot):
`bcdedit /set hypervisorlaunchtype off`
Worked for me.
