### ISSUE TITLE
No docker-compose installed V1.9.3-rc3

### ISSUE THREAD

**Issue by hantsy** [docker/toolbox#263]
I think v1.9.3-rc3 should contain `docker-compose` for windows. 

After I installed in my Windows 10, I can not find it in the installation folder. I also did not see it in **select components** wizard in the installation stage.

**Comment by jeffdm** [comment]
Fixed, thanks @hantsy @dnephin @thaJeztah

**Comment by thaJeztah** [comment]
Cool! thx!
