### ISSUE TITLE
Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.

### ISSUE THREAD

**Issue by canadatom** [docker/toolbox#267]
Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
fish: /usr/local/bin/docker-machine -D stop default || true && cp /Users/tom/.docker/machine/cache/boot2docker.iso /Users/tom/.docker/machine/machines/default/boot2docker.iso

**Comment by jeffdm** [comment]
This is a bug in the upgrade code - it assumes a bash environment. Working on a fix.

**Comment by jeffdm** [comment]
Fixed in 1.9.0b

**Comment by Masshat** [comment]
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
.bashrc (line 5): [[ $- != *i* ]] && return
from sourcing file .bashrc
	called on standard input
source: Error while reading file “.bashrc”
