### ISSUE TITLE
 No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by hmny** [docker/toolbox#268]
So I have tried all of possible solutions out there and none of the worked. I have docker running in my virtual machine, but for some reason I cannot get connected to it:
![docker](http://i.imgur.com/3RAbGae.png)

 Here is the message I get from Quick Start Terminal:
![docker](http://i.imgur.com/DQlVL3X.png)

**Comment by rushdyibrahim** [comment]
Did you try `eval $(docker-machine env default)` ?

**Comment by jeffdm** [comment]
Merging with https://github.com/docker/toolbox/issues/153
