### ISSUE TITLE
[SOLVED] Error attempting to invoke binary for plugin: dial tcp 127.0.0.1:59999

### ISSUE THREAD

**Issue by djsylvester** [docker/toolbox#272]
Win 7 x64

First run of quickstart after installing 1.9 over 1.8.x I got this error:

```Creating Machine default...
Error loading driver "virtualbox": Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
Looks like something went wrong... Press any key to continue...```

I immediately rebooted my machine and tried again (just to save time). After reboot I get:

```Creating Machine default...
Error loading driver "virtualbox": dial tcp 127.0.0.1:49547: connectex: No connection could be made because the target machine actively refused it.
Looks like something went wrong... Press any key to continue...```

On each additional attempt all that changes from the above error is the port number.

**Comment by xshyamx** [comment]
Win7 x64, virtualbox-4.3.28-100309

    $ docker-machine -D ls
    Docker Machine Version: 0.5.1 (7e8e38e)
    Found binary path at E:\docker-toolbox-1.9.1a\docker-machine-driver-virtualbox.exe
    Launching plugin server for driver virtualbox
    Plugin server listening at address 127.0.0.1:60918
    Error attempting to invoke binary for plugin 'virtualbox': dial-http tcp 127.0.0.1:60918: read tcp 127.0.0.1:60919->127.0.0.1:60918: wsarecv: An established connection was aborted by the software in your host machine.

**Comment by djsylvester** [comment]
I'm now up to 1.9.1f and the problem persists though I've gotten a bit further, and with some surprising results.

Since I use Outpost Firewall pro I decided to get it out of the way with some testing. I set the rules for Docker-Machine, VBoxManage, and VBoxSvc to "allow all activity". After doing so I got as far as:

```Creating Machine default...
Creating CA: C:\Users\user\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\user\.docker\machine\certs\cert.pem
Running pre-create checks...
Creating machine...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
Error attempting heartbeat call to plugin server: read tcp 127.0.0.1:49817->127.
0.0.1:49816: wsarecv: An existing connection was forcibly closed by the remote h
ost.
Error creating machine: Error in driver during machine creation: read tcp 127.0.
0.1:49817->127.0.0.1:49816: wsarecv: An existing connection was forcibly closed
by the remote host.
Looks like something went wrong... Press any key to continue...```

After deleting the default machine I tried something different. I started Virtual Box first, then Docker Quickstart. It also failed also but I got a bit further.

```Creating Machine default...
Creating CA: C:\Users\Boss\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\Boss\.docker\machine\certs\cert.pem
Running pre-create checks...
Creating machine...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting VM...
Error creating machine: Error in driver during machine creation: Maximum number
of retries (5) exceeded
Looks like something went wrong... Press any key to continue...```

However, VBox Manager  showed the default machine

![vboxmanager](https://cloud.githubusercontent.com/assets/3200236/11967234/5fc890da-a8be-11e5-95f4-476d533ba312.png)

When I clicked on the preview the window pops up showing the default machine "running"

![vboxrunning](https://cloud.githubusercontent.com/assets/3200236/11967252/95f0f1d4-a8be-11e5-9111-9ba4adb41e8f.png)

So now I need to figure out all the proper firewall rules (vmware just works) and why the failure message when in fact the machine is running.

If you have any ideas I certainly would appreciate some feedback. I've not been able to use Docker Toolbox since 1.8.x.

**Comment by djsylvester** [comment]
SOLVED.

Without too much unnecessary detail this is how I finally figured out what was causing Docker Toolbox (or more precisely Vbox) from working on my Win 7 Ultimate x64 w/ Outpost Firewall Pro and Avast anti-virus after 2 months.

First, after some searching I found this "solution" in the OFP forums.
http://www.agnitum.com/support/kb/article.php?id=1000061

Note: Though the article title names WMware specifically, the author noted in the forum that that was added to make it more searchable, not because it wasn't written in support of VirtualBox as well. Regardless, the solution didn't work.

I eventually found https://github.com/docker/machine/issues/2318 which targeted VPN, firewalls, and anit-virus. Flip the light switch on.

I disabled both Avast and OPF and stopped services. Solved. Default machine installs and starts w/out issue. I also shutdown the Docker/Vbox related processes and made sure on a restart w/ an existing default VM there were no problems. Success.

I restarted Avast, deleted the default machine and checked both the creation and restating of the default VM. Success. This left only OPF causing an issue somewhere.

I wasted a lot of time digging through the numerous log files OPF creates with little success other than 2-3 that indicated "something" was going wrong forcing processes to terminate. OPF has no documentation on their log files and little to no discussion of their log file "secrets." So I did the next best thing; I exported the current setup and then made sure everything was set to the "defaults," as originally installed. Success in both creating, starting, and restarting the default VM.

Checking the defaults against my exported settings turned out to be one non-default setting I had active. Settings -> Proactive Protection -> Anti-Leak. Mine was set to one step above "optimal" to "advanced":

![myopfantileak](https://cloud.githubusercontent.com/assets/3200236/12098346/08f5af7e-b2df-11e5-9c7a-0f809e06e0b6.png)

If you clicked on "Customize" you'd see these settings:

![myantileakcustomize](https://cloud.githubusercontent.com/assets/3200236/12098382/45a5d1d8-b2df-11e5-9fe5-ad9a0d4bb039.png)

And under the "Component Control" tab in same window settings were:

![mycomponentcontrol](https://cloud.githubusercontent.com/assets/3200236/12098437/8e841842-b2df-11e5-8f3e-c93ac2fafb9f.png)

Once I reset Settings -> Proactive Protection -> Anti-Leak to the default of "Optimal" both of the above, of course, changed:

Notice the events that are now "Allow" versus "Prompt" form the first image.
![opfdefaultantileak](https://cloud.githubusercontent.com/assets/3200236/12098485/db70f1ac-b2df-11e5-9b43-df33a6dba352.png)

Notice checkbox "Warn about starting changed executables" is unset in "optimal" (default) mode.
![opfdefaultcomponentcontrol](https://cloud.githubusercontent.com/assets/3200236/12098529/27fd18de-b2e0-11e5-82d5-dc792944408a.png)

Many of these items didn't throw prompts when OPF "Auto-Learn Mode" was disabled (my default use) and didn't correct any issues when on. As intricate as all these settings are there could be numerous reasons why. Although I prefer having anti-leak set to "advanced" and it has served me well with no application issues (or attacks on my system), and I could step through the allow/prompt one-by-one to determine which settings are actually causing the problem w/ Docker/Vbox I've just left it at the default for now. Perhaps sometime in the future I'll give it a go.

My conclusion is that although all my other applications, including VMware, run fine with anti-leak set to advanced for additional protection, Vbox has a problem within those settings. The odd ball.

**Comment by jeffdm** [comment]
@djsylvester Posting the solution is much appreciated! Thank you! Going to close this for now/merge it in with https://github.com/docker/toolbox/issues/153
