### ISSUE TITLE
error validating certificates for host "xxx.xxx.xxx.xxx:xxxx": connection refused

### ISSUE THREAD

**Issue by jcarpe** [docker/toolbox#275]
I am getting the following error when running the Quickstart Terminal:

```
Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: getsockopt: connection refused
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

When I try to run a docker command (in my case, docker info), the command eventually times out and I get a message asking if the docker host is running. I have tried regenerating the certificates for "default," but this seems to have no effect as I am left in the same situation as before.

**Comment by glw** [comment]
Im getting the same response on Windows 7 64 bit Docker 1.9b

```Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.```

**Comment by glw** [comment]
after doing the regenerate-certs command I get:

```$ docker-machine regenerate-certs default
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
WARNING >>>
This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.
SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.
You may need to add the route manually, or use another related workaround.
This could be due to a VPN, proxy, or host file configuration issue.
You also might want to clear any VirtualBox host only interfaces you are not using.```

It seems like Im close but a little guidance on fixing this would be much appreciated.

**Comment by RaspLuca** [comment]
Same here on OS X 10.10.5 Docker 1.9

Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "xxx.xxx.xx.xxx:xxxx": dial tcp xxx.xxx.xx.xxx:xxxx: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.


This didn't occur on Docker 1.8.3

**Comment by mcdop4880** [comment]
Same here on OS X 10.11.1 docker-machine 0.5 pulled from github

1. create a machine on AWS: docker-machine create -d amazonec2 aws
2. docker-machine ssh aws: completes, examine the filesystem - everything running fine
3. close computer return the next morning
4. eval "$(docker-machine env aws)"
Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "52.23.175.112:2376": tls: DialWithDialer timed out
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
5.docker-machine regenerate-certs aws 
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Error getting SSH command: Something went wrong running an SSH command!
command : cat /etc/os-release
err     : exit status 255
output  :

Looks like I keep losing 5-6 hours of processing time as I have to remove the machine that has my answers on its filesystem.

How can I get this working or at least recover information from amazon machine before removing it?

**Comment by smithwinston** [comment]
I have seen this previously with 1.5 and I still see it with the 1.9 release; the workaround seems to be to delete the machine and re-create.

Typically, this happens after doing a `docker-machine upgrade dockerdev`, after which I see the following:

```
$ docker-machine env dockerdev
Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "10.168.99.100:2376": dial tcp 10.168.99.100:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

The virtual machine becomes unpingable (I actually get an i/o timeout, not a connection refused).  Running regenerate-certs does **NOT** resolve the issue:

```
$ docker-machine regenerate-certs dockerdev
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
WARNING >>> 
This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using.
```

Looking through `dmesg` output on the VM, I did see some dbus related errors:

```
00:00:00.012456 vminfo   rtldrNativeLoad: dlopen('libdbus-1.so.3', RTLD_NOW | RTLD_LOCAL) failed: libdbus-1.so.3: cannot open shared object file: No such file or directory
00:00:00.012501 vminfo   Error: Unable to connect to system D-Bus (1/3): D-Bus not installed
IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
00:00:10.015130 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed
```

And in `/var/log/boot2docker.log` I saw the following (but this _could_ have been from the `docker-machine upgrade` command):

```
-------------------
Need TLS certs for dockerdev,127.0.0.1,10.0.2.15,10.168.99.100
-------------------
```

**NOTE**: I set a different IP address via `VIRTUALBOX_HOSTONLY_CIDR` during machine creation to avoid IP conflicts with the local network.

**Comment by ajorpheus** [comment]
On OSX 10.10.5,   upgrading Virtualbox to 5.0.10 and then running `docker-machine regenerate-certs default` worked for me:

```
> docker-machine regenerate-certs default
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
WARNING >>>
This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.
This could be due to a VPN, proxy, or host file configuration issue.
You also might want to clear any VirtualBox host only interfaces you are not using.
```

**Comment by jcarpe** [comment]
So, it looks like updating virtual box to the latest version (5.0.10) does resolve my issues. I'll go ahead and close this issue for now, but I'd suggest @RaspLuca, @glw, or @mcdop4880, re-open if your issues persist.

**Comment by glw** [comment]
I followed @jcarpe 's lead and upgraded virutalbox to 5.0.10 . Then uninstalled docker 1.9b and re-installed 1.9d and it installed fine. Thankfully. This by the way is on a Windows 7 64bit.

**Comment by zhangda89** [comment]
@ajorpheus Thanks

**Comment by iammerrick** [comment]
Not fixed for me, using Docker on Linux itself from OSX 1.9d. Ran a docker-machine upgrade and a docker-machine regenerate-certs...

**Comment by evacchi** [comment]
same problem for me. OS X 10.10; even tried to upgrade and then re-install 10.11 (not a clean install yet)

**Comment by Sharom** [comment]
I had got the same problem on my Mac. It happened because our local network is "192.168.99.1/24" and `docker-machine` creates VirtualBox VM with the same network by default!

Resolution:
```
docker-machine create --driver virtualbox --virtualbox-hostonly-cidr 192.168.60.1/24 dev
```

Check addresses of your networks. It may be the same problem.

**Comment by kamihicouki** [comment]
same problem on aws.
```
AWS_DEFAULT_REGION='ap-northeast-1'
AWS_ZONE='c'
AWS_INSTANCE_TYPE='t2.small'
AWS_AMI='ami-5f709f34' # https://cloud-images.ubuntu.com/locator/ec2/
...
```
```
MANAGER_NAME=MANAGER-$(date +%s-%N)
docker-machine create \
    --driver amazonec2 \
    --amazonec2-access-key $AWS_ACCESS_KEY_ID \
    --amazonec2-secret-key $AWS_SECRET_ACCESS_KEY \
    --amazonec2-vpc-id     $AWS_VPC_ID \
    --amazonec2-region     $AWS_DEFAULT_REGION \
    --amazonec2-zone       $AWS_ZONE \
    --amazonec2-instance-type $AWS_INSTANCE_TYPE \
    --amazonec2-ami        $AWS_AMI \
    --swarm \
    --swarm-master \
    --swarm-discovery token://$TOKEN_SWARM \
    $MANAGER_NAME &
```

**Comment by abhijitsarkar** [comment]
@Sharom I've the same issue on my Mac and saw someone else (another thread) suggested creating the VM with a private network.
Would you mind elaborating on the steps you followed to solve your problem? I've basic understanding of networking but I'm far from being a networking guy.

**Comment by OpakAlex** [comment]
Same problem:
```
docker-machine regenerate-certs dev
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Detecting the provisioner...
Error getting SSH command: Something went wrong running an SSH command!
command : cat /etc/os-release
err     : exit status 255
output  :
``` Mac - 10.11.2

**Comment by paulmcdonagh** [comment]
This is just a thought as these problems are hard to replicate by others: I was getting these errors when I was using a t1.micro at AWS for a longer running analysis job. After a while, the Amazon throttles the CPU usage down and can become almost non-responsive as t1.micros are not meant for this type of job. I couldn't even log-in to kill the job. Could these errors be a symptom of an non-responsive virtual machine either at Amazon or elsewhere including stalled local Virtualboxes? I've moved to large AWS instances and haven't seen this error again ... yet.

**Comment by AnilRedshift** [comment]
@paulmcdonagh very observant
Based on your comment I did a `docker-machine kill default` and then `docker-machine start default` and everything worked after that.

**Comment by cygmris** [comment]
Same error just happen to my OS X (10.10.4), everything goes well after restart my host system.It may due to confliction of the same subnet network(192.168.99.0/24) i connected yesterday.

**Comment by yoshiwaan** [comment]
@AnilRedshift the same worked for me on Windows with Docker Toolkit 1.10 and virtualbox 5.0.10.
I'd already performed `docker-machine stop default` and `docker-machine start default` numerous times, but running `docker-machine kill default` and then starting again fixed the problem right away. Not sure if it's a coincidence but worth trying for anyone else stuck.

**Comment by PikachuEXE** [comment]
`docker-machine kill default` + start also work for me
Upgraded docker 1.8 > 1.10 on OSX 10.10.5

**Comment by gjaldon** [comment]
The fix for me was to do `docker-machine rm default` and then run Docker Quickstart again. It created new certs and fixed this issue for me. What caused it in the first place was upgrading to a newer version of the Docker toolbox. It looks like the VM generated from the previous won't work with the newer version of docker/docker-machine.

**Comment by kumarrishav** [comment]
still same issue. Event after <code>docker-machine regenerate-certs</code> on Ec2

**Comment by cyberomin** [comment]
I was having the same issue and @gjaldon solution fixed my issues. What a legend.

**Comment by OpakAlex** [comment]
yes @gjaldon solution works.

**Comment by Jarema** [comment]
yep. @gjaldon solution is working, fortunately.

**Comment by chrisfosterelli** [comment]
Deleting the VM seems like a pretty heavy hammer. I was able to fix it by upgrading VirtualBox, which upgrading the toolbox apparently didn't do automatically.

**Comment by sriramsreedhar** [comment]
This was my error
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   -        virtualbox   Running   tcp://192.168.99.100:2376           Unknown   Unable to query docker version: Get https://192.168.99.100:2376/v1.15/version: x509: certificate is valid for 192.168.99.101, not 192.168.99.100

Solved -  as suggested by @gjaldon 

$ docker-machine rm default
About to remove default
Are you sure? (y/n): Y
Successfully removed default
$

$ docker-machine create --driver virtualbox default
Running pre-create checks...
(default) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(default) Latest release for github.com/boot2docker/boot2docker is v1.12.0
(default) Downloading /Users/sriram/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.12.0/boot2docker.iso...
(default) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(default) Copying /Users/sriram/.docker/machine/cache/boot2docker.iso to /Users/sriram/.docker/machine/machines/default/boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!

$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   -        virtualbox   Running   tcp://192.168.99.101:2376           v1.12.0

Hope this helps!

**Comment by martinbutt** [comment]
Ran into this problem today. "docker-machine upgrade" fixed it for me.

**Comment by bartlettpsj** [comment]
I've had this 2 or 3 times and each time it has been me running VPN software whilst starting docker-machine.  On a Mac 10.11 and using Cisco VPN.
