### ISSUE TITLE
Installer for 1.9.0 cannot upgrade if default shell is fish

### ISSUE THREAD

**Issue by jonaskello** [docker/toolbox#277]
During the step VM migration I get this error message:

Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
fish: /usr/local/bin/docker-machine -D stop default || true && cp /Users/JonKel/.docker/machine/cache/boot2docker.iso /Users/JonKel/.docker/machine/machines/default/boot2docker.iso
                                                     ^

**Comment by jeffdm** [comment]
Working on a fix - thanks!

**Comment by jonaskello** [comment]
Wow, fastest reply I have ever gotten on github, thanks! :-)

**Comment by jonaskello** [comment]
As a workaround, I did a chsh -s /bin/bash and re-ran the installer and it worked perfectly.

**Comment by jeffdm** [comment]
@jonaskello by the way this should be fixed now as of 1.9.0a.

Thanks for the issue
