### ISSUE TITLE
Docker basesize 10G limit

### ISSUE THREAD

**Issue by jaroslavlibal** [docker/toolbox#278]
Hello,

can you help me with my issue "how to increase the size limit for containers"?

I cannot load or create an image bigger than 10 GB and after two days of googling I have no working solution for that on Windows.

Thanks for any help.

**Comment by petaak** [comment]
+1

**Comment by SvenDowideit** [comment]
@nathanleclaire - what's the current proceedure for giving the VM more disk space?

**Comment by nathanleclaire** [comment]
Currently today you must create the machine with `--virtualbox-disk-size` greater than the default.
