### ISSUE TITLE
unable to find image I just created 

### ISSUE THREAD

**Issue by philcruz** [docker/toolbox#279]
I just created an image locally, "philcruz/mongo-base". I confirm it's there by running

    docker images

but when I do

    winpty docker run -it "philcruz/mongo-base" bash

I get the error 

    Unable to find image 'philcruz\mongo-base:latest' locally
    repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"

Why is docker changing "/" to "\"? This is on Windows 10.

**Comment by philcruz** [comment]
If I pass the image ID then it runs fine.

**Comment by philcruz** [comment]
Seems to be related to using winpty and trying to run interactively. This works fine

     docker run docker/whalesay cowsay boo

but this doesn't work

    winpty docker run -i -t docker/whalesay

and I can run philcruz/mongo-base without winpty

**Comment by ozlerhakan** [comment]
+1

**Comment by Cinderhaze** [comment]
+1 same issue on windows 10,

```
winpty docker run  jenkinsci/workflow-demo
Unable to find image 'jenkinsci\workflow-demo:latest' locally
repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-
*[a-z0-9])*)*"
```

```
$ docker --version
Docker version 1.9.1, build a34a1d5
```

**Comment by jeffdm** [comment]
I think it's because the shell is converting the `/` to a `\`.

This is fixed in the Docker Quickstart Terminal, but may still occur in other shell environments.
In that case run `export MSYS_NO_PATHCONV=1` or prepend your commands with `MSYS_NO_PATHCONV=1`.

**Comment by jeffdm** [comment]
Thanks for the issue, by the way!

**Comment by tbnorth** [comment]
In case it helps, I've found you can also, misleadingly, get this message when you do
```
... --link other_container myImage
```
if `other_container` doesn't exist.  I.e. with a typo in `other_container` I got a message saying `myImage` couldn't be found locally, fixing the typo fixed the problem.

**Comment by sheerun** [comment]
> if other_container doesn't exist. I.e. with a typo in other_container I got a message saying myImage couldn't be found locally, fixing the typo fixed the problem.

I had the same issue. `myImage` exists on the system

**Comment by southp** [comment]
Thanks for sharing your finding @tbnorth . I just have experienced the same issue and it almost drove me crazy.
