### ISSUE TITLE
Invalid repository name (sequenceiq\hadoop-docker), only [a-z0-9-_.] are allowed

### ISSUE THREAD

**Issue by medined** [docker/toolbox#280]
The toolbox seems great but I have run to a problem when using an interactive session. It seems like winpty is not handling images names with slashes. Or am I doing something wrong?

```
$ winpty docker run -it sequenceiq/hadoop-docker:2.7.0 /etc/bootstrap.sh -bash
Unable to find image 'sequenceiq\hadoop-docker:2.7.0' locally
FATA[0000] Invalid repository name (sequenceiq\hadoop-docker), only [a-z0-9-_.] are allowed
```

**Comment by Kosta-Github** [comment]
This is a problem of `winpty`; e.g.:
```
$ winpty echo http://google.de
http:\google.de
```
But I don't know a workaround/fix for this yet...

**Comment by medined** [comment]
I have a workaround. A hack. But it's enough to close this ticket.

1. re-tag the image to avoid the slash character.
2. start the container using "winpty docker run -it hadoop-docker bash"
3. execute the bootstrap script using "/etc/bootstrap.sh bash"

Now hadoop is running.

The utility of Docker on Windows is severely hampered by this issue. I hope someone finds better way to resolve the problem.
