### ISSUE TITLE
path expansion problem in Docker Quickstart Terminal

### ISSUE THREAD

**Issue by bVector** [docker/toolbox#282]
I'm trying to follow the instructions at https://hub.docker.com/r/jacksoncage/salt/ and the following command doesnt work:

docker run -i -t --name=saltdocker_master_1 -h master -p 4505 -p 4506 \
   -p 8080 -p 8081 -e SALT_NAME=master -e SALT_USE=master \
   -v `pwd`/srv/salt:/srv/salt:rw jacksoncage/salt

example:
```bash
$ docker run --name=saltdocker_master_1 -h master -p 4505 -p 4506    -p 8080 -p 8081 -e SALT_NAME=master -e SALT_USE=master -v "c/Users/bV/salt-docker/srv/salt:/srv/salt":rw jacksoncage/salt
invalid value "c\\Users\\bV\\salt-docker\\srv\\salt;H:\\Program Files\\Git\\srv\\salt;rw" for flag -v: \Program Files\Git\srv\salt;rw is not an absolute path
See 'G:\Docker Toolbox\docker.exe run --help'.
```

I've tried every form of quoting I can think of, is this supposed to work?

**Comment by jeffdm** [comment]
This should be fixed in https://github.com/docker/toolbox/releases/tag/v1.9.0c, can you please give it a try ? Thanks!

**Comment by jeffdm** [comment]
This still seems to be a problem. See details in https://github.com/docker/docker/issues/18290

**Comment by Paloh** [comment]
I have the same problem. Cannot provide path to docker run -v in windows. My Docker version is 1.9.1. Does anyone found the solution or a workaround?

**Comment by sewpafly** [comment]
Same issue with docker 1.9.1. Using the msys-git bash shell I'm seeing `$(pwd)` gives a path like `/c/Users/me` but a line like docker run --rm -it -v $(pwd):/source image gives an error:

```
invalid value "c:\\Users\\me;C:\\Users\\me\\AppData\\Local\\Programs\\Git\\source" for flag -v: bad mode specified: \Users\me\AppData\Local\Programs\Git\source
See 'c:\Users\me\bin\docker.exe run --help'.
```

**Comment by sewpafly** [comment]
Found a workaround:
```
docker run --rm -it -v //c/Users/me:/source <image>
```

Appears to work because the rules as defined [here](http://www.mingw.org/wiki/Posix_path_conversion), don't change the path being sent to the program if it starts with a double slash

**Comment by Paloh** [comment]
Hello @sewpafly, I think that your error response from deamon has nothing to do with the original problem. It just seems that you are trying to run docker container with command "bin/bash". To make this possible you have to to associate .sh file type in Windows Default programs with yourpathtogit/Git/bin/bash.exe program (this will make possible to use /bin/bash command when running docker containers). I found this solution somewhere in this topic: https://developer.ibm.com/bluemix/2015/04/16/installing-docker-windows-fixes-common-problems/.

UPDATE: strange things happend, I was able to run the container with no problems using method above 3 days ago and now I get similar error as you even when I have the .sh file associated with bash.exe.

**Comment by TamSzaGot** [comment]
As a workaround on Windows and DockerToolbox you can log into Boot2Docker with ssh and create the container from there.

<pre>
$ docker-machine ssh default
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.9.0, build master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
Docker version 1.9.0, build 76d6bc9
docker@default:~$ docker run -d -it --name=test -v /c/Users/DUMMY:/data centos
83d459ddb07564466570a60fd29d75f18aafd3400144bcd23e04b80391ba063b
docker@default:~$
</pre>

**Comment by jeffdm** [comment]
This should be fixed (at least with the Docker Quickstart Terminal), meaning you can now specify paths as `/c/Users/...`

For standalone git bash windows set `MSYS_NO_PATHCONV=1` before using `docker`

**Comment by atrauzzi** [comment]
Is it possible to get this `MSYS_NO_PATHCONV=1` documented officially somewhere?

I have a funny feeling it might be something *all* msys users will end up wanting to know.  Perhaps an msys section in the docker docs is in order?

**Comment by jeffdm** [comment]
@atrauzzi We can at least add something to the `README.md` for now - thanks for the heads up!
