### ISSUE TITLE
Older bin version cleanup

### ISSUE THREAD

**Issue by FrenchBen** [docker/toolbox#285]
Previous machine/docker bin may exist in `/usr/bin` which will be executed before the Toolbox installed `/usr/local/bin`.
Toolbox should cleanup any old machine/docker binaries prior to installing the latest version.

**Comment by SvenDowideit** [comment]
or at least detect that there's an issue and tell the user (and quickstart-cli can do a fixup)

**Comment by jeffdm** [comment]
I feel like this is something the user should be aware of by putting binaries in `/usr/bin/` manually. If we previously told users to put the binaries in `/usr/bin/` then please re-open this. Otherwise, I don't think this is an edge case we should handle in Toolbox.
