### ISSUE TITLE
Can't run images with slashes in interactive mode (tty mode/winpty)

### ISSUE THREAD

**Issue by readonly** [docker/toolbox#288]
(On Windows 7 Professional N/ 64bit, Docker Toolbox 1.9.0b)

We can not `docker run` images that have a slash in the name in `-ti` interactive mode. Running them without `-ti` works fine (but does not help us, as we need the interactive mode). The problem is that the vanilla docker binary seems to produce a tty error, which can be solved by using `winpty`, but winpty adds slash-backslash conversion, which then breaks the remaining docker command. There are some related issues, but they address the problem how to fix docker parameters like volume mounts for winpty, not the image name or command to call inside.

```
rico2@Havanna MINGW64 ~
$ docker run -ti progrium/busybox
cannot enable tty mode on non tty input 

rico2@Havanna MINGW64 ~
$ winpty docker run -ti progrium/busybox
Unable to find image 'progrium\busybox:latest' locally
repository name component must match "[a-z0-9](?:-​[a-z0-9])*(?:[._][a-z0-9](?:-​[a-z0-9])*)*"
```

As a workaround we can tag the image using a flat non-slash name and call it via that using winpty, but as winpty interfers with a lot more things (e.g. volume parameters, what command to run inside the container):

```
rico2@Havanna MINGW64 ~
$ docker tag progrium/busybox foobar

rico2@Havanna MINGW64 ~
$ winpty docker run -ti foobar /bin/sh
exec: "C:\\Program Files\\Git\\usr\\bin\\sh": executable file not found in $PATH
```

So we need do get back to not having to use winpty - but how can we get interactive mode working there?

(The busybox image is only an example for this issue.)

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/toolbox/issues/280 and https://github.com/docker/docker/issues/17712

**Comment by jeffdm** [comment]
Fixed in https://github.com/docker/toolbox/releases/tag/v1.9.0c, please give it a try :smiley:

**Comment by readonly** [comment]
Yes, it now finally works! Great!

Minor note: installing 1.9.0c over an exisitng 1.9.0b did not work, as it seems some settings are kept. Only completely deinstalling 1.9.0b and doing a fresh install helped.

**Comment by jsancho** [comment]
@readonly 
Alternatively, seeing that the patch is only changing the "docker quickstart terminal" shortcut.
You can also manually delete the shortcut and then install 1.9.0c with everything unchecked, but the "add shortcuts to home directory option" in the last step of the wizard.
this makes the installation fly through

**Comment by readonly** [comment]
Yes, the installer probably did not overwrite the shortcut (or we asked it to not do so).
