### ISSUE TITLE
VBOX creates new interface every time I start/stop/restart the default machine

### ISSUE THREAD

**Issue by dahendel** [docker/toolbox#289]
When I create the default machine docker-machine/virtualbox sets up the machine correctly(i have to adda route in my routing table), but if I start/stop/restart the machine it re-creates a new interface each time then cannot connect to the machine. This is extremely frustrating. I am using the docker-toolbox1.9.2b.exe installer to install everything. I can get it to work if delete all the interfaces and restart the machine, then add a route in my routing table.

**Comment by jeffdm** [comment]
cc @nathanleclaire

**Comment by foverzar** [comment]
If the issue with interfaces is raised, is it really necessary for toolbox to create a separate interface for itself? Couldn't we just specify the existing interface to be used? A lot of vm-powered apps tend to do interface breeding - should this really be "a common practice"? It doesn't seem to be a fine choice, as it pollutes system with *unnecessary stuff* and may cause a confusion in this hell of interfaces, which basically are only occasionally needed for only *one* service.

**Comment by dahendel** [comment]
I discovered why this is happening, I was connected to my corp VPN and trying to start docker toolbox. If I am not on a VPN the issue does not happen. I have verified this is reproducible with the latest toolbox install as well.

**Comment by nathanleclaire** [comment]
> If the issue with interfaces is raised, is it really necessary for toolbox to create a separate interface for itself? Couldn't we just specify the existing interface to be used?

It's meant to work that way: https://github.com/docker/machine/blob/181367b125d1c0fcf0cfa56b4d4987471a04223e/drivers/virtualbox/network.go#L162

I'd be curious to see the `--debug` output of a situation where we're spawning more than needed.  Seems there is some kind of state that we're not detecting properly.

**Comment by jeffdm** [comment]
Closing this since it's mostly related to `docker/machine` :smiley:  Please see https://github.com/docker/toolbox/issues/153 or continue the conversation in the `docker/machine` repo.
