### ISSUE TITLE
docker-toolbox issue on Windows 7 VBoxManage.exe: error: The host network interface with the given name could not be found

### ISSUE THREAD

**Issue by M-M-M-M** [docker/toolbox#291]
I am getting error on Windows 7 while installation and while trying to start docker-toolbox.
The error is relater to network interface of Virtualbox.

Tried with 1.9.0c

Error message on installation:
Creating Machine default...
Creating CA: C:\Users\username\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\username\.docker\machine\certs\cert.pem
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: C:\Program File
s\Oracle\VirtualBox\VBoxManage.exe hostonlyif ipconfig VirtualBox Host-Only Ethe
rnet Adapter #8 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage.exe: error: The host network interface with the given name could not
be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWr
ap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).ra
w(), hif.asOutParam())" at line 205 of file VBoxManageHostonly.cpp

Looks like something went wrong... Press any key to continue..

Error message when starting again docker-toolbox!
Machine default already exists in VirtualBox.
Starting machine default...
Error setting up host only network on machine start: C:\Program Files\Oracle\Vir
tualBox\VBoxManage.exe hostonlyif ipconfig VirtualBox Host-Only Ethernet Adapter
 #9 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage.exe: error: The host network interface with the given name could not
be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWr
ap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).ra
w(), hif.asOutParam())" at line 205 of file VBoxManageHostonly.cpp
Looks like something went wrong... Press any key to continue...

**Comment by virgo47** [comment]
I've got the same problem on Windows 10. I used VirtualBox before, I uninstalled it, installed shiny docker toolbox (which broke my previous tuned git bash installation so it seems), and all I get is exactly the same error as mentioned above.

**Comment by srranjan** [comment]
I have the same problem on Windows 10. Actually, I was okay on Windows 8.1 with no intention to go to 10, and then MS almost forced me to go to Windows 10 (I got some message on Windows 8.1 to "update" some driver, and when in good faith I tried to update, instead it "upgraded" me to Windows 10). And now I have this Docker toolkit issue.

**Comment by christianhuening** [comment]
The same here for windows 10 with Docker toolbox 1.9.0d.
With 1.9.1 I get a ton of permission denied errors when starting the command line.

**Comment by ccalebcarter** [comment]
having this problem as well, very frustrating have tried uninstall and re-install multiple times

**Comment by srranjan** [comment]
Found a simple solution to this problem: confine myself to ubuntu on virtualbox for now, till the things settles on windows!!!

**Comment by drasko** [comment]
Just installed Docker Toolbox and I am facing the same problem on Windows7. Any info on the fix?

**Comment by shainegordon** [comment]
exactly the same problem in Windows 10, DockerToolbox-1.9.1b

I even uninstalled my previous Virtual Box installation

**Comment by ccalebcarter** [comment]
I was able to fix mine by simply checking the NDIS driver in the host
network adapter (Network & Sharing / Modify Adapter Settings ) that virtual
box creates.  For some reason every time it would create the adapter but
not enable the NDIS driver so Docker had no way to talk to the default vm
it was creating.  That was what was causing my exit status 1 log entry.
Everything works fine now.

On Fri, Dec 4, 2015 at 4:38 AM, Shaine Gordon <notifications@github.com>
wrote:

> exactly the same problem in Windows 10, DockerToolbox-1.9.1b
>
> I even uninstalled my previous Virtual Box installation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/toolbox/issues/291#issuecomment-161957056>.
>



-- 
Regards,

*Caleb Carter*
Mobile: 425-229-7543
ccalebcarter@gmail.com
[image: LinkedIn]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.linkedin.com%2Fccalebcarter&sn=Y2NhbGViY2FydGVyQGdtYWlsLmNvbQ%3D%3D>

**Comment by christianhuening** [comment]
@ccalebcarter : You did it! That's been the solution for me as well! Thanks man! Everything's up and running again. 

However the NDIS driver of course should be set automatically. Is that an error with VirtualBox?

**Comment by jansoren** [comment]
Thanks! Solved it for me too:

![deactivate-ndis](https://cloud.githubusercontent.com/assets/1298854/11687642/1b0f2b6a-9e88-11e5-8480-1e7a21a9b8be.jpg)

**Comment by udoless** [comment]
I have the same problem on win10.
```
Machine default already exists in VirtualBox.
Starting machine default...
Error setting up host only network on machine start: D:\Oracle\VirtualBox\VBoxManage.exe hostonlyif ipconfig VirtualBox Host-Only Ethernet Adapter --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage.exe: error: The host network interface with the given name could not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWrap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 205 of file VBoxManageHostonly.cpp
Looks like something went wrong... Press any key to continue...
```

**Comment by christianhuening** [comment]
@jansoren : Nope, you should check it. When you create a new docker-vm a new interface is created in the network settings. Just keep the window open and watch it. The new interface has this NDIS option disabled. Enable it, and it should work.

**Comment by jansoren** [comment]
This is how i solved it: 
1. Removed all images from Virtual Box
2. Started Kitematic to download "default" - image 
3. Started Docker and ran "docker run hello-world"

**Comment by udoless** [comment]
I solved it:
* Uninstall VirtualBox
* Remove all networks about VirtualBox(generally, this is automatic)
* Reinstall DockerToolbox

**Comment by ttchin** [comment]
I have the same issue with windows 10 and dockertoolbox 1.9.1f

**Comment by shainegordon** [comment]
I reinstalled Windows and the problem went away. Possibly something to do
with UAC?

**Comment by dzhavatushev** [comment]
I'm using Windows 10 and have been fighting with a similar problem for a few hours.
The @udoless 's suggestion solved the issue. Thanks :)

**Comment by OwenChang** [comment]
I just follow @jansoren method，and it ok now

**Comment by jeffdm** [comment]
Merging with https://github.com/docker/toolbox/issues/153.

Thanks so much for the issue.

**Comment by murraybiscuit** [comment]
@ccalebcarter's solution worked for me. The NDIS driver on the adapter was disabled after I did an upgrade on Virtualbox.

**Comment by dongli** [comment]
Update VirtualBox from `5.1.24` to `5.1.26` solve my problem of the same form. OS is an plain and old Windows 7.

**Comment by LaPush** [comment]
On the Docker-Tool installation Windows prompted me , if i would like to install "Oracle Network Drivers" for the Virtual Box obviously. I cancelled it. So I reinstalled it and also installed the Drivers this time and that fixed it for me.

**Comment by qiangli** [comment]
For the record for future visitors:  Windows 10/Docker Toolbox first time installation, I had to download and install the latest VirtualBox (5.2.4) to make it work. Recent updates caused corruption;  reinstalling VirtualBox resolved the issue (Repair option did not work). I did not reinstall Toolbox.

**Comment by Itachi-Uchiha78** [comment]
I confirm qiangli's solution for Win7. Thanks man!

**Comment by stevelacerda7** [comment]
Resolved by:
1) open virtual box, stop default, remove it
2) right click Docker Quickstart, select run as administrator
resolved my issue.

**Comment by fjanon** [comment]
2018-02-25: I am not sure if there is another open issue for this bug, but it should still be open.

I had a very difficult time installing the latest version of Docker Toolbox over an existing one. My mistake was to want to update to the latest version, the one I had was working.

I tried to run DockerToolbox.exe several times, every time I launched The Docker Quickstart Terminal or Kinematic I was given an error about the network driver. I tried "run as an administrator" as well for DockerToolbox.exe, Docker Quickstart Terminal and Kinematic. Same error each time. I had a look at the network control panel and it seemed that one of the programs tried created a new instance of the VirtualBox Host-Only Network driver every time I tried the install. I had to remove the Docker program from the Windows control panel, remove every instance (6 of them!!) of the VirtualBox Host-Only Network: Control Panel\Network and Internet\Network Connections: Properties>Configure>Driver>Uninstall for each driver named VirtualBox Host-Only Network or VirtualBox Host-Only Network #n

Then I rebooted, downloaded the latest version of VirtualBox (VirtualBox-5.2.6-120293-Win.exe), installed it after removing the existing one. I ran VirtualBox and checked it was running fine and then installed DockerToolbox.exe . I ran Docker Quickstart Terminal which asked for a permission to create the network driver (yet another one???). After a couple of minutes, I got the Docker Quickstart Terminal prompt. This is a royal pain, I wasted half a day with that.

**Comment by pedrogalv** [comment]
@qiangli solutions works in Win10. Migrated from Virtual Box 5.1.x to 5.2.8

**Comment by mnordqvist** [comment]
For me. the problem was that the DOCKER_TOOLBOX_INSTALLPATH was only set for the user used to escalate priviligies at installation. When I run Docker Quickstart as my regular user, DOCKER_TOOLBOX_INSTALLPATH is not set for this user, producing the error. 
Setting DOCKER_TOOLBOX_INSTALLPATH system wide solved the problem in my case.

**Comment by rdunne2020** [comment]
@LaPush This fixed it for me! There's a box you can check asking you to allow VB to install some NDIS6 drivers, I checked that box and it created the network adapter. Thanks for this thread!

**Comment by naveenjeeri** [comment]
I tried multiple times the issue solved after I logged in as an admin. I think we should have admin access to download the docker image.

**Comment by TineoC** [comment]
I uninstall everything from any any folder of Docker, Git, VirtualBox, in documents and program files. Then i ran the terminal and it worked ;)

**Comment by ewangchong** [comment]
Reinstall VirtualBox resolved my issue.

**Comment by talk2ajay** [comment]
stevelacerda7's solution worked for me on WIN 10 and VM 5.2.8

**Comment by himaprakashd** [comment]
christianhuening comment helped me.

**Comment by rohitnirantar** [comment]
I had same issue. Followed below steps:
-Uninstall Docker and VM
-Delete temp folders from profile
-install Docker as admin
-Uninstalled VM and installed version 5.2.38
-Run docker as Admin

![image](https://user-images.githubusercontent.com/28030858/76584005-bb6d3080-64a8-11ea-9bab-fa19b27f8221.png)

**Comment by andres1234loa** [comment]
hola queria compartir de como solucione este problema:
1- si tienes instalado virtual-box(VM) antes de instalar docker-toolbox desinstale el VM 
2-una vez instalado el VM abra el vm verifique que no  tenga el  default (a mano izquierda de las otras maquinas virtuales que tenga configuradas), si llega a tener el default elimine esa maquina virtual 
3 abra la terminal de docker-toolbox, recuerde tener a bierto el vm, una vez abra el docker-toolbox le aparece un mensaje en vm: si quiere hacer una modifcacion a la interfaz  le dice que si  y espera que arranque docker 
 
espero que le sirve a alguien
