### ISSUE TITLE
Include an easy way to upgrade the Toolbox

### ISSUE THREAD

**Issue by afeld** [docker/toolbox#294]
I will preface all of this by saying that I'm new to Docker.

I installed the Toolbox with the .pkg (on a Mac) from https://www.docker.com/docker-toolbox, which went fine, but now that I have it installed, I have no idea what version of the Toolbox I have, when I need to update it, or how to do so. I _assume_ I can just download the newest Toolbox every once in awhile and it will (safely) install over the existing one, but there's nothing actually saying that. Would be helpful to put in some explicit instructions, if not including a tool to do all of this for me with a single click.

Thanks!

**Comment by guillaumemaka** [comment]
Totally agree! first time I see a software without update integration where the only way its to manually download the next release. Even in the site there is no indication of the current version (or maybe I didn't see it) where to see it you need to click the download link and inspect the version number in the filename.

+1

**Comment by BradRuderman** [comment]
+1 I also want to be able to upgrade the individual components to beta versions if needed, especially with how often releases are being pushed.

**Comment by dideler** [comment]
I want to upgrade the whole lot (especially docker and docker-compose) but not sure how to proceed.

Anyone experienced issues downloading a newer toolbox and running it?

**Comment by BradRuderman** [comment]
@dideler  nope when you download the new version it will prompt that it is an upgrade.

**Comment by dideler** [comment]
Can confirm that upgrading works by downloading and running the latest Docker Toolbox. :+1:

**Comment by bobcolner** [comment]
+1 for CLI upgrade UX
thanks!

**Comment by SvenDowideit** [comment]
This basically requires

1 some text in the release notes saying this will "install _or_ upgrade the following components"
2 nope, that's it :)

@jeffdm https://github.com/docker/toolbox/releases is pretty sparse :)

**Comment by alinford** [comment]
+1

**Comment by nathanleclaire** [comment]
I will revise the release text to indicate that if older versions of the bundled components are present, they will be upgraded to the bundled versions.

Thanks all for your participation
