### ISSUE TITLE
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

### ISSUE THREAD

**Issue by stonefury** [docker/toolbox#296]
OS-X Yosemite, this use to work fine, I didn't change vbox recently.  I can't get my terminal to connect to the vbox. Docker seems to be running fine on the vbox itself, I just can't interface with it from a terminal window. How can I debug?

One thing is I use iterm, and I recently and trying an iterm beta.  I don't know why it would matter.  But the quickstart terminal opens and closes immediately with nothing happening.

tnx

**Comment by stonefury** [comment]
I guess the basic problem I'm having for unknown reasons is I can't login to my virtual box from my iterm shell.  How can I do that manually using the certs in .docker?  The ssh port is open, but that's all I see in my network port forwarding rules in the vbox ui.

**Comment by stonefury** [comment]
If I run docker-machine env, it works, so it's just the quicklink that is the issue now.

**Comment by ryanwilliamquinn** [comment]
@stonefury did you sort this out?  i have the same issue

**Comment by chris-hydra** [comment]
Check to see if your docker `env` variables are set:
```
$> printenv | grep DOCKER
``` 
You should see `DOCKER_HOST`, `DOCKER_TLS_VERIFY` and `DOCKER_CERT_PATH` set. If not, then set them:
```
export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=/Users/{userName}/.docker/machine/machines/default
```

This worked for me OS X **10.10.3**, Docker **1.9.0**, Kitematic **0.9.3**

**Comment by ryanwilliamquinn** [comment]
@chris-hydra thanks very much, that works for me.

**Comment by alanpog** [comment]
Having same issue under El Capitan, but I get all the env variables so that's not it. Any other hint?
Tks.

**Comment by jcache** [comment]
Also running El Capitan and got the same error. I created a couple of machines using the docker-toobelt command ```docker-machine create```.

After I ran ```docker rm default``` I got this error...
```
machine [master] % docker rm default
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Error: failed to remove containers: [default]
```

The "Cannot connect to the Docker daemon. Is the docker daemon running on this host?" error continued until I ran ```docker-machine rm default```. It seems that the older docker command can clobber the newer ones.

**Comment by mcallaway** [comment]
I experienced this problem too. For me it occurs whenever I change networks. I use both wired and wireless connections, as well as VPN with the Cisco AnyConnect client. From time to time I have to restart the docker-machine, but this doesn't seem to fix routing entries whenever the Cisco VPN client has been in effect. In my case, the docker-machine wants to use 192.168.99.100:

    > docker-machine inspect default | grep IPAddress
            "IPAddress": "192.168.99.100",

In my case, VirtualBox wants to put that on vboxnet8:

    > ifconfig | grep -B 2 192.168.99
    vboxnet8: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
        ether 0a:00:27:00:00:08
        inet 192.168.99.1 netmask 0xffffff00 broadcast 192.168.99.255

After my VPN was on, this gets incorrectly mapped to the default route:

    > route get 192.168.98.100
       route to: 192.168.98.100
    destination: default
           mask: default
        gateway: homeportal
      interface: en0
          flags: <UP,GATEWAY,DONE,STATIC,PRCLONING>
     recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
           0         0         0         0         0         0      1500         0

Move it back to the right interface:

    > sudo route -nv add -net 192.168.99 -interface vboxnet8
    > ifconfig | grep -B 1 192.168.99
      ether 0a:00:27:00:00:08
      inet 192.168.99.1 netmask 0xffffff00 broadcast 192.168.99.255

Now it works again.

**Comment by bmfallon** [comment]
I seem to be having this issue with Docker Toolbox. When running:
```
docker-machine regenerate-certs default
```
I get the following: 
Regenerating TLS certificates
Host does not exist: "default"

It appears as though the quick start terminal doesn't create a machines directory with the default machine in it. Anyone else have this issue?

**Comment by trigun539** [comment]
I was able to get this working by removing any env variables I had set up for docker on .bashrc .profile

**Comment by cbs38** [comment]
I am experiencing this issue with Cisco AnyConnect. The routes appear to default to use the AnyConnect interface (which will certainly break).

**Comment by ob2** [comment]
It turns out it the docker service was not running in my case and had to be restarted by issuing a "sudo service docker start". You may have to run "docker -d" too.

**Comment by jeffdm** [comment]
Merging with https://github.com/docker/toolbox/issues/153. See the common issues in the first comment of this thread. VPN is definitely a known issue, sorry for the trouble!

Thanks for the issue!

**Comment by nwshane** [comment]
My issue was solved with a simple `docker-machine restart`.

Environment: Mac OS X 10.11.1, Docker 1.10.3

**Comment by lukewertz** [comment]
:+1: for @nwshane's suggestion. Doing ```docker-machine restart``` did the trick for me too.

**Comment by sghiassy** [comment]
As @nwshane pointed, out, I first had to do `docker-machine restart`. But afterwards I still had to re-eval the `env` variables using `eval $(docker-machine env default)` and restart the terminal. So my steps were:

* `docker-machine restart`
* Quit terminal (or iTerm2, etc, etc) and restart
* `eval $(docker-machine env default)`
