### ISSUE TITLE
docker rm `docker ps -aq` seems to not work on last version

### ISSUE THREAD

**Issue by tdeheurles** [docker/toolbox#299]
hi,

I'm a bit disapointed this morning as trying to remove my containers with the same way as usually does not work:

```bash
# the commands I use to clean
docker kill `docker ps -q`
docker rm `docker ps -a -q`
docker rmi `docker images -q -f dangling=true` # to clean the <none> containers
```
Today the command does not do anything.

It works when I explicitly give a container id: `docker rm <containerId>` ...

**Comment by tdeheurles** [comment]
Forgot to say:
- Windows 7
- DockerToolbox-1.9.0c
- standard shell with toolbox (MINGW64)

**Comment by jeffdm** [comment]
Try this:

`docker rm $(docker ps -aq)`

we recently reverted to the standard Windows Terminal emulator, which fixed several issues around using the `-it` flags, and with `docker-compose`.

**Comment by tdeheurles** [comment]
I tried with `$(...)` operation on `babun` and forgot on docker shell.

It works with `docker rm $(docker ps -aq)` on the `toolbox shell`

```
Babun: docker kill `docker ps -q` => does not work
Babun: docker kill $(docker ps -q) => does not work
Officiall toolbox shell: docker kill `docker ps -q` => does not work
Officiall toolbox shell: docker kill $(docker ps -q) => work
```

Hard to deploy the docker shell on windows `oO`

**Comment by tdeheurles** [comment]
Thanks for answer ;-)

**Comment by SafNaaz** [comment]
none of the commands working on windows cmd or toolbox shell
