### ISSUE TITLE
docker Quickstart Terminal deleted my default VM

### ISSUE THREAD

**Issue by timaschew** [docker/toolbox#302]
I cannot reproduce this issue anymore, but today I downloaded the dockertoolbox v1.9.0d and reinstall it (I had docker 1.8.x before)

When the installation was done I started the Quickstart Terminal and it realized that there is already a VM but it was shutdown, so it started the VM. Then I quit the terminal and start the Quickstart Terminal again.
The VirtualBox Manager window was open and I realized that the default VM in my list did disappear.
Then I verified it via `docker-machine ls`, it was really gone. The next time I started the Quickstart Terminal terminal, the default VM was created from scratch, but all my data is gone without any warning!

This bug is really serious!

Darwin Antons-MacBook-Air.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64
```

````
Containers: 0
Images: 0
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: 4EKG:SBYO:XLLO:2AXW:MPB4:6OPI:UBHK:SGFX:3NWF:W7P6:MX4X:DZT3
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 18
 System Time: 2015-11-17T12:41:52.645593699Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

VirtualBox 5.0.8

Not sure if it's related, but I had some similar on another mac with docker 1.9 and Kitematic.
I had a default machine but not for VirtualBox instead for VMFusion by creating it by hand. 
When I started Kitematic it removed the default machine (VMFusion) and created a new one for VirtualBox.

**Comment by jeffdm** [comment]
Merging with https://github.com/docker/toolbox/issues/351, sorry for the late reply
