### ISSUE TITLE
docker host ip address

### ISSUE THREAD

**Issue by harishpokharel** [docker/toolbox#303]
Running docker version 1.8.2. Install it via toolbox.
It creates a virtual host only adapter and associates IP address 192.168.99.1 with it. With DHCP IP address starting from 192.168.99.100 to 192.168.99.254.

The docker host gets IP in the range 192.168.99.x range. I get this.

I don't want to use IP address in this range. So, I changed the IP address on the interface to 192.168.200.1 with DHCP range from 192.168.200.100 to 192.168.200.254. 

When I reboot the docker host it still shows ip address in 192.168.99.x range. 

Is there any default config for docker that it always gets ip address in 192.168.99.x range and not other range that I need.

I uninstalled the docker and just ran iso in virtual box without installing it using docker toolbox but have similar issue.

*I can use 200 range ip address if ip provide ip to the eth1 interface with ifconfig command. But i loose this ip when i reboot the box.

**Comment by jeffdm** [comment]
I think this issue belongs in [docker/machine](https://github.com/docker/machine/issues), or at least they'll know more! Thanks for posting an issue - I'll close this one for now but please do follow up with them for more info.
