### ISSUE TITLE
Error creating machine: Error in driver during machine creation

### ISSUE THREAD

**Issue by godsmustbcrazy** [docker/toolbox#305]
Windows 10
Docker 1.0.9d
VirtualBox  5.0.11 r104101

Whenever I start the docker Quickstart terminal I get the following
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: Maximum number
of retries (5) exceeded

Attached is the log file

[VBox.txt](https://github.com/docker/toolbox/files/37511/VBox.txt)

**Comment by qinwf** [comment]
I have the same issue with Windows 10 DockerToolbox-1.9.1b.exe.

**Comment by dogik** [comment]
+1

**Comment by jeffdm** [comment]
Thanks so much for the issue, please see https://github.com/docker/toolbox/issues/153
