### ISSUE TITLE
docker-machine 0.5.1 is not in 1.9.0d toolbox release

### ISSUE THREAD

**Issue by jeanlaurent** [docker/toolbox#307]
The docker toolbox release note 1.9.0d wrongly indicates that it includes docker-machine 0.5.1, but it is not, it still include docker-machine 0.5.0 as the source indicates  : https://github.com/docker/toolbox/blob/v1.9.0d/Dockerfile.osx#L35-L36

Some users are confused about it.

**Comment by dmp42** [comment]
cc @jeffdm

**Comment by jeanlaurent** [comment]
see #308

**Comment by jeffdm** [comment]
Fixed, and sorry for the delay. It's included in https://github.com/docker/toolbox/releases/tag/v1.9.1
