### ISSUE TITLE
Automatic or assisted VM upgrades

### ISSUE THREAD

**Issue by aduermael** [docker/toolbox#31]
I already had a machine called `dev` when I installed the toolbox. 
When I launched the CLI I got that error: 

```shell
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)
```

Because I had Docker 1.6 installed on that machine.
I fixed it with: 

```shell
machine upgrade dev
```

But it should be automatized somehow.

**Comment by jeffdm** [comment]
Update:

- [x] Migration from Boot2Docker => Machine
- [ ] Upgrade existing machine VMs

**Comment by mchiang0610** [comment]
@jeffdm By upgrade you are meaning for the future version of Boot2Docker ISO?

**Comment by bfirsh** [comment]
:+1:

I installed Toolbox 1.8.1c but I'm still left with a 1.8.0 default VM.

**Comment by SvenDowideit** [comment]
@jeffdm this now happens doesn't it? my v1.10rc vm seems to have been auto-upgraded to the release...

**Comment by jeffdm** [comment]
@SvenDowideit it does indeed! Thanks for the ping
