### ISSUE TITLE
Make installation of Git optional

### ISSUE THREAD

**Issue by nerro** [docker/toolbox#310]
Many developers have already Git installed on their machines (as well as VirtualBox and it's optional). After Docker Toolbox installation already installed Git will be uninstalled and the version from Toolbox will be installed.

Would not be better to make a git installation optional?

**Comment by djsylvester** [comment]
Agreed. This is how it was in prior versions. Git for me is already installed and kept up to date separately.

**Comment by eshepelyuk** [comment]
Upvote the issue. It's even more annoying because docker toolbox uninstalls currently installed `git for windows` (with higher version) and installs own one.

**Comment by nerro** [comment]
Thanks for feedback. The fix is really small.
Perhaps @jeffdm will find time to look at it.

**Comment by radum** [comment]
:+1:

**Comment by simonthum** [comment]
+1

**Comment by virgo47** [comment]
+1

**Comment by wanderr** [comment]
+1

**Comment by hgwood** [comment]
:+1:

**Comment by princemaple** [comment]
:+1:

**Comment by thaJeztah** [comment]
@jeffdm I see https://github.com/docker/toolbox/issues/319 is merged; should this one be closed?

**Comment by princemaple** [comment]
could it wait til a new version that really has git as optional is released?
or could you guys release a new version with git being optional?
I had to re-install toolbox today and the latest version (1.9.1c) still has git as mandatory. I was quite annoyed.

**Comment by jeffdm** [comment]
Closing for now as Git is now optional. The Docker Quickstart Terminal does require an installation of 64-bit Git, though there's a separate issue for that.
