### ISSUE TITLE
Installing DockerToolbox-1.9.0d.pkg downgrade Virtualbox from 5.10 -> 5.8

### ISSUE THREAD

**Issue by kojustin** [docker/toolbox#311]
I had previously had VirtualBox installed on my OSX machine. After running the DockerToolbox-1.9.0d.pkg with all default settings my version of VirtualBox was downgraded to 5.8.

**Comment by SvenDowideit** [comment]
yes, it would be nice if the installer checked what version was installed, and prompted asking if the user wants to downgrade, not just for vbox, but the other components too.

**Comment by jeffdm** [comment]
This should no longer occur - the installer will only install VirtualBox if the version is lower than the included one.

**Comment by jeffdm** [comment]
Thank you for the issue!
