### ISSUE TITLE
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.

### ISSUE THREAD

**Issue by Masshat** [docker/toolbox#312]
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
.bashrc (line 5): [[ $- != i ]] && return
from sourcing file .bashrc
called on standard input
source: Error while reading file “.bashrc”

**Comment by jeffdm** [comment]
This doesn't seem to be a Docker Toolbox bug - we don't modify `.bashrc`. I'll close this for now - but would love to help figure this out for you. What do you have on line 5 of your `.bashrc` file?
