### ISSUE TITLE
Add version of included packages to installer and doc

### ISSUE THREAD

**Issue by gavioto** [docker/toolbox#313]
When installing docker toolbox on machines with some components installed could be useful to know the versions of included packages

**Comment by jeffdm** [comment]
The versions are included in the installer

<img width="732" alt="screen shot 2015-11-21 at 12 44 08 pm" src="https://cloud.githubusercontent.com/assets/251292/11319693/9bfb4414-904d-11e5-8093-3b7a554795af.png">

and also in the release notes here: https://github.com/docker/toolbox/releases

**Comment by gavioto** [comment]
ok. Thanks. I don't remember why I can't see the versions

**Comment by jeffdm** [comment]
No problem! :smile:  thanks for the issue!
