### ISSUE TITLE
DockerToolbox-dockercon-demopack.pkg (v1.9.1) removes docker binary

### ISSUE THREAD

**Issue by pettai** [docker/toolbox#316]
Then installing the new addon DockerToolbox-dockercon-demopack.pkg, (released along with the v1.9.1 release), the "docker" binary is removed:

```
frpet1l-13inch-3:~ pettai$ ls -l /usr/local/bin/docker
ls: /usr/local/bin/docker: No such file or directory

frpet1l-13inch-3:~ pettai$ ls -l /usr/local/bin/docker-x
lrwxr-xr-x  1 pettai  admin  41 Nov 20 10:42 /usr/local/bin/docker-x -> /usr/local/docker-experimental/bin/docker
```

I assume this is a bug, as the former bundle DockerToolbox-dockercon-demopack-edition-1.9.0d.pkg, installed both docker and docker-x

**Comment by jeffdm** [comment]
[Fixed](https://github.com/docker/toolbox/releases/download/v1.9.1/DockerToolbox-dockercon-demopack.pkg), thanks for the issue.  It seems Mac OS X was recognizing this as a replacement package. Apologies for this.
