### ISSUE TITLE
Error getting IP address: Something went wrong running an SSH command

### ISSUE THREAD

**Issue by kostonstyle** [docker/toolbox#317]
Hi all
I downloaded docker-machine from https://www.docker.com/docker-toolbox and installed on my mac os x el captain version 10.11. I followed the tutorials on the site and it worked fine.
Then today I start my computer and want to download mysql from docker hub.
I start Docker Quickstart Terminal and on the console, then it shows to me:

```
Machine default already exists in VirtualBox. 
Setting environment variables for machine default...
                    ##         .
              ## ## ##        ==
           ## ## ## ## ##    ===
       /"""""""""""""""""\___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
       \______ o           __/
         \    \         __/
          \____\_______/
Error getting IP address: Something went wrong running an SSH command!
command : ip addr show dev eth1
err : exit status 255
output : 
docker is configured to use the default machine with IP For help getting started, check out the docs at https://docs.docker.com 

Error running connection boilerplate: Error getting driver URL: Something went wrong running an SSH command!
command : ip addr show dev eth1
err : exit status 255
output :
```
What do am I doing wrong?
Thanks

**Comment by reviling** [comment]
I get the same problem on OSX 10.10.5.

**Comment by baoming** [comment]
windows 10 failed too.

windows 10 64bit
toolbox 1.9.1a

Creating Machine default...
Running pre-create checks...
Creating machine...
(default) OUT | Creating VirtualBox VM...
(default) OUT | Creating SSH key...
(default) OUT | Starting VirtualBox VM...
(default) OUT | Starting VM...
Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Looks like something went wrong... Press any key to continue...

**Comment by owlas** [comment]
I have the same set up as kostonstyle and have also had the same problem. I loaded the quickstart terminal once and all was working, I then reloaded the terminal and it has thrown this error ever since.

**Comment by reviling** [comment]
I don't know why this worked (I'm new to docker), but removing the default vm and then reloading the quickstart terminal (creates a new default vm) worked for me.

**Comment by bojanstef** [comment]
@reviling would there be a way to automate this? 
```bash
$ docker-machine rm default
$ docker-machine create
```

**Comment by bojanstef** [comment]
I was able to recreate the issue by running
```bash
# hack/make.sh
``` 
Then ctrl-c'ing out before it completed
From: http://docs.docker.com/opensource/project/set-up-dev-env/
Specifically without "binary" at the end.

```bash
Machine default already exists in VirtualBox.
Setting environment variables for machine default...

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": tls: DialWithDialer timed out
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

**Comment by marklocker** [comment]
I'm also experiencing this error and have the same results as @reviling, running `docker-machine rm default` and then firing up the quickstart terminal worked for me - but I also don't know why…

I'm having to do this quite regularly, so if anyone has any ideas then please share them!

**Comment by ewilliam** [comment]
running into the same issue here. `docker-machine rm default` works, though annoying.

**Comment by bobbypriambodo** [comment]
Encountered this issue after I ran `docker pull training/sinatra`, I don't know if it's relevant, but here are the full output of my terminal:

```shell
➜  ~  docker pull training/sinatra
Using default tag: latest
latest: Pulling from training/sinatra
d634beec75db: Pull complete
27fb5491e391: Pull complete
8e3415728a3f: Pull complete
630b03963440: Pull complete
962115fdbb58: Pull complete
9ea38b02c228: Pull complete
e20166048ece: Extracting [========================================>          ] 51.25 MB/62.67 MB
8b16a891bd1a: Download complete
Pulling repository docker.io/training/sinatra
f0f4ab557f95: Error pulling image (latest) from docker.io/training/sinatra, mkdir /mnt/sda1/var/lib/docker/graph/_tmp/acc5caf9b5f0080306956f9b43ae9106345e0ec675ae6e144e7ae869fa24811b: read-only file system 6e144e7ae869fa24811b: read-only file system
Error pulling image (latest) from docker.io/training/sinatra, mkdir /mnt/sda1/var/lib/docker/graph/_tmp/acc5caf9b5f0080306956f9b43ae9106345e0ec675ae6e144e7ae869fa24811b: read-only file system
```

You see, the `e20166048ece: Extracting...` part got stuck for a while and then the error pops out. I also tried one more time, but it gives me just the error.

```shell
➜  ~  docker pull training/sinatra
Using default tag: latest
latest: Pulling from training/sinatra
d634beec75db: Pulling fs layer
Pulling repository docker.io/training/sinatra
f0f4ab557f95: Error pulling image (latest) from docker.io/training/sinatra, mkdir /mnt/sda1/var/lib/docker/graph/_tmp/5d52c3b63b2a7c79b27a4d0d79ad4b544a6aacec467e6e35bb1847cb31e92097: read-only file system 6e35bb1847cb31e92097: read-only file system
Error pulling image (latest) from docker.io/training/sinatra, mkdir /mnt/sda1/var/lib/docker/graph/_tmp/5d52c3b63b2a7c79b27a4d0d79ad4b544a6aacec467e6e35bb1847cb31e92097: read-only file system
```

Thought the machine has stopped, so I checked, and here's where I encounter the error:

```shell
➜  ~  docker-machine start default
Machine "default" is already running.

➜  ~  docker-machine status default
Running

➜  ~  docker-machine ip default
Error getting IP address: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  :
```

`docker-machine rm default` and `docker-machine create --driver virtualbox default` fixed it, though... but my local images are lost! I'm still new to Docker so I find this confusing.

**Comment by illagrenan** [comment]
I have same issue on Windows 8.1.

```bash
docker --version
Docker version 1.9.1, build a34a1d5
docker-machine --version
C:\Program Files\Docker Toolbox\docker-machine.exe version 0.5.2 ( 0456b9f )
docker-compose --version
docker-compose version 1.5.2, build e5cf49d
```

**Comment by fergvick** [comment]
I have the same error though when trying 
```
docker-machine rm default
```
it just got stuck and never gave any output, so I went ahead and removed the default folder manually. Though when trying to run 
```
docker-machine create -d virtualbox default
```
It got stuck on creating shh again, this was the output;
```
Running pre-create checks...
Creating machine...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
Error creating machine: Error in driver during machine creation: /usr/local/bin/VBoxManage modifyvm default --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 1024 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd failed:
VBoxManage: error: The machine 'default' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp
```
The default folder is created though it still has the same SSH error. I've tried uninstalling and reinstalling the docker toolbox multiple times and nothing is changing, any suggestions???

**Comment by tomphp** [comment]
Also getting the same issue here (El Capitan)

**Comment by nasserahmed** [comment]
OSX: v10.11.2 (El Capitan)
Virtualbox: 5.0.10r104061
Docker version 1.9.1, build a34a1d5

The following worked for me:
https://github.com/docker/machine/issues/1801#issuecomment-147101937

**Comment by udoless** [comment]
Also getting the same issue here

**Comment by tomphp** [comment]
+1 for @nasserahmed's link - deleting all the Host-only networks from virtual box fixed it.

**Comment by skyer9** [comment]
+1 deleting all image from virtual box fixed it.

**Comment by stevelr** [comment]
I have a work-around that I've been using for a few weeks - all the regular "docker" commands work from my terminal, and I never use docker-machine anymore. To ssh into the vm, I use the docker-ssh alias defined below.

Put the following lines into a script in ~/bin/docker-setup and in my ~/.bashrc I source it with the command ". $HOME/bin/docker-setup" . You need to get the host ip address (probably the eth0 interface) to set in this file, which you can get by typing "ifconfig | more" in the console window (press Show on the Virtualbox UI if the console window is not visible). This is the only thing I ever need to do in that window. After this setup, you can just type "docker-ssh" to ssh into the boot2docker vm from your regular Terminal or iTerm window.
```
#
# source this
#

# Set this IP addr to the location of the docker host
# (For bridged networking, this is the LAN address on eth0)
export DOCKER_IP=10.100.1.114

export DOCKER_DEF="$HOME/.docker/machine/machines/default"
export DOCKER_ARGS="--tls=true --tlscacert=$DOCKER_DEF/ca.pem --tlscert=$DOCKER_DEF/cert.pem --tlskey=$DOCKER_DEF/key.pem"
alias docker-ssh="ssh -i ~/.docker/machine/machines/default/id_rsa docker@$DOCKER_IP"
alias docker-scp="scp -i ~/.docker/machine/machines/default/id_rsa docker@$DOCKER_IP"
alias docker="docker $DOCKER_ARGS"
```

With this setup, you can use any docker command "docker ps", "docker build" ,etc. If you use shell scripts (build.sh, or Makefile, etc.) to construct docker images, don't forget to include ${DOCKER_ARGS} on the command line in the script file. For example, 
```
    #!/bin/sh
    docker ${DOCKER_ARGS} build -t myimage .
```

Bonus tip:
If you want to set up port forwarding between the VM and your desktop, you can use standard ssh port forwarding. To do this you need to know the docker machine's host ip address, which you can get with 
"ifconfig docker0".  I run an http server on my mac on port 7770 that I want to make available to all docker containers, so I use the -R reverse port forwarding flag as follows (add these lines to ~/bin/docker-setup).
```
export DOCKER_BRIDGE_HOST_IP=172.17.0.1
alias docker-ports="ssh -f -N -g -R $DOCKER_BRIDGE_HOST_IP:7770:localhost:7770 -i ~/.docker/machine/machines/default/id_rsa docker@$DOCKER_IP"
```

To start port forwarding, type "docker-ports" in a terminal window. After executing this command, docker containers can access the server at http://$DOCKER_BRIDGE_HOST_IP:7770.When setting up remote port forwarding that binds to a specific IP address, you have to enable GatewayPorts in sshd_config. In /etc/ssh/ssh_config (or /usr/local/etc/ssh/sshd_config), add the line
```
    GatewayPorts yes
```

**Comment by iongion** [comment]
On windows 10 - using windows command prompt shell
Virtualbox: 5.0.10-r104061

```
docker-machine -v
docker-machine version 0.5.3, build 4d39a66
docker-machine rm default
Do you really want to remove "default"? (y/n): y
(default) Stopping VM...
Successfully removed default
```
Re-creating the machine
```
docker-machine create --driver virtualbox default
Running pre-create checks...
Creating machine...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting VM...
Error creating machine: Error in driver during machine creation: Maximum number of retries (5) exceeded
```

Although I see the machine running in Virtualbox Preview UI rectangle in the upper-right corner of the window.

What should I investigate more ?

**Comment by danpospisil** [comment]
I have exactly the same issue with the same behavior as iongion

**Comment by iongion** [comment]
http://superuser.com/questions/1002160/failed-to-start-virtual-device-in-oracle-virtual-box/1002243#1002243

**Comment by iongion** [comment]
Managed to make it be able to execute `docker-machine env default`

![image](https://cloud.githubusercontent.com/assets/867609/11845552/c57d0e50-a414-11e5-8310-9b86c0732d49.png)

Apparently adding that port mapping additional rule made it work.
The one for ssh is reset by docker-machine whenever you restart the default vm.

Now docker-compose is not running.
```
$ docker-compose --verbose build
compose.config.config.find: Using configuration files: .\docker-compose.yml
docker.auth.auth.load_config: Trying c:/Users/worker\.docker\config.json
docker.auth.auth.load_config: File doesn't exist
docker.auth.auth.load_config: Trying c:/Users/worker\.dockercfg
docker.auth.auth.load_config: File doesn't exist - returning empty config
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\projects\compose\compose\cli\main.py", line 54, in main
  File "C:\projects\compose\compose\cli\docopt_command.py", line 23, in sys_dispatch
  File "C:\projects\compose\compose\cli\docopt_command.py", line 26, in dispatch
  File "C:\projects\compose\compose\cli\main.py", line 169, in perform_command
  File "C:\projects\compose\compose\cli\command.py", line 53, in project_from_options
  File "C:\projects\compose\compose\cli\command.py", line 89, in get_project
  File "C:\projects\compose\compose\cli\command.py", line 72, in get_client
  File "c:\projects\compose\venv\lib\site-packages\docker\api\daemon.py", line 78, in version
  File "c:\projects\compose\venv\lib\site-packages\docker\client.py", line 110, in _get
  File "c:\projects\compose\venv\lib\site-packages\requests\sessions.py", line 477, in get
  File "c:\projects\compose\venv\lib\site-packages\requests\sessions.py", line 465, in request
  File "c:\projects\compose\venv\lib\site-packages\requests\sessions.py", line 573, in send
  File "c:\projects\compose\venv\lib\site-packages\requests\adapters.py", line 415, in send
requests.exceptions.ConnectionError: ('Connection aborted.', error(10061, 'No connection could be made because the target machine actively refused it'))
docker-compose returned -1
```

**Comment by danpospisil** [comment]
Today I got some update from Microsoft installed and Docker started working ... so try to install latest updates for Windows 10 - might work for you as well :)

**Comment by itayB** [comment]
Same issue append to me.
Windows7, VirtualBix 5.0.10

I changed the name of the default VM to default1 (in Oracle VM VirtualBox Manager GUI), and start Docker Quickstart Terminal again (with Run as administrator), Worked!

**Comment by baoming** [comment]
update 1.9.1f.exe ALL runs well.

**Comment by itayB** [comment]
Update: running 'Docker Quickstart Terminal' with 'Run as administrator' solved the problem for me (Windows7)

**Comment by amasson88** [comment]
I cannot start  "Docker Quickstart Terminal" or Kitematic (toolbox 1.9.1f), I have this error on Windows 8.1:
00:00:45.613089 VMMDev: Guest Log: 00:00:10.011751 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed
(is it related to https://github.com/docker/toolbox/issues/214 ?)

**Comment by zhentaoo** [comment]
@bojanstef 
thank you！
$ docker-machine rm default
$ docker-machine create --driver virtualbox default

**Comment by sahas-** [comment]
Its OS X EI Capitan. 
Remove and recreate default didn't work. 
Getting "Error creating machine: Error in driver during machine creation: Maximum number of retries (5) exceeded"
<img width="888" alt="screen shot 2016-01-10 at 8 53 50 pm" src="https://cloud.githubusercontent.com/assets/10361685/12226099/5794c712-b7dc-11e5-9dfa-9218d3c40a1a.png">

Sticking with boot2docker for now, its working well on the same box..

**Comment by eh1160** [comment]
I tried almost all the solutions and none of them worked.  But it works now and I'm pretty sure chmod on the ssh config ultimately fixed it.
```
chmod 600 /Users/<me>/.ssh/config
```

OS X El Capitan v10.11.2
Docker version 1.9.1h

**Comment by timqian** [comment]
OS X Yosemite v10.10.5
Docker version 1.9.1, build a34a1d5

`docker-machine rm default ` works for me 

don't konw why...

**Comment by jp-gorman** [comment]
I had the issue and the solution to remove the default is not of much use if you have spent a lot of time downloading images to it. I did note that I was getting the issue and I had a machine crash and upon reboot, I did not start the VM, but let Docker Quickstart Terminal start it, and it came up fine. I thought it might have deleted the default host, but no it was there with the images.

I believe for those wanting to know why the docker-machine rm default works, it's because it's building a new box and setting up new ssh etc to it, so like wiping completely and starting fresh. No idea why it gets the ssh tangled though after some time.

I need to get my NAS back online to let TimeMachine backup the .docker folder ASAP before it wipes the host again! The coupling of disk images between docker and VirtualBox (in my case) could be a lot cleaner to prevent restore issues between disk UIDs if your host does get blown away (I spent an afternoon matching these in xml files).

**Comment by hkaushalya** [comment]
I had the same issue, but removing the default as @reviling mentioned did work for me. Thanks to @reviling and @bojanstef for the commands. 

Docker version 1.9.1, build a34a1d5
Windows 7 Enterprise, service pack 1
VirtualBox version 5.0.12r104815

**Comment by adg-eric** [comment]
OS X Yosemite v10.10.5
Docker version 1.9.1, build a34a1d5
docker-machine version 0.5.5, build 02c4254

It's unusable. I cannot run a command which takes time.

**Comment by bshlgrs** [comment]
Mac OS X 10.11
Docker version 1.9.1, build a34a1d5
docker-machine version 0.5.6, build 61388e9

Same problem; and it had the same fix. But the fix is kind of annoying: I don't want to have to recreate my default machine from scratch.

**Comment by Malu44** [comment]
Same for me:
Mac OS X 10.10.5 Yosemite
Docker version 1.9.1, build a34a1d5

I want to start my docker again. Can't create all the time a new instance.

**Comment by Malu44** [comment]
docker-machine start default
Error checking TLS connection: Error getting driver URL: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  : Warning: Identity file machines/default/id_rsa not accessible: No such file or directory.

But the file is there and readable for my user
-rw-------  1 devel  staff  1679 28 Okt 09:10 /Users/devel/.docker/machine/machines/default/id_rsa

Maybe docker-machine sets the wrong path?

**Comment by Malu44** [comment]
This is an issue connection the docker-client to the docker-daemon. The daemon is running.
I've checked this by ssh to the virtual box.
There are all my images and containers.

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.9.1, build master : cef800b - Fri Nov 20 19:33:59 UTC 2015
Docker version 1.9.1, build a34a1d5
docker@default:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by kevincolyar** [comment]
Are any of you guys using multiplexed ssh connections in your `~/.ssh/config`?
 
Something similar to this:

```
ControlMaster auto
ControlPath /tmp/%r@%h:%p
ControlPersist yes
```

I disabled mine and appears to have solved my issue (for now).

**Comment by sandhujasmine** [comment]
Was running into the same problem and I removed my .ssh/config - then slowly added the lines back as I recreated default docker-machine. I had to remove the following lines in my config file and now everything seems to work fine.

```
Host *
    UseRoaming No
```

I believe I added this due to this [ssh-vulnerability](http://www.openssh.com/txt/release-7.1p2)

**Comment by timaschew** [comment]
I had this issue too. It hink the issue has something to do with the ssh keys, because when I started the quickstart terminal the first time, it tooks really long time at this step `(default) Creating SSH key...`.
Then I just started a new docker quickstart terminal, and there I saw the same message, so maybe two pairs of ssh keys were gerenerated and it become broken, because it were executed 2 times in parallel.

The error I get only after a trying to restart the machine.

**Comment by jeremysmitherman** [comment]
Same issue here, rming the default box and recreating it works, but this is an unacceptable workflow and I'll have to use an alternative in the meantime.

**Comment by leestack** [comment]
Thank you bojanstef, this worked. Lee

bojanstef commented on Nov 29, 2015
@reviling would there be a way to automate this?

$ docker-machine rm default
$ docker-machine create --driver virtualbox default

**Comment by leestack** [comment]
By the way, virtualbox seems to be the common thread here. Lee

**Comment by burzum** [comment]
I have the same issue, deleting and creating the machine as suggested two posts before mine doesn't work either for me.

```sh
λ docker-machine create --driver virtualbox default
Running pre-create checks...
Creating machine...
(default) Copying C:\Users\Florian\.docker\machine\cache\boot2docker.iso to C:\Users\Florian\.docker\machine\machines\default\boot2docker.iso... (default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

**Comment by drewlamur** [comment]
+1 @illagrenan 

Thank you - I was able resolve this issue yesterday using the link in your post. I am using OSX, not windows but I saw similar error output running and debugging docker-machine tool commands. Note: I was hung up at '(default) Starting VM...'

Here were the errors that I saw:

- Error getting IP address: Something went wrong running an SSH command!
- Error checking TLS connection: Error getting driver URL: Something went wrong running an SSH command!

Here were the steps that resolved the issue for me:

1 - Upgraded version of VirtualBox to Version 5.0.14 r105127 ( i do want to mention that this change likely did nothing for me, so you can skip this step ).
2 - In the terminal, run - sudo chmod -R 600 ~/.ssh/

When I completed step 2, I no longer saw the errors running docker-machine tool commands. If you are hung up at '(default) Starting VM...' and seeing similar error output debugging, I would recommend researching the owner permissions before deleting and re-creating your default machine. You will blow away your local images when you delete.

**Comment by jpierson** [comment]
Running the following seems to have fix my issue.

```
$ docker-machine rm default
$ docker-machine create --driver virtualbox default
```

I'm not sure if it's related but I first saw the error after opening up [Kitematic](https://github.com/docker/kitematic) which was installed along with the [Docker Toolbox](https://www.docker.com/toolbox).

Win 10
MacBook Pro
Docker version 1.10.1, build 9e83765

**Comment by jeffdm** [comment]
Merging this thread with https://github.com/docker/toolbox/issues/153 - feel free to continue the discussion there!

Just wanted to say a huge thanks to everyone who has provided input to this thread, and thanks for creating an issue!

**Comment by will-parsons** [comment]
OSX El Capitan. If it helps anyone, I had two obstacles:

1. I was connected to a VPN - my employer (rightly) restricts SSH and other connectivity around the network. 

2. By default I proxy all SSH connections (another security measure), and these scripts are using SSH to connect to the 'default' VM. 


After disconnecting VPN, and setting my ~/.ssh/config back to "normal", everything worked as intended.  Figuring out how to run this all seamlessly is my problem :) - might just use an independent VM or Cloud Server for development instead.

**Comment by TimoSolo** [comment]
Did the `docker-machine rm default` thing a couple times, but takes ages to download image.

Found a simpler solution though! Open VirtualBox, turn off the "default" machine. Run Docker Quickstart and it starts up the VM and connects fine!

**Comment by syzer** [comment]
+1

**Comment by chineshboy** [comment]
I have met the same problem, on OSX EI Capitan. I just restarted my Mac and then it became fine.
So I think it is something wrong with VirtualBox, @TimoSolo 's answer might be a very good way.

**Comment by Fernando9** [comment]
I was having the same problem. Thank you @drewlamur  changing the permissions on my ssh folder helped me with the issue for know. I hope that can give a better work around for this issue.

**Comment by iver3on** [comment]
$ docker-machine rm default
$ docker-machine create --driver virtualbox default

I just do like that. but it appear another fault:

``$ docker-machine create --driver virtualbox default
Running pre-create checks...
Creating machine...
(default) Copying C:\Users\31639\.docker\machine\cache\boot2docker.iso to C:\Users\31639\.docker\machine\machines\defaul
t\boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Waiting for an IP...

who can help me ?
windows 10 and docker 1.11

**Comment by Somebi** [comment]
In my case, problem was in low virtual memory. 256mb is not enough. Increasing it to 512mb have helped. There should be some error handling about out of memory or something like that at boot/loading time.

**Comment by Somebi** [comment]
See logs in virtualbox directly. If it stuck, it will show at which point it does.

**Comment by harzbecher** [comment]
Same issue for me (*Windows* OS), in my case I solved it by opening virtualBox and resetting (Ctrl+T) "default" machine, then I opened *'Docker Quickstart Terminal Again'* (It thrown the same error the first time) and ran `docker-machine ls`
![image](https://cloud.githubusercontent.com/assets/7651337/17192042/713b3b38-5412-11e6-87ad-c285bcb505f3.png)

**Comment by iver3on** [comment]
i  see.

**Comment by karneaud** [comment]
+1 @TimoSolo answer worked for me

**Comment by dgoutam** [comment]
OS X El Capitan
Docker version 1.12.0

docker-machine rm default works for me

**Comment by Avec112** [comment]
OS X El Capitan
Docker version 1.12.0

Had to run this after the ssh failed.
```
docker-machine rm default
docker-machine create --driver virtualbox default
```

However. 

1. I had Docker Toolbox earlier and installed Docker for Mac later. It worked like a charm.
2. Today I cleaned my mac for all docker and boot2docker related stuff and started over
3. As it seems to me, this problem occurs when installing Docker for mac without having boot2docker (or other needed files) in place from earlier.

**Comment by Giriraj24** [comment]
@iver3on , Were you able to find solution to your problem?

I am also facing the same issue?

See below:

$ docker-machine rm default
About to remove default
Are you sure? (y/n): y
Error removing host "default": Host does not exist: "default"


$ docker-machine create --virtualbox-no-vtx-check --driver virtualbox default
Running pre-create checks...
Creating machine...
(default) Copying C:\Users\girirajgujar\.docker\machine\cache\boot2docker.iso to C:\Users\girirajgujar\.docker\machine\machines\default\boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Waiting for an IP.......

It just get stuck there and nothing happens? Any idea? 

Any idea?

I am using Win10 and Docker version 1.12

**Comment by RaazTripathi** [comment]
create a port forwarding for 57760 to 22 and it will solve problem

**Comment by webguywalker** [comment]
Recreating the virtual machines seem to be pretty extreme, lol
I've noticed from time to time `docker-machine` will lose the state of the virtual box vm.
Suspecting this is  networking specifically with OSX/VirtualBox

**What I usually run:**
```
// disconnect Lan & get on wifi
virtualbox // Power-Off Machines
docker-machine stop {{name}}
docker-machine start {{name}}
eval $(docker-machine env {{name}})
```

**Specs:**
```
El Capitan 10.11.6
Docker version 1.13.0
docker-machine version 0.9.0
VirtualBox Version 5.0.28
```

**Maybe Related:**
- [VirtualBox Ticket](https://www.virtualbox.org/ticket/16084) - TLDR; on Mac SSL connections
- https://github.com/docker/docker/issues/27734#issuecomment-259144533

**Comment by doArcanjo** [comment]
Just one more possible solution:

Check "VBoxHardening.log" if it mentions "LavasoftTcpService.exe":

- Unistall Ad-Aware (lavasoft);

Source:
https://github.com/docker/kitematic/issues/2076#issuecomment-276613251

**Comment by konkeong** [comment]
Encountered same problem.
Cannot find the IP address.
Follow the steps here and fix the problem.

Windows 7 Enterprise 64-bit
Oracle VM VirtualBox 5.1.20.r114628 (64bit) (VirtualBox-5.1.20-114628-Win.exe)
Docker Toolbox (DockerToolbox-17.05.0-ce-rc1.exe)

https://forum.adaware.com/index.php?/topic/34376-solution-for-lavasofttcpservice-problem-after-uninstallation/

1. Please, start Command Prompt as an administrator by right-clicking it and select Run as administrator.

2. Enter this command to reset the network adapter (end with the Enter key):
netsh winsock reset

3. Restart the computer.

4. Please, delete these two files:
C:\WINDOWS\system32\LavasoftTcpService64.dll
C:\WINDOWS\system32\LavasoftTcpServiceOff.ini
C:\WINDOWS\SysWOW64\LavasoftTcpService.dll (only for 64-bit Windows)
C:\WINDOWS\SysWOW64\LavasoftTcpServiceOff.ini

**Comment by kapalesachin** [comment]
This is most of the time issue because of firewall or VPN connectivity. I would suggest to create VM after you disconnect from VPN.

**Comment by JanVanIm** [comment]
When I try to delete the default VM in the Virtual Box, I cannot as the option Delete is greyed when I right-click on it. How can I delete the default VM ?

**Comment by JanVanIm** [comment]
Finally the Delete option was available

**Comment by JaredLLewis** [comment]
> I don't know why this worked (I'm new to docker), but removing the default vm and then reloading the quickstart terminal (creates a new default vm) worked for me.

You don't need to remove the vm in my experience. Simply powering it off and turning it back on will work. It appears restarting your machine without shutting town the oracle vm will cause this issue.

**Comment by ShreyaSC05** [comment]
I'm also experiencing this error and have the same results, running 'docker-machine rm default' and then firing up the quickstart terminal worked for me - but I also don't know why…

**Comment by purplezimmermann** [comment]
Hi. Maybe something similar to https://github.com/docker/toolbox/issues/887#issuecomment-702302461 is happening at least on other Windows machines, too... Essentially a conflict of different SSH clients being used by Docker in different shell environments or after some new software installation with bundled OpenSSH

**Comment by Saswat956** [comment]
> Hi all
> I downloaded docker-machine from https://www.docker.com/docker-toolbox and installed on my mac os x el captain version 10.11. I followed the tutorials on the site and it worked fine.
> Then today I start my computer and want to download mysql from docker hub.
> I start Docker Quickstart Terminal and on the console, then it shows to me:
> 
> ```
> Machine default already exists in VirtualBox. 
> Setting environment variables for machine default...
>                     ##         .
>               ## ## ##        ==
>            ## ## ## ## ##    ===
>        /"""""""""""""""""\___/ ===
>   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
>        \______ o           __/
>          \    \         __/
>           \____\_______/
> Error getting IP address: Something went wrong running an SSH command!
> command : ip addr show dev eth1
> err : exit status 255
> output : 
> docker is configured to use the default machine with IP For help getting started, check out the docs at https://docs.docker.com 
> 
> Error running connection boilerplate: Error getting driver URL: Something went wrong running an SSH command!
> command : ip addr show dev eth1
> err : exit status 255
> output :
> ```
> 
> What do am I doing wrong?
> Thanks

Hi,Do you got any soln for this
