### ISSUE TITLE
After upgrading to v1.9.1, building an Ubuntu container + (ca-certificates-)java spins the CPU to 100%

### ISSUE THREAD

**Issue by pettai** [docker/toolbox#318]
This is an odd one... 
Then I build a container that uses the ubuntu image and installs ca-certificates-java, it always hangs at:
```
Setting up ca-certificates-java (20130815ubuntu1) ...
```
There it halts, and VBoxHeadless spins up the CPU at 100%. It seems the java processes becomes zombies and hogs all available CPU.
It doesn't seem to be the newly included VBox 5.0.10 included in 1.9.1, because I tried to downgrade to Docker Toolbox 1.9.0d (including downgrading VBox to 5.0.8) but the problem persists.

I'm just guess that it could be due to something changing in the docker-machine or the other included tools? As you can see below, I have two java processes below in the docker-machine "default" that hogs the CPU as much as possible:

```
  PID USER      PR  NI    VIRT    RES %CPU %MEM     TIME+ S COMMAND      
 1021 root      20   0  436.8m  40.4m  0.0  2.0   0:14.71 S  `- docker                                               
 6714 root      20   0    4.3m   0.7m  0.0  0.0   0:00.03 S      `- sh                                               
 6719 root      20   0   17.5m   2.8m  0.0  0.1   0:00.00 S          `- bash                                         
10543 root      20   0   67.5m  34.9m  0.0  1.7   2:37.33 R              `- apt-get                                  
12017 root      20   0   12.9m   3.3m  0.0  0.2   0:00.23 S                  `- dpkg                                 
16657 root      20   0    4.3m   0.8m  0.0  0.0   0:00.00 S                      `- ca-certificates                  
16658 root      20   0    4.3m   1.5m  0.0  0.1   0:00.00 S                          `- update-ca-certi              
17542 root      20   0    4.3m   0.1m  0.0  0.0   0:00.00 S                              `- update-ca-certi          
17545 root      20   0    4.3m   1.6m  0.0  0.1   0:00.00 S                                  `- jks-keystore         
17563 root      20   0    0.0m   0.0m 49.6  0.0   0:25.84 Z                                      `- java             
12255 root      20   0    0.0m   0.0m 49.6  0.0 344:22.60 Z          `- java                
```

kill -9 on the java doesn't work. (not even a while [ 1 ]; do pkill -9 java; done). 
(I did kill the parent of the first java process as a test to see if I could get further on, hence the second solo java process above...)

**Comment by pettai** [comment]
```
top - 20:47:00 up 13:06,  2 users,  load average: 1.66, 1.70, 1.70
Tasks: 125 total,   2 running, 122 sleeping,   0 stopped,   1 zombie
%Cpu0  :   0.0/100.0 100[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||]
GiB Mem : 12.5/1.956    [                                                                                           ]
GiB Swap:  0.0/1.371    [                                                                                           ]

  PID USER      PR  NI    VIRT    RES %CPU %MEM     TIME+ S COMMAND                                                  
    1 root      20   0    9.5m   1.7m  0.0  0.1   0:06.75 S init                                                     
  191 root      20   0    8.6m   2.2m  0.0  0.1   0:00.06 S  `- udevd                                                
  808 root      20   0    8.6m   2.0m  0.0  0.1   0:00.00 S      `- udevd                                            
  809 root      20   0    8.6m   2.0m  0.0  0.1   0:00.00 S      `- udevd                                            
  934 root      20   0    9.5m   1.7m  0.0  0.1   0:00.07 S  `- crond                                                
  952 root      20   0  160.3m   3.7m  0.0  0.2   0:07.14 S  `- VBoxService                                          
  974 root      20   0   25.2m   2.8m  0.0  0.1   0:00.00 S  `- sshd                                                 
15874 root      20   0   27.7m   4.1m  0.0  0.2   0:00.00 S      `- sshd                                             
15876 docker    20   0   27.8m   3.2m  0.0  0.2   0:04.71 S          `- sshd                                         
15877 docker    20   0   11.6m   2.1m  0.0  0.1   0:00.02 S              `- sh                                       
16469 docker    20   0   15.2m   2.3m  0.0  0.1   0:00.25 R                  `- top                                  
  978 root      20   0    5.9m   1.4m  0.0  0.1   0:00.00 S  `- acpid                                                
  991 root      20   0    9.5m   0.1m  0.0  0.0   0:00.00 S  `- udhcpc                                               
  993 root      20   0   15.7m   2.0m  0.0  0.1   0:00.20 S  `- ntpd                                                 
  997 root      20   0    9.5m   0.1m  0.0  0.0   0:00.03 S  `- udhcpc                                               
 1021 root      20   0  436.8m  40.4m  0.0  2.0   0:14.56 S  `- docker                                               
 6714 root      20   0    4.3m   0.7m  0.0  0.0   0:00.03 S      `- sh                                               
 6719 root      20   0   17.5m   2.8m  0.0  0.1   0:00.00 S          `- bash                                         
10543 root      20   0   67.5m  34.9m  0.0  1.7   2:33.43 R              `- apt-get                                  
12017 root      20   0   12.9m   3.2m  0.0  0.2   0:00.22 S                  `- dpkg                                 
12241 root      20   0   17.8m   3.0m  0.0  0.2   0:00.00 S                      `- ca-certificates                  
12255 root      20   0    0.0m   0.0m 98.7  0.0 332:51.23 Z                          `- java                         
 1043 root      20   0   11.6m   2.0m  0.0  0.1   0:00.01 S  `- sh                                                   
16482 root      20   0    9.5m   1.7m  0.0  0.1   0:00.00 S  `- getty                                                
16483 root      20   0    9.5m   1.8m  0.0  0.1   0:00.00 S  `- getty                                                
    2 root      20   0    0.0m   0.0m  0.0  0.0   0:00.00 S kthreadd                                                 
    3 root      20   0    0.0m   0.0m  0.0  0.0   0:01.93 S  `- ksoftirqd/0                                          
    5 root       0 -20    0.0m   0.0m  0.0  0.0   0:00.00 S  `- kworker/0:0H                                         
    7 root      20   0    0.0m   0.0m  0.0  0.0   0:01.09 S  `- rcu_sched                                            
    8 root      20   0    0.0m   0.0m  0.0  0.0   0:00.00 S  `- rcu_bh                                               
    9 root      rt   0    0.0m   0.0m  0.0  0.0   0:00.00 S  `- migration/0                                          
   10 root       0 -20    0.0m   0.0m  0.0  0.0   0:00.00 S  `- khelper                                              
   11 root       0 -20    0.0m   0.0m  0.0  0.0   0:00.00 S  `- netns                                                
   12 root       0 -20    0.0m   0.0m  0.0  0.0   0:00.00 S  `- perf                                                 
   13 root       0 -20    0.0m   0.0m  0.0  0.0   0:00.00 S  `- writeback                                            
   14 root      25   5    0.0m   0.0m  0.0  0.0   0:00.00 S  `- ksmd                                                 
   16 root      39  19    0.0m   0.0m  0.0  0.0   0:00.28 S  `- khugepaged                                           
```

**Comment by pettai** [comment]
It looks like java becomes a zombie process...

**Comment by pettai** [comment]
It's reproducible for me all the time I try to build a ubuntu container like this:

echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
apt-get update
apt-get -y install python python-dev python-pip libffi-dev redis-server wget
wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" \
 | tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
apt-get update
apt-get -y install openjdk-7-jre-headless elasticsearch

If you have any ideas on how I should debug this odd problem, please let me know...

**Comment by pettai** [comment]
I should have mentioned that this is on Mac OS X 10.9

**Comment by maxwellpeterson-wf** [comment]
Also see this. Related: https://github.com/docker/docker/issues/18180

**Comment by brunoborges** [comment]
Got into this issue today.

Host environment: Linux lenovo 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Distro: Ubuntu 15.10
Docker Engine: 1.9.1
Docker Machine: 0.5.0 (04cfa58)

I am following the [network multi-host](https://docs.docker.com/engine/userguide/networking/get-started-overlay/) tutorial. Only difference is that I am playing with the [oracle/nosql](https://hub.docker.com/r/oracle/nosql/) image. That image is based on Oracle Linux and uses OpenJDK.

**Comment by ohEmily** [comment]
+1 on this issue. Yosemite host with Ubuntu container.

**Comment by mailming** [comment]
I got the same problem, and passed by increasing CPU to 4, and Memory to 8GB. Then problem went away.

**Comment by joshblum** [comment]
+1

**Comment by smeggingsmegger** [comment]
+1

**Comment by rsgrafx** [comment]
+1

**Comment by seeyew** [comment]
+1

**Comment by tarath** [comment]
having same issue

**Comment by thaJeztah** [comment]
This issue has been identified as a kernel issue, and (unfortunately) not only affects boot2docker, but also other distributions that have a specific kernel version.

A contributor has now identified the exact change in the kernel that causes this; https://github.com/docker/docker/issues/18180#issuecomment-167042078

**Comment by tomroy** [comment]
+1.
Yosemite 10.10.4 host with Ubuntu container.

**Comment by Wikkjaz** [comment]
+1 
El Capitan 10.11.2, container: Ubuntu 14.04

**Comment by thaJeztah** [comment]
## people having this issue:

**please use he "subscribe" issue to stay informed**, *don't* leave a `+1`; docker version, and the container you're running are **not** relevant to this problem, it's a **kernel** bug, and just happens to be triggered by Docker. This issue **cannot** be solved in Docker, but has to be fixed in the kernel.

**Comment by ghahramani** [comment]
+1

**Comment by thaJeztah** [comment]
@ghahramani did you read my comment above?

**Comment by ghahramani** [comment]
@thaJeztah sorry I removed it ;)

**Comment by franciscocpg** [comment]
[Someone may wants to apply this solution by now](https://github.com/docker/docker/issues/18180#issuecomment-167763047)

**Comment by bric3** [comment]
FYI issue docker/docker#18080 is closed, it seems a new release is imminent

**Comment by schmunk42** [comment]
Still seeing this on 1.10.1 :(

**Comment by kenden** [comment]
@schmunk42 you might have to upgrade the kernel:
https://github.com/docker/docker/issues/18180#issuecomment-179002757
what kernel version are you running?

**Comment by schmunk42** [comment]
@kenden I saw that comment before, updated my kernel to the version mentioned.
Maybe I made a mistake, but I ran into the same error.

To be honest, I was too lazy to create an account at Ubuntu One to follow the link to "Upgrade kernel to 4.2.0-27.32hf1533043v20160201b1 (PPA)".

I tried to `apt-get update & apt-get dist-upgrade`, like so:

```
# apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  linux-headers-4.2.0-27 linux-headers-4.2.0-27-generic linux-image-4.2.0-27-generic
  x11-xserver-utils
The following packages will be upgraded:
  curl ifupdown initscripts libcurl3-gnutls libssl1.0.0 linux-headers-generic
  linux-headers-virtual linux-image-virtual linux-libc-dev linux-virtual openssl
  python3-distupgrade qemu-block-extra qemu-utils sysv-rc sysvinit-utils
  ubuntu-release-upgrader-core unattended-upgrades virtualbox-guest-dkms
  virtualbox-guest-utils virtualbox-guest-x11
21 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
```

Would that be the right kernel or not?

I'll try `devicemapper` for our build-system now.

**Comment by schmunk42** [comment]
Update: I created an Account, but I am not allowed to view the page :(

<img width="593" alt="bildschirmfoto 2016-02-15 um 11 05 39" src="https://cloud.githubusercontent.com/assets/649031/13045535/25ecd3a8-d3d4-11e5-9863-f3c6f83fd0cf.png">

And my Ubuntu Wily is from here https://vagrantcloud.com/ubuntu/boxes/wily64

**Comment by jeffdm** [comment]
This should be fixed as of https://github.com/boot2docker/boot2docker/pull/1113. Further, https://github.com/docker/docker/issues/18180 is closed.

Closing this issue! Thanks all for the discussion!
