### ISSUE TITLE
Mapping volume on Windows 10 fails

### ISSUE THREAD

**Issue by simonthum** [docker/toolbox#325]
I get:

```
$ docker run -it -v $(pwd):/opt/jekyll -p 9001:9001 <redacted>/jekyll jekyll serve
invalid value "T:\\wetf\\repos\\wetf-styles-guide;C:\\Program Files\\Git\\opt\\jekyll" for flag -v: bad mode specified: \Program Files\Git\opt\jekyll
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```
`/opt/jekyll` recieves quite some mangling, like some kind of a path hack. Apparently the shell is innocent:

```
$ echo $(pwd):/opt/jekyll
/t/wetf/repos/wetf-styles-guide:/opt/jekyll
```
althought that doesn't look too likely. I tried vairous forms of escaping but no success. Thus I'm here.

**Comment by simonthum** [comment]
I forgot to add it works fine without the -v. But without volume mapping the container is a bit pointless.

**Comment by thaJeztah** [comment]
The problem here is that, by default, only the C:\Users directory is shared with the boot2docker Virtual Machine Using VirtualBox Guest Additions. It's possible to share other directories, but that requires additional configuration. For more information see this section; https://github.com/boot2docker/boot2docker#virtualbox-guest-additions

**Comment by simonthum** [comment]
Sounds good but my virtualbox manager hangs itself as soon as it comes up. Neat. I'll try some other options and resurrect this when all esle fails.

**Comment by airmanx86** [comment]
I know it's closed, but would like to share this in case someone else are having similar problem.
In the above example change `/opt/jekyll` to `//opt/jekyll` should work. Because of path conversion [http://www.mingw.org/wiki/Posix_path_conversion](http://www.mingw.org/wiki/Posix_path_conversion)
