### ISSUE TITLE
Trouble setting up default, maybe caused by virtualbox

### ISSUE THREAD

**Issue by paix120** [docker/toolbox#329]
I've had a variety of issues since trying to do this tutorial yesterday (Docker & Jupyter)
https://www.dataquest.io/blog/data-science-quickstart-with-docker/

Most of my "saga" is documented here:
https://twitter.com/BecomingDataSci/status/670428747535904768

But the gist of it is I'm having issues similar to this
https://github.com/docker/toolbox/issues/66
and this
https://github.com/docker/toolbox/issues/105
and this
https://github.com/docker/toolbox/issues/229
and this
https://github.com/docker/toolbox/issues/273

I've tried many of the suggestions in those posts, with some success (at least the error messages changed), but still not working as expected.

I'm on Windows 7 Professional 64-bit, using VirtualBox 5.0.10 r104061. I'm going to delete the VMs and the .docker machine folders and uninstall everything and start all over, probably with a recent test build of virtualbox since a couple people suggested that would help.

I will document everything I do this time here. Maybe I'll start with a smaller machine image. If you have a suggestion for a good small Docker & Jupyter image, please let me know (the one I will eventually use from dataquest has a whole bunch of packages from the scipy stack).

Thanks in advance for any help!

**Comment by paix120** [comment]
Here's my latest error, before I start over:
![no error after remove default then error](https://cloud.githubusercontent.com/assets/6315051/11454853/f86f4c1c-960c-11e5-95c6-47916f536f03.JPG)

"No connection could be made because the target machine actively refused it."

**Comment by paix120** [comment]
OK, so far, I stopped the VM, removed "default", allowed it to "delete all files". I removed the 7 "host-only networks" ethernet adapters it created from virtualbox preferences, just in case. I used Windows to uninstall Oracle VM VirtualBox 5.0.10 and Docker Toolbox version 1.9.1a (it said that uninstall was incomplete). I went into my C:/Users/Renee folder and deleted the .docker and .virtualbox folders.

Now I'm going to reboot, then download the test build of VirtualBox.

I forgot to mention in the above posts that I did get this whole setup to work once, successfully created a Jupyter notebook, then after my computer rebooted, it wouldn't work any more and I started all of this debugging.

**Comment by paix120** [comment]
The test build version of virtualbox I got is Version 5.0.11 r104393.

Just launched Docker Quickstart Terminal, which reminds me, when I was getting the  "Machine default already exists in VirtualBox... Host does not exist: "default" " error when I first tried this process, it was because windows doesn't automatically launch it with Administrator permissions, even though I'm in the admin account. I have to "run as Administrator".

So far so good, i got a Docker prompt with no errors. I'm going to attempt the docker run mentioned in the dataquest article to get the Python 3/Jupyter/scipy libraries image. dataquestio/python3-starter

It's downloading that image now.

**Comment by paix120** [comment]
It's working!! I was able to browse and create a Jupyter notebook, stopped the container and the VM, then rebooted, and I'm back and it still works!

The only thing I definitely did differently was install a test build version of virtualbox.
It gave me some funny errors when shutting down (example screenshot below), but it still worked when it came back, and I used Docker Quickstart with no issues this time!

![working_then_virtualbox error 5 before reboot](https://cloud.githubusercontent.com/assets/6315051/11455246/72613f5c-9622-11e5-98df-d6e870230886.JPG)

**Comment by paix120** [comment]
I noticed that in this version of virtualbox, the DHCP server on Ethernet #2 was enabled by default (which was a fix I tried manually before when someone suggested that was a problem)

**Comment by thaJeztah** [comment]
Thanks for opening this issue, :+1:

**Comment by jeffdm** [comment]
Merging this with https://github.com/docker/toolbox/issues/153

Thanks @paix120 @thaJeztah ! There are some common problems / solutions in the first comment of that thread.

Glad to hear the test version of VBox helped - will look into this further.

**Comment by vagif-lalaev** [comment]
The correct installation of Docker helped me when removing the virtual machine and launching the terminal as an administrator
