### ISSUE TITLE
Error loading driver "virtualbox": dial tcp: missing address with Win7 AMD64

### ISSUE THREAD

**Issue by fakegit** [docker/toolbox#330]
I Followed the instruction bellow to install the docker tool 1.91 on my win7 amd64 pc.
http://docs.docker.com/engine/installation/windows/

When Using the Docker Quickstart Terminal to create the defalt docker-machine, I got this error code:
Creating Machine default...
Error loading driver "virtualbox": dial tcp: missing address
Looks like something went wrong... Press any key to continue...

What am I missing? please help me.

**Comment by christophdebaene** [comment]
I just installed version 1.9.1b on Windows 7 Pro (64bit) and I have a similar error.

```
C:\Program Files\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. 
Stderr: Docker Machine Version: 0.5.2 ( 0456b9f ) Found binary path at .\docker-machine-driver-virtualbox.exe Launching plugin server for driver virtualbox Plugin server listening at address 127.0.0.1:59180 Error loading driver "virtualbox": dial-http tcp 127.0.0.1:59180: read tcp 127.0.0.1:59181->127.0.0.1:59180: wsarecv: An existing connection was forcibly closed by the remote host.
```

**Comment by fakegit** [comment]
The problem may be caused by virtualbox, I changed to install virtualbox 4.3.34 (pre-installed version 5.0.10), and it worked.

**Comment by narendra370** [comment]
missing ip address in my  docker terminal
