### ISSUE TITLE
[OS X Yosemite] Cannot connect to docker daemon

### ISSUE THREAD

**Issue by bmfallon** [docker/toolbox#339]
When trying to install docker toolbox on OS X Yosemite, I cannot connect to docker daemon when running the Docker Quickstart Terminal that comes with the Docker Toolbox installation.  when I run docker version I get the following:

bfallon@BFALLONMAC1:~|⇒  docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Now I have done some digging and I see some people saying to export the following variables as they don't get set automaticaly:

export DOCKER_HOST=tcp://192.168.99.101:2376
export DOCKER_TLS_VERIFY=1
export DOCKER_MACHINE_NAME=default
export DOCKER_CERT_PATH=/Users/bfallon/.docker/machine/machines/default

I notice when I navigate to the ~/.docker/machine/machines directory that it does not exist so it appears that a default machine is not being created when running the Quickstart terminal.  Has anyone had this issue before or know a fix for it?

**Comment by bmfallon** [comment]
It appears as though running Kitematic generated the default VM and fixed this issue for me. Still think it should be considered a bug as the Quickstart Terminal should have created it.

**Comment by mariussoutier** [comment]
Same here, Kitematic works, Docker Quickstart doesn't.

**Comment by Andi24** [comment]
+1 running the docker cli from Kitematic solved the issue

**Comment by ingokeck** [comment]
Same issue here. Trying out a fresh install only yields the error "Can't connect to docker daemon. Is 'docker -d' running on this host?" Very annoying as you should expect that a fresh install works out-of-the-box, which it does not.

Fix: Add the following line to my .profile:
eval "$(docker-machine env default)"

Btw, I have the impression the "export DOCKER_HOST"  lines above are now only relevant for boot2docker and not needed for docker machine anymore?

**Comment by 4kochi** [comment]
Executing `eval "$(docker-machine env default)"` in the Terminal helped.

**Comment by RVN-BR** [comment]
I hit this issue when upgrading to 1.10.1, the suggested eval didnt work...  I had to manually delete the default vm in virtualbox and then I was able to access the docker quickstart (without the addl eval)...  Could be an edge case or something to look at in the installer upgrade routine...

**Comment by jeffdm** [comment]
Merging this with https://github.com/docker/toolbox/issues/153

Namely, see the 2nd bullet point. This seems to be caused by having `DOCKER_HOST=xxxxxxxx` in your `~/.bashrc`  file

**Comment by UltimateTechDeveloper** [comment]
I am having the same issue when i execute the following command: 
`docker run --name etc.` 
The error I get:
`docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.`
The following code didn't work for me:
`eval "$(docker-machine env default)"`
