### ISSUE TITLE
[Windows] No uninstall option in Windows' control panel

### ISSUE THREAD

**Issue by hgwood** [docker/toolbox#344]
Neither Docker Toolbox or Virtual Box (when installed along Docker Toolbox) appear in the list of installed programs in Windows' control panel. The only way to uninstall is to go to the installation directory and run `unins000.exe` for Docker Toolbox, and `installers/virtualbox/virtualbox.msi` for Virtual Box only.

Notes:
- Virtual Box appears in the control panel when installed using the Oracle installer
- Git appears in the control panel

**Comment by jeffdm** [comment]
Did you try refreshing (Ctrl + R)? It should be there :smiley: 

Sorry for the late reply

**Comment by hgwood** [comment]
Wow, didn't know there was a reload feature in there! Thanks, you are right about the items being there.
