### ISSUE TITLE
toolbox-1.9.1f: docker-compose seems to be broken in OSX package

### ISSUE THREAD

**Issue by jenisys** [docker/toolbox#356]
OSX: El Capitan 10.11.2
After package installation:

```shell
$ /usr/local/bin/docker-compose --version
Illegal instruction: 4
```

The other parts seem to be OK (version-check works for docker, docker-machine; basic machine creation works, too).

**Comment by FrenchBen** [comment]
what about `docker-compose version` ?

**Comment by jenisys** [comment]
The "Illegal instruction" indicates that the "executable" is not usable IMHO. 
Therefore, ``docker-compose --help`` has the same result.

**Comment by jenisys** [comment]
Same as ``docker-compose version``.

**Comment by FrenchBen** [comment]
What's the output of:
`python --version`
`ls -lah /usr/local/bin/docker-compose`

**Comment by jenisys** [comment]
Python: Python 2.7.11 (installed package from python.org, under "/Library/Frameworks/Python.framework/Versions/2.7/bin/python").
Symlink "/usr/local/bin/python" points to installed version/location above.

```shell
$ ls -lah /usr/local/bin/docker-compose
-rwxr-xr-x  1 user_xxx  user_xxx   4.7M Dec 19 03:27 /usr/local/bin/docker-compose
```

**Comment by FrenchBen** [comment]
Do you still have the original python of 2.7.10 ? It'd be interesting to see if it changes anything (just suggesting stuff)

Also checking that you don't have any odd aliases?

**Comment by jenisys** [comment]
```shell
$ type -a python
python is /usr/local/bin/python
python is /usr/bin/python
```

The second one is the original one (version: 2.7.10), bundled with OSX according to Python sys.path.

**Comment by FrenchBen** [comment]
`which python` 

Also can you try to download the latest master of compose from here:
https://dl.bintray.com/docker-compose/master/

Taken from: https://github.com/docker/compose/issues/271

**Comment by jenisys** [comment]
I'll try that. OK, bleading edge works;

```shell
$ ./docker-compose-Darwin-x86_64 --version
docker-compose version 1.6.0dev, build ea8cc1c
```

**Comment by jenisys** [comment]
Note that I used a similar procedure initially with ``brew cask install dockertoolbox`` (like mentioned in docker/compose#271 ). After I run into problems, I removed the package, downloaded the toolbox package and installed it by hand.

**Comment by jenisys** [comment]
OK, thanks (working for me now) :-).

**Comment by FrenchBen** [comment]
I would advise against the brew cask install, as it is sometimes not fully up to date.

**Comment by jenisys** [comment]
Mmh, but the manual installation with the OSX package had the same problem. And brew-cask is basically only a command-line executor for installing "*.pkg" and "*.dmg" files. 

I noticed that I had manually installed the docker-py utils with pip and docker-compose in the correct version with it. And it is working there. But each variant of docker-compose (that I have seen up to now) shows a different openssl-version.

I still do not understand completely what the problem is. As far as I understand, you are using "pyinstaller" to build a standalone, self-sufficient executable that would even work, if no python is installed (or that is at least how I am using "py2exe"). Therefore, either this pyinstaller executable is not completely self-sufficient or it points to a shared-library that does not exists or has another API (version) as expected.

From the discussion in docker/compose#271 I assume it is an openssl linking problem:
```shell
# EITHER: Last steps or both steps should fix the problem
brew install openssl
brew link --force openssl
```

**Comment by FrenchBen** [comment]
@jenisys We aren't responsible for the brew updates (aka no maintainers of it) - Although it may be doing something similar, getting the official toolbox insures that you have the latest fixes. 

As far as compose is concerned, I'm unsure what the issue is - It may be easier to keep track of it in their repo.
