### ISSUE TITLE
More specific error message in Windows start.sh

### ISSUE THREAD

**Issue by johncmckim** [docker/toolbox#357]
In the Windows toolbox `start.sh` has the following

```
if [ ! -f $DOCKER_MACHINE ] || [ ! -f "${VBOXMANAGE}" ]; then
  echo "Either VirtualBox or Docker Machine are not installed. Please re-run the Toolbox Installer and try again."
  exit 1
fi
```

This makes it hard to see whether it is VirtualBox or Docker Machine that is the issue. I would rather see the if statement split in two as so.

```
if [ ! -f $DOCKER_MACHINE ] ; then
  echo "Docker Machine is not installed. Please re-run the Toolbox Installer and try again."
  exit 1
fi

if [ ! -f "${VBOXMANAGE}" ]; then
  echo "VirtualBox is not installed. Please re-run the Toolbox Installer and try again."
  exit 1
fi
```

In my case using this `start.sh` I was able to resolve the issue without re-installing the toolbox. This enabled me to see that the issue was with Virtual box and the Env variables. I was able to fix my environment variables to resolve the issue far more quickly than re-installing the toolbox would have taken.

I would think that generally Docker users are more advanced users. I think many users would rather repair an issue rather than simply re-installing every time something is wrong. Providing detailed error messages that allows them to do this.

**Comment by Gum-Joe** [comment]
:+1:
