### ISSUE TITLE
Cannot connect to remote docker: certificates issue?

### ISSUE THREAD

**Issue by the42** [docker/toolbox#358]
Running docker-machine on Linux ebola 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker-machine version 0.5.4, build 6643d0e

When I run
docker-machine env fiware-postgres I get the error:

Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "193.205.211.110:2376": dial tcp 193.205.211.110:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

When I run

docker-machine ls fiware-postgres I get

NAME              ACTIVE   DRIVER      STATE     URL   SWARM   DOCKER   ERRORS
fiware-postgres   -        openstack   Timeout 

Concerning connectivity:
docker-machine ssh fiware-postgres works

I cannot ping the host
I can telnet host on port 22
I cannot telnet host on port 2376

Host OS: uname -a
Linux fiware-postgres 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker version executed on host OS:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Output of ps aux  | grep docker on host OS:
root       839  1.4  0.6 312976 24548 ?        Ssl  06:50   0:00 /usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=openstack

docker version executed locally:
john@ebola:~$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

**Comment by jeffdm** [comment]
Hi there - folding this into https://github.com/docker/toolbox/issues/153
