### ISSUE TITLE
Setting iTerm for the QuickStart Terminal doesn't work

### ISSUE THREAD

**Issue by raguay** [docker/toolbox#362]
Setting the QuickStart Terminal to iTerm simply opens iTerm and not docker. The following output was generated on the iterm window that pops up:

I did not know the tools had a repo. The output requested:

➜  ~ env | grep -i docker
➜  ~ docker version
Client:
Version:      1.9.1
API version:  1.21
Go version:   go1.4.3
Git commit:   a34a1d5
Built:        Fri Nov 20 17:56:04 UTC 2015
OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
➜  ~  which docker
/usr/local/bin/docker
➜  ~

**Comment by bopbi** [comment]
try to run: 

    docker-machine env default

it will show the env variable:

    export DOCKER_TLS_VERIFY="1"
    export DOCKER_HOST="tcp://192.168.99.100:2376"
    export DOCKER_CERT_PATH="/Users/bobbyadiprabowo/.docker/machine/machines/default"
    export DOCKER_MACHINE_NAME="default"
    # Run this command to configure your shell:
    # eval $(docker-machine env default)

run the last command on the output above:

    eval $(docker-machine env default)

i think you need to run the eval command every time after launching the docker quickstart terminal app

**Comment by raguay** [comment]
Okay, that gets me a docker in iTerm, but only works after Kitematic has
started. But, the Quick Terminal should launch the docker daemon and then
setup iTerm. When I used earlier versions and without iTerm, the Quick Start
launched the daemons okay and I was able to work directly with Docker without
opening Kitematic gui.

> On Jan 7 2016, at 11:22 pm, Bobby Prabowo &lt;notifications@github.com&gt;
wrote:  

>

> try to run:

>  
>  
>     docker-machine env default

>  
>

> it will show the env variable:

>  
>  
>     export DOCKER_TLS_VERIFY="1"

>     export DOCKER_HOST="tcp://192.168.99.100:2376"

>     export
DOCKER_CERT_PATH="/Users/bobbyadiprabowo/.docker/machine/machines/default"

>     export DOCKER_MACHINE_NAME="default"

>     # Run this command to configure your shell:

>     # eval $(docker-machine env default)

>  
>

> run the last command on the output above:

>  
>  
>     eval $(docker-machine env default)

>  
>

> i think you need to run the eval command every time after launching the
docker quickstart terminal app

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/docker/
toolbox/issues/362#issuecomment-169713879).![](https://github.com/notification
s/beacon/ACX0x80mQh2sS0ko_mn1jNsePyOd6aBrks5pXogqgaJpZM4G9KAp.gif)

**Comment by erg** [comment]
I have the same problem with ``iterm2 Build 2.9.20160209-nightly``. (This is the most recent iterm2, perhaps the point release version doesn't have this issue.)

Launching the Quickstart Terminal just pops up a regular prompt with no docker output, exactly as if launching an iterm2 from the OSX dock.

Then running the command you suggested does this:
```
ergmac:~ erg$ docker-machine env default
Host does not exist: "default"
```

After running Kitematic manually and letting it load the command gives the correct output:
```
ergmac:~ erg$ docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/erg/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval $(docker-machine env default)
```

Before running Kitematic, the console.app log shows:
```
2/12/16 5:39:07.253 AM iTerm2[20613]: ReceiveMessageAndFileDescriptor
2/12/16 5:39:07.279 AM iTerm2-Server[20615]: Installing SIGHUP handler.
2/12/16 5:39:07.279 AM iTerm2-Server[20615]: Installing SIGCHLD handler.
2/12/16 5:39:07.279 AM iTerm2-Server[20615]: Sending file descriptor and waiting on initial connection
2/12/16 5:39:07.280 AM iTerm2-Server[20615]: send master fd and child pid 20616
2/12/16 5:39:07.280 AM iTerm2[20613]: recvmsg returned 4
2/12/16 5:39:07.280 AM iTerm2[20613]: Got a fd
2/12/16 5:39:07.280 AM iTerm2[20613]: Return 4
2/12/16 5:39:07.280 AM iTerm2-Server[20615]: All done. Waiting for client to disconnect or child to die.
2/12/16 5:39:07.280 AM iTerm2-Server[20615]: Calling select...
2/12/16 5:39:07.285 AM iTerm2[20613]: Try to connect to orphaned server at /var/tmp/iTerm2.socket.1402
2/12/16 5:39:07.285 AM iTerm2[20613]: Connect to path /var/tmp/iTerm2.socket.1402
2/12/16 5:39:07.286 AM iTerm2[20613]: Connect failed: Connection refused
2/12/16 5:39:07.286 AM iTerm2[20613]: Failed: Connection refused
2/12/16 5:39:07.320 AM login[20616]: USER_PROCESS: 20616 ttys000
2/12/16 5:39:07.450 AM launchservicesd[84]: SecTaskLoadEntitlements failed error=22
2/12/16 5:39:07.554 AM launchservicesd[84]: SecTaskLoadEntitlements failed error=22
2/12/16 5:39:07.627 AM launchservicesd[84]: SecTaskLoadEntitlements failed error=22
2/12/16 5:39:07.630 AM tccd[19755]: SecTaskLoadEntitlements failed error=22
2/12/16 5:39:07.000 AM kernel[0]: **** [IOBluetoothHostControllerUSBTransport][ClearFeatureInterruptEndpointHalt] -- successfully posting another read for the mInt0InterruptPipe -- mInterruptPipeInOutstandingIOCount = 1 -- this = 0x3000
2/12/16 5:39:07.677 AM launchservicesd[84]: SecTaskLoadEntitlements failed error=22
2/12/16 5:39:07.680 AM iTerm2[20613]: Time to encode state for window <PseudoTerminal: 0x7ff2abfa2890 tabs=1 window=<PTYWindow: 0x7ff2ae045980 frame=NSRect: {{0, 325}, {570, 452}} title=1. Shell — 80✕25 alpha=1.000000 isMain=1 isKey=1 isVisible=1 delegate=0x7ff2abfa2890>>: 0.001736998558044434
2/12/16 5:39:07.688 AM iTerm2[20613]: Time to save app restorable state: 0.0001130104064941406
2/12/16 5:39:08.466 AM iTerm2[20613]: Time to encode state for window <PseudoTerminal: 0x7ff2abfa2890 tabs=1 window=<PTYWindow: 0x7ff2ae045980 frame=NSRect: {{0, 325}, {570, 452}} title=1. Shell alpha=1.000000 isMain=0 isKey=0 isVisible=1 delegate=0x7ff2abfa2890>>: 0.001478016376495361
2/12/16 5:39:08.471 AM iTerm2[20613]: Time to save app restorable state: 7.802248001098633e-05
```

**Comment by satakeh** [comment]
The same problem also occurred with `iTerm2 2.9.20160206 beta` which is the latest test release. With `iTerm2 2.1.4`, the latest stable release, works fine.

**Comment by sudomilk** [comment]
Just chiming in to report the issue on **Build 2.9.20160223-nightly** as well.

**Comment by jeffdm** [comment]
Thanks all - merging this with https://github.com/docker/toolbox/issues/348

**Comment by brenogil** [comment]
I have updated to Build 3.0.0 and I experience pretty much what was reported by @erg

**Comment by gravitypersists** [comment]
if you're like me and set iTerm to your default on first try, you can fix that by following solution [here](http://stackoverflow.com/a/36066223): 

`rm ~/Library/Application Support/DockerToolbox/default_terminal`

**Comment by raymondji** [comment]
Was this issue resolved?

**Comment by janson123** [comment]
@raymondji It doesn't look like it. I'm currently having the same issue as @erg

**Comment by diazgilberto** [comment]
This issue is not fixed for the iTerm2 Build 3.0.10.

**Comment by wpcarro** [comment]
What worked for me was using @gravitypersists tip, i.e.:

```
$ rm ~/Library/Application\ Support/DockerToolbox/default_terminal
```

I also unset my `env` variable, `TERM_PROGRAM`, which was set to `iTerm.app`:

```
$ unset TERM_PROGRAM
```

With this value undefined, Docker Quickstart Terminal should prompt you for a terminal selection.

**Comment by hafizullah** [comment]
I had to switch to standard terminal. not able to start docker with iTerm :(

**Comment by wilroboly** [comment]
I'm also using Build 3.0.15. The following worked:

- Start up using Docker Quickstart Terminal and choose the normal MacOS Terminal. Let the process run to completion.
- Exit the Docker session
- Instantiate a iTerm2 window and run `docker-machine env default`
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.0.1:2376"
export DOCKER_CERT_PATH="/Users/dummy/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval $(docker-machine env default)
```
- When you get your list of values, run the `eval $(docker-machine env default)` command
- Once that is done, you should be able to do `docker ps` without a hitch.
