### ISSUE TITLE
docker-compose v 1.5.2 issues on Mac (10.11.2)

### ISSUE THREAD

**Issue by dmmueller** [docker/toolbox#366]
Attempting to run docker-compose with any command returns an Illegal instruction: 4

Versions released in DockerToolbox-1.9.1f and DockerToolbox-1.9.1g appear to have this issue.
example:
docker-compose --version
Illegal instruction: 4

Reverting back to v1.5.1 works,

**Comment by maltyxx** [comment]
me to

**Comment by yankedev** [comment]
I have the same.
Reverted installing manually : 

```
curl -L https://github.com/docker/compose/releases/download/1.5.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
then it worked again

**Comment by jeffdm** [comment]
Closing as this is an issue with [`docker/compose`](https://github.com/docker/compose)

Thanks all!
