### ISSUE TITLE
MinGW screws with paths that are supposed to be run inside containers

### ISSUE THREAD

**Issue by muellermichel** [docker/toolbox#371]
e.g. AFAIK the recommended way to run a docker container interactively is still `docker run -t -t myimage /bin/bash` right? Well, MinGW takes this path and rewrites it to something the hosts understands. Should MinGW be patched to ignore everything after `docker run`?

**Comment by jeffdm** [comment]
The Docker QuickStart Terminal should fix this, but if you can set the env var `MSYS_NO_PATHCONV=1` to avoid needing two slashes (e.g. `//bin/bash`)

**Comment by jeffdm** [comment]
Ideally there's a way to fix this with some global alias without users having to rely on the Docker Quickstart Terminal

**Comment by muellermichel** [comment]
sorry not to have been clear, but this happens in quickstart terminal. I've downloaded and installed it about two weeks ago. Is there a way to check the toolbox version?

**Comment by jeffdm** [comment]
@muellermichel there is! Try version `1.9.1i`: https://github.com/docker/toolbox/releases/tag/v1.9.1i

**Comment by jeffdm** [comment]
Going to close this for now - please reopen if still an issue
