### ISSUE TITLE
New install on OS X El Capitan cannot create machine

### ISSUE THREAD

**Issue by patrickmay** [docker/toolbox#373]
I completely removed all old versions of Docker and VirtualBox, then installed the latest Docker Toolbox.  When I try to create a machine I get this error consistently:

~> docker-machine create --driver virtualbox default
Creating CA: /Users/Patrick/.docker/machine/certs/ca.pem
Creating client certificate: /Users/Patrick/.docker/machine/certs/cert.pem
Running pre-create checks...
(default) Image cache directory does not exist, creating it at /Users/Patrick/.docker/machine/cache...
(default) No default Boot2Docker ISO found locally, downloading the latest release...
(default) Latest release for github.com/boot2docker/boot2docker is v1.9.1
(default) 
(default) Boot2Docker v1.9.1 has a known issue with AUFS.
(default) See here for more details: https://github.com/docker/docker/issues/18180
(default) Consider specifying another storage driver (e.g. 'overlay') using '--engine-storage-driver' instead.
(default) 
(default) Downloading /Users/Patrick/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.9.1/boot2docker.iso...
(default) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(default) Copying /Users/Patrick/.docker/machine/cache/boot2docker.iso to /Users/Patrick/.docker/machine/machines/default/boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Creating a new host-only adapter produced an error: /usr/local/bin/VBoxManage hostonlyif create failed:
(default) 0%...
(default) Progress state: NS_ERROR_FAILURE
(default) VBoxManage: error: Failed to create the host-only adapter
(default) VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
(default) VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(default) VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg*)" at line 71 of file VBoxManageHostonly.cpp
(default) 
(default) This is a known VirtualBox bug. Let's try to recover anyway...
Error creating machine: Error in driver during machine creation: Error setting up host only network on machine start: Failed to find a new host-only adapter

I've tried rebooting, reinstalling, but no joy.  The only thing that's remotely different from when I've installed before is that my network is wifi only.

**Comment by patrickmay** [comment]
I did some more research online and found out that people had problems with Cisco AnyConnect Secure Mobility Client.  I shut that down, uninstalled and reinstalled Docker Toolbox, and I'm able to create a machine.  If there's already an open issue about the Cisco VPN, this one can be closed.

Thanks.

**Comment by jeffdm** [comment]
@patrickmay good to hear - thanks for the issue.

We're tracking VPN problems in this repo as well as in the `docker/machine` repo.

Thanks again
