### ISSUE TITLE
Cannot connect to the Docker daemon. Is 'docker -d' running ubuntu 14.04

### ISSUE THREAD

**Issue by suniisunny** [docker/toolbox#374]
Cannot connect to the Docker daemon. Is 'docker -d' running ubuntu 14.04

**Comment by jeffdm** [comment]
Closing in favor of https://github.com/docker/toolbox/issues/153

If this doesn't seem like the same issue - please re-open and provide a little more details:

- Error you're seeing
- Are you inside the VM?
- Is this via the `Docker Quickstart Terminal`? 

Thanks for the issue!
