### ISSUE TITLE
don't count as failure in mixpanel, docker-machine pre-create checks

### ISSUE THREAD

**Issue by jeanlaurent** [docker/toolbox#376]
We altered docker-machine with https://github.com/docker/machine/pull/2807  so it returns exit code 3 in case of pre-create check. ( basically the machine on which we are installing does not have all the pre-requisites for docker-machine do run properly, VTX-Flag not enabled, machine already existing etc...)

We still returns exit code 1 in case of errors.

The idea is that toolbox does not consider as failure in mixpanel when a pre-create checks error occurs.

**Comment by embray** [comment]
Incidentally, is there some documentation for what exit codes `docker-machine` returns, and why?  (Or incidentally for other docker-related commands too?)  I couldn't find this anywhere in the docs, and it I think this deserves better documentation than "read the code" :/

**Comment by jeffdm** [comment]
Closing as this was fixed in a previous release of Toolbox - 

@embray I think at the moment it's undocumented. Not sure, best to ask in `docker/machine` :smiley:
