### ISSUE TITLE
Very slow response time

### ISSUE THREAD

**Issue by homoky** [docker/toolbox#378]
Hi guys. 

When I try to pull some image it took about one hour on my Mac with Toolbox. My college is working on a linux and he say that it tooks max 5 minutes. It seems that there are some network problem, maybe with the Virtual box.

Have you anyone else experienced something similar?

Thank you.

**Comment by iiro** [comment]
It seems that network speed varies a lot with VirtualBox - it's definitely not constant. Wish it would be possible to use something else instead...

**Comment by nathanleclaire** [comment]
Hi @homoky -- do you see the same result if you change the NIC type in VirtualBox (power down VM > go to VM settings > Network > Adapter 2 > advanced settings > change to `virtio-net` or maybe `PCnet-PC II`?

**Comment by jeffdm** [comment]
Don't feel like this is something we can tackle head-on in Toolbox, so I'm going to close this in favor of https://github.com/docker/toolbox/issues/107

Thanks all!
