### ISSUE TITLE
VBoxManage not found

### ISSUE THREAD

**Issue by eastwood8** [docker/toolbox#381]
bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
Last login: Fri Jan 22 21:22:48 on ttys000
ProBook:~ cs$ bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
Starting "default"...
VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): Regenerating TLS certificates
Detecting the provisioner...
Error getting SSH command: Something went wrong running an SSH command!
command : cat /etc/os-release
err     : exit status 255
output  :
Error checking TLS connection: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

**Comment by jeffdm** [comment]
Thanks for the issue. Is VirtualBox installed? If so then please re-open as this is a bug. Otherwise, please re-run the installer with VirtualBox enabled.
