### ISSUE TITLE
Windows 7: Error creating machine: Error in driver during machine creation: Unable to start the VM: exit status 1

### ISSUE THREAD

**Issue by ignacio-serrano** [docker/toolbox#383]
This is what happens when I run *Docker Quickstart Terminal*:

    Running pre-create checks...
    Creating machine...
    (default) Copying D:\Users\Iñaki\.docker\machine\cache\boot2docker.iso to D:\Users\Iñaki\.docker\machine\machines\default\boot2docker.iso...
    (default) Creating VirtualBox VM...
    (default) Creating SSH key...
    (default) Starting the VM...
    Error creating machine: Error in driver during machine creation: Unable to start the VM: exit status 1
    Looks like something went wrong... Press any key to continue...

Nevertheless *default* virtual machine gets created. However, when I run *Docker Quickstart Terminal* for the sencond time, I get:

    Starting "default"...
    Unable to start the VM: exit status 1
    Looks like something went wrong... Press any key to continue...

I'm using DockerToolbox-1.9.1i, including its VirtualBox and Git client installations.

Following the advice in similar issues, I checked if VT-X was enabled at BIOS level and it is. I also tried removing default virtual machine and letting *Docker Quickstart Terminal* to create it again, but it just displays the first log again. I also tried removing *host only network adapters* from VirtualBox, but they just get created again.

**Comment by livia-b** [comment]
I had a similar problem, and it turned out to be a driver from avira https://forums.virtualbox.org/viewtopic.php?f=6&t=67840&p=347563#p347694

**Comment by jo-me** [comment]
Same issue here, but I don't have Avira.

**Comment by jo-me** [comment]
even though I upgraded to the latest virtualbox the error did not go away. So I uninstalled virtualbox, rebooted and reinstalled the latest version (5.0.14). Then rebooted again.
After that, I was able to execute the start.sh script to create the initial "default" vm.

Note that I'm on Windows 10 x64 though.

**Comment by W7PEA** [comment]
Reproduced today... 
I had 9f installed, uninstalled that.
installed 1.10 and ran quickstart with this fail.
I then deleted the default vm in virtualbox and tried to start quickstart again and this was the output:

```
Running pre-create checks...
(default) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(default) Latest release for github.com/boot2docker/boot2docker is v1.10.0
(default) Downloading C:\Users\Patrick\.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2do
(default) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(default) Copying C:\Users\Patrick\.docker\machine\cache\boot2docker.iso to C:\Users\Patrick\.docker\machine\machines\de
fault\boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
Error creating machine: Error in driver during machine creation: Unable to start the VM: exit status 1
Details: 00:00:01.689347 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))
Looks like something went wrong... Press any key to continue...
```

Windows10 x64 1511 10589.71

**Comment by W7PEA** [comment]
This worked for me as a workaround. I assume you're not doing any other complicated VM scenarios, if you are you need to know what you can and cannot remove, I can't help you there.

1. Open virtualbox manager
2. Go to File, Preferences, Network, Host-only Networks
3. Delete all the things.
4. Exit out of Virtualbox Prefences
5. You should have a VM called default. Remove it and when prompted also select to delete all files.
6. Open a command prompt
7. `cd %HOMEPATH%`
8. Is there a .docker folder there? `dir .docker`
9. Remove it. `rd /s /q .docker`

Now run the Docker Quick Start shortcut and your docker window should now be available. It worked for me, hope it works for you.

This is just something I think we're going to need to keep doing as we upgrade... Maybe Uninstall should delete those Host-Only Networks? Not sure.

**Comment by jeffdm** [comment]
Wrapping this into https://github.com/docker/toolbox/issues/153

**Comment by lansanasylla** [comment]
hello,i had exaclty the same problem on my ubuntu 14.4 LTS
but after upgrading my virtual box version to 5.1.2
now i have this error message : `Error creating machine: Error in driver during machine creation: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
` but the machine is created and running. someone can help please ?

**Comment by Eloyjaws** [comment]
Running pre-create checks...
Creating machine...
(default) Copying C:\Users\Eloyjaws\.docker\machine\cache\boot2docker.iso to C:\Users\Eloyjaws\.docker\machine\machines\default\boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Windows might ask for the permission to create a network adapter. Sometimes, such confirmation window is minimized in the taskbar.
(default) Creating a new host-only adapter produced an error: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create failed:
(default) 0%...
(default) Progress state: E_INVALIDARG
(default) VBoxManage.exe: error: Failed to create the host-only adapter
(default) VBoxManage.exe: error: Assertion failed: [!aInterfaceName.isEmpty()] at 'F:\tinderbox\win-5.1\src\VBox\Main\src-server\HostNetworkInterfaceImpl.cpp' (74) in long __cdecl HostNetworkInterface::init(class com::Bstr,class com::Bstr,class com::Guid,enum __MIDL___MIDL_itf_VirtualBox_0000_0000_0038).
(default) VBoxManage.exe: error: Please contact the product vendor!
(default) VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(default) VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 71 of file VBoxManageHostonly.cpp
(default)
(default) This is a known VirtualBox bug. Let's try to recover anyway...
Error creating machine: Error in driver during machine creation: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
Looks like something went wrong in step Â´Checking if machine default existsÂ´... Press any key to continue...

**Comment by BigDataPeter** [comment]
W7PEA, now I just successfully launched the docker quick start. Thanks for you suggestion !
