### ISSUE TITLE
Link is a 404

### ISSUE THREAD

**Issue by tomyan** [docker/toolbox#386]
The link in the project description (as well as in quite a few places on the docker site) is a currently returning a 404:

https://docker.com/toolbox

I can't seem to find where to download the installer.

Tom

**Comment by mlimotte** [comment]
I'm not seeing a 404, but I don't see an "installer link", either.

**Comment by tomyan** [comment]
Yeah, I get a redirect too now, but no installer link. Perhaps the site is mid-update?

**Comment by delsdog** [comment]
Yeah, can't see the installer either.

**Comment by fosil** [comment]
Reply from Twitter: 
Jeff Morgan
@jmorgan	
25. 1. 
@filip_f_novak @docker Sorry about this. Should be fixed soon. For now see github.com/docker/toolbox… to download.

Link: https://github.com/docker/toolbox/releases/tag/v1.9.1i

**Comment by jeffdm** [comment]
Sorry all - had a hiccup with our docker.com website, but things are back to normal now. Thanks for the patience.
