### ISSUE TITLE
"Docker Quickstart Terminal" bug

### ISSUE THREAD

**Issue by meotimdihia** [docker/toolbox#389]
- DockerToolbox-1.9.1i.exe  
- Docker version 1.9.1, build a34a1d5  
- VirtualBox Graphical User Interface Version 5.0.14 r105127  
- Bug: `Either VirtualBox or Docker Machine are not installed. Please re-run the Toolbox Installer and try again.`  

https://github.com/docker/toolbox/blob/23876a5bc9c3f2bbb3306c380a0ec76083ac91da/windows/start.sh#L18
this line code always return `false`
```shell
if [ ! -f "${DOCKER_MACHINE}" ] || [ ! -f "${VBOXMANAGE}" ];
```

i think this path was not found:

```shell
DOCKER_MACHINE=./docker-machine.exe
```

I must open Git-bash, `cd` change location to `C:\Program Files\Docker Toolbox` and manually start `start.sh`.

hopefully, this small problem will be fix , avoid to confuse everyone.

**Comment by embray** [comment]
The shortcut link for Docker Quicklaunch Terminal *should* start you out in `C:\Program Files\Docker Toolbox`.  I installed Docker Toolbox 1.10 and it was fine; you might try updating the shortcut properties so it looks like this (screenshot is in French but you should get the idea):

![docker-quickstart](https://cloud.githubusercontent.com/assets/676149/12972410/33f4dfea-d0a5-11e5-83e2-fff9a448235d.png)

**Comment by jeffdm** [comment]
As @embray mentioned it seems that the "Start in" directory is wrong on your shortcut - can you double check and verify?

If still a problem, please do re-open this.

Thanks @meotimdihia @embray !
