### ISSUE TITLE
can't create new docker machine

### ISSUE THREAD

**Issue by SydOps** [docker/toolbox#391]
Today I uninstall old Toolbox and download the latest version and install.

But when I create a new docker machine with command ` docker-machine create -d virtualbox default` I got below error.

>Error creating machine: Error with pre-create check: VirtualBox is configured with multiple host-only adapters with the same IP "192.168.99.1". Please remove one.

How to fix it?

**Comment by SydOps** [comment]
seems it is related to this issue https://github.com/docker/machine/issues/2136

**Comment by SydOps** [comment]
Fix the issue with manually remove the duplicated host-only networks in virtualbox.

>VirtualBox GUI -- (in menu bar: VirtualBox => Preferences => Network => Host-only networks).

**Comment by nathanleclaire** [comment]
Was going to pitch in but :+1: glad to hear you fixed the issue

**Comment by craigboman** [comment]
@SydOps  This worked for me as well. Many thanks.

**Comment by tomtruitt** [comment]
how can i fix this in a headless vm?

**Comment by deedat** [comment]
vvf

**Comment by deedat** [comment]
![screenshot from 2019-02-05 23-36-50](https://user-images.githubusercontent.com/31182856/52308956-feec9580-299e-11e9-8e69-f46284774ed7.png)

i canit see any Host-only networks, please help

**Comment by iamrz1** [comment]
Manually remove the host network interface(s) from File > Host Network Manager.
![dd](https://user-images.githubusercontent.com/36768796/54009091-a2de8200-4193-11e9-9ef8-2c3c85ce5c84.png)
