### ISSUE TITLE
upgrading visualstudio replaces Git for Windows!

### ISSUE THREAD

**Issue by SvenDowideit** [docker/toolbox#395]
WOW - i don't know how this is going to affect things, will let you know.

![vstudioupgrade](https://cloud.githubusercontent.com/assets/28492/12661970/0418fb7c-c5d2-11e5-98fb-c5df78109252.png)

**Comment by jeffdm** [comment]
@SvenDowideit thanks

**Comment by jeffdm** [comment]
Closing in favor of https://github.com/docker/toolbox/issues/394
