### ISSUE TITLE
Where is boot2docker 1.10.0-rc2?

### ISSUE THREAD

**Issue by noose** [docker/toolbox#398]
I have downloaded https://github.com/docker/toolbox/releases/tag/v1.10.0-rc2 which should include `Boot2Docker ISO 1.10.0-rc2` but when I'm creating new vm:
```(default) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(default) Latest release for github.com/boot2docker/boot2docker is v1.9.1
(default)
(default) Boot2Docker v1.9.1 has a known issue with AUFS.
(default) See here for more details: https://github.com/docker/docker/issues/18180
(default) Consider specifying another storage driver (e.g. 'overlay') using '--engine-storage-driver' instead.
(default)
(default) Downloading /Users/noose/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.9.1/boot2docker.iso...
```
Where can I download the v1.10.0-rc2 version? On boot2docker repository there isn't tag or release with v1.10.0-rc2 name.

**Comment by yveslaroche** [comment]
https://github.com/tianon/boot2docker-legacy/releases/tag/v1.10.0-rc2

```
docker-machine create default -d=virtualbox -virtualbox-boot2docker-url https://github.com/tianon/boot2docker-legacy/releases/download/v1.10.0-rc2/boot2docker.iso
```

However, I get the following error:
```
Provisioning with boot2docker...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
```

**Comment by bnemutlu** [comment]
I get the same error and I found no solution yet

**Comment by Vaudesir** [comment]
+1 I tried a bunch of more or less obvious things but no luck so far.

**Comment by pkernevez** [comment]
+1, I gone back to 1.9.1j.
Toolbox 1.10.0.rc2 on mac os.

It seems that docker ignores the local iso image and prefers to download the 1.9.1 iso.

**Comment by eastTowest** [comment]
I used rc1 and it works just fine; 
docker-machine create default -d=virtualbox -virtualbox-boot2docker-url https://github.com/tianon/boot2docker-legacy/releases/download/v1.10.0-rc1/boot2docker.iso

**Comment by nathanleclaire** [comment]
This issue is fixed and the releases have now been moved to https://github.com/boot2docker/boot2docker
