### ISSUE TITLE
docker login: Unexpected status code [403]

### ISSUE THREAD

**Issue by tdeheurles** [docker/toolbox#400]
I have some issues trying to login to docker from windows.
```
$ docker login
Username: myname
Password:
Email: my@mail.com
Error response from daemon: Unexpected status code [403] : <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

When I ssh into the machine it's fine and working.

**Comment by nathanleclaire** [comment]
Really weird.  Sounds like it might be an upstream (docker/docker) issue.

**Comment by SvenDowideit** [comment]
@tdeheurles what version of things were you running? and is is still happening?

**Comment by tdeheurles** [comment]
I'm running version 1.9.1g as there is [another issue](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/issues/165) (with `h` and `i`) that unable me to update further. 

As I remember the issue was the same but I need to re-install for confirmation. Am I the only one with that login issue ?

**Comment by tdeheurles** [comment]
Just seen the 1.10 has been released, I'll test with it and come back with informations

**Comment by tdeheurles** [comment]
The error have gone with 1.10.
Thank you.
