### ISSUE TITLE
Docker-Toolbox won't install with EOF error (RPCServerDriver does not work)

### ISSUE THREAD

**Issue by eestein** [docker/toolbox#401]
I'm getting this error when I try to install docker toolbox:

> Encountered an error: Error: Command failed: /usr/local/bin/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.5.6, build 61388e9,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:58756,() Calling .GetVersion,unexpected EOF,Client () with RPCServerDriver does not work, re-attempting with RpcServerDriver,() Calling .GetVersion,connection is shut down,

Any ideas?

Thanks

**Comment by nathanleclaire** [comment]
Do you mean when you launch the Quickstart terminal?  Does it happen every time?  What's the networking setup like on your Mac, anything funny?

**Comment by eestein** [comment]
Hi, thanks for your reply. When I launch Kitematic for the first time. Yes.
I assume it's pretty basic, although I do have parallels running and I was
able to install kitematic on my windows VM running on parallels...
Is there any extra information I can give to help sort it out?

Thanks!

On Fri, Feb 5, 2016 at 5:49 PM, Nathan LeClaire <notifications@github.com>
wrote:

> Do you mean when you launch the Quickstart terminal? Does it happen every
> time? What's the networking setup like on your Mac, anything funny?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/toolbox/issues/401#issuecomment-180520506>.
>



-- 
Eros Eduardo Stein
m +55 27 98182 8770
Microsoft Certified Professional ID:9878485

**Comment by jeffdm** [comment]
@eestein thanks for the issue, and thank you @nathanleclaire for chiming in!

I think it would be best to find the right issue in the [docker/machine](http://github.com/docker/machine/issues) repo and bring the convo there.

Thanks again!
