### ISSUE TITLE
DockerToolbox-1.10.0.pkg reports that virtualbox is running and won't install

### ISSUE THREAD

**Issue by paul42** [docker/toolbox#406]
Not certain if it's me, but I get the repeated errors when trying to install latest docker toolbox - I can't seem to figure out how to tell if virtualbox is running or not, since greps for ps aux | grep virtual doesn't come up with anything

Thanks in advance,
Paul

**Comment by jeffdm** [comment]
Hi there- this usually means a VBox background process is running. Usually if you shut down all VMs and close the VirtualBox GUI, after 10 or so seconds it should work.

If this still doesn't work, then running `ps aux | grep VBox` should yield the remaining processes
