### ISSUE TITLE
Error while installation Docker Toolbox 1.10.0 on OSX

### ISSUE THREAD

**Issue by ducky427** [docker/toolbox#407]
Hi,
When I am trying to install docker toolbox, after the **Installation Type** wizard, I get an error dialog "_Unapproved caller! - SecurityAgent may only be invoked by Apple software_". I am unable to proceed after that.

I am running: OS X El Capitan Version 10.11.4 Beta (15E33e) on a MacBook Pro.

Thanks

**Comment by nathanleclaire** [comment]
Hm, @tiffanyfj mentioned having a similar issue.  I'm not sure what's going on but I'm going to see if there might be some sort of log we could take a look at.

**Comment by ducky427** [comment]
thanks!

**Comment by tiffanyfj** [comment]
It's kind of weird because after my laptop restarted, it didn't give me an error anymore.

**Comment by ducky427** [comment]
That fixed my issue as well.

thanks!

**Comment by nathanleclaire** [comment]
Ah so weird!  Thanks for following up y'all -- I'm going to close this for now.
