### ISSUE TITLE
Make .app package 

### ISSUE THREAD

**Issue by cpuguy83** [docker/toolbox#41]
The one thing I don't like here is the installer itself.
Is there a way to uninstall?

Whenever I run an installer on OSX I get a little sick.
Would be nice if the toolbox itself was just a `.app` package that had  UI for install/removal/upgrades.

**Comment by michaelbarton** [comment]
I believe if you did this, then this would also allow command line installation via `brew cask`. I often use this for installing a large number of applications when setting up a new mac.

**Comment by mchiang0610** [comment]
Closing this for now because we don't have the time or resources to do this right now for this and other projects. We really love this idea though.
