### ISSUE TITLE
Slow network checks and dhcp at machine startup. static ip?

### ISSUE THREAD

**Issue by krodelabestiole** [docker/toolbox#410]
hello

im on windows 10 and my docker machine (virtualbox driver) takes a bit more than 40 sec to boot (without container)
it takes 5 sec to "check network to re-create if needed"
and 35 sec "waiting for an IP"
i obviously dont need neither of this. i don't need DHCP for it's the only machine i use, and i would prefer to set a static ip. (the only info i found about setting a static IP is a dirty one-ip-range-DHCP workaround hack which does not solve my problem)

does anyone have an idea about why it is taking so long and how i could get rid of this useless boot time ?

**Comment by jeffdm** [comment]
@krodelabestiole thanks for creating an issue! I think you'll find better help in the [docker/machine](https://github.com/docker/machine) repo. These settings are specific to Docker Machine :smiley:
