### ISSUE TITLE
Pin version of Inno Setup used in Dockerfile.windows

### ISSUE THREAD

**Issue by embray** [docker/toolbox#421]
The build for the Windows installer currently grabs the latest version of Inno Setup, which can lead to broken installers or other unexpected issues when there are changes in Inno Setup, especially since automated tests of the installer would be difficult to do (though not impossible!) 

This would help mitigate issues like #419, #414, and likely others.

**Comment by jeffdm** [comment]
@embray thanks for creating an issue for this! Much appreciated!

I went ahead and directly patched the Dockerfile: https://github.com/docker/toolbox/commit/0c949dd3df573f7223b84843b54397c1bbd0fa55.

**Comment by embray** [comment]
Oops! You probably made the commit just as I was starting to write the issue, or just before it, so I missed that!  Just didn't want to forget.

**Comment by jeffdm** [comment]
Sorry for the confusion - I should have made a PR. Thanks again @embray!
