### ISSUE TITLE
Restarted machines fail to start Docker due to Cert issues

### ISSUE THREAD

**Issue by rogeralsing** [docker/toolbox#425]
I'm using Docker Toolbox on Windows.
If I set up a Swarm Cluster of a few nodes using Docker Machine and then restart one of the nodes. the node might end up with a new IP, which makes Docker fail to start on that machine due to Cert issues.
And in turn, the restarted node fails to join the Swarm cluster again.
If I regenerate the certs for that machine, it starts to work as expected again... most of the times.

Some times, even after cert regeneration, the nodes might get stuck on pending when trying to join the Swarm cluster again. even if Docker have started on the machine.

I'm really not sure if this is due to some iffyness in docker-machine, or if it is a Swarm problem, or even a Windows issue, or if it is just my complete ignorance of what I am actually doing here.
Any help would be welcome.

**Comment by jeffdm** [comment]
Hi there! Thanks so much for the issue. This is specific to `docker/machine`, so I'll point you [over there](https://github.com/docker/machine). The maintainers there can definitely provide more information on how to best handle this!

Thanks again.
