### ISSUE TITLE
DockerToolbox-1.10.2a.pkg invalid

### ISSUE THREAD

**Issue by seanewest** [docker/toolbox#428]
The .pkg for the 1.10.2a release is only 12.8kb and when downloaded does not work.

When I try to run it I get the following screen

![screen shot 2016-02-23 at 7 55 24 pm](https://cloud.githubusercontent.com/assets/3216121/13272127/c3c6892c-da67-11e5-8df2-da758f55f40f.png)

**Comment by nathanleclaire** [comment]
Thanks, the upload is corrupt due to a signing issue in our automation, we're working on it.

**Comment by nathanleclaire** [comment]
Fixed, thanks for your patience
