### ISSUE TITLE
starting service in debian docker container kicks out

### ISSUE THREAD

**Issue by 573** [docker/toolbox#429]
To describe it in a few words:

- have docker toolbox on windows 7 host installed
- have docker image per docker pull
- started container from that image per `docker run -i -t -p 80:80 debian /bin/bash`
- after installing usual stuff for apache exited from container session per CTRL-D
- later attached session to the started container again per `docker exec -i -t boring_archimedes /bin/bash`
- inside the container ran `/etc/init.d/apache2 start`

got 

> [....] Starting web server: apache2panic: runtime error: slice bounds out of ran
ge
>
goroutine 12 [running]:
bufio.(*Reader).fill(0xc0820f6360)
        /usr/local/go/src/bufio/bufio.go:86 +0x2e2
bufio.(*Reader).WriteTo(0xc0820f6360, 0x383aa0, 0xc08200aa50, 0xb29, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:449 +0x285
io.Copy(0x383aa0, 0xc08200aa50, 0x386158, 0xc0820f6360, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:354 +0xb9
github.com/docker/docker/api/client.func┬À012(0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/hijack.go:217 +0x1e0
github.com/docker/docker/pkg/promise.func┬À001()
        /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
created by github.com/docker/docker/pkg/promise.Go
        /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102

being kicked out of the containers session back to my hosts docker toolbox session.

**Comment by thaJeztah** [comment]
What version of docker are you running? This sounds like a bug in docker ("engine"), but may have been resolved already in the latest (1.10.2) release

**Comment by 573** [comment]
> $ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      windows/amd64
>
Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        2016-02-22T22:37:33.778002647+00:00
 OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment]
Was the docker daemon still running after you had this crash? (trying to determine if the "panic" was server-side (in the daemon) or in the client.

If it was client-side, can you try and upgrade the docker client (the binary on your Mac) to see if that resolves the issue? You can download the OS X binary for 1.10.2 here; https://get.docker.com/builds/Darwin/x86_64/docker-1.10.2

**Comment by 573** [comment]
> docker daemon still running ...

I'm not sure how to determine that but if you mean this:

> $ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED
STATUS                    PORTS                NAMES
fdf438bf2c78        debian              "/bin/bash"         25 hours ago
Up 3 hours                0.0.0.0:80->80/tcp   boring_archimedes

seems like the answer is yes.

For the binary I'm using Windows actually not OS X.

**Comment by thaJeztah** [comment]
Alright, looks like the daemon didn't crash. 

> For the binary I'm using Windows actually not OS X.

Doh! Well, download-links can be found on the releases page :smile: https://github.com/docker/docker/releases/tag/v1.10.2

**Comment by 573** [comment]
OK  :smile: I replaced the binary with the downloaded one but the error remains.

**Comment by thaJeztah** [comment]
Oh, hold on; looking at your original description; you're *exiting* the container (using `CTRL-D`) so it's no longer running? How did you manage to `docker exec` into that container if it's no longer running?

**Comment by 573** [comment]
If `docker ps -a` shows that it is running, it is easy to `docker exec` into it, otherwise I'd `docker start boring_archimedes` before.

**Comment by jeffdm** [comment]
Please feel free to continue the conversation - I'm going to close this for housekeeping since it's a `docker/docker` issue.

Thanks for the issue!

**Comment by 573** [comment]
@jeffdm what is a `docker/docker` issue? Where should the issue be reported?

**Comment by 573** [comment]
Ok IC! :+1:
