### ISSUE TITLE
v1.10.2a missing docker-compose 1.6.2 for Mac

### ISSUE THREAD

**Issue by Maks3w** [docker/toolbox#437]
Release v1.10.2a claims to ship docker-composer v1.6.2 but v1.6.0 is shipped (which is important for fix the merge bug on v2 files)

PD: Windows release ship the expected version

**Comment by greggilbert** [comment]
+1

**Comment by dmp42** [comment]
cc @nathanleclaire @dgageot

**Comment by sawalls** [comment]
I disagree. Maybe something has changed in the last 2 days?

1.10.2 ships docker-compose v1.6.0,
1.10.2a ships docker-compose v.1.6.2.

Here's the 1.10.2a pkg file I used: https://github.com/docker/toolbox/releases/download/v1.10.2a/DockerToolbox-1.10.2a.pkg

It's worth noting that https://www.docker.com/products/docker-toolbox links to a v1.10.2 pkg, which might not be desired behavior.

**Comment by Maks3w** [comment]
Did you check your installed version is 1.6.2?

**Comment by sawalls** [comment]
Yep!

```
$ docker-compose --version
docker-compose version 1.6.2, build 4d72027
```

**Comment by Maks3w** [comment]
I confirm right now ship the expected version.

**Comment by nathanleclaire** [comment]
Thanks for following up to close @Maks3w, I can confirm the version looks the same, but oddly SHA seems different cross-oS.

Windows:

```
$ docker-compose --version
docker-compose version 1.6.2, build e80fc83
```

On OSX:

```
docker-compose --version
docker-compose version 1.6.2, build 4d72027
```

**Comment by sawalls** [comment]
@nathanleclaire That's a little bit weird.
(keep in mind all the SHAs below are in docker/compose, not here in toolbox)

4d72027 is the commit that bumps up to 1.6.2:

```
$ git show 4d72027
commit 4d720279a0a1152af70dee720a67c395392aaff3
Author: Aanand Prasad <aanand.prasad@gmail.com>
Date:   Tue Feb 23 15:50:59 2016 -0800

    Bump 1.6.2
    
    Signed-off-by: Aanand Prasad <aanand.prasad@gmail.com>
```

e80fc83 doesn't appear to be anywhere in the repo:

```
$ git show e80fc83
fatal: ambiguous argument 'e80fc83': unknown revision or path not in the working tree.
```

It may be super-benign, but it seems like it's worth at least talking to someone on compose about it.

**Comment by dmp42** [comment]
ping @dnephin on the commit sha oddity

**Comment by dnephin** [comment]
The windows SHA can be seen here: https://ci.appveyor.com/project/docker/compose/build/release-1363

The only difference is this merge commit: https://github.com/docker/compose/compare/1.6.2...e80fc8308bf42dc351d2583eb9205671969a562e

I guess we build the windows binary from the PR branch, but we build the OSX/linux binary from the branch that was merged into `release`, which is what got tagged.
