### ISSUE TITLE
Windows 10 Starting Docker VM freezes @ 100%

### ISSUE THREAD

**Issue by gleblanc1783** [docker/toolbox#438]
Latest installer, (just downloaded today).

Had the Toolbox installer install Virtualbox, Git, Kitematic, etc -- I can see the VirtualBox "default" VM being created in the Virtual Box UI. When I go ahead and view the console on the default VM, it pauses for a few minutes here: 

![image](https://cloud.githubusercontent.com/assets/111515/13438543/79c144de-dfb7-11e5-8807-63c85f900733.png)

After that "completes" and the default VM successfully logs in, the Kitematic UI is stuck at 100%.

![image](https://cloud.githubusercontent.com/assets/111515/13438586/99effc32-dfb7-11e5-9c62-b330fd1797de.png)

Checked other issues here and tried many other solutions when they were stuck at 99% -- no luck there. 

I can provide any/all info if needed.

**Comment by gleblanc1783** [comment]
Well this is one for the books.

Come to find out this wasn't an issue with Docker (or Virtualbox), or even Windows 10 itself.

I was digging through the Virtualbox logs for the `default` VM and I saw it complaining about some Windows driver not being signed. So I went to go check it out and Google knew nothing of the DLL and the hash wasn't in Virustotal. Come to find out I had some PUP infection that was running under dasHost.exe and Virtualbox didn't like it.

After I installed and ran MalwareBytes and it removed a few EXEs, DLLs, and reg keys, well, would you look at that, Docker Toolbox ran fine! 

Virtualbox, the best malware detection engine there is. I ended up re-imaging my machine just in case (after docker worked).

**Comment by linonetwo** [comment]
「Virtualbox, the best malware detection engine there is.」 I totally agree. Actually, not only can it detect malware , but also 360.
