### ISSUE TITLE
Unable to start docker quickstart terminal when .bashrc contains a cd

### ISSUE THREAD

**Issue by Sch3lp** [docker/toolbox#445]
Hi!

I don't know if this is an issue or not, but here's what I went through:

1. Installed docker-toolbox on my Windows 10 machine.
2. Ran quickstart terminal
3. Got message `Looks like something went wrong... Press any key to continue...`
4. Reinstalled with `Git for windows` checked, but same message.
5. Googled that message, came across an issue where a previous Git Bash install was producing same error due to profile/HOME path issue.
6. Tinkered with my own .bashrc of my existing Git Bash install and ended up removing a `cd /c/dev/ws` line.
7. Reran quickstart terminal and now it's working.

If anything I just wanted to log an issue so other users might come across this fix. Especially because there's really nothing to go on other than that ominous message.

**Comment by nathanleclaire** [comment]
Thanks for filing the issue and solution!  Since there's no action items on our end, I'm going to close this issue.

**Comment by Sch3lp** [comment]
Cheers!

**Comment by mcadavid** [comment]
I had problems finding the .bashrc in windows 7. It was located in c:\Users\<userid>. After that, editing it solved the problem.
