### ISSUE TITLE
Clogged by "waiting for an IP"

### ISSUE THREAD

**Issue by Sraw** [docker/toolbox#448]
I just run the quickstart terminal and wait for creating machine. But it blocked when showing "waiting for an IP". And no response.
How could I fix this problem? I have searched the network and found that there are someone meets the same problem as me but no solution.
Hoping answers.

**Comment by nathanleclaire** [comment]
Hi @Sraw, thanks for the issue.

Do you have any unusual network configuration?

- VPN?
- Proxy
- Firewall
- Antivirus
- (m)DNS server
- What's your `/etc/hosts` file look like
- What's the output for `ifconfig` on your computer?

**Comment by mchiang0610** [comment]
@Sraw 

If anyone still has problems with this, please contact me at mchiang@docker.com.

We are working on something to help address this issue.

**Comment by Sraw** [comment]
I run the docker on windows, so it needs to create a VM to run an linux image.
I have already shut down my firewall and Antivirus. No VPN and No DNS server problem, I just run it on my computer.
In the VM image, hosts as the following:
127.0.0.1 boot2docker localhost localhost.local

::1            ip6-localhost ip6-loopback
fe00::0     ip6-localnet
ff00::0      ip-mcastprefix
ff02::1      ip6-allnodes
ff02::2      ip6-allrouters
ff02::3      ip6-allhosts

Actually, after automatically trying 60 times, terminal shows cannot get an IP. But there is an IP for VM. I can ping it in my host environment.

**Comment by guillaumeoudill** [comment]
Hi,
I'm facing exactly the same issue on my machine. The command 
docker-machine create --virtualbox-no-vtx-check --driver virtualbox default
is blocked on "Waiting for an IP"

I tried reinstalling virtualbox and dockertools but nothing worked for me.

Do you have any idea ?

**Comment by mchiang0610** [comment]
This seems like to be an error from Virtualbox networking. Do you happen to
be connected through a VPN or proxy?
Please try our beta - Docker for Mac and Windows available here:
https://beta.docker.com

On Tue, Jun 7, 2016 at 2:15 PM guillaumeoudill <notifications@github.com>
wrote:

> Hi,
> I'm facing exactly the same issue on my machine. The command
> docker-machine create --virtualbox-no-vtx-check --driver virtualbox default
> is blocked on "Waiting for an IP"
>
> I tried reinstalling virtualbox and dockertools but nothing worked for me.
>
> Do you have any idea ?
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/toolbox/issues/448#issuecomment-224416727>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ADK-B0FB3cRhPgE3f3gi_SQ1hEvhJH3fks5qJd9mgaJpZM4HvT0j>
> .
>
-- 
Thanks,
Michael Chiang

**Comment by guillaumeoudill** [comment]
Thanks Micheal
I've just registered to the beta. I'll try it as soon as I get access

**Comment by guillaumeoudill** [comment]
Hi, I've finally get rid of this issue! I uninstalled Hyper-V from my machine and reboot. The docker-machine create command worked this time... Is it possible to host the docker toolbox and hyper-V on the same machine?

**Comment by nathanleclaire** [comment]
I don't think VirtualBox and Hyper-V are compatible to use at the same time.  They can be installed side-by-side but if Hyper-V is enabled Virtualbox won't work.

**Comment by iver3on** [comment]
Starting "default"...
(default) Check network to re-create if needed...
(default) Waiting for an IP...

any suggestion?

**Comment by Sraw** [comment]
At this time I look back to this issue. I think I got it.
Only one VM software can be installed in computer.
VirtualBox, then no VM station or Hyper-V.

**Comment by Sraw** [comment]
@iver3on Hope it be helpful.

**Comment by iver3on** [comment]
I fix it by reinstall my os. from win10 preview to win10 pro. all have fixed.

**Comment by nathanleclaire** [comment]
Going to go ahead and close -- glad to hear things worked out for you folks.
