### ISSUE TITLE
PATH confusion

### ISSUE THREAD

**Issue by AndreKR** [docker/toolbox#469]
During the installation of Docker toolbox you have the choice between adding Docker to the PATH globally or not. Neither option works properly.

Adding Docker to the global PATH:
Trying to run any Docker command gives the error message:
`An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/images/json`
Running the same command from inside the Quickstart Terminal works.

Not adding it to the global PATH:
The Quickstart Terminal seems to fail finding docker.exe. No Docker command works, neither outside the Quickstart Terminal (expected) nor inside it (not expected).

**Comment by bandrzej** [comment]
The work around is as follows:
1. Close Quickstart Terminal

2. Open Windows Command Prompt

3. Verify if Docker Toolbox is in your Windows PATH as TRUE:  
`echo %PATH% | C:\Windows\system32\findstr /C:"Docker Toolbox" > nul && ( echo.TRUE ) || ( echo.FALSE)`

4. If not, run the following (assuming default location):  
`set PATH="%PATH%;C:\Program Files\Docker Toolbox"`

6.Re-open Docker Quickstart Terminal and try trying:
`docker -status`

**Comment by AndreKR** [comment]
`setx` sets the environment variable globally. After I do that it still only works in Docker Quickstart Terminal, not in a normal command prompt. There is no difference to adding it during the installation.

**Comment by bandrzej** [comment]
@AndreKR 
My issue is that **I didn't use a default install path**

When i tried this install from *another* computer with Windows 7 x64, I had to manually add my Docker Toolbox install path via GUI in Computer->Properties->Advanced system settings->Environment Variables->System Variables->Path to work both within Docker Quickstart Terminal and command prompt.  

Setting the path via bash in Docker Quickstart Terminial or using set/setx in Windows command prompt failed.

**Comment by AndreKR** [comment]
Closed in favor of https://github.com/docker/toolbox/pull/482 and https://github.com/docker/toolbox/issues/484
