### ISSUE TITLE
Running Docker container from Scheduled Task

### ISSUE THREAD

**Issue by cgatian** [docker/toolbox#474]
I'm attempting to run a Docker container using a Windows Task Scheduler.

The task is configured to run the following script.bat file:

```
docker-machine env --shell cmd default
@FOR /f "tokens=*" %%i IN ('docker-machine env --shell cmd default') DO @%%i
docker run hello-world

```

When the script executes via Task Scheduler, the following error is returned by the console:
*_Error Checking TLS Connection *_

When I execute the .bat file manually everything works.  I've gathered that the Task Scheduler cannot see the machine.  Any thoughts or suggestions?

**Comment by bmontalvo** [comment]
How did you resolve this?

**Comment by sveerabathini** [comment]
where you people able to run the task scheduler with in the windows containers
