### ISSUE TITLE
Error creating default machine 

### ISSUE THREAD

**Issue by igorchucky** [docker/toolbox#475]
Please, if somene could help me with this . I've been searching for some days and didn't found any answers for it. Have tried to downgrade my VirtualBox version but didn't solve the problem.

Thanks in advance.
![docker-error](https://cloud.githubusercontent.com/assets/4961663/14604977/bd1c9e58-054c-11e6-8de2-af5ed879d90e.png)

**Comment by ajaxscape** [comment]
Likewise for me.  I have VirtualBox 5.0.16 r105871

**Comment by DiJu519** [comment]
What version of the toolbox are you using?

**Comment by igorchucky** [comment]
It's the 1.11.0 version. Guess it's the last one, right ?

![docker-version](https://cloud.githubusercontent.com/assets/4961663/14995259/40628f80-114a-11e6-8450-1bf6e7a35ef9.png)

**Comment by igorchucky** [comment]
Removing all virtual hosts network adapters created, then I've updated my dockertoolbox, and my virtualbox. Now I'm getting a different error. Maybe is any missing driver from my computer ???

tks in advance.

![erro-docker](https://cloud.githubusercontent.com/assets/4961663/15045968/d14b0850-12b3-11e6-921e-33f2e030bb17.png)

**Comment by zandaqo** [comment]
I had something similar after updating to Docker 1.11/VirtualBox 5.0.16. Installing the latest VirtualBox 5.0.**20** helped to solve these issues. Not sure what was the cause though.

**Comment by igorchucky** [comment]
In windows I've reinstalled the docker toolbox and check all options during the setup installation wizard. this installed the newest nbs driver and this made my environment work quite well. thanks

**Comment by DiJu519** [comment]
The actual fix for me, was to go to the Network Adapter Virtualbox creates, and updating the network driver, just by selecting the same one it already had installed.
