### ISSUE TITLE
[1.11] Can't mount volume on non-C drive

### ISSUE THREAD

**Issue by DiJu519** [docker/toolbox#478]
$ pwd
/e/devspace/project/docker

$ docker run -v ~/.ssh/:/usr/share/jenkins/ref/.ssh/ -v **/e/**devspace/project/docker:/var/jenkins_ho
me/userContent/ -p 8080:8080 -p 50000:50000 -i -t jenkins

the .ssh credentials mount in correctly, but the full path to docker doesnt. I've had to copy the docker folder over to my C: drive and reference using that. 

also tried:

$ docker run -v ~/.ssh/:/usr/share/jenkins/ref/.ssh/ -v **//e/**devspace/project/docker:/var/jenkins_ho
me/userContent/ -p 8080:8080 -p 50000:50000 -i -t jenkins

**Comment by thaJeztah** [comment]
By default, only the `c:\Users` directory is shared with the VirtualBox VM, anything outside that directory is not shared with the VM, so the docker daemon running inside the VM will create an empty-directory and bind-mount that into the container. see https://github.com/boot2docker/boot2docker/#virtualbox-guest-additions

**Comment by DiJu519** [comment]
Thanks for the reply @thaJeztah 

From what i read, i can confirm that only /c/Users is mounted by default. Having anything mounted outside of that requires an addition to the VM settings "Shared Folders", and a call within the running VM of Boot2Docker to mount the folder.

Instead, i've used a symlink. 

Thanks
