### ISSUE TITLE
Windows: Docker Quickstart Terminal returns command not found for docker

### ISSUE THREAD

**Issue by moxiegirl** [docker/toolbox#48]
![screenshot 2015-08-04 14 49 10](https://cloud.githubusercontent.com/assets/1347209/9073710/23cf3bd4-3ab8-11e5-84a0-39c333b3a3cf.png)

**Comment by moxiegirl** [comment]
ping @jeffdm

**Comment by moxiegirl** [comment]
Looks like the quickstart closed or something...when I close what was installed and reopen by clicking on the icon it works.  I'll uninstall and see if I can recreate the sequence again.

**Comment by jeffdm** [comment]
@moxiegirl thanks, trying to reproduce, please keep me posted :smiley:

**Comment by moxiegirl** [comment]
Reproduced @jeffdm

**Comment by jeffdm** [comment]
Fixed on master and the rc4 exe was updated
