### ISSUE TITLE
docker.exe cannot be run from outside the Docker Quickstart Terminal

### ISSUE THREAD

**Issue by AndreKR** [docker/toolbox#484]
When I try to run `docker.exe` from a regular Command Prompt, I get this error:

```
C:\Users\andre>docker run -it ubuntu:14.04 bash
docker: An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/containers/create: open //./pipe/docker_engine: The system cannot find the file specified..
See 'docker run --help'.
```

I believe this is by design, but then the option "Add docker binaries to PATH" in the installer makes no sense.

**Comment by AndreKR** [comment]
Created PR to remove that option:
https://github.com/docker/toolbox/pull/483

**Comment by sxn** [comment]
This ticket is misleading. While it's true that you can't just fire up a shell and run Docker in it right off the bat, it does *not* mean that it is impossible to do so. There are a few things happening in `start.sh`, and recreating them (more or less) in our terminal of choice (in my case, `git bash`) makes it possible to run Docker:

```
$ docker run -it ubuntu:14.04 bash
D:\Tools\Docker\docker.exe: An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engi
ne/v1.23/containers/create: open //./pipe/docker_engine: The system cannot find the file specified..
See 'D:\Tools\Docker\docker.exe run --help'.
$ docker-machine status
Stopped
$ docker-machine start
Starting "default"...
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Machine "default" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
$ docker run -it ubuntu:14.04 bash
D:\Tools\Docker\docker.exe: An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engi
ne/v1.23/containers/create: open //./pipe/docker_engine: The system cannot find the file specified..
See 'D:\Tools\Docker\docker.exe run --help'.
$ docker-machine env --shell=bash
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="C:\Users\Sorin\machines\default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval $("D:\Tools\Docker\docker-machine.exe" env --shell=bash)
$ docker run -it ubuntu:14.04 bash
D:\Tools\Docker\docker.exe: An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engi
ne/v1.23/containers/create: open //./pipe/docker_engine: The system cannot find the file specified..
See 'D:\Tools\Docker\docker.exe run --help'.
$ export DOCKER_TLS_VERIFY="1"
$ export DOCKER_HOST="tcp://192.168.99.100:2376"
$ export DOCKER_CERT_PATH="C:\Users\Sorin\machines\default"
$ export DOCKER_MACHINE_NAME="default"
$ docker run -it ubuntu:14.04 bash
Unable to find image 'ubuntu:14.04' locally
14.04: Pulling from library/ubuntu
6c953ac5d795: Pull complete
3eed5ff20a90: Pull complete
f8419ea7c1b5: Pull complete
51900bc9e720: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:7c151496aefa83d7d5faeff87493d471f86ff5673b829b0e1724e66be69d011c
Status: Downloaded newer image for ubuntu:14.04
root@b3a5d2075f3e:/#
```

**Comment by eromoe** [comment]
same issue if I don't use docker-terminal-shortcut

**Comment by MaherJendoubi** [comment]
You have to run this: @FOR /f "tokens=*" %i IN ('docker-machine env docker1') DO @%i

**Comment by NLKNguyen** [comment]
Yes,  running this in cmd `@FOR /f "tokens=*" %i IN ('docker-machine.exe env --shell cmd') DO @%i` made it work for me. Thanks.

**Comment by NLKNguyen** [comment]
But how to not having to run that every time I open a new cmd window?

**Comment by amherdt** [comment]
What environment variables need?
**_~$_** docker-machine env

    SET DOCKER_TLS_VERIFY=1
    SET DOCKER_HOST=tcp://192.168.99.100:2376
    SET DOCKER_CERT_PATH=C:\Users\lol\.docker\machine\machines\default
    SET DOCKER_MACHINE_NAME=default
    REM Run this command to configure your shell:
    REM     @FOR /f "tokens=*" %i IN ('docker-machine env') DO @%i
    
As recommended in the end, if we execute the following command we would have all variables available.
**_~$_**   @FOR /f "tokens=*" %i IN ('docker-machine env') DO @%i

**SHIT**: If close the terminal, I lose the variables and have to set them again -.-
**SOLUTION**: Set permanent variables

For set permanent variable from the command line, see: https://technet.microsoft.com/en-us/library/cc755104(v=ws.11).aspx _Good luck my friend!_ =D

For set permanent variable easily:

1. Right-click on the Windows Button
2. Select System, from the menu.
3. From there, select “Advanced system settings” → “Environment Variables”.
4. Under the System Variables section, add all variables displayed when you ran the command: **docker-machine env**
5. Fuck Docker!

Bye Girls.

**Comment by amherdt** [comment]
I forgot it ...
You must have a docker-machine of course: 
`docker-machine create --driver virtualbox default`

**Comment by NLKNguyen** [comment]
I've just found another solution, and I think this is cleaner.

Simply create a batch script and register it to autorun everytime a cmd is open.

At user's home directory, create a file called `init.cmd` with the following content. I got from this issue https://github.com/docker/machine/issues/3023 and only added `@echo off` to not print anything
```Batch
@echo off

IF DEFINED DOCKER_MACHINE_EXECUTING (GOTO :eod)
set DOCKER_MACHINE_EXECUTING=1

:configureDocker
 FOR /f "tokens=*" %%i IN ('docker-machine env default') DO %%i

:eod
```

Then open cmd and run this command to register the script to autorun:
```cmd
reg add "HKCU\Software\Microsoft\Command Processor" /v AutoRun ^
  /t REG_EXPAND_SZ /d "%"USERPROFILE"%\init.cmd" /f
```
Learned from: http://stackoverflow.com/questions/17404165/how-to-run-a-command-on-command-prompt-startup-in-windows

Now Docker just works everytime I open cmd. It didn't work for PowerShell though, but I'm pretty sure it can be done similarly. I just have no need for PowerShell at the moment to figure out.

**Comment by koppor** [comment]
The solution for the issue on my side as pretty simple:

1. Enable HyperV as described at https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/quick_start/walkthrough_install
2. Reboot the PC. Do  not shut down and start it again, really to a restart!

**Comment by carlin-q-scott** [comment]
Docker-Machine should use setx, not set, on Windows. setx persists the environment variables, set does not. I know, it's stupid but that's Microsoft for ya.

**Comment by AndreKR** [comment]
@carlin-q-scott "Persist" as in "they are still there after the next reboot"? That would be a reason to report the software as malware.

**Comment by carlin-q-scott** [comment]
@AndreKR Modifying environment variables permanently is a standard practice for installers; I doubt docker would be classified as malware for doing this. 

Using the normal set doesn't even persist between command prompts so it has very limited utility.

**Comment by AndreKR** [comment]
@carlin-q-scott Oh, you were talking about the installation. I thought you meant it should use `setx` when *running*.

**Comment by carlin-q-scott** [comment]
@AndreKR For clarity, I meant it should use setx when it is installed. I thought it used the script that's output by `docker-machine env` during the install but I could totally be wrong about that. Regardless, that particular command should output a script that sets up the docker-machine environment which will last beyond the current shell session, no?

**Comment by AndreKR** [comment]
I am closing this issue for now because it was based on false premises. I initially thought that start.sh and bash are necessary for docker to work properly.
But indeed (thanks @sxn for clarifying) `docker` and `docker-machine` work just as well from a regular command prompt (or whatever terminal emulator of your choice). The _Docker Quickstart Terminal_ just adds complication with bash, msys, mingw and whatnot. (IMO Docker Toolbox would be better off if Git Bash was taken out of the equation.)

The only reason why `docker` didn't work out of the box is that the credentials to the boot2docker machine need to be set. This is no different from a Linux machine where only the docker command line tools are installed.

`docker-machine` even conveniently outputs the correct command in Windows command line syntax:
```
FOR /f "tokens=*" %%i IN ('docker-machine env default') DO %%i
```
And if it's the very first run, the machine needs to be created (also no different from Linux):
```
docker-machine create -d virtualbox default
```

**Comment by carlin-q-scott** [comment]
@AndreKR  I guess your issue is different than mine. I'll have to create another issue report then.

**Comment by xzessmedia** [comment]
its a real shame.. 1 year and still no resolvement... and thats in the official docker repository....
