### ISSUE TITLE
Docker complains error "proxy: unknown scheme: http"

### ISSUE THREAD

**Issue by usherfu** [docker/toolbox#539]
I am facing above error when running hello-world example:

docker run hello-world.

I found following thread stating similar issue, and I am using docker 1.11.2 behind a corporate proxy.  I also posted my workaround in below link, which is to downgrade the docker toolbox to 1.10.3.     However, I would like to know if anyone else is also facing this issue with newer docker version, and maybe a fix if possible. 

http://stackoverflow.com/questions/37573476/docker-complaining-about-all-proxy-environment-variable-with-proxy-unknown-sch

**Comment by bbodenmiller** [comment]
Related to https://github.com/docker/docker/issues/25740 and https://github.com/golang/go/issues/16715
