### ISSUE TITLE
[win8.1] Clean install (error) - right after double clicking on .exe

### ISSUE THREAD

**Issue by mchiang0610** [docker/toolbox#54]
![img_1203](https://cloud.githubusercontent.com/assets/3325447/9188623/0ea29cb2-3f93-11e5-940d-07184af94849.JPG)

**Comment by mchiang0610** [comment]
Sorry. This computer is fresh so no easy access to screencapture + login to github

**Comment by jeffdm** [comment]
Fixed on `master`
