### ISSUE TITLE
Still using VirtualBox?

### ISSUE THREAD

**Issue by benlau** [docker/toolbox#545]
Hi,

According to this article:

[Docker for Mac and Windows is Now Generally Available and Ready for Production | Docker Blog](https://blog.docker.com/2016/07/docker-for-mac-and-windows-production-ready/)

    native development environment using hypervisors built into each operating system. (No more VirtualBox!)

However, even I have upgraded to DockerToolbox-1.12. It is still using VirtualBox. Is the migration finished? Or I have to modify any setting in order to turn off VirtualBox?

Thanks for any advise.

**Comment by bbodenmiller** [comment]
Docker Toolbox still uses VirtualBox. A new product, Docker for Windows uses Hyper-V: https://www.docker.com/products/docker#/windows

**Comment by benlau** [comment]
I see. 

Thank you!

**Comment by airtonix** [comment]
It also needs to be mentioned that hyper-v is only available on enterprise versions of windows...

So home users still need to use docker-toolbox
