### ISSUE TITLE
windows -- start.sh assumes hardwired installation path which may not match actual install

### ISSUE THREAD

**Issue by dreftymac** [docker/toolbox#562]
- PROBLEM: 
  - start.sh seems to assume the user installed to c:\program files\docker toolbox\
  - this causes breakage if the user installed to a custom directory such as c:\programs\dockertoolbox
  - https://github.com/docker/toolbox/blob/master/windows/start.sh#L8

**Comment by somombo** [comment]
Hi there this is one of the things that has been address in my pull request. See https://github.com/docker/toolbox/pull/578/files

In addition, I have an open issue https://github.com/docker/toolbox/issues/579 discussing how we might be able to have a more robust Docker Quickstart Terminal for windows.. which is what the pull request above is trying to solve.

Any comments or support you are able to provide or contribute are greatly appreciated!
