### ISSUE TITLE
Migration does not check for incompatible boot2docker vms

### ISSUE THREAD

**Issue by thaJeztah** [docker/toolbox#57]
This might be a non-issue, because I had a pre-release on my computer that I installed while reviewing the install docs; I don't remember which version (didn't keep the original installer around); after installing the 1.8 release, I got a pop-up offering me to upgrade my boot2docker installation, which failed:
https://gist.github.com/thaJeztah/65cec885a32748583fc5

Feel free to close, just posting the logs in case they're useful

**Comment by jeffdm** [comment]
Seems like an old version of Boot2Docker that did not use SSH keys. Migration should check for this

**Comment by thaJeztah** [comment]
Sorry, I looked around, but I think I trashed the installer, so no able to offer which version it was

**Comment by jeffdm** [comment]
@nathanleclaire can you speak to the requirements the toolbox can check before committing to migrating?

- SSH Keys
- TLS certs
- Boot2Docker VM file

**Comment by nathanleclaire** [comment]
Ah, @thaJeztah did you somehow set the boot2docker SSH key file to a different location?  Or this was from an old version of boot2docker?

**Comment by thaJeztah** [comment]
@nathanleclaire afaik, I hadn't changed anything there; I only had installed toolbox for following the install instructions and started kitematic, running a hello-world (or comparable) :dancers:

As I said, the previous version was a pre-release, so I'm not even sure this is a problem actual users will run into.

Any info I can provide that you're interested in?

**Comment by jeffdm** [comment]
This should be fixed in 1.8.1c. Thank again!
