### ISSUE TITLE
[Windows] Robust docker-terminal: Run docker and docker-compose from powershell or cmd

### ISSUE THREAD

**Issue by somombo** [docker/toolbox#579]
As it currently stands, one has to run docker or docker-compose commands only through the "Docker Quickstart Terminal" (DQT).. This is problematic and tedious. I have made improvements to the start.sh script that DQT invokes to make the script portable and persistable in the windows environment. So that one can run docker from powershell or command prompt (or indeed git-bash if they so wish).

Rather than looking for a DQT shortcut.. one simply runs the command `docker-terminal` from any command line interface and any directory context. This is roughly equivalent then, to clicking on DQT and then doing a cd to the precise directory where I'd want to be (except if you are typing `docker-terminal` at the cli, you are probably already in the directory you want to be in). This has really help my workflow.

I have made this contribution to the docker-toolbox project and would like to get some feedback about my pull request https://github.com/docker/toolbox/pull/578 to make sure I am following contribution guidelines. In addition, if anyone is willing to test the code, it is available here https://github.com/somombo/toolbox. 

Let me know if I can clarify how to use this better.
I look forward to hearing from you all.

**Comment by narration-sd** [comment]
Just to say thanks for providing this, and I hope they take you up on it, as it's a good idea.

Can't help with clarification of your  pull request, but hope the organizers get back to you soon.

**Comment by somombo** [comment]
@narration-sd thanks for acknowledging this as a good idea.. I appreciate that feedback!

**Comment by narration-sd** [comment]
Yes, and the issue with not having it is that you end up with several shell windows open on the desktop, but they are not the same, with regard to commonly-used abilities like copy-paste.

Much nicer if they take up your work and plan ;)

**Comment by embray** [comment]
I definitely like this idea as well.  I was sort of under the impression that docker-toolbox wasn't being supported anymore, but I could be wrong.  It's sometimes hard to find clear documentation from Docker what their Windows strategy is...

**Comment by somombo** [comment]
@embray You might be aware that Hyper-V is required for the non-Docker-toolbox version of docker; "Docker for Windows". As far as I know, there is no way to run Virtualbox VMs whilst also having Hyper-V installed. However, there are people such as myself, that have specific and independent uses for virtualbox that would not be supported by hyper-V e.g. Android app dev emulation using Genymotion.

Therefore,  I personally think docker-toolbox on windows  has to continue to be supported.

**Comment by embray** [comment]
@somombo Yes, I agree. I think requiring Hyper-V is also particularly burdensome for one of my main Docker use cases, which is providing teaching environments for tutorials.  So I *hope* something like Docker Toolbox is its current form is still supported but that hasn't been clear to me.

**Comment by danieltwigg** [comment]
@somombo I have the exact same issue. I need Android emulation *AND* Hyper-V Docker for Windows :(

**Comment by somombo** [comment]
Looks like this is now all taken care of
