### ISSUE TITLE
Toolbox hangs during the installation process 

### ISSUE THREAD

**Issue by rogaha** [docker/toolbox#58]
``docker-machine`` is unable to connect to `Docker` daemon. It seems to be related to existing VPN connections.

![screen shot 2015-08-11 at 4 00 42 pm](https://cloud.githubusercontent.com/assets/4483394/9213642/cb258b5e-4049-11e5-8ff7-7dd63a0afa47.png)

**Comment by mjrust** [comment]
I just experienced the same thing, I was also connected to a work VPN.

**Comment by jeffdm** [comment]
To kill the installer for now do `pkill Installer`

For those not on VPN, try:

**On OS X 10.9**: `sudo /Library/StartupItems/VirtualBox/VirtualBox restart`
**On OSX 10.10+**: `sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart`


Relevant: https://github.com/mitchellh/vagrant/issues/1671

**Comment by inkel** [comment]
@jeffdm I've reported it also in https://github.com/docker/machine/issues/1678

I don't have the `/Library/StartupItems/VirtualBox/VirtualBox` command.

**Comment by kevinSuttle** [comment]
I kiled it, the `installerd`. Then re-ran it, and it appeared to be fine. I am using Cisco AnyConnect for Mac, though.

**Comment by jeffdm** [comment]
Closing in favor of #65

**Comment by mchiang0610** [comment]
If anyone still has problems with this, please contact me at mchiang@docker.com.

We are working on something to help address this issue.
