### ISSUE TITLE
My Docker would not even Create virtual machine default

### ISSUE THREAD

**Issue by opemipoVRB** [docker/toolbox#581]
My Docker would not even Create virtual machine default it has been stuck on 
Running pre-create checks. . .
for over 6hrs can anybody help me out ASAP..

it has worked before but then I deleted the the virtual machine so I could enable Tensorflow to work on my Console and not just Jupyter Note book but now it doesn't even want to create any virtual machine My boot2loader iso is still in cache folder.

**Comment by londoncalling** [comment]
@opemipoVRB can you provide this information?
@nathanleclaire can you jump in? Not sure where to route this.

- version and platform info info
- which product you installed (e.g., are you using Docker Machine from a Toolbox install? or Docker Machine from a Docker for Mac or Windows install?)
- If you say "it worked before you deleted the VM..." does that mean that when you originally installed the product you had a running `default` and deleted it?
- exact steps / commands you used? (e.g. how did you delete the machine?, command you used to recreate the `default` machine?)

**Comment by opemipoVRB** [comment]
DockerToolbox-1.12.0 on Windows 8  64bit 
Yeah I had a running Docker machine default but it ran only on jupyter note I couldn't acess it from a terminal or my PyCharm IDE. so I deleted the whole directory C:\Users\<username>\.docker without using any command

**Comment by londoncalling** [comment]
@opemipoVRB can you uninstall Toolbox / Docker and reinstall? Deleting the `.docker` directory is probably the problem, or definitely contributing to it. 

- Instructions for uninstalling Toolbox on Windows are here: https://docs.docker.com/toolbox/toolbox_install_windows/#/how-to-uninstall-toolbox
- Instructions for re-installing are on that same page here: https://docs.docker.com/toolbox/toolbox_install_windows/#/install-docker-for-windows

**Comment by opemipoVRB** [comment]
Still the same problem. So I just completely abandoned the docker tool and switched to using my Linux in VMWare so i could install Theano so I dont need Docker again probably till the problem gets fixed
it would be nice to do what you can do in linux on windows too..

**Comment by londoncalling** [comment]
@opemipoVRB are you not able to use Docker for Windows? (https://docs.docker.com/docker-for-windows/), and if not I'd like to re-visit the problem you are having with Toolbox and see if we can fix it. (ping @nathanleclaire )

**Comment by londoncalling** [comment]
@opemipoVRB @nathanleclaire I'm closing this issue as I've not heard anything on it, and Docker Toolbox is a legacy app, and our recommendation in general is to upgrade to [Docker for Windows](https://docs.docker.com/docker-for-windows/) at this point. Please re-open this issue, if you want to re-start the discussion.
