### ISSUE TITLE
Getting started does not allow me to download right away

### ISSUE THREAD

**Issue by mchiang0610** [docker/toolbox#6]
I had to look around (no search) to find link to download on the next page: 

![image](https://cloud.githubusercontent.com/assets/3325447/8654607/3c6b8802-2940-11e5-993c-6570475da701.png)

On the next page, it was super hard find the download: 

http://docker-manthony.s3-website-us-east-1.amazonaws.com/mac/step_one/

**Comment by jeffdm** [comment]
Closing for now - please open a ticket on the docs repo :memo:
