### ISSUE TITLE
Sign the package with a developer ID to prevent OS X 10 Gatekeeper warnings

### ISSUE THREAD

**Issue by ChrisPearce** [docker/toolbox#60]
When installing the package on OS X, the operating system advises that the package cannot be opened because it is from an unidentified developer.

It would be great if this package could be signed, to avoid users having to turn off Gatekeeper or Control-Click install.

A screenshot of the message is attached
<img width="414" alt="screen shot 2015-08-12 at 08 39 09" src="https://cloud.githubusercontent.com/assets/402894/9218806/a8da64b4-40cd-11e5-98ea-6afa72a29515.png">

**Comment by jeffdm** [comment]
Fixed, thanks for the issue!

**Comment by kunklejr** [comment]
Just experienced the same issue with 1.9.1g this morning. I'd rather not install an unsigned version of the package, especially when there's no published hash of the file to verify it against. Is it supposed to be signed?

**Comment by jeffdm** [comment]
It is, if you try again, does it work? We've seen some rare cases where opening it for the first time shows this message but not for the second time.

**Comment by kunklejr** [comment]
As strange as it sounds, it didn't work for a whole day after repeated downloads of multiple versions. I tried it again yesterday afternoon, after two days had passed, and the error was gone. Unfortunately, I have no good explanation for why things changed, but it's very odd.
