### ISSUE TITLE
No mention of VMware fusion support - is Virtualbox mandatory?

### ISSUE THREAD

**Issue by sammcj** [docker/toolbox#61]
It appears that docker/toolbox is a Virtualbox only option - is this correct because I thought docker-machine did support VMware Fusion now?

Reasoning:

A lot of people don't want to run Virtualbox due to it's poor performance and Oracle ownership and would rather use VMware Fusion - source.

Somewhat related:
- https://github.com/boot2docker/boot2docker/issues/464

**Comment by jeffdm** [comment]
Thanks for the issue!

The Toolbox is definitely not a VirtualBox-only option. For creating Docker VMs, the toolbox includes `docker-machine`, which supports a variety of providers.

For fusion, try running: `docker-machine create -d vmwarefusion mytestvm`.

Going to close this issue for now, but feel free to re-open if this doesn't answer your question!

**Comment by wchrisjohnson** [comment]
@jeffdm Please correct me if I'm wrong, but when you install Toolbox, it forces the use of virtualbox... Kitematic won't move past the startup screen without virtualbox installed. 

There also appear to be issues with the way the VMware shared folder implementation works: https://github.com/docker/machine/issues/1817 such that I had to abandon use of Fusion and install virtualbox to get Toolbox to properly work. From that thread it doesn't look like that has been addressed.

If there is a way to get the Toolbox (including Kitematic) working with VMware Fusion, I'd love to hear how.
