### ISSUE TITLE
Why Docker Toolbox v1.13.0 doesn't include Docker Daemon v1.13 ?

### ISSUE THREAD

**Issue by s101d1** [docker/toolbox#622]
I have installed Docker Toolbox v1.13.0-rc7 on windows. When I run `docker version`, I got result:

```
Client:
 Version:      1.13.0-rc7
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.5
 API version:  1.24 (minimum version )
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

So the docker daemon/server is still v1.12. I expected the toolbox v1.13 would have included daemon v1.13 too. Is there a reason why the daemon 1.13 is not included while the client version is already 1.13?

**Comment by thaJeztah** [comment]
I don't think it automatically upgrades an existing VM; try `docker-machine upgrade` to upgrade your VM

**Comment by s101d1** [comment]
^Thanks, it's solved.

**Comment by thaJeztah** [comment]
Cool, let me close this issue then 👍
