### ISSUE TITLE
Toolbox installation option to continue after VB is closed

### ISSUE THREAD

**Issue by arun-gupta** [docker/toolbox#63]
If VirtualBox is running, then Toolbox installation shows the following message:

```
The installer has detected that VirtualBox is out of date, and is still running. Please shut down all VMs, quit VirtualBox, and then restart the Docker Toolbox installation.
```

The only way to continue is to click on the `Close` button and restart the installation. There should be an option to shutdown the VMs, exit VirtualBox, and continue with the installation within the wizard. This would not require to restart the installation.

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by mchiang0610** [comment]
@arun-gupta We are looking for help on this issue. Would you be able to help create a pull request for this? 

Thank you so much!
