### ISSUE TITLE
host-only cidr conflicts with the network address of a host interface

### ISSUE THREAD

**Issue by hailinzeng** [docker/toolbox#630]
Hi, I got the following error when I start the DockerQuickstart Terminal in Windows Server 2008.

(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
Error creating machine: Error in driver during machine creation: Error setting up host only network on machine start: host-only cidr conflicts with the network address of a host interface
Looks like something went wrong in step 'Checking if machine default exists'...
Press any key to continue...

I am using:
docker version: 17.03.0-ce
os version: Windows Server 2008 R2 Enterprise SP1

And the network adapter configuration:
1) Local Area Connection
    IPv4 Addr: 192.168.99.243
    IPv4 Subnet Mask: 255.255.255.0
    IPv4 Default Gateway: 192.168.99.1
    IPv4 DHCP Server: 192.168.99.1
    IPv4 DNS Server: 192.168.99.1
2) Virtualbox Host-Only Network
    IPv4 Addr: 192.168.56.1
    IPv4 Subnet Mask: 255.255.255.0

**Comment by hailinzeng** [comment]
docker-machine start default verbose log
> PS C:\Users\Administrator> docker-machine.exe --debug start default
Docker Machine Version:  0.10.0, build 76ed2a6
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:49685
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
command=start machine=default
Starting "default"...
(default) Calling .GetState
(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo default --machinereadable
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | name="default"
(default) DBG | groups="/"
(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(default) DBG | UUID="05294aac-fce7-4a18-abbf-fbdf17055721"
(default) DBG | CfgFile="C:\\Users\\Administrator\\.docker\\machine\\machines\\default\\default\\default.vbox"
(default) DBG | SnapFldr="C:\\Users\\Administrator\\.docker\\machine\\machines\\default\\default\\Snapshots"
(default) DBG | LogFldr="C:\\Users\\Administrator\\.docker\\machine\\machines\\default\\default\\Logs"
(default) DBG | hardwareuuid="05294aac-fce7-4a18-abbf-fbdf17055721"
(default) DBG | memory=1024
(default) DBG | pagefusion="off"
(default) DBG | vram=8
(default) DBG | cpuexecutioncap=100
(default) DBG | hpet="on"
(default) DBG | chipset="piix3"
(default) DBG | firmware="BIOS"
(default) Calling .Start
(default) DBG | cpus=1
(default) DBG | pae="on"
(default) DBG | longmode="on"
(default) DBG | triplefaultreset="off"
(default) DBG | apic="on"
(default) DBG | x2apic="off"
(default) DBG | cpuid-portability-level=0
(default) DBG | bootmenu="disabled"
(default) DBG | boot1="dvd"
(default) DBG | boot2="dvd"
(default) DBG | boot3="disk"
(default) DBG | boot4="none"
(default) DBG | acpi="on"
(default) DBG | ioapic="on"
(default) DBG | biosapic="apic"
(default) DBG | biossystemtimeoffset=0
(default) DBG | rtcuseutc="on"
(default) DBG | hwvirtex="on"
(default) DBG | nestedpaging="on"
(default) DBG | largepages="on"
(default) DBG | vtxvpid="on"
(default) DBG | vtxux="on"
(default) DBG | paravirtprovider="default"
(default) DBG | effparavirtprovider="kvm"
(default) DBG | VMState="poweroff"
(default) DBG | VMStateChangeTime="2017-03-07T20:13:51.000000000"
(default) DBG | monitorcount=1
(default) DBG | accelerate3d="off"
(default) DBG | accelerate2dvideo="off"
(default) DBG | teleporterenabled="off"
(default) DBG | teleporterport=0
(default) DBG | teleporteraddress=""
(default) DBG | teleporterpassword=""
(default) DBG | tracing-enabled="off"
(default) DBG | tracing-allow-vm-access="off"
(default) DBG | tracing-config=""
(default) DBG | autostart-enabled="off"
(default) DBG | autostart-delay=0
(default) DBG | defaultfrontend=""
(default) DBG | storagecontrollername0="SATA"
(default) DBG | storagecontrollertype0="IntelAhci"
(default) DBG | storagecontrollerinstance0="0"
(default) DBG | storagecontrollermaxportcount0="30"
(default) DBG | storagecontrollerportcount0="30"
(default) DBG | storagecontrollerbootable0="on"
(default) DBG | "SATA-0-0"="C:\Users\Administrator\.docker\machine\machines\default\boot2docker.iso"
(default) DBG | "SATA-ImageUUID-0-0"="d3e1ea60-42f7-4fcb-81b2-9dff2a2e2164"
(default) DBG | "SATA-tempeject"="off"
(default) DBG | "SATA-IsEjected"="off"
(default) DBG | "SATA-1-0"="C:\Users\Administrator\.docker\machine\machines\default\disk.vmdk"
(default) DBG | "SATA-ImageUUID-1-0"="46d4f749-b98a-413b-826d-2bf365134bbc"
(default) DBG | "SATA-2-0"="none"
(default) DBG | "SATA-3-0"="none"
(default) DBG | "SATA-4-0"="none"
(default) DBG | "SATA-5-0"="none"
(default) DBG | "SATA-6-0"="none"
(default) DBG | "SATA-7-0"="none"
(default) DBG | "SATA-8-0"="none"
(default) DBG | "SATA-9-0"="none"
(default) DBG | "SATA-10-0"="none"
(default) Check network to re-create if needed...
(default) DBG | "SATA-11-0"="none"
(default) DBG | "SATA-12-0"="none"
(default) DBG | "SATA-13-0"="none"
(default) DBG | "SATA-14-0"="none"
(default) DBG | "SATA-15-0"="none"
(default) DBG | "SATA-16-0"="none"
(default) DBG | "SATA-17-0"="none"
(default) DBG | "SATA-18-0"="none"
(default) DBG | "SATA-19-0"="none"
(default) DBG | "SATA-20-0"="none"
(default) DBG | "SATA-21-0"="none"
(default) DBG | "SATA-22-0"="none"
(default) DBG | "SATA-23-0"="none"
(default) DBG | "SATA-24-0"="none"
(default) DBG | "SATA-25-0"="none"
(default) DBG | "SATA-26-0"="none"
(default) DBG | "SATA-27-0"="none"
(default) DBG | "SATA-28-0"="none"
(default) DBG | "SATA-29-0"="none"
(default) DBG | natnet1="nat"
(default) DBG | macaddress1="0800277C224E"
(default) DBG | cableconnected1="on"
(default) DBG | nic1="nat"
(default) DBG | nictype1="82540EM"
(default) DBG | nicspeed1="0"
(default) DBG | mtu="0"
(default) DBG | sockSnd="64"
(default) DBG | sockRcv="64"
(default) DBG | tcpWndSnd="64"
(default) DBG | tcpWndRcv="64"
(default) DBG | nic2="none"
(default) DBG | nic3="none"
(default) DBG | nic4="none"
(default) DBG | nic5="none"
(default) DBG | nic6="none"
(default) DBG | nic7="none"
(default) DBG | nic8="none"
(default) DBG | hidpointing="ps2mouse"
(default) DBG | hidkeyboard="ps2kbd"
(default) DBG | uart1="off"
(default) DBG | uart2="off"
(default) DBG | uart3="off"
(default) DBG | uart4="off"
(default) DBG | lpt1="off"
(default) DBG | lpt2="off"
(default) DBG | audio="dsound"
(default) DBG | clipboard="disabled"
(default) DBG | draganddrop="disabled"
(default) DBG | vrde="off"
(default) DBG | usb="off"
(default) DBG | ehci="off"
(default) DBG | xhci="off"
(default) DBG | SharedFolderNameMachineMapping1="c/Users"
(default) DBG | SharedFolderPathMachineMapping1="\\?\c:\Users"
(default) DBG | vcpenabled="off"
(default) DBG | vcpscreens=0
(default) DBG | vcpfile="C:\Users\Administrator\.docker\machine\machines\default\default\default.webm"
(default) DBG | vcpwidth=1024
(default) DBG | vcpheight=768
(default) DBG | vcprate=512
(default) DBG | vcpfps=25
(default) DBG | GuestMemoryBalloon=0
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo default --machinereadable
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | name="default"
(default) DBG | groups="/"
(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(default) DBG | UUID="05294aac-fce7-4a18-abbf-fbdf17055721"
(default) DBG | CfgFile="C:\\Users\\Administrator\\.docker\\machine\\machines\\default\\default\\default.vbox"
(default) DBG | SnapFldr="C:\\Users\\Administrator\\.docker\\machine\\machines\\default\\default\\Snapshots"
(default) DBG | LogFldr="C:\\Users\\Administrator\\.docker\\machine\\machines\\default\\default\\Logs"
(default) DBG | hardwareuuid="05294aac-fce7-4a18-abbf-fbdf17055721"
(default) DBG | memory=1024
(default) DBG | pagefusion="off"
(default) DBG | vram=8
(default) DBG | cpuexecutioncap=100
(default) DBG | hpet="on"
(default) DBG | chipset="piix3"
(default) DBG | firmware="BIOS"
(default) DBG | cpus=1
(default) DBG | pae="on"
(default) DBG | longmode="on"
(default) DBG | triplefaultreset="off"
(default) DBG | apic="on"
(default) DBG | x2apic="off"
(default) DBG | cpuid-portability-level=0
(default) DBG | bootmenu="disabled"
(default) DBG | boot1="dvd"
(default) DBG | boot2="dvd"
(default) DBG | boot3="disk"
(default) DBG | boot4="none"
(default) DBG | acpi="on"
(default) DBG | ioapic="on"
(default) DBG | biosapic="apic"
(default) DBG | biossystemtimeoffset=0
(default) DBG | rtcuseutc="on"
(default) DBG | hwvirtex="on"
(default) DBG | nestedpaging="on"
(default) DBG | largepages="on"
(default) DBG | vtxvpid="on"
(default) DBG | vtxux="on"
(default) DBG | paravirtprovider="default"
(default) DBG | effparavirtprovider="kvm"
(default) DBG | VMState="poweroff"
(default) DBG | VMStateChangeTime="2017-03-07T20:13:51.000000000"
(default) DBG | monitorcount=1
(default) DBG | accelerate3d="off"
(default) DBG | accelerate2dvideo="off"
(default) DBG | teleporterenabled="off"
(default) DBG | teleporterport=0
(default) DBG | teleporteraddress=""
(default) DBG | teleporterpassword=""
(default) DBG | tracing-enabled="off"
(default) DBG | tracing-allow-vm-access="off"
(default) DBG | tracing-config=""
(default) DBG | autostart-enabled="off"
(default) DBG | autostart-delay=0
(default) DBG | defaultfrontend=""
(default) DBG | storagecontrollername0="SATA"
(default) DBG | storagecontrollertype0="IntelAhci"
(default) DBG | storagecontrollerinstance0="0"
(default) DBG | storagecontrollermaxportcount0="30"
(default) DBG | storagecontrollerportcount0="30"
(default) DBG | storagecontrollerbootable0="on"
(default) DBG | "SATA-0-0"="C:\Users\Administrator\.docker\machine\machines\default\boot2docker.iso"
(default) DBG | "SATA-ImageUUID-0-0"="d3e1ea60-42f7-4fcb-81b2-9dff2a2e2164"
(default) DBG | "SATA-tempeject"="off"
(default) DBG | "SATA-IsEjected"="off"
(default) DBG | "SATA-1-0"="C:\Users\Administrator\.docker\machine\machines\default\disk.vmdk"
(default) DBG | "SATA-ImageUUID-1-0"="46d4f749-b98a-413b-826d-2bf365134bbc"
(default) DBG | "SATA-2-0"="none"
(default) DBG | "SATA-3-0"="none"
(default) DBG | "SATA-4-0"="none"
(default) DBG | "SATA-5-0"="none"
(default) DBG | "SATA-6-0"="none"
(default) DBG | "SATA-7-0"="none"
(default) DBG | "SATA-8-0"="none"
(default) DBG | "SATA-9-0"="none"
(default) DBG | "SATA-10-0"="none"
(default) DBG | "SATA-11-0"="none"
(default) DBG | "SATA-12-0"="none"
(default) DBG | "SATA-13-0"="none"
(default) DBG | "SATA-14-0"="none"
(default) DBG | "SATA-15-0"="none"
(default) DBG | "SATA-16-0"="none"
(default) DBG | "SATA-17-0"="none"
(default) DBG | "SATA-18-0"="none"
(default) DBG | "SATA-19-0"="none"
(default) DBG | "SATA-20-0"="none"
(default) DBG | "SATA-21-0"="none"
(default) DBG | "SATA-22-0"="none"
(default) DBG | "SATA-23-0"="none"
(default) DBG | "SATA-24-0"="none"
(default) DBG | "SATA-25-0"="none"
(default) DBG | "SATA-26-0"="none"
(default) DBG | "SATA-27-0"="none"
(default) DBG | "SATA-28-0"="none"
(default) DBG | "SATA-29-0"="none"
(default) DBG | natnet1="nat"
(default) DBG | macaddress1="0800277C224E"
(default) DBG | cableconnected1="on"
(default) DBG | nic1="nat"
(default) DBG | nictype1="82540EM"
(default) DBG | nicspeed1="0"
(default) DBG | mtu="0"
(default) DBG | sockSnd="64"
(default) DBG | sockRcv="64"
(default) DBG | tcpWndSnd="64"
(default) DBG | tcpWndRcv="64"
(default) DBG | nic2="none"
(default) DBG | nic3="none"
(default) DBG | nic4="none"
(default) DBG | nic5="none"
(default) DBG | nic6="none"
(default) DBG | nic7="none"
(default) DBG | nic8="none"
(default) DBG | hidpointing="ps2mouse"
(default) DBG | hidkeyboard="ps2kbd"
(default) DBG | uart1="off"
(default) DBG | uart2="off"
(default) DBG | uart3="off"
(default) DBG | uart4="off"
(default) DBG | lpt1="off"
(default) DBG | lpt2="off"
(default) DBG | audio="dsound"
(default) DBG | clipboard="disabled"
(default) DBG | draganddrop="disabled"
(default) DBG | vrde="off"
(default) DBG | usb="off"
(default) DBG | ehci="off"
(default) DBG | xhci="off"
(default) DBG | SharedFolderNameMachineMapping1="c/Users"
(default) DBG | SharedFolderPathMachineMapping1="\\?\c:\Users"
(default) DBG | vcpenabled="off"
(default) DBG | vcpscreens=0
(default) DBG | vcpfile="C:\Users\Administrator\.docker\machine\machines\default\default\default.webm"
(default) DBG | vcpwidth=1024
(default) DBG | vcpheight=768
(default) DBG | vcprate=512
(default) DBG | vcpfps=25
(default) DBG | GuestMemoryBalloon=0
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | Name:            VirtualBox Host-Only Ethernet Adapter
(default) DBG | GUID:            d9562b86-f8bb-4706-aa16-10cbccad2de9
(default) DBG | DHCP:            Disabled
(default) DBG | IPAddress:       192.168.56.1
(default) DBG | NetworkMask:     255.255.255.0
(default) DBG | IPV6Address:     fe80:0000:0000:0000:9804:8f59:a857:a357
(default) DBG | IPV6NetworkMaskPrefixLength: 64
(default) DBG | HardwareAddress: 0a:00:27:00:00:17
(default) DBG | MediumType:      Ethernet
(default) DBG | Status:          Up
(default) DBG | VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
(default) DBG |
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
Error setting up host only network on machine start: host-only cidr conflicts with the network address of a host interfa
ce
PS C:\Users\Administrator>

**Comment by hailinzeng** [comment]
I found in C:\Users\Administrator\.docker\machine\machines\default\config.json , the HostOnlyCIDR is 192.168.99.1/24, which does not match the virtualbox adapter address 192.168.56.1 .

I manually edit the HostOnlyCIDR to 192.168.56.1/24, and the issue is gone.

**Comment by zhugw** [comment]
Because my  machine has used `192.168.99.1/24`

```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether f4:5c:89:a8:18:81
	inet 192.168.99.171 netmask 0xffffff00 broadcast 192.168.99.255
```
So I specify another network segment (`10.10.10.1/24`) for it

docker-machine create --virtualbox-hostonly-cidr "10.10.10.1/24" --driver virtualbox myvm1
