### ISSUE TITLE
Exit Status 1 + Hanging in QuickStart Terminal or Kitematic

### ISSUE THREAD

**Issue by jeffdm** [docker/toolbox#65]
Placeholder thread to keep possible causes:

- Do you have VT-X enabled on your Windows PC?

- Are you connected to a VPN?

If not, virtualbox may not be up and running. Restarting your computer will usually fix this, or try:

**On OS X 10.9**: `sudo /Library/StartupItems/VirtualBox/VirtualBox restart`
**On OSX 10.10+**: `sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart`

**Comment by mkavis** [comment]
Getting error looking for ca.pem file on Win 7 box
![dockertoolbox](https://cloud.githubusercontent.com/assets/2903281/9233425/e222fe60-4100-11e5-9762-7c33d1f7cdbc.png)

**Comment by jeffdm** [comment]
Thanks @mkavis !

**Comment by ehazlett** [comment]
@mkavis could you try running `docker-machine regenerate-certs default`?

**Comment by ehazlett** [comment]
@mkavis can you also list the contents of that machine dir (`C:\Users\...\.docker\machine\machines\default`)
?

**Comment by mkavis** [comment]
Tried that command from within virtual box boot2docker VM and get command not found

**Comment by mkavis** [comment]
![dockertoolbox2](https://cloud.githubusercontent.com/assets/2903281/9234128/f4625d4c-4104-11e5-874f-d634ba834720.png)

**Comment by jeffdm** [comment]
One possibility: the VirtualBox network service is down. Does the following work:

- Delete the default VM (or `docker-machine rm -f default`)
- Restart your Windows PC so VirtualBox 5 services (including networking) restart
- Try creating the machine again

**Comment by mkavis** [comment]
Kitematic works and the CLI I launch from it works. Everything in Virtual Box works. Only issue is the Docker Quickstart still has an issue. It looks like it is an environment variable issue with HOME. But I am off and running now. Thanks.

![dockertoolbox3](https://cloud.githubusercontent.com/assets/2903281/9235412/902f3c16-410c-11e5-818a-b0f678fbb7d0.png)

**Comment by jeffdm** [comment]
Great to hear! Thanks for the info.

**Comment by kevinSuttle** [comment]
Man. I just tried the latest 1.8.2.c Toolbox build and it seems to have gotten worse. 

```bash
MacBook-Pro:~ kevinsuttle$ . '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


host is not running
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com

default is not running. Please start this with docker-machine start default
MacBook-Pro:~ kevinsuttle$ docker-machine start default
exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
MacBook-Pro:~ kevinsuttle$ docker-machine env
Error: Expected either one machine name, or -u flag to unset the variables in the arguments.
MacBook-Pro:~ kevinsuttle$ 
```

Deleting the VM does nothing. Kitematic is especially boned. At one point, the progress loading UI was going in reverse. 

<img width="1280" alt="screen shot 2015-09-10 at 6 04 15 pm" src="https://cloud.githubusercontent.com/assets/95672/9802305/309cd9b0-57e7-11e5-83cb-b1644351a244.png">

<img width="1280" alt="screen shot 2015-09-10 at 6 04 29 pm" src="https://cloud.githubusercontent.com/assets/95672/9802309/368fb1c6-57e7-11e5-936f-0ed1063c84cb.png">

<img width="620" alt="screen shot 2015-09-10 at 6 05 11 pm" src="https://cloud.githubusercontent.com/assets/95672/9802312/3c4e091e-57e7-11e5-9855-29a90d271fd0.png">

**Comment by mchiang0610** [comment]
Merging this with #153
