### ISSUE TITLE
Are checksums correct?

### ISSUE THREAD

**Issue by mihaiparaschiv** [docker/toolbox#651]
For the latest release, I get this:
```
$ shasum -a 256 DockerToolbox*
f81f859f68989007f1da0204f170a9c98fd7b65a7c2db40398739d7c8dec29e8 *DockerToolbox-17.05.0-ce.exe
```

```
$ md5sum DockerToolbox*
544913bc0468a806f872ff70730cb11d *DockerToolbox-17.05.0-ce.exe
```

This is different from what I can find at [github.com/docker/toolbox/releases/download/v17.05.0-ce/sha256sum.txt](https://github.com/docker/toolbox/releases/download/v17.05.0-ce/sha256sum.txt):
SHA 256: `ba292bdc2d2177106d359767b800856029031768b6c68413df859234a17ec535  DockerToolbox.exe`
MD5: `0bd4a59f4f62143b6dba0b8b9d35b0e5  DockerToolbox.exe`

I see similar differences for other releases. And, I did the checks on another computer.

Am I missing something? Or, are the release checksums incorrect?

**Comment by skyiron** [comment]
I get the same sha256 checksum as mihaiparaschiv for DockerToolbox-17.05.0-ce.exe

**Comment by kelbyers** [comment]
None of the last three stable releases match:
```
# curl -L https://github.com/docker/toolbox/releases/download/v17.03.1-ce/sha256sum.txt | grep exe
ff291d7ecbb4dc1e744fbf1383e23a98c604f8b080b8fc51ffc0a0fe6cff49ef  DockerToolbox.exe
# sha256sum DockerToolbox-17.03.1-ce.exe
a7622b93ba4543ea7df7b0cc8336a60588cb799e48463a68b9f66aa36509cd34 *DockerToolbox-17.03.1-ce.exe
# curl -L https://github.com/docker/toolbox/releases/download/v17.04.0-ce/sha256sum.txt | grep exe
987021e1f752515a6868b51e01cf4a1e245d7bb1c26c17dfdf5a81f2a41d720c  DockerToolbox.exe
# sha256sum DockerToolbox-17.04.0-ce.exe
9157ed0db9cac984fbd5f308b7cf92f27c449185efa42e64eaaf3c7a747f5144 *DockerToolbox-17.04.0-ce.exe
# curl -L https://github.com/docker/toolbox/releases/download/v17.05.0-ce/sha256sum.txt | grep exe
ba292bdc2d2177106d359767b800856029031768b6c68413df859234a17ec535  DockerToolbox exe
# sha256sum DockerToolbox-17.05.0-ce.exe
f81f859f68989007f1da0204f170a9c98fd7b65a7c2db40398739d7c8dec29e8 *DockerToolbox-17.05.0-ce.exe
```

**Comment by hmtelbi** [comment]
I noticed that the windows executable is digitally signed.
It seems that the published checksums are calculated **before** the signing process takes place.
Since the signing process modifies the executable, the actual checksums will be different from the published checksums.

**Comment by kelbyers** [comment]
You are still publishing release packages with incorrect checksums. You need to publish checksums for the signed packages that you make available.

```
# sha256sum /cygdrive/c/Users/kel/Downloads/DockerToolbox-17.06.0-ce-rc2.exe
f4cb68c8a36a6559ce9ef7f7b55854c561628c501c3b150a389a121ca8bbc7af */cygdrive/c/Users/kel/Downloads/DockerToolbox-17.06.0-ce-rc2.exe
# cat sha256sum.txt
169b69e7c91de5973eb17914957f8de2b719f778fadc3d80ab56a8f029f1e7c9  DockerToolbox.exe
f3941164b4ec7b3302a69ceac31b6233a65387d78e0edc27e5068f1658e97411  DockerToolbox.pkg
```

Publishing incorrect checksums breaks automated deployment systems like chocolatey that rely on the checksums published here to validate that the downloaded install package has not been compromised.

**Comment by tossj** [comment]
@shin- @seemethere @FrenchBen @nathanleclaire Any comments on this issue? Can the correct MD5 and SHA256 sums be provided?

**Comment by nathanleclaire** [comment]
I am not maintainer anymore, please reach out to @shin- thanks.

**Comment by shin-** [comment]
Fixed for https://github.com/docker/toolbox/releases/tag/v18.01.0-ce
