### ISSUE TITLE
v17.06.0-ce Pre-release?

### ISSUE THREAD

**Issue by dsanders11** [docker/toolbox#670]
Why is the [v17.06.0-ce tag](https://github.com/docker/toolbox/releases/tag/v17.06.0-ce) marked as pre-release? Is it not the final v17.06.0-ce release?

The links for toolbox [on the Docker site](https://www.docker.com/products/docker-toolbox) still point to v17.05.0-ce, probably due to this.

**Comment by shin-** [comment]
Fixed, thanks for the report, sorry it took a while to sort it out!
