### ISSUE TITLE
migrated my VMs to Docker Machine, containers missing

### ISSUE THREAD

**Issue by franzinc** [docker/toolbox#68]
The docs say:

Docker Toolbox includes a tool called Docker machine, and it creates new and separate virtual machines (VM) from your old Boot2Docker VM. Your old containers and images are still in the old Boot2Docker VM and are not lost. You can migrate your Boot2Docker VM to machine by typing in the command in the previous Q&A.

The command in "previous Q&A" is:

    docker-machine create -d virtualbox --virtualbox-import-boot2docker-vm boot2docker-vm dev

After

    eval "$(docker-machine env docker-vm)"

"docker images" shows no images.

The docs then said if this doesn't work to open a ticket.  Here I am.

**Comment by jeffdm** [comment]
Hi there, the eval command you're looking for is: `eval "$(docker-machine env dev)"` (note the **dev**).

Hope this helps!

**Comment by franzinc** [comment]
Error: Host does not exist: dev

**Comment by franzinc** [comment]
@layerpro[git:master]$ docker-machine ls
    NAME        ACTIVE   DRIVER       STATE     URL                         SWARM
    docker-vm   *        virtualbox   Running   tcp://192.168.99.100:2376   
    @layerpro[git:master]$

**Comment by franzinc** [comment]
See http://docs.docker.com/installation/mac/#migrate-from-boot2docker for where I found the command.

Also, I had tried the exact command on the Q&A page first.
