### ISSUE TITLE
Can't run VM in El Capitan

### ISSUE THREAD

**Issue by TannerFilip** [docker/toolbox#69]
I tried installing Toolbox on my Mac with 10.11, but the VMs won't start at all.

Error messags: https://gist.github.com/TannerFilip/77c699e0fca54ccc9ce3

**Comment by jeffdm** [comment]
Thanks for the issue! Quick Fix:

- Delete the vm `docker-machine rm -f default`
- run `sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart`
- Try again


Closing as it's a duplicate of #65

**Comment by bmorton** [comment]
The quick fix didn't work for me on 10.11 beta (15A244d).  I've uninstalled toolbox and gone back to boot2docker for now, which works fine.

**Comment by chacken** [comment]
I'm getting
    Error: Unknown action ''
when i run the above.
