### ISSUE TITLE
17.09.0-ce Release

### ISSUE THREAD

**Issue by dsanders11** [docker/toolbox#699]
Can we get a 17.09.0-ce release? It's been out for 2 weeks now.

**Comment by dsanders11** [comment]
@shin, why was 17.10.0-ce given a release but not 17.09.0-ce? The latter is the current stable CE release, it seems strange that toolbox skips over it. I want to be able to run the same version of Docker in production and development, but without the 17.09.0-ce release that's not possible at the moment.

**Comment by zot24** [comment]
Same thing here we need 17.09.0-ce for our development environments, any reason behind this?
