### ISSUE TITLE
Docker Quickstart fails to start upon initial installation

### ISSUE THREAD

**Issue by EMCP** [docker/toolbox#727]
OS Windows 7
Freshly installed Docker Toolbox gives errors when quickstart is initiated.  Tried reinstalling with latest virtualbox and still nothing changed.

I believe my gitbash starts in a network drive, heard that might be the issue but unsure what the fix is

Tried even pasting in latest start.sh to no avail, installing with NDIS5 network driver...

![image](https://user-images.githubusercontent.com/3691722/35409246-e9a54eac-0211-11e8-90c7-daf64720898a.png)

**Comment by EMCP** [comment]
i started the vm, switched it to host networking while i was at it... seems I got further

![image](https://user-images.githubusercontent.com/3691722/35410306-4c9c7348-0215-11e8-9bf8-ae33159920a6.png)

**Comment by Frondor** [comment]
Same is happening to me, just downloaded latest version:

![](https://i.imgur.com/DoIaxDD.png)

Default VM fails at creations and its state is "meditation guru"
