### ISSUE TITLE
Can't do docker login

### ISSUE THREAD

**Issue by bubo77** [docker/toolbox#73]
After my docker default machine starts up and issue docker login the cursor just blinking but i can't type anything doesn't react to enter either. the same happening if i use my own registry.

$ docker login
Username:

The only way to login if i fully parametrize the command with password/username/email

My system is a windows 8.1 64 bit.

**Comment by jeffdm** [comment]
Thanks for the issue. Closing in favor of this issue: https://github.com/docker/docker/issues/14336

There seems to be a good work around here: https://github.com/docker/docker/issues/14336

Hope this helps1
