### ISSUE TITLE
"VirtualBox requires Mac OS X 10.6 or later" when trying to install in 10.8.4

### ISSUE THREAD

**Issue by oscarmlage** [docker/toolbox#74]
I get this error message when trying to install DockerToolbox-1.8.1-pkg in OSX 10.8.4. I've tried with different releases (https://github.com/docker/toolbox/releases) and it seems to take place since 1.8.0b, (1.8.0a and 1.8.0 are running).

**Comment by oscarmlage** [comment]
![captura de pantalla 2015-08-13 a la s 16 43 14](https://cloud.githubusercontent.com/assets/98542/9252824/c6f52462-41da-11e5-9d3e-645ca091e19d.png)

**Comment by pyrat** [comment]
I experience the same on OSX 10.8.4

**Comment by jeffdm** [comment]
Thanks for the issue. Fixed in https://github.com/docker/toolbox/releases/tag/v1.8.1a
