### ISSUE TITLE
Installation(DockerToolbox-1.8.1.exe) failed again !!!!

### ISSUE THREAD

**Issue by JasonChoi1992** [docker/toolbox#75]
I delete the "default" at virtualbox, restart the windows 10, double click the docker quickstart terminal, it seems to be the same problem, I don't use VPN.
![capture](https://cloud.githubusercontent.com/assets/10534230/9252790/d600704c-420c-11e5-8fb9-3bbd442e91d1.PNG)

**Comment by jeffdm** [comment]
Sorry, Windows 10 is not currently supported by VirtualBox and therefore the Toolbox. Stay tuned for an update!
