### ISSUE TITLE
Failed to create symbolic link. Read-only file system

### ISSUE THREAD

**Issue by gety9** [docker/toolbox#762]
Guys hi,

I am getting error when trying to create symbolic link.
`ln: failed to create symbolic link 'foo': Read-only file system`

According to [this suggestion](https://github.com/docker/toolbox/issues/619#issuecomment-282591417) tried running it as administrator - no luck.

I am using Docker toolbox on Windows 10 home
```
Client:
 Version:       18.01.0-ce
 API version:   1.26 (downgraded from 1.35)
 Go version:    go1.9.2
 Git commit:    03596f51b1
 Built: Thu Jan 11 22:29:41 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      1.13.1
  API version:  1.26 (minimum version 1.12)
  Go version:   go1.7.5
  Git commit:   092cba3
  Built:        Wed Feb  8 08:47:51 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by mjarosie** [comment]
Hi @gety9 do you remember how exactly did you fix it? After running `VBoxManage setextradata ...` command I get `Protocol error` instead of `Read-only file system`...
