### ISSUE TITLE
Docker Error creating machine

### ISSUE THREAD

**Issue by ariefarfiansyah** [docker/toolbox#770]
Guys, anyone can help this error , i have trouble when creating machine docker.
it says : 
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": remote error: tls: bad certificate
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.

i use docker toolbox, and running on win 10 10240.

thankss help me to figured out this problem :(

**Comment by shin-** [comment]
Error message is self-explanatory.
