### ISSUE TITLE
docker on Windows: Invalid volume specification

### ISSUE THREAD

**Issue by jesaremi** [docker/toolbox#773]
I am trying to share my local drive with a container i created. I'm using the command line option -v or --volume= for this purpose.
I can't seem to be getting the syntax right.

Basic command: `docker run -it --entrypoint "cmd" autofaqrestcontainer:latest-debug "/K"`
(works with no issues)
I have added the following options to no avail. The response is always: "

> docker: Error response from daemon: invalid volume specification:

":

```
--volume=D:\:/C:\data
--volume=/D:/data
--volume=/D:/:/data
--volume=/D/:/data
```

**Comment by jesaremi** [comment]
the following worked:
--volume=D:\:C:\ddrive:ro

**Comment by malanvaneck** [comment]
What does this mean?
--volume=D::C:\ddrive:ro
