### ISSUE TITLE
VirtualBox 5.0.0 does not allow Kubernetes cluster to start

### ISSUE THREAD

**Issue by arun-gupta** [docker/toolbox#79]
Kubernetes cluster does not start with VirutalBox 5.0.0:

https://github.com/kubernetes/kubernetes/issues/12614

Highly recommend an older version of VirtualBox. I've already uninstalled Toolbox from my machine for this one reason.

**Comment by mchiang0610** [comment]
@arun-gupta Thanks for reporting this. We will pass this onto the Kubernetes team.

**Comment by arun-gupta** [comment]
Bug has already been filed with Kubernetes: https://github.com/kubernetes/kubernetes/issues/12614
