### ISSUE TITLE
docker-compose has stopped working

### ISSUE THREAD

**Issue by leocgpe** [docker/toolbox#795]
docker-compose has stopped working.
Windows 10 Home with Docker Toolbox

Everything was working normally and after creating a new .yml in the project and trying to run it, docker-compose stopped working anywhere, including the version query.

![capturar](https://user-images.githubusercontent.com/7947286/46513535-57642880-c82f-11e8-8be1-cd5f66eabab8.JPG)

**Comment by leocgpe** [comment]
I managed to make it work by replacing the docker-compose with the version https://github.com/docker/compose/releases/tag/1.19.0

**Comment by diogo-raphael-cravo** [comment]
Hey @leocgpe thanks for your post. I'm having the same issue you were having. How did you replace docker-compose by v1.19.0?

**Comment by leocgpe** [comment]
> Olá @leocgpe obrigado pelo seu post. Estou tendo o mesmo problema que você estava tendo. Como você substituiu o docker-compose por v1.19.0?

just download the file from the link, in my case:
docker-compose-windows-x86_64.exe
Copy it to the C: \ Program Files \ Docker Toolbox directory
Rename it to docker-compose.exe
