### ISSUE TITLE
Kitematic can not show "My Images" after update to toolbox 18.09.0

### ISSUE THREAD

**Issue by CC-Hsu** [docker/toolbox#805]
### Expected behavior
Show local images
### Actual behavior
Can not show local images
### Information about the Issue
I updated docker toolbox from 18.06.1-ce to 18.09.0, then kitematic can not show local images while my local images are still there.
```
PS C:\Program Files\Docker Toolbox> docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
postgres            11.1                8d84c7940aa6        4 days ago          311MB
postgres            11.1-alpine         daa3d8ceab8f        10 days ago         71.7MB
centos-dev-tool     latest              f39ab5db474c        5 weeks ago         566MB
alpine              3.8                 11cd0b38bc3c        4 months ago        4.41MB
centos              7.5.1804            49f7960eb7e4        5 months ago        200MB
PS C:\Program Files\Docker Toolbox>
```
![image](https://user-images.githubusercontent.com/8018872/48785330-81aa7080-ed1f-11e8-99e8-96df727af774.png)

### Steps to reproduce the behavior
Just update toolkit to 18.09.0 under windows 10

**Comment by glsorre** [comment]
I have the same problem on Ubuntu 18.04 with Docker CE 18.04 and kitematic 0.17.5.

**Comment by saidogoid** [comment]
Same here. 
The filters and images won't work, they don't change the windows. It's like unresponsive. How can we debug it?

**Comment by iennacca** [comment]
Upvote. Seems like something locks up the UI after I select any of the Filter By option tabs on the upper right corner - the gear Settings button works fine when I first fire up the app, but then becomes unresponsive once I start clicking on the Filter By option tabs.

**Comment by shin-** [comment]
Please file a report on [docker/kitematic](https://github.com/docker/kitematic).
