### ISSUE TITLE
iTerm support wanted

### ISSUE THREAD

**Issue by maacl** [docker/toolbox#81]
Please support iTerm and zsh on OSX.

**Comment by mchiang0610** [comment]
@maacl Thanks for the request!  Is this referring to the Docker QuickStart terminal?

**Comment by maacl** [comment]
Yes, it is indeed.

**Comment by mchiang0610** [comment]
@maacl You are able to use your own terminal with Docker Machine.

**Comment by brunowego** [comment]
+1

**Comment by brunowego** [comment]
By default "Docker QuickStart terminal" opens only with Terminal.app, will be cool select another terminal like iTerm.app. :+1:

**Comment by brunowego** [comment]
@maacl try:

```bash
echo '\neval "$(docker-machine env default)"' >> ~/.zshrc
```

Restart your terminal or run: source ~/.zshrc

**Comment by maacl** [comment]
@bruno Thanks I am aware of that, but I was looking for iTerm/zsh support
in Docker QuickStart Terminal.

**Comment by kudos** [comment]
For reference, this how Kitematic does it: https://github.com/kitematic/kitematic/blob/master/resources/terminal

I also have PR languishing that adds support for iTerm 2.9 beta here: https://github.com/kitematic/kitematic/pull/855

**Comment by paynerc** [comment]
:+1:

**Comment by lanvige** [comment]
:+1:

**Comment by gcdesigner** [comment]
+1

**Comment by spencerbeggs** [comment]
+1

**Comment by VincentDS** [comment]
+1

**Comment by charlieegan3** [comment]
+1

**Comment by SvenDowideit** [comment]
from the docker user's mailing list:

```
Saulo Vallory me@saulovallory.com via googlegroups.com 
1:38 AM (8 hours ago)

to Docker-user 
open iTerm and run:

source /Applications/Docker/Docker\ Quickstart\ Terminal.app/Contents/Resources/Scripts/start.sh

or create an alias for it in your .bashrc or .zshrc

alias docker-init="source /Applications/Docker/Docker\ Quickstart\ Terminal.app/Contents/Resources/Scripts/start.sh"
```

**Comment by SvenDowideit** [comment]
see also #123

**Comment by guillermo-carrasco** [comment]
Thanks @SvenDowideit , I tried executing the script but didn't work well with environment variables like the machine IP. Sourcing it seems to work better.

**Comment by paulredmond** [comment]
Thanks @SvenDowideit worked like a charm!

**Comment by diegoleme** [comment]
Tks @SvenDowideit :smile:

**Comment by rkulla** [comment]
+1  `echo '\neval "$(docker-machine env default)"' >> ~/.zshrc && source ~/.zshrc` worked for me, and I just had to delete out my old `eval "$(boot2docker shellinit)"` line.

**Comment by gzoller** [comment]
+1 This @SvenDowideit's script is a great start, but when I run it in iterm I still get the little standard terminal window popping up.  Any idea how to disable that?  I did see this post for wiring boot2docker to iterm and it worked really well.  [http://dev.documize.com/boot2docker-iterm/](http://dev.documize.com/boot2docker-iterm/)

I don't know enough about how docker toolbox is laid out to modify the script.

**Comment by virajkanwade** [comment]
For people who had issue with #123 could you please try #155 and let me know any issues? Thanks

**Comment by lukabirsa** [comment]
+1 for

```
echo '\neval "$(docker-machine env default)"' >> ~/.zshrc
```

Just add this line to the docker installation manual for souls using nonstandard term setups.

**Comment by igorspasic** [comment]
+1

**Comment by mchiang0610** [comment]
@maacl iTerm support is in PR https://github.com/docker/toolbox/pull/155

**Comment by mchiang0610** [comment]
We are looking for help with others. Anyone willing to contribute?

**Comment by virajkanwade** [comment]
For shell other than bash, try #164. Uses your default shell instead of forcing bash.

**Comment by jeffdm** [comment]
Because of @virajkanwade, look out for *both* zsh (or your default shell) support and iTerm support in the next version. Huge thanks!

**Comment by spencerbeggs** [comment]
Thank you so much! Not having Zsh and iTerm available was getting me down.

**Comment by jeffdm** [comment]
This should be available in https://github.com/docker/toolbox/releases/tag/v1.8.1d now, please give it a try!

Closing for now.

**Comment by ronsmith** [comment]
v1.8.1d seems to have made things worse.  At least before I didn't get an error dialog:

![screen shot 2015-11-03 at 11 51 50 am](https://cloud.githubusercontent.com/assets/3209187/10916545/8bee0d66-8221-11e5-833c-ad7c764989be.png)

**Comment by eddiemonge** [comment]
@jeffdm How? It give me the choice and I selected `iTerm (Always)` but it flashes to iterm but doesn't seem to do anything. 

```
$ docker run hello-world
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

Clicking `Docker CLI` in Kitematic opens a Terminal window where that command works. Is there something else I'm supposed to do? 

Is it because I'm running zsh? I can't tell is zsh support is available now. https://github.com/docker/toolbox/commit/e185d7addf9913beffb051e6d926ea5cf70ca44e seemed to enable it but then https://github.com/docker/toolbox/commit/d0d816fc8c88a28c4f7195432516d2a5188ab0c1 seems to have reverted it

**Comment by timothyjlaurent** [comment]
OMG!!! why is it SO hard to use docker on OSX??

**Comment by hedefalk** [comment]
I choose "iterm (always)" and iterm just get's focus but nothing happens. How can I reset my setting to at least use it in standard terminal?

**Comment by waysidekoi** [comment]
+1 @hedefalk

**Comment by virajkanwade** [comment]
~/Library/Application\ Support/DockerToolbox/default_terminal

**Comment by virajkanwade** [comment]
For people who are facing issues with iTerm, can you please mention the iTerm version?

**Comment by hedefalk** [comment]
@virajkanwade Build 2.9.20151006-nightly

**Comment by kudos** [comment]
@hedefalk nightly and beta builds are not supported, the Applescript API it provides is not compatible. See https://www.iterm2.com/applescript.html

**Comment by hedefalk** [comment]
@kudos Ok, thanks!

**Comment by diego898** [comment]
I'm using `Build 2.9.20160313` with zsh, and when I click the Quick start icon a blank terminal window appears. I have to type 

`bash /Applications/Docker/Docker\ Quickstart\ Terminal.app/Contents/Resources/Scripts/start.sh`

To get things setup. I thought iterm+zsh were supported?

**Comment by mooreniemi** [comment]
@diego898 thanks for that, worked for me too

**Comment by bobintornado** [comment]
@diego898 thanks for that too. Worked for me. 

Hoping iTerm2 + ZSH could be more fully supported soon.

**Comment by andrewhanksqa** [comment]
@diego898 This worked for me too. Good find. Thanks.

**Comment by michaeljonathan** [comment]
Not working on my iTerm2, build 3.0.0, although works great with Terminal. It seems to work when I `eval $(docker-machine env)`, though. Anyone having any luck?

**Comment by igorspasic** [comment]
Same here, iterm2 v3

**Comment by virajkanwade** [comment]
For all who are facing issue with iterm 3.0.0, the iterm api has changed. I
will try and submit a patch today.

**Comment by virajkanwade** [comment]
Added a fix, https://github.com/docker/toolbox/pull/508
Not sure when it will be accepted. But if somebody wants to give it a try.
