### ISSUE TITLE
Outdated / old release on website

### ISSUE THREAD

**Issue by DanielRuf** [docker/toolbox#820]
https://docs.docker.com/toolbox/toolbox_install_windows/ does not download the latest release but `Docker version 18.03.0-ce, build 0520e24302`.

**Comment by wahyuway** [comment]
Yup, i noticed that too. Please refer to https://github.com/docker/toolbox/releases to get the latest version.

**Comment by DanielRuf** [comment]
I did so too. But might be nice to update the download button on the website or always point at the latest release.
