### ISSUE TITLE
Can't pull images from private registry after upgrading from boot2docker to toolbox

### ISSUE THREAD

**Issue by brianbianco** [docker/toolbox#83]
I've migrated from boot2docker to toolbox.  I can no longer push / pull images from our private registry.  It bombs out like so.

```
$ docker pull docker-registry.service.dc1.consul:5000/test_image:0.6.0
Error response from daemon: unable to ping registry endpoint https://docker-registry.service.dc1.consul:5000/v0/
v2 ping attempt failed with error: Get https://docker-registry.service.dc1.consul:5000/v2/: x509: certificate signed by unknown authority
 v1 ping attempt failed with error: Get https://docker-registry.service.dc1.consul:5000/v1/_ping: x509: certificate signed by unknown authority
```
My env appears to be set correctly

```
$ env | grep DOCKER
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=default
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/bbianco/.docker/machine/machines/default
```

Docker machine output

```
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   *        virtualbox   Running   tcp://192.168.99.100:2376
```

contents of CERT PATH

```
$ ls /Users/bbianco/.docker/machine/machines/default
boot2docker.iso cert.pem        default         id_rsa          server-key.pem
ca.pem          config.json     disk.vmdk       key.pem         server.pem
```

**Comment by brianbianco** [comment]
Apparently the migration from boot2docker to toolbox did not carry over my --insecure-registry flag.  I modified /var/lib/boot2docker/profile so that EXTRA_ARGS contains --insecure-registry docker-registry.service.dc1.consul:5000 and now everything works.

**Comment by SiriusHu** [comment]
my situation is same as yours, but I don't have /var/lib/boot2docker/profile, do I need to vim it? can you show me your profile setting grammar

**Comment by kevana** [comment]
A bit late, but this might help someone. My `/var/lib/boot2docker/profile` looked like this after migration with Toolbox `1.8.2c`:
```

EXTRA_ARGS='
--label provider=virtualbox

'
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem

```
I just added `--insecure-registry registry.mycorp.com` to EXTRA_ARGS

**Comment by juharris** [comment]
For those needing more details:
Get into the VM:
`docker-machine ssh default`

Now you're in the VM, edit `/var/lib/boot2docker/profile`:
`sudo vi /var/lib/boot2docker/profile`

Now add your registry to EXTRA_ARGS: for example, add `--insecure-registry somehostorip.com:5000` (see below for the full example).
Save the file.
Hit Ctrl+D to logout.

Check the file:
`docker-machine ssh default 'cat /var/lib/boot2docker/profile'`
It should look like:
```
EXTRA_ARGS='
--label provider=virtualbox
--insecure-registry somehostorip.com:5000

'
CACERT=/var/lib/boot2docker/ca.pem
...
```

Restart the VM so that the env updates (not sure if needed):
`docker-machine restart default`

Test it:
`docker pull somehostorip.com:5000/yourcompany/yourproject`

You might need a tag if you didn't explicitly push `latest` to the registry:
`docker pull somehostorip.com:5000/yourcompany/yourproject:mytag`

**Comment by xuebaofeng** [comment]
This fixed my problem on Docker toolbox on windows, thanks a lot!

**Comment by mituladhia19** [comment]
This has solved my problem too :)

**Comment by shmpe** [comment]
> This fixed my problem on Docker toolbox on windows, thanks a lot!
Can you please tell me which solution did you follow? Thanks :)

**Comment by shmpe** [comment]
> This fixed my problem on Docker toolbox on windows, thanks a lot!

Can you please tell me which solution did you follow? Thanks! :)
