### ISSUE TITLE
New version of virtualbox no longer compatable with docker toolbox

### ISSUE THREAD

**Issue by thelastofreed** [docker/toolbox#837]
When I launch either kitematic or the quickstart terminal, neither successfully builds the virtualbox vm.  Kitematic just freezes at 100% and the quickstart terminal hangs at "Waiting for IP" for a while before it too finally fails.

**Comment by thelastofreed** [comment]
When the quickstart terminal finally fails, it generates the below error:
```
Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Looks like something went wrong in step ´Checking if machine default exists´
```

**Comment by jianboy** [comment]
Can you provide detailed version information?

virtualbox 6.0 compatible with docker tools. I had tried .

**Comment by thelastofreed** [comment]
Sure.  The version of virtualbox I am using is Version 6.0.8 r130520.  However, now I am getting a slightly different error:

```
Starting "default"...
(default) Check network to re-create if needed...
(default) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm default --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.196367 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))
Looks like something went wrong in step ´Checking status on default´... Press any key to continue...
```

**Comment by jianboy** [comment]
Failed to open/create the internal network


so, you can try:
```
docker-machine create -d virtualbox default 

```

![image](https://user-images.githubusercontent.com/11532015/59073787-39d5ea00-88fb-11e9-9398-ec839df058db.png)

**Comment by thelastofreed** [comment]
Ah.  Nevermind.  It is all good.  I updated performed an in-place upgrade to the latest version of windows 10, then removed the default machine and all of the host network adapters from virtualbox and tried again and it worked.
