### ISSUE TITLE
No way to uninstall DockerToolbox

### ISSUE THREAD

**Issue by franzinc** [docker/toolbox#84]
On a Mac.  Had boot2docker before installing 1.8.0a.

See https://github.com/docker/toolbox/issues/70 for why I can't use DockerToolbox.

Now I want to go back, but I have not found anywhere (and I've looked a lot) for instructions on uninstalling DockerToolbox.

So, I'm completely hosed right now.  Can't use the old setup and the new setup doesn't work.

Please advise.

**Comment by mchiang0610** [comment]
@franzinc You can uninstall using 

https://github.com/docker/toolbox/blob/master/osx/uninstall.sh 

Thanks!

**Comment by albertjan** [comment]
@mchiang0610 this doesn't uninstall the virtual box thats installed with the toolbox.

**Comment by mateodelnorte** [comment]
Where is this script located, on a mac install?

**Comment by ClintEsteMadera** [comment]
> Where is this script located, on a mac install?
You just download that script to anywhere in your computer and run it. It does the trick (PS: too bad they didn't bundle the script in, in the first place!)
