### ISSUE TITLE
Release v19.03.1 haven't setup file

### ISSUE THREAD

**Issue by KytoSai** [docker/toolbox#845]
Release v19.03.1 haven't setup file 

Image: https://i.imgur.com/18XjQYa.png

**Comment by CollinChaffin** [comment]
Surprised since there is a HUGE bug with volumes on .0 that .1 still doesn't have installers built and this issue not even acknowledged yet.

**Comment by namelus** [comment]
Your [documentation](https://docs.docker.com/toolbox/toolbox_install_windows/)  is misleading / incorrect.

![image](https://user-images.githubusercontent.com/11214040/62412598-2087ac00-b5d3-11e9-8fc9-95ff71d05d84.png)

It directs the user to click on the exe after d/l. But there is no exe.

Can we get someone's attention on this please and thanks?

**Comment by amshekar** [comment]
Upload exe or update the document here https://docs.docker.com/toolbox/toolbox_install_windows/
ended up with downloading the exe from one version lower to latest.

**Comment by crazy-max** [comment]
Artifacts are now available: https://github.com/docker/toolbox/releases/tag/v19.03.1

**Comment by pradeepjindal** [comment]
Thank You

**Comment by amshekar** [comment]
Thank you

**Comment by guillaumerose** [comment]
Yes sorry for that. The release pipeline failed in the middle.
