### ISSUE TITLE
docker toolbox 19.03.1: kitematic not able to login to docker hub

### ISSUE THREAD

**Issue by thelastofreed** [docker/toolbox#855]
Kitematic is not able to connect and login to Docker hub in the most up to date version of docker toolbox.  When I enter my credentials, the "processing" circle just spins and spins and spins ans spins until I close the application.

**Comment by mike247** [comment]
+1

**Comment by Sn0w-blind** [comment]
+1

**Comment by bdoelfs** [comment]
same for me on MAC and Windows

**Comment by ulrich** [comment]
Hello all,

Can reproduce this issue and there is a PR for fixing this trouble : https://github.com/docker/kitematic/pull/5306

We need to validate this PR before the new release.

Thank you,

**Comment by stephen-turner** [comment]
Thanks for the report. There was a change in the Hub login API code a few days ago, and we accidentally lost a backward compatibility fix. If possible, we're looking to re-fix it in Hub, rather than get everyone to download a new Kitematic.

**Comment by meticulous-dft** [comment]
We deployed our fix in Docker Hub. Please check to see if this issue is resolved.

**Comment by stephen-turner** [comment]
Closing, but please reopen if you're still having trouble.
