### ISSUE TITLE
docker-compose not found after installing 2.2.0.0

### ISSUE THREAD

**Issue by Garito** [docker/toolbox#871]
Any idea?
I'm using mac

**Comment by djs55** [comment]
@Garito thanks for your report. Docker Desktop for Mac issues should be reported on https://github.com/docker/for-mac/. Could you open a ticket over there, gather a diagnostics report (from the whale menu -> Troubleshoot -> Run Diagnostics -> Upload) and quote the ID so we can take a look at your logs? Thanks in advance!
