### ISSUE TITLE
Default setup trim search domains in resolv.conf

### ISSUE THREAD

**Issue by frconil** [docker/toolbox#88]
I went through the default setup (using virtual box) and couldn't build docker images from our working dockerfiles.

After a bit of digging around, turns out the virtualbox vm only included the first search domain in its resolv.conf, which would break our dns lookups.

Deleting the default docker-machine and recreating it with vmwarefusion instead fixed those dns lookup issues.

**Comment by mchiang0610** [comment]
Thanks for this! Noted. 

Closing this now.
