### ISSUE TITLE
Docker QuickStart Terminal Fails : VirtualBox path hardcoded to C Drive

### ISSUE THREAD

**Issue by rominirani** [docker/toolbox#89]
Completed a standard installation of Toolbox, except that I prefered to install it in another Drive (E). The Quick Start terminal failed to launch due to VirtualBox not being present on system. I inspected the start.sh and it had a /c/ in the path to VBoxManage.exe.

Environment : Windows 7

**Comment by Mordead** [comment]
+1

**Comment by doxxx** [comment]
The VirtualBox installation location can be found on Windows in the Registry, in the `InstallDir` value in the path `HKEY_LOCAL_MACHINE\SOFTWARE\Oracle\VirtualBox`. Windows 7 includes a "reg" command, which I had difficulty using from the MSYS bash commandline, but in the `cmd` prompt could be used like so:

```
C:\>reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Oracle\VirtualBox" /v InstallDir

HKEY_LOCAL_MACHINE\SOFTWARE\Oracle\VirtualBox
    InstallDir    REG_SZ    C:\Program Files\Oracle\VirtualBox\
```

**Comment by doxxx** [comment]
Even after I managed to wangle the syntax to work from a bash command-line, I still get this error:

```ERROR: The system was unable to find the specified registry key or value.```

It's possible that something about the MSYS environment is preventing the reg command from working.

**Comment by doxxx** [comment]
It may be due to this: http://superuser.com/a/664779/78821

**Comment by doxxx** [comment]
Apparently there is a way to explicitly invoke the 64-bit versions of the Windows command-line tools from a 32-bit context:

```
$ $WINDIR/sysnative/reg query HKEY_LOCAL_MACHINE\\SOFTWARE\\Oracle\\VirtualBox
//v InstallDir

HKEY_LOCAL_MACHINE\SOFTWARE\Oracle\VirtualBox
    InstallDir    REG_SZ    C:\Program Files\Oracle\VirtualBox\
```

Note the escaped backslashes and the doubled forward-slash 'v'.

**Comment by jeffdm** [comment]
This should be fixed in 1.8.1c. Thank again!

**Comment by jeremydyoung** [comment]
This gave me trouble in my freshly installed Docker-Toolbox 1.8.1c.  

I changed it from:
```bash
VBOXMANAGE=/$(reg query HKEY_LOCAL_MACHINE\\SOFTWARE\\Oracle\\VirtualBox //v InstallDir | grep InstallDir | awk '{print substr($0, index($0,$3))}' | sed 's/\\/\//g' | sed 's/://')VBoxManage.exe```
to
```bash
VBOXMANAGE=/$($WINDIR/sysnative/reg query HKEY_LOCAL_MACHINE\\SOFTWARE\\Oracle\\VirtualBox //v InstallDir | grep InstallDir | awk '{print substr($0, index($0,$3))}' | sed 's/\\/\//g' | sed 's/://')VBoxManage.exe```

And it fired up my Docker straight away.

I already had VirtualBox 5.0.2 (64 bit) freshly installed, and Git for Windows 1.9.4 installed, so I unchecked those from the installer.

I'm on Windows 7 Enterprise.

**Comment by fredpedro** [comment]
I have tried the solution of @jeremydyoung above, but at the end of the process, it gave an exit status 255.

**Comment by geedew** [comment]
Removing some of the virtualbox host-only network adapters in Preferences panel of virtualbox was necessary for me to get this to work with @jeremydyoung 's solution.

**Comment by rominirani** [comment]
Docker Quickstart terminal does not work for me still with 1.8.c -- it throws up "Looks like something went wrong ..." ... the first thing in the .\start.sh.

**Comment by rominirani** [comment]
Docker Quickstart terminal does not work for me still with 1.8.c -- it throws up "Looks like something went wrong ..." ... the first thing in the .\start.sh.

**Comment by michaelrtedford** [comment]
^^same

**Comment by puggie-wuggie** [comment]
^ same with 1.8.3 when I start Docker Quickstart terminal
