### ISSUE TITLE
FEAT: Docker-Compose Container Restart Policy Config in Toolbox

### ISSUE THREAD

**Issue by ecbrodie** [docker/toolbox#891]
This is a feature request, apologies for ditching the issue template (which seemed more appropriate for bug reports).

A very handy feature in Kitematic was to be able to view and set the restart policy for docker-compose containers. That functionality seems to be unimplemented in Docker Toolbox. I would love to have a quick way to toggle container restart policies in the GUI. Any plans to bring this to Toolbox?

**Comment by stephen-turner** [comment]
Moving to docker/toolbox repo

**Comment by ecbrodie** [comment]
Whoops, I didn't realize that there was a separate repo for Toolbox. Thanks for moving it here @stephen-turner.

Any thoughts on whether this Feature Request will be picked up by the maintainers? I know PRs are welcome of course, although it would probably be well out of my strike zone.

**Comment by stephen-turner** [comment]
TBH, Toolbox is not getting much love at the moment, our attention has mainly moved to Desktop.

**Comment by ecbrodie** [comment]
@stephen-turner oh that's interesting. Then, what do you think is the best solution for toggling the _Restart Policy_ of an existing Docker-Compose container on Docker For Mac? If it's not Toolbox, then is it really the deprecated Kitematic tool?

**Comment by stephen-turner** [comment]
Right now, possibly still Kitematic. We're gradually building the functionality of Kitematic into Docker Desktop itself. In fact, there's an issue on our public roadmap where our PM is asking what the top priorities are: https://github.com/docker/roadmap/issues/75. Thinking about it, maybe the best thing is for you to comment there.

**Comment by ecbrodie** [comment]
Will do, thank you :)
