### ISSUE TITLE
Docker Machine ls command : error messages

### ISSUE THREAD

**Issue by rominirani** [docker/toolbox#90]
When I run `docker-machine ls` , it throws up some errors related to kitematic. Note that in the installation, I chose not to install kitematic. 

The output of `docker-machine ls` is:

error getting state for host kitematic: machine does not exist
error getting URL for host kitematic: machine does not exist
error getting state for host kitematic: machine does not exist
error determining if host is active for host kitematic: machine does not exist
.... rest of the output is correct i.e. it lists the machines, except that it also lists kitematic machine that I don't have. 

Environment : Windows 7

**Comment by mchiang0610** [comment]
@rominirani does this happen in 1.8.1c as well? Closing this for now, if the issue persists, please reopen! 

Thanks!

**Comment by rominirani** [comment]
Confirmed that it is not happening in 1.8.1.c. Thanks.
