### ISSUE TITLE
Certificate missing. 

### ISSUE THREAD

**Issue by rominirani** [docker/toolbox#91]
The default machine was created by QuickStart Terminal. When I try to do the following:

`docker-machine env --shell cmd default`

I get the following error:
open <filepath\ca.pem : The system cannot find the file specified. 

I created another machine `dev` and this one goes through fine. So I am not sure what happened to the default one.

Environment : Windows

**Comment by gowthamgts** [comment]
I'm also getting the same error.

**Comment by gimerstedt** [comment]
experiencing the same issue on w7 using both the terminal as well as kitematic.

**Comment by bill2004158** [comment]
I'm also getting the same error.

**Comment by LongLiveCHIEF** [comment]
+1

**Comment by mchiang0610** [comment]
Just wanted to update that we are aware of this. 

You can currently use docker machine to regenerate certs: 

```
 docker-machine regenerate-certs default
```

**Comment by gowthamgts** [comment]
The problem is solved for me by upgrading the Virtualbox to the test build version `5.0.3`. Please try this.

**Comment by mchiang0610** [comment]
@gowthamgts Thanks. The issue can be sometimes solved by just running it again (which installing test build would do). We still have some users with the same problem with 5.0.3. 

In any case, 5.0.4 is out.

**Comment by gowthamgts** [comment]
Oh. May be in my case it worked well. :smile:

**Comment by rominirani** [comment]
I upgraded to 1.8.1c , my VirtualBox is still 5.0.2 and the problem has gone away.

**Comment by defaria** [comment]
running this worked for me. Thanks.
docker-machine regenerate-certs default

**Comment by T1m1** [comment]
thanks @rominirani. 
Worked for me, too.

**Comment by gerrywastaken** [comment]
Just downloaded the latest docker toolbox and this bug still happens.

**Comment by tanepiper** [comment]
I have the latest DockerToolbox (DockerToolbox-1.8.3) and VirtualBox 5.0.6 and I'm getting this on a clean install.

When I do `docker-machine regenerate-certs default` it just seems to hang there, this is using the Docker Quickstart Console

**Comment by mchiang0610** [comment]
Merging this with #153

**Comment by prayagupd** [comment]
```
docker-machine regenerate-certs default
```

did the trick. (Thx to closed issue)
