### ISSUE TITLE
Proposal for a Windows dev & test box

### ISSUE THREAD

**Issue by StefanScherer** [docker/toolbox#94]
To test the Windows version of the Docker Toolbox it would be nice to have a Windows test box to play with it. This could be done within a Vagrant box.

I test the "out of the box" experience playing Docker on Windows with this little repo: https://github.com/StefanScherer/docker-windows-box

This creates a Windows VM and tries to install the Docker tools through Chocolatey. 

And you don't have to leave your Mac, the Windows VM runs in VMware Fusion and the Windows VM can spin up a VirtualBox boot2docker VM without a problem.

I think of some scenarios:

* A development environment as described in [windows/README.md](https://github.com/docker/toolbox/blob/master/windows/README.md)
* Installation into a fresh Windows machine
* Test some different Windows platforms (7, 8, 8.1, 10)
* Update from existing Tools
* Update from older Docker Toolbox versions: I did some similar about a year ago with a nasty update bug in Vagrant by creating a Vagrant box to reproduce the update https://github.com/StefanScherer/test-vagrant-update

Such an update test could also be automatically tested eg. with Vagrant + Cucumber to snapshot and rollback the VM for each test scenario. An example for [vagrant-cucumber](https://github.com/scalefactory/vagrant-cucumber/#description) could be found here [for a cups test](https://github.com/StefanScherer/cups-cucumber-test/blob/master/features/lpr.feature), but I already played updating a windows application with MSI with that (closed source, sorry).

**Comment by StefanScherer** [comment]
Forgot to mention that this could also be done for a Mac VM running on a Mac: https://github.com/StefanScherer/mac-dev-box

**Comment by mchiang0610** [comment]
@StefanScherer Thanks for this! This is a great suggestion, and definitely useful for the community in general. 

That being said, this is out of the scope of this project, but I would love to help you tweet about it if you write a blog on this! 

Thank you so much!
