### ISSUE TITLE
Mac install doesn't work behind a proxy

### ISSUE THREAD

**Issue by jsolis** [docker/toolbox#96]
Description of problem:
The installer does not let me proceed past the Welcome screen when connected to a network which requires a proxy.

<img width="622" alt="screen shot 2015-08-15 at 1 03 44 pm" src="https://cloud.githubusercontent.com/assets/3266502/9289966/8ad03e20-434e-11e5-9300-953b17e7e258.png">

`docker version`: 1.8.1
`docker info`: n/a
`uname -a`: Darwin NW-8303LM 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

Environment details (VirtualBox):

How reproducible: 100%

Steps to Reproduce:
1. Connect to a network which requires a proxy to connect out
2. Run the docker toolbox installer

Actual Results:
The continue button on the welcome screen never gets enabled and so I'm stuck on that first screen.  I assume it's trying to make a connection to check for the latest versions of the different components, but the installer is not respecting my OS proxy settings.

Expected Results:
Expected the continue button to become enabled so I can continue with the install process.

Additional info:
When I connected to a different network which does not require a proxy, the installer was able to check for the latest versions of whatever it needed, and the continue button immediately appeared.  I was able to proceed with the install process without any trouble after that.

**Comment by SydOps** [comment]
i download the release directly to avoid the issue.

**Comment by zedtux** [comment]
I got the same issue

**Comment by jeffdm** [comment]
Thanks for this! Merging with #78
