### ISSUE TITLE
Exposed port are not visible on the Windows host using the vm docker host ip

### ISSUE THREAD

**Issue by betd-claumond** [docker/toolbox#99]
Hello,

I installed Docker Toolbox on Windows (version DockerToolbox-1.8.1a), and it's working pretty well, thanks !

My issue is that I have a custom container running php5-fpm/nginx that I launch with parameters
-p 80:3000
and I wasn't able to connect to it from windows, meaning
http://192.168.99.100:3000 was not working

with 192.168.99.100 being the VM docker host IP:
$ docker-machine ip default
192.168.99.100

Connection from other container with --link and from docker hos was working well.

For fixing it, I did the following steps:

- connect in SSH to docker VM host
ssh docker@192.168.99.100
password: tcuser

- connect as root
sudo su

- add a route
iptables -t nat -A  DOCKER -p tcp --dport 3000 -j DNAT --to-destination 172.17.0.78:80

where 172.17.0.78 is the IP of my container
$docker inspect  smart_web  | grep IPAddress
        "IPAddress": "172.17.0.78",

Is there a better way to fix the issue please ?
Because the IP of the container will change, so it's not practical to add the route manually on docker host.

Thanks for feedback.

Regards,
Christophe

**Comment by jeffdm** [comment]
Is 80 the container port? If so, I think the correct launch parameters in this case would be:

`docker run ... -p 3000:80`

Connecting to `http://192.168.99.100:3000 ` should work.

Please re-open this issue if the above doesn't work. Thanks!
